ClearAll["Global`*"]
AppendTo[$Path,"/home/gabor/github/butools/Mathematica"];
<<BuTools`
Print["---BuTools: DPH package test file---"//OutputForm];
Print["Enable the verbose messages with the BuToolsVerbose flag"//OutputForm];
BuTools`Verbose = True;
Print["Enable input parameter checking with the BuToolsCheckInput flag"//OutputForm];
BuTools`CheckInput = true;
On[Assert];
tmpOut = $Output;
stream = OpenWrite["/home/gabor/github/butools/test/docex/DPH_mathematica.docex", FormatType -> InputForm, PageWidth -> Infinity];
$Output = {stream};
Unprotect[Print];
Print[args___] := Block[{$inMsg = True, result, str},
   If[MatrixQ[args],
       str = "{";
       Do[str = StringJoin[str, ToString[args[[r]], FormatType -> InputForm]]; 
            If[r < Length[args], str = StringJoin[str, ",\n "]], {r, Length[args]}];
            str = StringJoin[str, "}"];
            Print[str//OutputForm],
            result = Print[args],
            result = Print[args]
        ]] /; ! TrueQ[$inMsg];
Print["=== MomentsFromMG ==="]
Print[">>> a = {-0.6,0.3,1.3};"//OutputForm];
a = {-0.6,0.3,1.3};
Print[">>> A = {{0.25, 0.2, -0.15},{0.3, 0.1, 0.25},{0, 0.2, 0.47}};"//OutputForm];
A = {{0.25, 0.2, -0.15},{0.3, 0.1, 0.25},{0, 0.2, 0.47}};
Print[">>> moms = MomentsFromMG[a, A];"//OutputForm];
moms = MomentsFromMG[a, A];
Print[">>> Print[moms];"//OutputForm];
Print[moms];
Print[">>> moms = MomentsFromMG[a, A, 3];"//OutputForm];
moms = MomentsFromMG[a, A, 3];
Print[">>> Print[moms];"//OutputForm];
Print[moms];
Print["=== MomentsFromDPH ==="]
Print[">>> a = {0.76,0,0.24};"//OutputForm];
a = {0.76,0,0.24};
Print[">>> A = {{0.34, 0.66, 0},{0.79, 0.05, 0.07},{0.26, 0.73, 0.01}};"//OutputForm];
A = {{0.34, 0.66, 0},{0.79, 0.05, 0.07},{0.26, 0.73, 0.01}};
Print[">>> moms = MomentsFromDPH[a, A, 5];"//OutputForm];
moms = MomentsFromDPH[a, A, 5];
Print[">>> Print[moms];"//OutputForm];
Print[moms];
Print["=== PmfFromMG ==="]
Print[">>> a = {-0.6,0.3,1.3};"//OutputForm];
a = {-0.6,0.3,1.3};
Print[">>> A = {{0.25, 0.2, -0.15},{0.3, 0.1, 0.25},{0, 0.2, 0.47}};"//OutputForm];
A = {{0.25, 0.2, -0.15},{0.3, 0.1, 0.25},{0, 0.2, 0.47}};
Print[">>> x = Range[0.0,100.0,1.0];"//OutputForm];
x = Range[0.0,100.0,1.0];
Print[">>> pmf = PmfFromMG[a, A, x];"//OutputForm];
pmf = PmfFromMG[a, A, x];
Print[">>> ListLinePlot[{Transpose[{x, pmf}]}]"//OutputForm];
Print["=== PmfFromDPH ==="]
Print[">>> a = {0.76,0,0.24};"//OutputForm];
a = {0.76,0,0.24};
Print[">>> A = {{0.34, 0.66, 0},{0.79, 0.05, 0.07},{0.26, 0.73, 0.01}};"//OutputForm];
A = {{0.34, 0.66, 0},{0.79, 0.05, 0.07},{0.26, 0.73, 0.01}};
Print[">>> x = Range[0.0,1000.0,1.0];"//OutputForm];
x = Range[0.0,1000.0,1.0];
Print[">>> pmf = PmfFromDPH[a, A, x];"//OutputForm];
pmf = PmfFromDPH[a, A, x];
Print[">>> ListLinePlot[{Transpose[{x, pmf}]}]"//OutputForm];
Print["=== CdfFromMG ==="]
Print[">>> a = {-0.6,0.3,1.3};"//OutputForm];
a = {-0.6,0.3,1.3};
Print[">>> A = {{0.25, 0.2, -0.15},{0.3, 0.1, 0.25},{0, 0.2, 0.47}};"//OutputForm];
A = {{0.25, 0.2, -0.15},{0.3, 0.1, 0.25},{0, 0.2, 0.47}};
Print[">>> x = Range[0.0,100.0,1.0];"//OutputForm];
x = Range[0.0,100.0,1.0];
Print[">>> cdf = CdfFromMG[a, A, x];"//OutputForm];
cdf = CdfFromMG[a, A, x];
Print[">>> ListLinePlot[{Transpose[{x, cdf}]}]"//OutputForm];
Print["=== CdfFromDPH ==="]
Print[">>> a = {0.76,0,0.24};"//OutputForm];
a = {0.76,0,0.24};
Print[">>> A = {{0.34, 0.66, 0},{0.79, 0.05, 0.07},{0.26, 0.73, 0.01}};"//OutputForm];
A = {{0.34, 0.66, 0},{0.79, 0.05, 0.07},{0.26, 0.73, 0.01}};
Print[">>> x = Range[0.0,1000.0,1.0];"//OutputForm];
x = Range[0.0,1000.0,1.0];
Print[">>> cdf = CdfFromDPH[a, A, x];"//OutputForm];
cdf = CdfFromDPH[a, A, x];
Print[">>> ListLinePlot[{Transpose[{x, cdf}]}]"//OutputForm];
Print["=== RandomDPH ==="]
Print[">>> {a, A} = RandomDPH[3, 10, 5];"//OutputForm];
{a, A} = RandomDPH[3, 10, 5];
Print[">>> Print[a];"//OutputForm];
Print[a];
Print[">>> Print[A];"//OutputForm];
Print[A];
Print["=== CheckMGRepresentation ==="]
Print[">>> a = {-0.6,0.3,1.3};"//OutputForm];
a = {-0.6,0.3,1.3};
Print[">>> A = {{0.25, 0.2, -0.15},{0.3, 0.1, 0.25},{0, 0.2, 0.47}};"//OutputForm];
A = {{0.25, 0.2, -0.15},{0.3, 0.1, 0.25},{0, 0.2, 0.47}};
Print[">>> flag = CheckMGRepresentation[a, A];"//OutputForm];
flag = CheckMGRepresentation[a, A];
Print[">>> Print[flag];"//OutputForm];
Print[flag];
Print[">>> a = {-0.6,0.3,1.3};"//OutputForm];
a = {-0.6,0.3,1.3};
Print[">>> A = {{0.35, 0.2, -0.25},{0.3, 0.1, 0.25},{0, 0.2, 0.47}};"//OutputForm];
A = {{0.35, 0.2, -0.25},{0.3, 0.1, 0.25},{0, 0.2, 0.47}};
Print[">>> flag = CheckMGRepresentation[a, A];"//OutputForm];
flag = CheckMGRepresentation[a, A];
Print[">>> Print[flag];"//OutputForm];
Print[flag];
Print["=== CheckDPHRepresentation ==="]
Print[">>> a = {0.48,0.08,0.26,0.18};"//OutputForm];
a = {0.48,0.08,0.26,0.18};
Print[">>> A = {{0, 0.08, 0.08, 0.8},{0.55, 0, 0.24, 0.19},{0.06, 0.03, 0, 0.001},{0.23, 0.005, 0.2, 0.53}};"//OutputForm];
A = {{0, 0.08, 0.08, 0.8},{0.55, 0, 0.24, 0.19},{0.06, 0.03, 0, 0.001},{0.23, 0.005, 0.2, 0.53}};
Print[">>> flag = CheckDPHRepresentation[a, A];"//OutputForm];
flag = CheckDPHRepresentation[a, A];
Print[">>> Print[flag];"//OutputForm];
Print[flag];
Print[">>> a = {0.48,0.08};"//OutputForm];
a = {0.48,0.08};
Print[">>> A = {{0, 0.08},{0.55, 0.5}};"//OutputForm];
A = {{0, 0.08},{0.55, 0.5}};
Print[">>> flag = CheckDPHRepresentation[a, A];"//OutputForm];
flag = CheckDPHRepresentation[a, A];
Print[">>> Print[flag];"//OutputForm];
Print[flag];
Print["=== MGFromMoments ==="]
Print[">>> moms = {4.08, 20.41, 130.45, 1054.41, 10463.73};"//OutputForm];
moms = {4.08, 20.41, 130.45, 1054.41, 10463.73};
Print[">>> {a, A} = MGFromMoments[moms];"//OutputForm];
{a, A} = MGFromMoments[moms];
Print[">>> Print[a];"//OutputForm];
Print[a];
Print[">>> Print[A];"//OutputForm];
Print[A];
Print[">>> memoms = MomentsFromMG[a, A, 5];"//OutputForm];
memoms = MomentsFromMG[a, A, 5];
Print[">>> Print[memoms];"//OutputForm];
Print[memoms];
Print["=== DPHFromMG ==="]
Print[">>> a = {-0.6,0.3,1.3};"//OutputForm];
a = {-0.6,0.3,1.3};
Print[">>> A = {{0.1, 0.2, 0},{0.3, 0.1, 0.25},{-0.3, 0.2, 0.77}};"//OutputForm];
A = {{0.1, 0.2, 0},{0.3, 0.1, 0.25},{-0.3, 0.2, 0.77}};
Print[">>> flag = CheckMGRepresentation[a, A];"//OutputForm];
flag = CheckMGRepresentation[a, A];
Print[">>> Print[flag];"//OutputForm];
Print[flag];
Print[">>> flag = CheckDPHRepresentation[a, A];"//OutputForm];
flag = CheckDPHRepresentation[a, A];
Print[">>> Print[flag];"//OutputForm];
Print[flag];
Print[">>> {b, B} = DPHFromMG[a, A];"//OutputForm];
{b, B} = DPHFromMG[a, A];
Print[">>> Print[b];"//OutputForm];
Print[b];
Print[">>> Print[B];"//OutputForm];
Print[B];
Print[">>> flag = CheckDPHRepresentation[b, B];"//OutputForm];
flag = CheckDPHRepresentation[b, B];
Print[">>> Print[flag];"//OutputForm];
Print[flag];
Print[">>> Cm = SimilarityMatrix[A, B];"//OutputForm];
Cm = SimilarityMatrix[A, B];
Print[">>> err1 = Norm[A.Cm-Cm.B];"//OutputForm];
err1 = Norm[A.Cm-Cm.B];
Print[">>> err2 = Norm[a.Cm-b];"//OutputForm];
err2 = Norm[a.Cm-b];
Print[">>> Print[Max[err1, err2]];"//OutputForm];
Print[Max[err1, err2]];
Print["=== CanonicalFromDPH2 ==="]
Print[">>> a = {0,1.0};"//OutputForm];
a = {0,1.0};
Print[">>> A = {{0.23, 0.22},{0.41, 0.48}};"//OutputForm];
A = {{0.23, 0.22},{0.41, 0.48}};
Print[">>> {b, B} = CanonicalFromDPH2[a, A];"//OutputForm];
{b, B} = CanonicalFromDPH2[a, A];
Print[">>> Print[b];"//OutputForm];
Print[b];
Print[">>> Print[B];"//OutputForm];
Print[B];
Print[">>> ev = Eigenvalues[A];"//OutputForm];
ev = Eigenvalues[A];
Print[">>> Print[ev];"//OutputForm];
Print[ev];
Print[">>> flag = CheckDPHRepresentation[b, B];"//OutputForm];
flag = CheckDPHRepresentation[b, B];
Print[">>> Print[flag];"//OutputForm];
Print[flag];
Print[">>> Cm = SimilarityMatrix[A, B];"//OutputForm];
Cm = SimilarityMatrix[A, B];
Print[">>> err1 = Norm[A.Cm-Cm.B];"//OutputForm];
err1 = Norm[A.Cm-Cm.B];
Print[">>> err2 = Norm[a.Cm-b];"//OutputForm];
err2 = Norm[a.Cm-b];
Print[">>> a = {1.0,0};"//OutputForm];
a = {1.0,0};
Print[">>> A = {{0, 0.61},{0.56, 0.44}};"//OutputForm];
A = {{0, 0.61},{0.56, 0.44}};
Print[">>> {b, B} = CanonicalFromDPH2[a, A];"//OutputForm];
{b, B} = CanonicalFromDPH2[a, A];
Print[">>> Print[b];"//OutputForm];
Print[b];
Print[">>> Print[B];"//OutputForm];
Print[B];
Print[">>> ev = Eigenvalues[A];"//OutputForm];
ev = Eigenvalues[A];
Print[">>> Print[ev];"//OutputForm];
Print[ev];
Print[">>> flag = CheckDPHRepresentation[b, B];"//OutputForm];
flag = CheckDPHRepresentation[b, B];
Print[">>> Print[flag];"//OutputForm];
Print[flag];
Print[">>> Cm = SimilarityMatrix[A, B];"//OutputForm];
Cm = SimilarityMatrix[A, B];
Print[">>> err1 = Norm[A.Cm-Cm.B];"//OutputForm];
err1 = Norm[A.Cm-Cm.B];
Print[">>> err2 = Norm[a.Cm-b];"//OutputForm];
err2 = Norm[a.Cm-b];
Print[">>> Print[Max[err1, err2]];"//OutputForm];
Print[Max[err1, err2]];
Print["=== CanonicalFromDPH3 ==="]
Print[">>> a = {0.46,0.22,0.32};"//OutputForm];
a = {0.46,0.22,0.32};
Print[">>> A = {{0.67, 0.01, 0.12},{0.06, 0.45, 0.15},{0.18, 0.43, 0.32}};"//OutputForm];
A = {{0.67, 0.01, 0.12},{0.06, 0.45, 0.15},{0.18, 0.43, 0.32}};
Print[">>> {b, B} = CanonicalFromDPH3[a, A];"//OutputForm];
{b, B} = CanonicalFromDPH3[a, A];
Print[">>> Print[b];"//OutputForm];
Print[b];
Print[">>> Print[B];"//OutputForm];
Print[B];
Print[">>> ev = Eigenvalues[A];"//OutputForm];
ev = Eigenvalues[A];
Print[">>> Print[ev];"//OutputForm];
Print[ev];
Print[">>> flag = CheckDPHRepresentation[b, B];"//OutputForm];
flag = CheckDPHRepresentation[b, B];
Print[">>> Print[flag];"//OutputForm];
Print[flag];
Print[">>> Cm = SimilarityMatrix[A, B];"//OutputForm];
Cm = SimilarityMatrix[A, B];
Print[">>> err1 = Norm[A.Cm-Cm.B];"//OutputForm];
err1 = Norm[A.Cm-Cm.B];
Print[">>> err2 = Norm[a.Cm-b];"//OutputForm];
err2 = Norm[a.Cm-b];
Print[">>> Print[Max[err1, err2]];"//OutputForm];
Print[Max[err1, err2]];
Print[">>> a = {0.76,0.12,0.12};"//OutputForm];
a = {0.76,0.12,0.12};
Print[">>> A = {{0.31, 0., 0.},{0.98, 0., 0.02},{0.88, 0.04, 0.08}};"//OutputForm];
A = {{0.31, 0., 0.},{0.98, 0., 0.02},{0.88, 0.04, 0.08}};
Print[">>> {b, B} = CanonicalFromDPH3[a, A];"//OutputForm];
{b, B} = CanonicalFromDPH3[a, A];
Print[">>> Print[b];"//OutputForm];
Print[b];
Print[">>> Print[B];"//OutputForm];
Print[B];
Print[">>> ev = Eigenvalues[A];"//OutputForm];
ev = Eigenvalues[A];
Print[">>> Print[ev];"//OutputForm];
Print[ev];
Print[">>> flag = CheckDPHRepresentation[b, B];"//OutputForm];
flag = CheckDPHRepresentation[b, B];
Print[">>> Print[flag];"//OutputForm];
Print[flag];
Print[">>> Cm = SimilarityMatrix[A, B];"//OutputForm];
Cm = SimilarityMatrix[A, B];
Print[">>> err1 = Norm[A.Cm-Cm.B];"//OutputForm];
err1 = Norm[A.Cm-Cm.B];
Print[">>> err2 = Norm[a.Cm-b];"//OutputForm];
err2 = Norm[a.Cm-b];
Print[">>> Print[Max[err1, err2]];"//OutputForm];
Print[Max[err1, err2]];
Print[">>> a = {0.67,0.07,0.26};"//OutputForm];
a = {0.67,0.07,0.26};
Print[">>> A = {{0.31, 0., 0.},{0.98, 0., 0.02},{0.88, 0.04, 0.08}};"//OutputForm];
A = {{0.31, 0., 0.},{0.98, 0., 0.02},{0.88, 0.04, 0.08}};
Print[">>> {b, B} = CanonicalFromDPH3[a, A];"//OutputForm];
{b, B} = CanonicalFromDPH3[a, A];
Print[">>> Print[b];"//OutputForm];
Print[b];
Print[">>> Print[B];"//OutputForm];
Print[B];
Print[">>> ev = Eigenvalues[A];"//OutputForm];
ev = Eigenvalues[A];
Print[">>> Print[ev];"//OutputForm];
Print[ev];
Print[">>> flag = CheckDPHRepresentation[b, B];"//OutputForm];
flag = CheckDPHRepresentation[b, B];
Print[">>> Print[flag];"//OutputForm];
Print[flag];
Print[">>> Cm = SimilarityMatrix[A, B];"//OutputForm];
Cm = SimilarityMatrix[A, B];
Print[">>> err1 = Norm[A.Cm-Cm.B];"//OutputForm];
err1 = Norm[A.Cm-Cm.B];
Print[">>> err2 = Norm[a.Cm-b];"//OutputForm];
err2 = Norm[a.Cm-b];
Print[">>> Print[Max[err1, err2]];"//OutputForm];
Print[Max[err1, err2]];
Print[">>> a = {0.78,0.04,0.18};"//OutputForm];
a = {0.78,0.04,0.18};
Print[">>> A = {{0.06, 0.25, 0.31},{0.45, 0.18, 0.33},{0.98, 0, 0.01}};"//OutputForm];
A = {{0.06, 0.25, 0.31},{0.45, 0.18, 0.33},{0.98, 0, 0.01}};
Print[">>> {b, B} = CanonicalFromDPH3[a, A];"//OutputForm];
{b, B} = CanonicalFromDPH3[a, A];
Print[">>> Print[b];"//OutputForm];
Print[b];
Print[">>> Print[B];"//OutputForm];
Print[B];
Print[">>> ev = Eigenvalues[A];"//OutputForm];
ev = Eigenvalues[A];
Print[">>> Print[ev];"//OutputForm];
Print[ev];
Print[">>> flag = CheckDPHRepresentation[b, B];"//OutputForm];
flag = CheckDPHRepresentation[b, B];
Print[">>> Print[flag];"//OutputForm];
Print[flag];
Print[">>> Cm = SimilarityMatrix[A, B];"//OutputForm];
Cm = SimilarityMatrix[A, B];
Print[">>> err1 = Norm[A.Cm-Cm.B];"//OutputForm];
err1 = Norm[A.Cm-Cm.B];
Print[">>> err2 = Norm[a.Cm-b];"//OutputForm];
err2 = Norm[a.Cm-b];
Print[">>> Print[Max[err1, err2]];"//OutputForm];
Print[Max[err1, err2]];
Print["=== AcyclicDPHFromMG ==="]
Print[">>> a = {0,0,1.0};"//OutputForm];
a = {0,0,1.0};
Print[">>> A = {{0.22, 0, 0},{0.3, 0.1, 0.55},{0.26, 0, 0.73}};"//OutputForm];
A = {{0.22, 0, 0},{0.3, 0.1, 0.55},{0.26, 0, 0.73}};
Print[">>> {b, B} = AcyclicDPHFromMG[a, A];"//OutputForm];
{b, B} = AcyclicDPHFromMG[a, A];
Print[">>> Print[b];"//OutputForm];
Print[b];
Print[">>> Print[B];"//OutputForm];
Print[B];
Print[">>> ma = MomentsFromMG[a, A, 5];"//OutputForm];
ma = MomentsFromMG[a, A, 5];
Print[">>> Print[ma];"//OutputForm];
Print[ma];
Print[">>> mb = MomentsFromMG[b, B, 5];"//OutputForm];
mb = MomentsFromMG[b, B, 5];
Print[">>> Print[mb];"//OutputForm];
Print[mb];
Print[">>> flag = CheckDPHRepresentation[b, B];"//OutputForm];
flag = CheckDPHRepresentation[b, B];
Print[">>> Print[flag];"//OutputForm];
Print[flag];
Print[">>> Cm = SimilarityMatrix[A, B];"//OutputForm];
Cm = SimilarityMatrix[A, B];
Print[">>> err1 = Norm[A.Cm-Cm.B];"//OutputForm];
err1 = Norm[A.Cm-Cm.B];
Print[">>> err2 = Norm[a.Cm-b];"//OutputForm];
err2 = Norm[a.Cm-b];
Print[">>> Print[Max[err1, err2]];"//OutputForm];
Print[Max[err1, err2]];
Print["=== DPH2From3Moments ==="]
Print[">>> a = {0.9,0.1};"//OutputForm];
a = {0.9,0.1};
Print[">>> A = {{0.2, 0.61},{0.58, 0.41}};"//OutputForm];
A = {{0.2, 0.61},{0.58, 0.41}};
Print[">>> moms = MomentsFromDPH[a, A];"//OutputForm];
moms = MomentsFromDPH[a, A];
Print[">>> Print[moms];"//OutputForm];
Print[moms];
Print[">>> {b, B} = DPH2From3Moments[moms];"//OutputForm];
{b, B} = DPH2From3Moments[moms];
Print[">>> Print[b];"//OutputForm];
Print[b];
Print[">>> Print[B];"//OutputForm];
Print[B];
Print[">>> phmoms = MomentsFromDPH[b, B, 3];"//OutputForm];
phmoms = MomentsFromDPH[b, B, 3];
Print[">>> Print[phmoms];"//OutputForm];
Print[phmoms];
Print["=== DPH3From5Moments ==="]
Print[">>> a = {0.7,0.1,0.2};"//OutputForm];
a = {0.7,0.1,0.2};
Print[">>> A = {{0.2, 0.51, 0.1},{0.58, 0.41, 0},{0.1, 0.4, 0.3}};"//OutputForm];
A = {{0.2, 0.51, 0.1},{0.58, 0.41, 0},{0.1, 0.4, 0.3}};
Print[">>> moms = MomentsFromDPH[a, A];"//OutputForm];
moms = MomentsFromDPH[a, A];
Print[">>> Print[moms];"//OutputForm];
Print[moms];
Print[">>> {b, B} = DPH3From5Moments[moms];"//OutputForm];
{b, B} = DPH3From5Moments[moms];
Print[">>> Print[b];"//OutputForm];
Print[b];
Print[">>> Print[B];"//OutputForm];
Print[B];
Print[">>> phmoms = MomentsFromMG[b, B, 5];"//OutputForm];
phmoms = MomentsFromMG[b, B, 5];
Print[">>> Print[phmoms];"//OutputForm];
Print[phmoms];
Print["=== SamplesFromDPH ==="]
Print[">>> a = {0.76,0,0.24};"//OutputForm];
a = {0.76,0,0.24};
Print[">>> A = {{0.34, 0.66, 0},{0.79, 0.05, 0.07},{0.26, 0.73, 0.01}};"//OutputForm];
A = {{0.34, 0.66, 0},{0.79, 0.05, 0.07},{0.26, 0.73, 0.01}};
Print[">>> x = SamplesFromDPH[a, A, 1000];"//OutputForm];
x = SamplesFromDPH[a, A, 1000];
Print[">>> mt = MarginalMomentsFromTrace[x, 3];"//OutputForm];
mt = MarginalMomentsFromTrace[x, 3];
Print[">>> Print[mt];"//OutputForm];
Print[mt];
Print[">>> mp = MomentsFromDPH[a, A, 3];"//OutputForm];
mp = MomentsFromDPH[a, A, 3];
Print[">>> Print[mp];"//OutputForm];
Print[mp];
$Output = tmpOut;Close[stream];

