clear all
run('/home/gabor/github/butools/Matlab/BuToolsInit.m')

disp('---BuTools: Queues package test file---');
disp('Enable the verbose messages with the BuToolsVerbose flag');
global BuToolsVerbose;
BuToolsVerbose = true;
disp('Enable input parameter checking with the BuToolsCheckInput flag');
global BuToolsCheckInput;
BuToolsCheckInput = true;
global BuToolsCheckPrecision;
format short g;
format compact
delete('/home/gabor/github/butools/test/docex/Queues_matlab.docex');
diary('/home/gabor/github/butools/test/docex/Queues_matlab.docex');
disp('=== QBDQueue ===')
disp('>>> B = [6., 1., 0.; 0., 4., 1.; 2., 0., 0.];');
B = [6., 1., 0.; 0., 4., 1.; 2., 0., 0.];
disp('>>> F = [0., 1., 1.; 5., 0., 0.; 1., 3., 0.];');
F = [0., 1., 1.; 5., 0., 0.; 1., 3., 0.];
disp('>>> L = [-14., 3., 2.; 0., -14., 4.; 3., 1., -10.];');
L = [-14., 3., 2.; 0., -14., 4.; 3., 1., -10.];
disp('>>> L0 = L+B;');
L0 = L+B;
disp('>>> disp(L0);');
disp(L0);
BuToolsVerbose = false;
[pi0, R] = QBDSolve(B, L, F, L0);
lambd = sum(pi0*inv(eye(size(R,1))-R)*F);
BuToolsVerbose = true;
disp('>>> [qld, qlm] = QBDQueue(B, L, F, L0, ''qlDistr'', (0:1:10), ''qlMoms'', 5);');
[qld, qlm] = QBDQueue(B, L, F, L0, 'qlDistr', (0:1:10), 'qlMoms', 5);
disp('>>> disp(qld);');
disp(qld);
disp('>>> disp(qlm);');
disp(qlm);
disp('>>> [alphap, Ap] = QBDQueue(B, L, F, L0, ''qlDistrDPH'');');
[alphap, Ap] = QBDQueue(B, L, F, L0, 'qlDistrDPH');
disp('>>> disp(alphap);');
disp(alphap);
disp('>>> disp(Ap);');
disp(Ap);
disp('>>> [alpha, A] = QBDQueue(B, L, F, L0, ''qlDistrMG'');');
[alpha, A] = QBDQueue(B, L, F, L0, 'qlDistrMG');
disp('>>> disp(alpha);');
disp(alpha);
disp('>>> disp(A);');
disp(A);
disp('>>> qldFromDPH = PmfFromDPH(alphap, Ap, (0:1:10));');
qldFromDPH = PmfFromDPH(alphap, Ap, (0:1:10));
disp('>>> disp(qldFromDPH);');
disp(qldFromDPH);
disp('>>> qlmFromMG = MomentsFromMG(alpha, A, 5);');
qlmFromMG = MomentsFromMG(alpha, A, 5);
disp('>>> disp(qlmFromMG);');
disp(qlmFromMG);
disp('>>> [std, stm] = QBDQueue(B, L, F, L0, ''stDistr'', (0.:0.1:1.), ''stMoms'', 5);');
[std, stm] = QBDQueue(B, L, F, L0, 'stDistr', (0.:0.1:1.), 'stMoms', 5);
disp('>>> disp(std);');
disp(std);
disp('>>> disp(stm);');
disp(stm);
disp('>>> [betap, Bp] = QBDQueue(B, L, F, L0, ''stDistrPH'');');
[betap, Bp] = QBDQueue(B, L, F, L0, 'stDistrPH');
disp('>>> disp(betap);');
disp(betap);
disp('>>> disp(Bp);');
disp(Bp);
disp('>>> [beta, B] = QBDQueue(B, L, F, L0, ''stDistrME'');');
[beta, B] = QBDQueue(B, L, F, L0, 'stDistrME');
disp('>>> disp(beta);');
disp(beta);
disp('>>> disp(B);');
disp(B);
disp('>>> stdFromPH = CdfFromPH(betap, Bp, (0.:0.1:1.));');
stdFromPH = CdfFromPH(betap, Bp, (0.:0.1:1.));
disp('>>> disp(stdFromPH);');
disp(stdFromPH);
disp('>>> stmFromME = MomentsFromME(beta, B, 5);');
stmFromME = MomentsFromME(beta, B, 5);
disp('>>> disp(stmFromME);');
disp(stmFromME);
disp('=== MAPMAP1 ===')
disp('>>> D0 = [-8., 1., 2.; 0., -6., 4.; 3., 0., -3.];');
D0 = [-8., 1., 2.; 0., -6., 4.; 3., 0., -3.];
disp('>>> D1 = [4., 1., 0.; 0., 2., 0.; 0., 0., 0.];');
D1 = [4., 1., 0.; 0., 2., 0.; 0., 0., 0.];
disp('>>> S0 = [-10., 4.; 0., -7.];');
S0 = [-10., 4.; 0., -7.];
disp('>>> S1 = [5., 1.; 4., 3.];');
S1 = [5., 1.; 4., 3.];
lambd = 1./MarginalMomentsFromMAP(D0, D1, 1);
disp('>>> [qld, qlm] = MAPMAP1(D0, D1, S0, S1, ''qlDistr'', (0:1:10), ''qlMoms'', 5);');
[qld, qlm] = MAPMAP1(D0, D1, S0, S1, 'qlDistr', (0:1:10), 'qlMoms', 5);
disp('>>> disp(qld);');
disp(qld);
disp('>>> disp(qlm);');
disp(qlm);
disp('>>> [alphap, Ap] = MAPMAP1(D0, D1, S0, S1, ''qlDistrDPH'');');
[alphap, Ap] = MAPMAP1(D0, D1, S0, S1, 'qlDistrDPH');
disp('>>> disp(alphap);');
disp(alphap);
disp('>>> disp(Ap);');
disp(Ap);
disp('>>> [alpha, A] = MAPMAP1(D0, D1, S0, S1, ''qlDistrMG'');');
[alpha, A] = MAPMAP1(D0, D1, S0, S1, 'qlDistrMG');
disp('>>> disp(alpha);');
disp(alpha);
disp('>>> disp(A);');
disp(A);
disp('>>> qldFromDPH = PmfFromDPH(alphap, Ap, (0:1:10));');
qldFromDPH = PmfFromDPH(alphap, Ap, (0:1:10));
disp('>>> disp(qldFromDPH);');
disp(qldFromDPH);
disp('>>> qlmFromMG = MomentsFromMG(alpha, A, 5);');
qlmFromMG = MomentsFromMG(alpha, A, 5);
disp('>>> disp(qlmFromMG);');
disp(qlmFromMG);
disp('>>> [std, stm] = MAPMAP1(D0, D1, S0, S1, ''stDistr'', (0.:0.1:1.), ''stMoms'', 5);');
[std, stm] = MAPMAP1(D0, D1, S0, S1, 'stDistr', (0.:0.1:1.), 'stMoms', 5);
disp('>>> disp(std);');
disp(std);
disp('>>> disp(stm);');
disp(stm);
disp('>>> [betap, Bp] = MAPMAP1(D0, D1, S0, S1, ''stDistrPH'');');
[betap, Bp] = MAPMAP1(D0, D1, S0, S1, 'stDistrPH');
disp('>>> disp(betap);');
disp(betap);
disp('>>> disp(Bp);');
disp(Bp);
disp('>>> [beta, B] = MAPMAP1(D0, D1, S0, S1, ''stDistrME'');');
[beta, B] = MAPMAP1(D0, D1, S0, S1, 'stDistrME');
disp('>>> disp(beta);');
disp(beta);
disp('>>> disp(B);');
disp(B);
disp('>>> stdFromPH = CdfFromPH(betap, Bp, (0.:0.1:1.));');
stdFromPH = CdfFromPH(betap, Bp, (0.:0.1:1.));
disp('>>> disp(stdFromPH);');
disp(stdFromPH);
disp('>>> stmFromME = MomentsFromME(beta, B, 5);');
stmFromME = MomentsFromME(beta, B, 5);
disp('>>> disp(stmFromME);');
disp(stmFromME);
IA = eye(size(D0,1));
IS = eye(size(S0,1));
BuToolsVerbose = false;
[gamma, G] = QBDQueue(kron(IA, S1), kron(D0, IS)+kron(IA, S0), kron(D1, IS), kron(D0, IS), 'stDistrME');
BuToolsVerbose = true;
msmall = MomentsFromME(beta, B, 5);
mlarge = MomentsFromME(gamma, G, 5);
disp('>>> delta = [0.5,0.1,0.4];');
delta = [0.5,0.1,0.4];
disp('>>> Dm = [-8., 1., 2.; 0., -6., 4.; 3., 0., -3.];');
Dm = [-8., 1., 2.; 0., -6., 4.; 3., 0., -3.];
disp('>>> sigma = [0.2,0.7,0.1];');
sigma = [0.2,0.7,0.1];
disp('>>> S = [-10., 4., 0.; 5., -7., 2.; 1., 2., -8.];');
S = [-10., 4., 0.; 5., -7., 2.; 1., 2., -8.];
disp('>>> D0 = Dm;');
D0 = Dm;
disp('>>> D1 = sum(-Dm,2)*delta;');
D1 = sum(-Dm,2)*delta;
disp('>>> S0 = S;');
S0 = S;
disp('>>> S1 = sum(-S,2)*sigma;');
S1 = sum(-S,2)*sigma;
lambd = 1./MarginalMomentsFromMAP(D0, D1, 1);
disp('>>> [qld, qlm] = MAPMAP1(D0, D1, S0, S1, ''qlDistr'', (0:1:10), ''qlMoms'', 5);');
[qld, qlm] = MAPMAP1(D0, D1, S0, S1, 'qlDistr', (0:1:10), 'qlMoms', 5);
disp('>>> disp(qld);');
disp(qld);
disp('>>> disp(qlm);');
disp(qlm);
disp('>>> [alphap, Ap] = MAPMAP1(D0, D1, S0, S1, ''qlDistrDPH'');');
[alphap, Ap] = MAPMAP1(D0, D1, S0, S1, 'qlDistrDPH');
disp('>>> disp(alphap);');
disp(alphap);
disp('>>> disp(Ap);');
disp(Ap);
disp('>>> [alpha, A] = MAPMAP1(D0, D1, S0, S1, ''qlDistrMG'');');
[alpha, A] = MAPMAP1(D0, D1, S0, S1, 'qlDistrMG');
disp('>>> disp(alpha);');
disp(alpha);
disp('>>> disp(A);');
disp(A);
disp('>>> qldFromDPH = PmfFromDPH(alphap, Ap, (0:1:10));');
qldFromDPH = PmfFromDPH(alphap, Ap, (0:1:10));
disp('>>> disp(qldFromDPH);');
disp(qldFromDPH);
disp('>>> qlmFromMG = MomentsFromMG(alpha, A, 5);');
qlmFromMG = MomentsFromMG(alpha, A, 5);
disp('>>> disp(qlmFromMG);');
disp(qlmFromMG);
disp('>>> [std, stm] = MAPMAP1(D0, D1, S0, S1, ''stDistr'', (0.:0.1:1.), ''stMoms'', 5);');
[std, stm] = MAPMAP1(D0, D1, S0, S1, 'stDistr', (0.:0.1:1.), 'stMoms', 5);
disp('>>> disp(std);');
disp(std);
disp('>>> disp(stm);');
disp(stm);
disp('>>> [betap, Bp] = MAPMAP1(D0, D1, S0, S1, ''stDistrPH'');');
[betap, Bp] = MAPMAP1(D0, D1, S0, S1, 'stDistrPH');
disp('>>> disp(betap);');
disp(betap);
disp('>>> disp(Bp);');
disp(Bp);
disp('>>> [beta, B] = MAPMAP1(D0, D1, S0, S1, ''stDistrME'');');
[beta, B] = MAPMAP1(D0, D1, S0, S1, 'stDistrME');
disp('>>> disp(beta);');
disp(beta);
disp('>>> disp(B);');
disp(B);
disp('>>> stdFromPH = CdfFromPH(betap, Bp, (0.:0.1:1.));');
stdFromPH = CdfFromPH(betap, Bp, (0.:0.1:1.));
disp('>>> disp(stdFromPH);');
disp(stdFromPH);
disp('>>> stmFromME = MomentsFromME(beta, B, 5);');
stmFromME = MomentsFromME(beta, B, 5);
disp('>>> disp(stmFromME);');
disp(stmFromME);
IA = eye(size(D0,1));
IS = eye(size(S0,1));
BuToolsVerbose = false;
[gamma, G] = QBDQueue(kron(IA, S1), kron(D0, IS)+kron(IA, S0), kron(D1, IS), kron(D0, IS), 'stDistrME');
BuToolsVerbose = true;
msmall = MomentsFromME(beta, B, 5);
mlarge = MomentsFromME(gamma, G, 5);
disp('=== MMAPPH1PRPR ===')
disp('>>> D0 = [-5.49, 0., 1.15, 0.; 0., -2.29, 0., 0.; 0., 0.08, -1.32, 0.; 0.72, 1.17, 0.7, -7.07];');
D0 = [-5.49, 0., 1.15, 0.; 0., -2.29, 0., 0.; 0., 0.08, -1.32, 0.; 0.72, 1.17, 0.7, -7.07];
disp('>>> D1 = [0.25, 0.38, 0.64, 0.; 0., 0., 0., 1.09; 0., 1.24, 0., 0.; 0.37, 0., 0., 0.];');
D1 = [0.25, 0.38, 0.64, 0.; 0., 0., 0., 1.09; 0., 1.24, 0., 0.; 0.37, 0., 0., 0.];
disp('>>> D2 = [0.3, 1.0, 0., 0.48; 0., 0.2, 0., 0.; 0., 0., 0., 0.; 0.61, 0., 0., 0.2];');
D2 = [0.3, 1.0, 0., 0.48; 0., 0.2, 0., 0.; 0., 0., 0., 0.; 0.61, 0., 0., 0.2];
disp('>>> D3 = [0., 0.98, 0., 0.31; 0., 0., 1.0, 0.; 0., 0., 0., 0.; 1.1, 0.84, 0.33, 1.03];');
D3 = [0., 0.98, 0., 0.31; 0., 0., 1.0, 0.; 0., 0., 0., 0.; 1.1, 0.84, 0.33, 1.03];
disp('>>> sigma3 = [0.83333,0.11404,0.05263];');
sigma3 = [0.83333,0.11404,0.05263];
disp('>>> S3 = [-3., 0., 0.; 0.73077, -0.73077, 0.; 0., 0.5, -0.5];');
S3 = [-3., 0., 0.; 0.73077, -0.73077, 0.; 0., 0.5, -0.5];
disp('>>> sigma2 = [1.];');
sigma2 = [1.];
disp('>>> S2 = [-2.];');
S2 = [-2.];
disp('>>> sigma1 = [0.25,0.75];');
sigma1 = [0.25,0.75];
disp('>>> S1 = [-2.5, 2.5; 0., -10.];');
S1 = [-2.5, 2.5; 0., -10.];
disp('>>> [qlm, qld] = MMAPPH1PRPR({D0, D1, D2, D3}, {sigma1, sigma2, sigma3}, {S1, S2, S3}, ''qlMoms'', 3, ''qlDistr'', 500);');
[qlm, qld] = MMAPPH1PRPR({D0, D1, D2, D3}, {sigma1, sigma2, sigma3}, {S1, S2, S3}, 'qlMoms', 3, 'qlDistr', 500);
momFromDistr = [(0:1:499);(0:1:499).^2;(0:1:499).^3]*qld;
disp('>>> distrPoints = [1., 5., 10.];');
distrPoints = [1., 5., 10.];
disp('>>> [stm, std] = MMAPPH1PRPR({D0, D1, D2, D3}, {sigma1, sigma2, sigma3}, {S1, S2, S3}, ''stMoms'', 3, ''stDistr'', distrPoints);');
[stm, std] = MMAPPH1PRPR({D0, D1, D2, D3}, {sigma1, sigma2, sigma3}, {S1, S2, S3}, 'stMoms', 3, 'stDistr', distrPoints);
disp('>>> disp(stm);');
disp(stm);
disp('>>> disp(std);');
disp(std);
lambda1 = 1./MarginalMomentsFromMAP(D0+D2+D3, D1, 1);
lambda2 = 1./MarginalMomentsFromMAP(D0+D1+D3, D2, 1);
lambda3 = 1./MarginalMomentsFromMAP(D0+D1+D2, D3, 1);
disp('=== MMAPPH1NPPR ===')
disp('>>> D0 = [-5.49, 0., 1.15, 0.; 0., -2.29, 0., 0.; 0., 0.08, -1.32, 0.; 0.72, 1.17, 0.7, -7.07];');
D0 = [-5.49, 0., 1.15, 0.; 0., -2.29, 0., 0.; 0., 0.08, -1.32, 0.; 0.72, 1.17, 0.7, -7.07];
disp('>>> D1 = [0.25, 0.38, 0.64, 0.; 0., 0., 0., 1.09; 0., 1.24, 0., 0.; 0.37, 0., 0., 0.];');
D1 = [0.25, 0.38, 0.64, 0.; 0., 0., 0., 1.09; 0., 1.24, 0., 0.; 0.37, 0., 0., 0.];
disp('>>> D2 = [0.3, 1.0, 0., 0.48; 0., 0.2, 0., 0.; 0., 0., 0., 0.; 0.61, 0., 0., 0.2];');
D2 = [0.3, 1.0, 0., 0.48; 0., 0.2, 0., 0.; 0., 0., 0., 0.; 0.61, 0., 0., 0.2];
disp('>>> D3 = [0., 0.98, 0., 0.31; 0., 0., 1.0, 0.; 0., 0., 0., 0.; 1.1, 0.84, 0.33, 1.03];');
D3 = [0., 0.98, 0., 0.31; 0., 0., 1.0, 0.; 0., 0., 0., 0.; 1.1, 0.84, 0.33, 1.03];
disp('>>> sigma3 = [0.83333,0.11404,0.05263];');
sigma3 = [0.83333,0.11404,0.05263];
disp('>>> S3 = [-3., 0., 0.; 0.73077, -0.73077, 0.; 0., 0.5, -0.5];');
S3 = [-3., 0., 0.; 0.73077, -0.73077, 0.; 0., 0.5, -0.5];
disp('>>> sigma2 = [1.];');
sigma2 = [1.];
disp('>>> S2 = [-2.];');
S2 = [-2.];
disp('>>> sigma1 = [0.25,0.75];');
sigma1 = [0.25,0.75];
disp('>>> S1 = [-2.5, 2.5; 0., -10.];');
S1 = [-2.5, 2.5; 0., -10.];
disp('>>> [qlm, qld] = MMAPPH1NPPR({D0, D1, D2, D3}, {sigma1, sigma2, sigma3}, {S1, S2, S3}, ''qlMoms'', 3, ''qlDistr'', 500);');
[qlm, qld] = MMAPPH1NPPR({D0, D1, D2, D3}, {sigma1, sigma2, sigma3}, {S1, S2, S3}, 'qlMoms', 3, 'qlDistr', 500);
momFromDistr = [(0:1:499);(0:1:499).^2;(0:1:499).^3]*qld;
disp('>>> distrPoints = [1., 5., 10.];');
distrPoints = [1., 5., 10.];
disp('>>> [stm, std] = MMAPPH1NPPR({D0, D1, D2, D3}, {sigma1, sigma2, sigma3}, {S1, S2, S3}, ''stMoms'', 3, ''stDistr'', distrPoints);');
[stm, std] = MMAPPH1NPPR({D0, D1, D2, D3}, {sigma1, sigma2, sigma3}, {S1, S2, S3}, 'stMoms', 3, 'stDistr', distrPoints);
disp('>>> disp(stm);');
disp(stm);
disp('>>> disp(std);');
disp(std);
lambda1 = 1./MarginalMomentsFromMAP(D0+D2+D3, D1, 1);
lambda2 = 1./MarginalMomentsFromMAP(D0+D1+D3, D2, 1);
lambda3 = 1./MarginalMomentsFromMAP(D0+D1+D2, D3, 1);
disp('=== FluidQueue ===')
disp('>>> Q = [-9., 2., 4., 0., 1., 2.; 6., -25., 5., 3., 7., 4.; 1., 3., -4., 0., 0., 0.; 0., 0., 0., -8., 3., 5.; 7., 3., 0., 2., -13., 1.; 7., 8., 0., 3., 8., -26.];');
Q = [-9., 2., 4., 0., 1., 2.; 6., -25., 5., 3., 7., 4.; 1., 3., -4., 0., 0., 0.; 0., 0., 0., -8., 3., 5.; 7., 3., 0., 2., -13., 1.; 7., 8., 0., 3., 8., -26.];
disp('>>> vRin = [4.,2.,1.,0.,0.,3.];');
vRin = [4.,2.,1.,0.,0.,3.];
disp('>>> vRout = [6.,2.,0.,0.,3.,2.];');
vRout = [6.,2.,0.,0.,3.,2.];
disp('>>> Rin = diag(vRin);');
Rin = diag(vRin);
disp('>>> Rout = diag(vRout);');
Rout = diag(vRout);
lambd = sum(CTMCSolve(Q)*Rin);
disp('>>> [qld, qlm] = FluidQueue(Q, Rin, Rout, ''qlDistr'', (0.:0.1:1.), ''qlMoms'', 5);');
[qld, qlm] = FluidQueue(Q, Rin, Rout, 'qlDistr', (0.:0.1:1.), 'qlMoms', 5);
disp('>>> disp(qld);');
disp(qld);
disp('>>> disp(qlm);');
disp(qlm);
disp('>>> [alphap, Ap] = FluidQueue(Q, Rin, Rout, ''qlDistrPH'');');
[alphap, Ap] = FluidQueue(Q, Rin, Rout, 'qlDistrPH');
disp('>>> disp(alphap);');
disp(alphap);
disp('>>> disp(Ap);');
disp(Ap);
disp('>>> [alpha, A] = FluidQueue(Q, Rin, Rout, ''qlDistrME'');');
[alpha, A] = FluidQueue(Q, Rin, Rout, 'qlDistrME');
disp('>>> disp(alpha);');
disp(alpha);
disp('>>> disp(A);');
disp(A);
disp('>>> qldFromPH = CdfFromPH(alphap, Ap, (0.:0.1:1.));');
qldFromPH = CdfFromPH(alphap, Ap, (0.:0.1:1.));
disp('>>> disp(qldFromPH);');
disp(qldFromPH);
disp('>>> qlmFromME = MomentsFromME(alpha, A, 5);');
qlmFromME = MomentsFromME(alpha, A, 5);
disp('>>> disp(qlmFromME);');
disp(qlmFromME);
disp('>>> [std, stm] = FluidQueue(Q, Rin, Rout, ''stDistr'', (0.:0.1:1.), ''stMoms'', 5);');
[std, stm] = FluidQueue(Q, Rin, Rout, 'stDistr', (0.:0.1:1.), 'stMoms', 5);
disp('>>> disp(std);');
disp(std);
disp('>>> disp(stm);');
disp(stm);
disp('>>> [betap, Bp] = FluidQueue(Q, Rin, Rout, ''stDistrPH'');');
[betap, Bp] = FluidQueue(Q, Rin, Rout, 'stDistrPH');
disp('>>> disp(betap);');
disp(betap);
disp('>>> disp(Bp);');
disp(Bp);
disp('>>> [beta, B] = FluidQueue(Q, Rin, Rout, ''stDistrME'');');
[beta, B] = FluidQueue(Q, Rin, Rout, 'stDistrME');
disp('>>> disp(beta);');
disp(beta);
disp('>>> disp(B);');
disp(B);
disp('>>> stdFromPH = CdfFromPH(betap, Bp, (0.:0.1:1.));');
stdFromPH = CdfFromPH(betap, Bp, (0.:0.1:1.));
disp('>>> disp(stdFromPH);');
disp(stdFromPH);
disp('>>> stmFromME = MomentsFromME(beta, B, 5);');
stmFromME = MomentsFromME(beta, B, 5);
disp('>>> disp(stmFromME);');
disp(stmFromME);
disp('=== FluFluQueue ===')
disp('>>> Qin = [-2., 1., 1.; 2., -5., 3.; 4., 0., -4.];');
Qin = [-2., 1., 1.; 2., -5., 3.; 4., 0., -4.];
disp('>>> vRin = [3.,7.,0.];');
vRin = [3.,7.,0.];
disp('>>> Rin = diag(vRin);');
Rin = diag(vRin);
disp('>>> Qout = [-4., 1., 3.; 6., -8., 2.; 3., 7., -10.];');
Qout = [-4., 1., 3.; 6., -8., 2.; 3., 7., -10.];
disp('>>> vRout = [1.,7.,15.];');
vRout = [1.,7.,15.];
disp('>>> Rout = diag(vRout);');
Rout = diag(vRout);
lambd = sum(CTMCSolve(Qin)*Rin);
disp('>>> [qld, qlm] = FluFluQueue(Qin, Rin, Qout, Rout, false, ''qlDistr'', (0.:0.1:1.), ''qlMoms'', 5);');
[qld, qlm] = FluFluQueue(Qin, Rin, Qout, Rout, false, 'qlDistr', (0.:0.1:1.), 'qlMoms', 5);
disp('>>> disp(qld);');
disp(qld);
disp('>>> disp(qlm);');
disp(qlm);
disp('>>> [alphap, Ap] = FluFluQueue(Qin, Rin, Qout, Rout, false, ''qlDistrPH'');');
[alphap, Ap] = FluFluQueue(Qin, Rin, Qout, Rout, false, 'qlDistrPH');
disp('>>> disp(alphap);');
disp(alphap);
disp('>>> disp(Ap);');
disp(Ap);
disp('>>> [alpha, A] = FluFluQueue(Qin, Rin, Qout, Rout, false, ''qlDistrME'');');
[alpha, A] = FluFluQueue(Qin, Rin, Qout, Rout, false, 'qlDistrME');
disp('>>> disp(alpha);');
disp(alpha);
disp('>>> disp(A);');
disp(A);
disp('>>> qldFromPH = CdfFromPH(alphap, Ap, (0.:0.1:1.));');
qldFromPH = CdfFromPH(alphap, Ap, (0.:0.1:1.));
disp('>>> disp(qldFromPH);');
disp(qldFromPH);
disp('>>> qlmFromME = MomentsFromME(alpha, A, 5);');
qlmFromME = MomentsFromME(alpha, A, 5);
disp('>>> disp(qlmFromME);');
disp(qlmFromME);
disp('>>> [std, stm] = FluFluQueue(Qin, Rin, Qout, Rout, false, ''stDistr'', (0.:0.1:1.), ''stMoms'', 5);');
[std, stm] = FluFluQueue(Qin, Rin, Qout, Rout, false, 'stDistr', (0.:0.1:1.), 'stMoms', 5);
disp('>>> disp(std);');
disp(std);
disp('>>> disp(stm);');
disp(stm);
disp('>>> [betap, Bp] = FluFluQueue(Qin, Rin, Qout, Rout, false, ''stDistrPH'');');
[betap, Bp] = FluFluQueue(Qin, Rin, Qout, Rout, false, 'stDistrPH');
disp('>>> disp(betap);');
disp(betap);
disp('>>> disp(Bp);');
disp(Bp);
disp('>>> [beta, B] = FluFluQueue(Qin, Rin, Qout, Rout, false, ''stDistrME'');');
[beta, B] = FluFluQueue(Qin, Rin, Qout, Rout, false, 'stDistrME');
disp('>>> disp(beta);');
disp(beta);
disp('>>> disp(B);');
disp(B);
disp('>>> stdFromPH = CdfFromPH(betap, Bp, (0.:0.1:1.));');
stdFromPH = CdfFromPH(betap, Bp, (0.:0.1:1.));
disp('>>> disp(stdFromPH);');
disp(stdFromPH);
disp('>>> stmFromME = MomentsFromME(beta, B, 5);');
stmFromME = MomentsFromME(beta, B, 5);
disp('>>> disp(stmFromME);');
disp(stmFromME);
Iin = eye(size(Qin,1));
Iout = eye(size(Qout,1));
BuToolsVerbose = false;
[gamma, G] = FluidQueue(kron(Qin, Iout)+kron(Iin, Qout), kron(Rin, Iout), kron(Iin, Rout), 'stDistrME');
BuToolsVerbose = true;
msmall = MomentsFromME(beta, B, 5);
mlarge = MomentsFromME(gamma, G, 5);
disp('>>> [qld, qlm] = FluFluQueue(Qin, Rin, Qout, Rout, true, ''qlDistr'', (0.:0.1:1.), ''qlMoms'', 5);');
[qld, qlm] = FluFluQueue(Qin, Rin, Qout, Rout, true, 'qlDistr', (0.:0.1:1.), 'qlMoms', 5);
disp('>>> disp(qld);');
disp(qld);
disp('>>> disp(qlm);');
disp(qlm);
disp('>>> [alphap, Ap] = FluFluQueue(Qin, Rin, Qout, Rout, true, ''qlDistrPH'');');
[alphap, Ap] = FluFluQueue(Qin, Rin, Qout, Rout, true, 'qlDistrPH');
disp('>>> disp(alphap);');
disp(alphap);
disp('>>> disp(Ap);');
disp(Ap);
disp('>>> [alpha, A] = FluFluQueue(Qin, Rin, Qout, Rout, true, ''qlDistrME'');');
[alpha, A] = FluFluQueue(Qin, Rin, Qout, Rout, true, 'qlDistrME');
disp('>>> disp(alpha);');
disp(alpha);
disp('>>> disp(A);');
disp(A);
disp('>>> qldFromPH = CdfFromPH(alphap, Ap, (0.:0.1:1.));');
qldFromPH = CdfFromPH(alphap, Ap, (0.:0.1:1.));
disp('>>> disp(qldFromPH);');
disp(qldFromPH);
disp('>>> qlmFromME = MomentsFromME(alpha, A, 5);');
qlmFromME = MomentsFromME(alpha, A, 5);
disp('>>> disp(qlmFromME);');
disp(qlmFromME);
disp('>>> [std, stm] = FluFluQueue(Qin, Rin, Qout, Rout, true, ''stDistr'', (0.:0.1:1.), ''stMoms'', 5);');
[std, stm] = FluFluQueue(Qin, Rin, Qout, Rout, true, 'stDistr', (0.:0.1:1.), 'stMoms', 5);
disp('>>> disp(std);');
disp(std);
disp('>>> disp(stm);');
disp(stm);
disp('>>> [betap, Bp] = FluFluQueue(Qin, Rin, Qout, Rout, true, ''stDistrPH'');');
[betap, Bp] = FluFluQueue(Qin, Rin, Qout, Rout, true, 'stDistrPH');
disp('>>> disp(betap);');
disp(betap);
disp('>>> disp(Bp);');
disp(Bp);
disp('>>> [beta, B] = FluFluQueue(Qin, Rin, Qout, Rout, true, ''stDistrME'');');
[beta, B] = FluFluQueue(Qin, Rin, Qout, Rout, true, 'stDistrME');
disp('>>> disp(beta);');
disp(beta);
disp('>>> disp(B);');
disp(B);
disp('>>> stdFromPH = CdfFromPH(betap, Bp, (0.:0.1:1.));');
stdFromPH = CdfFromPH(betap, Bp, (0.:0.1:1.));
disp('>>> disp(stdFromPH);');
disp(stdFromPH);
disp('>>> stmFromME = MomentsFromME(beta, B, 5);');
stmFromME = MomentsFromME(beta, B, 5);
disp('>>> disp(stmFromME);');
disp(stmFromME);
Iin = eye(size(Qin,1));
Iout = eye(size(Qout,1));
BuToolsVerbose = false;
[gamma, G] = FluidQueue(kron(Qin, Iout)+kron(Iin, Qout), kron(Rin, Iout), kron(Iin, Rout), 'Q0', kron(Qin, Iout)+kron(Rin, pinv(Rout)*Qout), 'stDistrME');
BuToolsVerbose = true;
msmall = MomentsFromME(beta, B, 5);
mlarge = MomentsFromME(gamma, G, 5);

