import sys
sys.path.append("/home/gabor/project/butools/Python")
import math
import numpy as np
import numpy.matlib as ml
import matplotlib.pyplot as plt
import butools
from butools.utils import *
from butools.ph import *
from butools.dph import *
from butools.map import *
from butools.moments import *
from butools.reptrans import*
from butools.mc import *
from butools.dmap import *
from butools.trace import *
from butools.mam import *
from butools.queues import *
from butools.fitting import *
from contextlib import redirect_stdout
import os


print('---BuTools: Queues package test file---')
print('Enable the verbose messages with the BuToolsVerbose flag')
butools.verbose = True
print('Enable input parameter checking with the BuToolsCheckInput flag')
butools.checkInput = True
np.set_printoptions(precision=5,linewidth=1024)
outFile = open('/home/gabor/project/butools/test/docex/Queues_python.docex','w')
with redirect_stdout(outFile):
    print('=== QBDQueue ===')
    print('>>> B = ml.matrix([[6., 1., 0.],[0., 4., 1.],[2., 0., 0.]])')
    B = ml.matrix([[6., 1., 0.],[0., 4., 1.],[2., 0., 0.]])
    print('>>> F = ml.matrix([[0., 1., 1.],[5., 0., 0.],[1., 3., 0.]])')
    F = ml.matrix([[0., 1., 1.],[5., 0., 0.],[1., 3., 0.]])
    print('>>> L = ml.matrix([[-14., 3., 2.],[0., -14., 4.],[3., 1., -10.]])')
    L = ml.matrix([[-14., 3., 2.],[0., -14., 4.],[3., 1., -10.]])
    print('>>> L0 = L+B')
    L0 = L+B
    print('>>> print(L0)')
    print(L0)
    butools.verbose = False
    pi0, R = QBDSolve(B, L, F, L0)
    lambd = np.sum(pi0*la.inv(ml.eye(R.shape[0])-R)*F)
    butools.verbose = True
    print('>>> ncd, ncm = QBDQueue(B, L, F, L0, "ncDistr", 11, "ncMoms", 5)')
    ncd, ncm = QBDQueue(B, L, F, L0, "ncDistr", 11, "ncMoms", 5)
    print('>>> print(ncd)')
    print(ncd)
    print('>>> print(ncm)')
    print(ncm)
    print('>>> alphap, Ap = QBDQueue(B, L, F, L0, "ncDistrDPH")')
    alphap, Ap = QBDQueue(B, L, F, L0, "ncDistrDPH")
    print('>>> print(alphap)')
    print(alphap)
    print('>>> print(Ap)')
    print(Ap)
    print('>>> alpha, A = QBDQueue(B, L, F, L0, "ncDistrMG")')
    alpha, A = QBDQueue(B, L, F, L0, "ncDistrMG")
    print('>>> print(alpha)')
    print(alpha)
    print('>>> print(A)')
    print(A)
    print('>>> ncdFromDPH = PmfFromDPH(alphap, Ap, np.arange(0,11.0,1))')
    ncdFromDPH = PmfFromDPH(alphap, Ap, np.arange(0,11.0,1))
    print('>>> print(ncdFromDPH)')
    print(ncdFromDPH)
    print('>>> ncmFromMG = MomentsFromMG(alpha, A, 5)')
    ncmFromMG = MomentsFromMG(alpha, A, 5)
    print('>>> print(ncmFromMG)')
    print(ncmFromMG)
    print('>>> std, stm = QBDQueue(B, L, F, L0, "stDistr", np.arange(0.,1.1,0.1), "stMoms", 5)')
    std, stm = QBDQueue(B, L, F, L0, "stDistr", np.arange(0.,1.1,0.1), "stMoms", 5)
    print('>>> print(std)')
    print(std)
    print('>>> print(stm)')
    print(stm)
    print('>>> betap, Bp = QBDQueue(B, L, F, L0, "stDistrPH")')
    betap, Bp = QBDQueue(B, L, F, L0, "stDistrPH")
    print('>>> print(betap)')
    print(betap)
    print('>>> print(Bp)')
    print(Bp)
    print('>>> beta, B = QBDQueue(B, L, F, L0, "stDistrME")')
    beta, B = QBDQueue(B, L, F, L0, "stDistrME")
    print('>>> print(beta)')
    print(beta)
    print('>>> print(B)')
    print(B)
    print('>>> stdFromPH = CdfFromPH(betap, Bp, np.arange(0.,1.1,0.1))')
    stdFromPH = CdfFromPH(betap, Bp, np.arange(0.,1.1,0.1))
    print('>>> print(stdFromPH)')
    print(stdFromPH)
    print('>>> stmFromME = MomentsFromME(beta, B, 5)')
    stmFromME = MomentsFromME(beta, B, 5)
    print('>>> print(stmFromME)')
    print(stmFromME)
    print('=== MAPMAP1 ===')
    print('>>> D0 = ml.matrix([[-8., 1., 2.],[0., -6., 4.],[3., 0., -3.]])')
    D0 = ml.matrix([[-8., 1., 2.],[0., -6., 4.],[3., 0., -3.]])
    print('>>> D1 = ml.matrix([[4., 1., 0.],[0., 2., 0.],[0., 0., 0.]])')
    D1 = ml.matrix([[4., 1., 0.],[0., 2., 0.],[0., 0., 0.]])
    print('>>> S0 = ml.matrix([[-10., 4.],[0., -7.]])')
    S0 = ml.matrix([[-10., 4.],[0., -7.]])
    print('>>> S1 = ml.matrix([[5., 1.],[4., 3.]])')
    S1 = ml.matrix([[5., 1.],[4., 3.]])
    lambd = 1./MarginalMomentsFromMAP(D0, D1, 1)[0]
    print('>>> ncd, ncm = MAPMAP1(D0, D1, S0, S1, "ncDistr", 11, "ncMoms", 5)')
    ncd, ncm = MAPMAP1(D0, D1, S0, S1, "ncDistr", 11, "ncMoms", 5)
    print('>>> print(ncd)')
    print(ncd)
    print('>>> print(ncm)')
    print(ncm)
    print('>>> alphap, Ap = MAPMAP1(D0, D1, S0, S1, "ncDistrDPH")')
    alphap, Ap = MAPMAP1(D0, D1, S0, S1, "ncDistrDPH")
    print('>>> print(alphap)')
    print(alphap)
    print('>>> print(Ap)')
    print(Ap)
    print('>>> alpha, A = MAPMAP1(D0, D1, S0, S1, "ncDistrMG")')
    alpha, A = MAPMAP1(D0, D1, S0, S1, "ncDistrMG")
    print('>>> print(alpha)')
    print(alpha)
    print('>>> print(A)')
    print(A)
    print('>>> ncdFromDPH = PmfFromDPH(alphap, Ap, np.arange(0,11.0,1))')
    ncdFromDPH = PmfFromDPH(alphap, Ap, np.arange(0,11.0,1))
    print('>>> print(ncdFromDPH)')
    print(ncdFromDPH)
    print('>>> ncmFromMG = MomentsFromMG(alpha, A, 5)')
    ncmFromMG = MomentsFromMG(alpha, A, 5)
    print('>>> print(ncmFromMG)')
    print(ncmFromMG)
    print('>>> std, stm = MAPMAP1(D0, D1, S0, S1, "stDistr", np.arange(0.,1.1,0.1), "stMoms", 5)')
    std, stm = MAPMAP1(D0, D1, S0, S1, "stDistr", np.arange(0.,1.1,0.1), "stMoms", 5)
    print('>>> print(std)')
    print(std)
    print('>>> print(stm)')
    print(stm)
    print('>>> betap, Bp = MAPMAP1(D0, D1, S0, S1, "stDistrPH")')
    betap, Bp = MAPMAP1(D0, D1, S0, S1, "stDistrPH")
    print('>>> print(betap)')
    print(betap)
    print('>>> print(Bp)')
    print(Bp)
    print('>>> beta, B = MAPMAP1(D0, D1, S0, S1, "stDistrME")')
    beta, B = MAPMAP1(D0, D1, S0, S1, "stDistrME")
    print('>>> print(beta)')
    print(beta)
    print('>>> print(B)')
    print(B)
    print('>>> stdFromPH = CdfFromPH(betap, Bp, np.arange(0.,1.1,0.1))')
    stdFromPH = CdfFromPH(betap, Bp, np.arange(0.,1.1,0.1))
    print('>>> print(stdFromPH)')
    print(stdFromPH)
    print('>>> stmFromME = MomentsFromME(beta, B, 5)')
    stmFromME = MomentsFromME(beta, B, 5)
    print('>>> print(stmFromME)')
    print(stmFromME)
    IA = ml.eye(D0.shape[0])
    IS = ml.eye(S0.shape[0])
    butools.verbose = False
    gamma, G = QBDQueue(ml.kron(IA, S1), ml.kron(D0, IS)+ml.kron(IA, S0), ml.kron(D1, IS), ml.kron(D0, IS), "stDistrME")
    butools.verbose = True
    msmall = MomentsFromME(beta, B, 5)
    mlarge = MomentsFromME(gamma, G, 5)
    print('>>> delta = ml.matrix([[0.5,0.1,0.4]])')
    delta = ml.matrix([[0.5,0.1,0.4]])
    print('>>> Dm = ml.matrix([[-8., 1., 2.],[0., -6., 4.],[3., 0., -3.]])')
    Dm = ml.matrix([[-8., 1., 2.],[0., -6., 4.],[3., 0., -3.]])
    print('>>> sigma = ml.matrix([[0.2,0.7,0.1]])')
    sigma = ml.matrix([[0.2,0.7,0.1]])
    print('>>> S = ml.matrix([[-10., 4., 0.],[5., -7., 2.],[1., 2., -8.]])')
    S = ml.matrix([[-10., 4., 0.],[5., -7., 2.],[1., 2., -8.]])
    print('>>> D0 = Dm')
    D0 = Dm
    print('>>> D1 = np.sum(-Dm,1)*delta')
    D1 = np.sum(-Dm,1)*delta
    print('>>> S0 = S')
    S0 = S
    print('>>> S1 = np.sum(-S,1)*sigma')
    S1 = np.sum(-S,1)*sigma
    lambd = 1./MarginalMomentsFromMAP(D0, D1, 1)[0]
    print('>>> ncd, ncm = MAPMAP1(D0, D1, S0, S1, "ncDistr", 11, "ncMoms", 5)')
    ncd, ncm = MAPMAP1(D0, D1, S0, S1, "ncDistr", 11, "ncMoms", 5)
    print('>>> print(ncd)')
    print(ncd)
    print('>>> print(ncm)')
    print(ncm)
    print('>>> alphap, Ap = MAPMAP1(D0, D1, S0, S1, "ncDistrDPH")')
    alphap, Ap = MAPMAP1(D0, D1, S0, S1, "ncDistrDPH")
    print('>>> print(alphap)')
    print(alphap)
    print('>>> print(Ap)')
    print(Ap)
    print('>>> alpha, A = MAPMAP1(D0, D1, S0, S1, "ncDistrMG")')
    alpha, A = MAPMAP1(D0, D1, S0, S1, "ncDistrMG")
    print('>>> print(alpha)')
    print(alpha)
    print('>>> print(A)')
    print(A)
    print('>>> ncdFromDPH = PmfFromDPH(alphap, Ap, np.arange(0,11.0,1))')
    ncdFromDPH = PmfFromDPH(alphap, Ap, np.arange(0,11.0,1))
    print('>>> print(ncdFromDPH)')
    print(ncdFromDPH)
    print('>>> ncmFromMG = MomentsFromMG(alpha, A, 5)')
    ncmFromMG = MomentsFromMG(alpha, A, 5)
    print('>>> print(ncmFromMG)')
    print(ncmFromMG)
    print('>>> std, stm = MAPMAP1(D0, D1, S0, S1, "stDistr", np.arange(0.,1.1,0.1), "stMoms", 5)')
    std, stm = MAPMAP1(D0, D1, S0, S1, "stDistr", np.arange(0.,1.1,0.1), "stMoms", 5)
    print('>>> print(std)')
    print(std)
    print('>>> print(stm)')
    print(stm)
    print('>>> betap, Bp = MAPMAP1(D0, D1, S0, S1, "stDistrPH")')
    betap, Bp = MAPMAP1(D0, D1, S0, S1, "stDistrPH")
    print('>>> print(betap)')
    print(betap)
    print('>>> print(Bp)')
    print(Bp)
    print('>>> beta, B = MAPMAP1(D0, D1, S0, S1, "stDistrME")')
    beta, B = MAPMAP1(D0, D1, S0, S1, "stDistrME")
    print('>>> print(beta)')
    print(beta)
    print('>>> print(B)')
    print(B)
    print('>>> stdFromPH = CdfFromPH(betap, Bp, np.arange(0.,1.1,0.1))')
    stdFromPH = CdfFromPH(betap, Bp, np.arange(0.,1.1,0.1))
    print('>>> print(stdFromPH)')
    print(stdFromPH)
    print('>>> stmFromME = MomentsFromME(beta, B, 5)')
    stmFromME = MomentsFromME(beta, B, 5)
    print('>>> print(stmFromME)')
    print(stmFromME)
    IA = ml.eye(D0.shape[0])
    IS = ml.eye(S0.shape[0])
    butools.verbose = False
    gamma, G = QBDQueue(ml.kron(IA, S1), ml.kron(D0, IS)+ml.kron(IA, S0), ml.kron(D1, IS), ml.kron(D0, IS), "stDistrME")
    butools.verbose = True
    msmall = MomentsFromME(beta, B, 5)
    mlarge = MomentsFromME(gamma, G, 5)
    print('=== MMAPPH1PRPR ===')
    print('>>> D0 = ml.matrix([[-5.49, 0., 1.15, 0.],[0., -2.29, 0., 0.],[0., 0.08, -1.32, 0.],[0.72, 1.17, 0.7, -7.07]])')
    D0 = ml.matrix([[-5.49, 0., 1.15, 0.],[0., -2.29, 0., 0.],[0., 0.08, -1.32, 0.],[0.72, 1.17, 0.7, -7.07]])
    print('>>> D1 = ml.matrix([[0.25, 0.38, 0.64, 0.],[0., 0., 0., 1.09],[0., 1.24, 0., 0.],[0.37, 0., 0., 0.]])')
    D1 = ml.matrix([[0.25, 0.38, 0.64, 0.],[0., 0., 0., 1.09],[0., 1.24, 0., 0.],[0.37, 0., 0., 0.]])
    print('>>> D2 = ml.matrix([[0.3, 1.0, 0., 0.48],[0., 0.2, 0., 0.],[0., 0., 0., 0.],[0.61, 0., 0., 0.2]])')
    D2 = ml.matrix([[0.3, 1.0, 0., 0.48],[0., 0.2, 0., 0.],[0., 0., 0., 0.],[0.61, 0., 0., 0.2]])
    print('>>> D3 = ml.matrix([[0., 0.98, 0., 0.31],[0., 0., 1.0, 0.],[0., 0., 0., 0.],[1.1, 0.84, 0.33, 1.03]])')
    D3 = ml.matrix([[0., 0.98, 0., 0.31],[0., 0., 1.0, 0.],[0., 0., 0., 0.],[1.1, 0.84, 0.33, 1.03]])
    print('>>> sigma3 = ml.matrix([[0.83333,0.11404,0.05263]])')
    sigma3 = ml.matrix([[0.83333,0.11404,0.05263]])
    print('>>> S3 = ml.matrix([[-3., 0., 0.],[0.73077, -0.73077, 0.],[0., 0.5, -0.5]])')
    S3 = ml.matrix([[-3., 0., 0.],[0.73077, -0.73077, 0.],[0., 0.5, -0.5]])
    print('>>> sigma2 = ml.matrix([[1.]])')
    sigma2 = ml.matrix([[1.]])
    print('>>> S2 = ml.matrix([[-2.]])')
    S2 = ml.matrix([[-2.]])
    print('>>> sigma1 = ml.matrix([[0.25,0.75]])')
    sigma1 = ml.matrix([[0.25,0.75]])
    print('>>> S1 = ml.matrix([[-2.5, 2.5],[0., -10.]])')
    S1 = ml.matrix([[-2.5, 2.5],[0., -10.]])
    print('>>> ncm1, ncd1, ncm2, ncd2, ncm3, ncd3 = MMAPPH1PRPR([D0, D1, D2, D3], [sigma1, sigma2, sigma3], [S1, S2, S3], "ncMoms", 3, "ncDistr", 500)')
    ncm1, ncd1, ncm2, ncd2, ncm3, ncd3 = MMAPPH1PRPR([D0, D1, D2, D3], [sigma1, sigma2, sigma3], [S1, S2, S3], "ncMoms", 3, "ncDistr", 500)
    momFromDistr1 = ncd1*ml.vstack((ml.matrix(np.arange(0,500.0,1)),ml.matrix(np.arange(0,500.0,1)**2),ml.matrix(np.arange(0,500.0,1)**3))).T
    momFromDistr2 = ncd2*ml.vstack((ml.matrix(np.arange(0,500.0,1)),ml.matrix(np.arange(0,500.0,1)**2),ml.matrix(np.arange(0,500.0,1)**3))).T
    momFromDistr3 = ncd3*ml.vstack((ml.matrix(np.arange(0,500.0,1)),ml.matrix(np.arange(0,500.0,1)**2),ml.matrix(np.arange(0,500.0,1)**3))).T
    print('>>> distrPoints = [1., 5., 10.]')
    distrPoints = [1., 5., 10.]
    print('>>> stm1, std1, stm2, std2, stm3, std3 = MMAPPH1PRPR([D0, D1, D2, D3], [sigma1, sigma2, sigma3], [S1, S2, S3], "stMoms", 3, "stDistr", distrPoints)')
    stm1, std1, stm2, std2, stm3, std3 = MMAPPH1PRPR([D0, D1, D2, D3], [sigma1, sigma2, sigma3], [S1, S2, S3], "stMoms", 3, "stDistr", distrPoints)
    print('>>> print(stm1)')
    print(stm1)
    print('>>> print(std1)')
    print(std1)
    print('>>> print(stm2)')
    print(stm2)
    print('>>> print(std2)')
    print(std2)
    print('>>> print(stm3)')
    print(stm3)
    print('>>> print(std3)')
    print(std3)
    lambda1 = 1./MarginalMomentsFromMAP(D0+D2+D3, D1, 1)[0]
    lambda2 = 1./MarginalMomentsFromMAP(D0+D1+D3, D2, 1)[0]
    lambda3 = 1./MarginalMomentsFromMAP(D0+D1+D2, D3, 1)[0]
    print('=== MMAPPH1NPPR ===')
    print('>>> D0 = ml.matrix([[-5.49, 0., 1.15, 0.],[0., -2.29, 0., 0.],[0., 0.08, -1.32, 0.],[0.72, 1.17, 0.7, -7.07]])')
    D0 = ml.matrix([[-5.49, 0., 1.15, 0.],[0., -2.29, 0., 0.],[0., 0.08, -1.32, 0.],[0.72, 1.17, 0.7, -7.07]])
    print('>>> D1 = ml.matrix([[0.25, 0.38, 0.64, 0.],[0., 0., 0., 1.09],[0., 1.24, 0., 0.],[0.37, 0., 0., 0.]])')
    D1 = ml.matrix([[0.25, 0.38, 0.64, 0.],[0., 0., 0., 1.09],[0., 1.24, 0., 0.],[0.37, 0., 0., 0.]])
    print('>>> D2 = ml.matrix([[0.3, 1.0, 0., 0.48],[0., 0.2, 0., 0.],[0., 0., 0., 0.],[0.61, 0., 0., 0.2]])')
    D2 = ml.matrix([[0.3, 1.0, 0., 0.48],[0., 0.2, 0., 0.],[0., 0., 0., 0.],[0.61, 0., 0., 0.2]])
    print('>>> D3 = ml.matrix([[0., 0.98, 0., 0.31],[0., 0., 1.0, 0.],[0., 0., 0., 0.],[1.1, 0.84, 0.33, 1.03]])')
    D3 = ml.matrix([[0., 0.98, 0., 0.31],[0., 0., 1.0, 0.],[0., 0., 0., 0.],[1.1, 0.84, 0.33, 1.03]])
    print('>>> sigma3 = ml.matrix([[0.83333,0.11404,0.05263]])')
    sigma3 = ml.matrix([[0.83333,0.11404,0.05263]])
    print('>>> S3 = ml.matrix([[-3., 0., 0.],[0.73077, -0.73077, 0.],[0., 0.5, -0.5]])')
    S3 = ml.matrix([[-3., 0., 0.],[0.73077, -0.73077, 0.],[0., 0.5, -0.5]])
    print('>>> sigma2 = ml.matrix([[1.]])')
    sigma2 = ml.matrix([[1.]])
    print('>>> S2 = ml.matrix([[-2.]])')
    S2 = ml.matrix([[-2.]])
    print('>>> sigma1 = ml.matrix([[0.25,0.75]])')
    sigma1 = ml.matrix([[0.25,0.75]])
    print('>>> S1 = ml.matrix([[-2.5, 2.5],[0., -10.]])')
    S1 = ml.matrix([[-2.5, 2.5],[0., -10.]])
    print('>>> ncm1, ncd1, ncm2, ncd2, ncm3, ncd3 = MMAPPH1NPPR([D0, D1, D2, D3], [sigma1, sigma2, sigma3], [S1, S2, S3], "ncMoms", 3, "ncDistr", 500)')
    ncm1, ncd1, ncm2, ncd2, ncm3, ncd3 = MMAPPH1NPPR([D0, D1, D2, D3], [sigma1, sigma2, sigma3], [S1, S2, S3], "ncMoms", 3, "ncDistr", 500)
    momFromDistr1 = ncd1*ml.vstack((ml.matrix(np.arange(0,500.0,1)),ml.matrix(np.arange(0,500.0,1)**2),ml.matrix(np.arange(0,500.0,1)**3))).T
    momFromDistr2 = ncd2*ml.vstack((ml.matrix(np.arange(0,500.0,1)),ml.matrix(np.arange(0,500.0,1)**2),ml.matrix(np.arange(0,500.0,1)**3))).T
    momFromDistr3 = ncd3*ml.vstack((ml.matrix(np.arange(0,500.0,1)),ml.matrix(np.arange(0,500.0,1)**2),ml.matrix(np.arange(0,500.0,1)**3))).T
    print('>>> distrPoints = [1., 5., 10.]')
    distrPoints = [1., 5., 10.]
    print('>>> stm1, std1, stm2, std2, stm3, std3 = MMAPPH1NPPR([D0, D1, D2, D3], [sigma1, sigma2, sigma3], [S1, S2, S3], "stMoms", 3, "stDistr", distrPoints)')
    stm1, std1, stm2, std2, stm3, std3 = MMAPPH1NPPR([D0, D1, D2, D3], [sigma1, sigma2, sigma3], [S1, S2, S3], "stMoms", 3, "stDistr", distrPoints)
    print('>>> print(stm1)')
    print(stm1)
    print('>>> print(std1)')
    print(std1)
    print('>>> print(stm2)')
    print(stm2)
    print('>>> print(std2)')
    print(std2)
    print('>>> print(stm3)')
    print(stm3)
    print('>>> print(std3)')
    print(std3)
    lambda1 = 1./MarginalMomentsFromMAP(D0+D2+D3, D1, 1)[0]
    lambda2 = 1./MarginalMomentsFromMAP(D0+D1+D3, D2, 1)[0]
    lambda3 = 1./MarginalMomentsFromMAP(D0+D1+D2, D3, 1)[0]
    print('=== MMAPPH1FCFS ===')
    print('>>> D0 = ml.matrix([[-5.49, 0., 1.15, 0.],[0., -2.29, 0., 0.],[0., 0.08, -1.32, 0.],[0.72, 1.17, 0.7, -7.07]])')
    D0 = ml.matrix([[-5.49, 0., 1.15, 0.],[0., -2.29, 0., 0.],[0., 0.08, -1.32, 0.],[0.72, 1.17, 0.7, -7.07]])
    print('>>> D1 = ml.matrix([[0.25, 0.38, 0.64, 0.],[0., 0., 0., 1.09],[0., 1.24, 0., 0.],[0.37, 0., 0., 0.]])')
    D1 = ml.matrix([[0.25, 0.38, 0.64, 0.],[0., 0., 0., 1.09],[0., 1.24, 0., 0.],[0.37, 0., 0., 0.]])
    print('>>> D2 = ml.matrix([[0.3, 1.0, 0., 0.48],[0., 0.2, 0., 0.],[0., 0., 0., 0.],[0.61, 0., 0., 0.2]])')
    D2 = ml.matrix([[0.3, 1.0, 0., 0.48],[0., 0.2, 0., 0.],[0., 0., 0., 0.],[0.61, 0., 0., 0.2]])
    print('>>> D3 = ml.matrix([[0., 0.98, 0., 0.31],[0., 0., 1.0, 0.],[0., 0., 0., 0.],[1.1, 0.84, 0.33, 1.03]])')
    D3 = ml.matrix([[0., 0.98, 0., 0.31],[0., 0., 1.0, 0.],[0., 0., 0., 0.],[1.1, 0.84, 0.33, 1.03]])
    print('>>> sigma3 = ml.matrix([[0.83333,0.11404,0.05263]])')
    sigma3 = ml.matrix([[0.83333,0.11404,0.05263]])
    print('>>> S3 = ml.matrix([[-3., 0., 0.],[0.73077, -0.73077, 0.],[0., 0.5, -0.5]])')
    S3 = ml.matrix([[-3., 0., 0.],[0.73077, -0.73077, 0.],[0., 0.5, -0.5]])
    print('>>> sigma2 = ml.matrix([[1.]])')
    sigma2 = ml.matrix([[1.]])
    print('>>> S2 = ml.matrix([[-2.]])')
    S2 = ml.matrix([[-2.]])
    print('>>> sigma1 = ml.matrix([[0.25,0.75]])')
    sigma1 = ml.matrix([[0.25,0.75]])
    print('>>> S1 = ml.matrix([[-2.5, 2.5],[0., -10.]])')
    S1 = ml.matrix([[-2.5, 2.5],[0., -10.]])
    print('>>> ncm1, ncd1, ncm2, ncd2, ncm3, ncd3 = MMAPPH1FCFS([D0, D1, D2, D3], [sigma1, sigma2, sigma3], [S1, S2, S3], "ncMoms", 3, "ncDistr", 500)')
    ncm1, ncd1, ncm2, ncd2, ncm3, ncd3 = MMAPPH1FCFS([D0, D1, D2, D3], [sigma1, sigma2, sigma3], [S1, S2, S3], "ncMoms", 3, "ncDistr", 500)
    momFromDistr1 = ncd1*ml.vstack((ml.matrix(np.arange(0,500.0,1)),ml.matrix(np.arange(0,500.0,1)**2),ml.matrix(np.arange(0,500.0,1)**3))).T
    momFromDistr2 = ncd2*ml.vstack((ml.matrix(np.arange(0,500.0,1)),ml.matrix(np.arange(0,500.0,1)**2),ml.matrix(np.arange(0,500.0,1)**3))).T
    momFromDistr3 = ncd3*ml.vstack((ml.matrix(np.arange(0,500.0,1)),ml.matrix(np.arange(0,500.0,1)**2),ml.matrix(np.arange(0,500.0,1)**3))).T
    print('>>> distrPoints = [1., 5., 10.]')
    distrPoints = [1., 5., 10.]
    print('>>> stm1, std1, stm2, std2, stm3, std3 = MMAPPH1FCFS([D0, D1, D2, D3], [sigma1, sigma2, sigma3], [S1, S2, S3], "stMoms", 3, "stDistr", distrPoints)')
    stm1, std1, stm2, std2, stm3, std3 = MMAPPH1FCFS([D0, D1, D2, D3], [sigma1, sigma2, sigma3], [S1, S2, S3], "stMoms", 3, "stDistr", distrPoints)
    print('>>> print(stm1)')
    print(stm1)
    print('>>> print(std1)')
    print(std1)
    print('>>> print(stm2)')
    print(stm2)
    print('>>> print(std2)')
    print(std2)
    print('>>> print(stm3)')
    print(stm3)
    print('>>> print(std3)')
    print(std3)
    print('>>> betap1, Bp1, betap2, Bp2, betap3, Bp3 = MMAPPH1FCFS([D0, D1, D2, D3], [sigma1, sigma2, sigma3], [S1, S2, S3], "stDistrPH")')
    betap1, Bp1, betap2, Bp2, betap3, Bp3 = MMAPPH1FCFS([D0, D1, D2, D3], [sigma1, sigma2, sigma3], [S1, S2, S3], "stDistrPH")
    print('>>> beta1, B1, beta2, B2, beta3, B3 = MMAPPH1FCFS([D0, D1, D2, D3], [sigma1, sigma2, sigma3], [S1, S2, S3], "stDistrME")')
    beta1, B1, beta2, B2, beta3, B3 = MMAPPH1FCFS([D0, D1, D2, D3], [sigma1, sigma2, sigma3], [S1, S2, S3], "stDistrME")
    print('>>> stdFromPH1 = CdfFromPH(betap1, Bp1, distrPoints)')
    stdFromPH1 = CdfFromPH(betap1, Bp1, distrPoints)
    print('>>> print(stdFromPH1)')
    print(stdFromPH1)
    print('>>> stmFromME1 = MomentsFromME(beta1, B1, 3)')
    stmFromME1 = MomentsFromME(beta1, B1, 3)
    print('>>> print(stmFromME1)')
    print(stmFromME1)
    print('>>> stdFromPH2 = CdfFromPH(betap2, Bp2, distrPoints)')
    stdFromPH2 = CdfFromPH(betap2, Bp2, distrPoints)
    print('>>> print(stdFromPH2)')
    print(stdFromPH2)
    print('>>> stmFromME2 = MomentsFromME(beta2, B2, 3)')
    stmFromME2 = MomentsFromME(beta2, B2, 3)
    print('>>> print(stmFromME2)')
    print(stmFromME2)
    print('>>> stdFromPH3 = CdfFromPH(betap3, Bp3, distrPoints)')
    stdFromPH3 = CdfFromPH(betap3, Bp3, distrPoints)
    print('>>> print(stdFromPH3)')
    print(stdFromPH3)
    print('>>> stmFromME3 = MomentsFromME(beta3, B3, 3)')
    stmFromME3 = MomentsFromME(beta3, B3, 3)
    print('>>> print(stmFromME3)')
    print(stmFromME3)
    lambda1 = 1./MarginalMomentsFromMAP(D0+D2+D3, D1, 1)[0]
    lambda2 = 1./MarginalMomentsFromMAP(D0+D1+D3, D2, 1)[0]
    lambda3 = 1./MarginalMomentsFromMAP(D0+D1+D2, D3, 1)[0]
    print('=== FluidQueue ===')
    print('>>> Q = ml.matrix([[-9., 2., 4., 0., 1., 2.],[6., -25., 5., 3., 7., 4.],[1., 3., -4., 0., 0., 0.],[0., 0., 0., -8., 3., 5.],[7., 3., 0., 2., -13., 1.],[7., 8., 0., 3., 8., -26.]])')
    Q = ml.matrix([[-9., 2., 4., 0., 1., 2.],[6., -25., 5., 3., 7., 4.],[1., 3., -4., 0., 0., 0.],[0., 0., 0., -8., 3., 5.],[7., 3., 0., 2., -13., 1.],[7., 8., 0., 3., 8., -26.]])
    print('>>> vRin = ml.matrix([[4.,2.,1.,0.,0.,3.]])')
    vRin = ml.matrix([[4.,2.,1.,0.,0.,3.]])
    print('>>> vRout = ml.matrix([[6.,2.,0.,0.,3.,2.]])')
    vRout = ml.matrix([[6.,2.,0.,0.,3.,2.]])
    print('>>> Rin = Diag(vRin)')
    Rin = Diag(vRin)
    print('>>> Rout = Diag(vRout)')
    Rout = Diag(vRout)
    lambd = np.sum(CTMCSolve(Q)*Rin)
    print('>>> fld, flm = FluidQueue(Q, Rin, Rout, "flDistr", np.arange(0.,1.1,0.1), "flMoms", 5)')
    fld, flm = FluidQueue(Q, Rin, Rout, "flDistr", np.arange(0.,1.1,0.1), "flMoms", 5)
    print('>>> print(fld)')
    print(fld)
    print('>>> print(flm)')
    print(flm)
    print('>>> alphap, Ap = FluidQueue(Q, Rin, Rout, "flDistrPH")')
    alphap, Ap = FluidQueue(Q, Rin, Rout, "flDistrPH")
    print('>>> print(alphap)')
    print(alphap)
    print('>>> print(Ap)')
    print(Ap)
    print('>>> alpha, A = FluidQueue(Q, Rin, Rout, "flDistrME")')
    alpha, A = FluidQueue(Q, Rin, Rout, "flDistrME")
    print('>>> print(alpha)')
    print(alpha)
    print('>>> print(A)')
    print(A)
    print('>>> fldFromPH = CdfFromPH(alphap, Ap, np.arange(0.,1.1,0.1))')
    fldFromPH = CdfFromPH(alphap, Ap, np.arange(0.,1.1,0.1))
    print('>>> print(fldFromPH)')
    print(fldFromPH)
    print('>>> flmFromME = MomentsFromME(alpha, A, 5)')
    flmFromME = MomentsFromME(alpha, A, 5)
    print('>>> print(flmFromME)')
    print(flmFromME)
    print('>>> std, stm = FluidQueue(Q, Rin, Rout, "stDistr", np.arange(0.,1.1,0.1), "stMoms", 5)')
    std, stm = FluidQueue(Q, Rin, Rout, "stDistr", np.arange(0.,1.1,0.1), "stMoms", 5)
    print('>>> print(std)')
    print(std)
    print('>>> print(stm)')
    print(stm)
    print('>>> betap, Bp = FluidQueue(Q, Rin, Rout, "stDistrPH")')
    betap, Bp = FluidQueue(Q, Rin, Rout, "stDistrPH")
    print('>>> print(betap)')
    print(betap)
    print('>>> print(Bp)')
    print(Bp)
    print('>>> beta, B = FluidQueue(Q, Rin, Rout, "stDistrME")')
    beta, B = FluidQueue(Q, Rin, Rout, "stDistrME")
    print('>>> print(beta)')
    print(beta)
    print('>>> print(B)')
    print(B)
    print('>>> stdFromPH = CdfFromPH(betap, Bp, np.arange(0.,1.1,0.1))')
    stdFromPH = CdfFromPH(betap, Bp, np.arange(0.,1.1,0.1))
    print('>>> print(stdFromPH)')
    print(stdFromPH)
    print('>>> stmFromME = MomentsFromME(beta, B, 5)')
    stmFromME = MomentsFromME(beta, B, 5)
    print('>>> print(stmFromME)')
    print(stmFromME)
    print('=== FluFluQueue ===')
    print('>>> Qin = ml.matrix([[-2., 1., 1.],[2., -5., 3.],[4., 0., -4.]])')
    Qin = ml.matrix([[-2., 1., 1.],[2., -5., 3.],[4., 0., -4.]])
    print('>>> vRin = ml.matrix([[3.,7.,0.]])')
    vRin = ml.matrix([[3.,7.,0.]])
    print('>>> Rin = Diag(vRin)')
    Rin = Diag(vRin)
    print('>>> Qout = ml.matrix([[-4., 1., 3.],[6., -8., 2.],[3., 7., -10.]])')
    Qout = ml.matrix([[-4., 1., 3.],[6., -8., 2.],[3., 7., -10.]])
    print('>>> vRout = ml.matrix([[1.,7.,15.]])')
    vRout = ml.matrix([[1.,7.,15.]])
    print('>>> Rout = Diag(vRout)')
    Rout = Diag(vRout)
    lambd = np.sum(CTMCSolve(Qin)*Rin)
    print('>>> fld, flm = FluFluQueue(Qin, Rin, Qout, Rout, False, "flDistr", np.arange(0.,1.1,0.1), "flMoms", 5)')
    fld, flm = FluFluQueue(Qin, Rin, Qout, Rout, False, "flDistr", np.arange(0.,1.1,0.1), "flMoms", 5)
    print('>>> print(fld)')
    print(fld)
    print('>>> print(flm)')
    print(flm)
    print('>>> alphap, Ap = FluFluQueue(Qin, Rin, Qout, Rout, False, "flDistrPH")')
    alphap, Ap = FluFluQueue(Qin, Rin, Qout, Rout, False, "flDistrPH")
    print('>>> print(alphap)')
    print(alphap)
    print('>>> print(Ap)')
    print(Ap)
    print('>>> alpha, A = FluFluQueue(Qin, Rin, Qout, Rout, False, "flDistrME")')
    alpha, A = FluFluQueue(Qin, Rin, Qout, Rout, False, "flDistrME")
    print('>>> print(alpha)')
    print(alpha)
    print('>>> print(A)')
    print(A)
    print('>>> fldFromPH = CdfFromPH(alphap, Ap, np.arange(0.,1.1,0.1))')
    fldFromPH = CdfFromPH(alphap, Ap, np.arange(0.,1.1,0.1))
    print('>>> print(fldFromPH)')
    print(fldFromPH)
    print('>>> flmFromME = MomentsFromME(alpha, A, 5)')
    flmFromME = MomentsFromME(alpha, A, 5)
    print('>>> print(flmFromME)')
    print(flmFromME)
    print('>>> std, stm = FluFluQueue(Qin, Rin, Qout, Rout, False, "stDistr", np.arange(0.,1.1,0.1), "stMoms", 5)')
    std, stm = FluFluQueue(Qin, Rin, Qout, Rout, False, "stDistr", np.arange(0.,1.1,0.1), "stMoms", 5)
    print('>>> print(std)')
    print(std)
    print('>>> print(stm)')
    print(stm)
    print('>>> betap, Bp = FluFluQueue(Qin, Rin, Qout, Rout, False, "stDistrPH")')
    betap, Bp = FluFluQueue(Qin, Rin, Qout, Rout, False, "stDistrPH")
    print('>>> print(betap)')
    print(betap)
    print('>>> print(Bp)')
    print(Bp)
    print('>>> beta, B = FluFluQueue(Qin, Rin, Qout, Rout, False, "stDistrME")')
    beta, B = FluFluQueue(Qin, Rin, Qout, Rout, False, "stDistrME")
    print('>>> print(beta)')
    print(beta)
    print('>>> print(B)')
    print(B)
    print('>>> stdFromPH = CdfFromPH(betap, Bp, np.arange(0.,1.1,0.1))')
    stdFromPH = CdfFromPH(betap, Bp, np.arange(0.,1.1,0.1))
    print('>>> print(stdFromPH)')
    print(stdFromPH)
    print('>>> stmFromME = MomentsFromME(beta, B, 5)')
    stmFromME = MomentsFromME(beta, B, 5)
    print('>>> print(stmFromME)')
    print(stmFromME)
    Iin = ml.eye(Qin.shape[0])
    Iout = ml.eye(Qout.shape[0])
    butools.verbose = False
    gamma, G = FluidQueue(ml.kron(Qin, Iout)+ml.kron(Iin, Qout), ml.kron(Rin, Iout), ml.kron(Iin, Rout), "stDistrME")
    butools.verbose = True
    msmall = MomentsFromME(beta, B, 5)
    mlarge = MomentsFromME(gamma, G, 5)
    print('>>> fld, flm = FluFluQueue(Qin, Rin, Qout, Rout, True, "flDistr", np.arange(0.,1.1,0.1), "flMoms", 5)')
    fld, flm = FluFluQueue(Qin, Rin, Qout, Rout, True, "flDistr", np.arange(0.,1.1,0.1), "flMoms", 5)
    print('>>> print(fld)')
    print(fld)
    print('>>> print(flm)')
    print(flm)
    print('>>> alphap, Ap = FluFluQueue(Qin, Rin, Qout, Rout, True, "flDistrPH")')
    alphap, Ap = FluFluQueue(Qin, Rin, Qout, Rout, True, "flDistrPH")
    print('>>> print(alphap)')
    print(alphap)
    print('>>> print(Ap)')
    print(Ap)
    print('>>> alpha, A = FluFluQueue(Qin, Rin, Qout, Rout, True, "flDistrME")')
    alpha, A = FluFluQueue(Qin, Rin, Qout, Rout, True, "flDistrME")
    print('>>> print(alpha)')
    print(alpha)
    print('>>> print(A)')
    print(A)
    print('>>> fldFromPH = CdfFromPH(alphap, Ap, np.arange(0.,1.1,0.1))')
    fldFromPH = CdfFromPH(alphap, Ap, np.arange(0.,1.1,0.1))
    print('>>> print(fldFromPH)')
    print(fldFromPH)
    print('>>> flmFromME = MomentsFromME(alpha, A, 5)')
    flmFromME = MomentsFromME(alpha, A, 5)
    print('>>> print(flmFromME)')
    print(flmFromME)
    print('>>> std, stm = FluFluQueue(Qin, Rin, Qout, Rout, True, "stDistr", np.arange(0.,1.1,0.1), "stMoms", 5)')
    std, stm = FluFluQueue(Qin, Rin, Qout, Rout, True, "stDistr", np.arange(0.,1.1,0.1), "stMoms", 5)
    print('>>> print(std)')
    print(std)
    print('>>> print(stm)')
    print(stm)
    print('>>> betap, Bp = FluFluQueue(Qin, Rin, Qout, Rout, True, "stDistrPH")')
    betap, Bp = FluFluQueue(Qin, Rin, Qout, Rout, True, "stDistrPH")
    print('>>> print(betap)')
    print(betap)
    print('>>> print(Bp)')
    print(Bp)
    print('>>> beta, B = FluFluQueue(Qin, Rin, Qout, Rout, True, "stDistrME")')
    beta, B = FluFluQueue(Qin, Rin, Qout, Rout, True, "stDistrME")
    print('>>> print(beta)')
    print(beta)
    print('>>> print(B)')
    print(B)
    print('>>> stdFromPH = CdfFromPH(betap, Bp, np.arange(0.,1.1,0.1))')
    stdFromPH = CdfFromPH(betap, Bp, np.arange(0.,1.1,0.1))
    print('>>> print(stdFromPH)')
    print(stdFromPH)
    print('>>> stmFromME = MomentsFromME(beta, B, 5)')
    stmFromME = MomentsFromME(beta, B, 5)
    print('>>> print(stmFromME)')
    print(stmFromME)
    Iin = ml.eye(Qin.shape[0])
    Iout = ml.eye(Qout.shape[0])
    butools.verbose = False
    gamma, G = FluidQueue(ml.kron(Qin, Iout)+ml.kron(Iin, Qout), ml.kron(Rin, Iout), ml.kron(Iin, Rout), "Q0", ml.kron(Qin, Iout)+ml.kron(Rin, la.pinv(Rout)*Qout), "stDistrME")
    butools.verbose = True
    msmall = MomentsFromME(beta, B, 5)
    mlarge = MomentsFromME(gamma, G, 5)

