MCMathematicaGendocex[]:=
Module[{ret, Q, tmpOut, stream, flag},
	Unprotect[Print];
	Print[args___] := Block[{$inMsg = True, result, str},
	   If[MatrixQ[args],
	    str = "{";
	    Do[str = StringJoin[str, ToString[args[[r]], FormatType -> InputForm]]; 
	     If[r < Length[args], str = StringJoin[str, ",\n "]], {r, Length[args]}];
	    str = StringJoin[str, "}"]; Print[str//OutputForm],
	    result = Print[args],
	    result = Print[args]
	    ]] /; ! TrueQ[$inMsg];
	Print["---BuTools: MC package test file---"//OutputForm];
	Print["Enable the verbose messages with the BuToolsVerbose flag"//OutputForm];
	BuTools`Verbose = True;
	Print["Enable input parameter checking with the BuToolsCheckInput flag"//OutputForm];
	BuTools`CheckInput = True;
	On[Assert];
	tmpOut = $Output;
	stream = OpenWrite["MC_mathematica.docex", FormatType -> InputForm, PageWidth -> Infinity];
	$Output = {stream};
	Print["=== CRPSolve ==="//OutputForm];
	Print[">>> Q = {{-4.3, 3.5, 0.8},{-8.4, 6.5, 1.9},{17.3, -12.7, -4.6}};"//OutputForm];
	Q = {{-4.3, 3.5, 0.8},{-8.4, 6.5, 1.9},{17.3, -12.7, -4.6}};
	Print[">>> ret = CRPSolve[Q];"//OutputForm];
	ret = CRPSolve[Q];
	Print[">>> Print[ret];"//OutputForm];
	Print[ret];
	Print[">>> Print[ret.Q];"//OutputForm];
	Print[ret.Q];
	Print["=== DRPSolve ==="//OutputForm];
	Print[">>> Q = {{-0.9, 0.5, 1.4},{0.9, -0.9, 1},{0.3, 1.3, -0.6}};"//OutputForm];
	Q = {{-0.9, 0.5, 1.4},{0.9, -0.9, 1},{0.3, 1.3, -0.6}};
	Print[">>> ret = DRPSolve[Q];"//OutputForm];
	ret = DRPSolve[Q];
	Print[">>> Print[ret];"//OutputForm];
	Print[ret];
	Print[">>> Print[ret.Q - ret];"//OutputForm];
	Print[ret.Q - ret];
	Print["=== CTMCSolve ==="//OutputForm];
	Print[">>> Q = {{-0.9, 0.5, 0.4},{0.9, -0.9, 0},{0.3, 0.3, -0.6}};"//OutputForm];
	Q = {{-0.9, 0.5, 0.4},{0.9, -0.9, 0},{0.3, 0.3, -0.6}};
	Print[">>> ret = CTMCSolve[Q];"//OutputForm];
	ret = CTMCSolve[Q];
	Print[">>> Print[ret];"//OutputForm];
	Print[ret];
	Print[">>> Print[ret.Q];"//OutputForm];
	Print[ret.Q];
	Print["=== DTMCSolve ==="//OutputForm];
	Print[">>> Q = {{0.1, 0.5, 0.4},{0.9, 0.1, 0},{0.3, 0.3, 0.4}};"//OutputForm];
	Q = {{0.1, 0.5, 0.4},{0.9, 0.1, 0},{0.3, 0.3, 0.4}};
	Print[">>> ret = DTMCSolve[Q];"//OutputForm];
	ret = DTMCSolve[Q];
	Print[">>> Print[ret];"//OutputForm];
	Print[ret];
	Print[">>> Print[ret.Q - ret];"//OutputForm];
	Print[ret.Q - ret];
	Print["=== CheckGenerator ==="//OutputForm];
	Print[">>> Q = {{-0.9, 0.2, 0.4},{0, 0.9, 0.9},{0, 0.6, -0.6}};"//OutputForm];
	Q = {{-0.9, 0.2, 0.4},{0, 0.9, 0.9},{0, 0.6, -0.6}};
	Print[">>> flag = CheckGenerator[Q,True];"//OutputForm];
	flag = CheckGenerator[Q,True];
	Print[">>> Print[flag];"//OutputForm];
	Print[flag];
	Print[">>> Q = {{-0.9, 0.5, 0.4},{0.9, -0.9, 0},{0.3, 0.3, -0.6}};"//OutputForm];
	Q = {{-0.9, 0.5, 0.4},{0.9, -0.9, 0},{0.3, 0.3, -0.6}};
	Print[">>> flag = CheckGenerator[Q,True];"//OutputForm];
	flag = CheckGenerator[Q,True];
	Print[">>> Print[flag];"//OutputForm];
	Print[flag];
	Print[">>> Q = {{-0.9, 0.2, 0.4},{0.9, -0.9, 0},{0.3, 0.3, -0.6}};"//OutputForm];
	Q = {{-0.9, 0.2, 0.4},{0.9, -0.9, 0},{0.3, 0.3, -0.6}};
	Print[">>> flag = CheckGenerator[Q,True];"//OutputForm];
	flag = CheckGenerator[Q,True];
	Print[">>> Print[flag];"//OutputForm];
	Print[flag];
	Print[">>> Q = {{-0.9, 0.5, 0.4},{0.9, -1.1, 0},{0.3, 0.3, -0.6}};"//OutputForm];
	Q = {{-0.9, 0.5, 0.4},{0.9, -1.1, 0},{0.3, 0.3, -0.6}};
	Print[">>> flag = CheckGenerator[Q];"//OutputForm];
	flag = CheckGenerator[Q];
	Print[">>> Print[flag];"//OutputForm];
	Print[flag];
	Print[">>> Q = {{-0.9, 0.5, 0.4},{0.9, -0.9, 0},{0.3, 0.3, -0.6}};"//OutputForm];
	Q = {{-0.9, 0.5, 0.4},{0.9, -0.9, 0},{0.3, 0.3, -0.6}};
	Print[">>> flag = CheckGenerator[Q];"//OutputForm];
	flag = CheckGenerator[Q];
	Print[">>> Print[flag];"//OutputForm];
	Print[flag];
	Print["=== CheckProbMatrix ==="//OutputForm];
	Print[">>> Q = {{0.1, 0.5, 0.4},{0.9, 0.1, 0},{0.3, -0.1, 0.4}};"//OutputForm];
	Q = {{0.1, 0.5, 0.4},{0.9, 0.1, 0},{0.3, -0.1, 0.4}};
	Print[">>> flag = CheckProbMatrix[Q];"//OutputForm];
	flag = CheckProbMatrix[Q];
	Print[">>> Print[flag];"//OutputForm];
	Print[flag];
	Print[">>> Q = {{0.1, 0.5, 0.4},{0.9, 0.1, 0},{0.3, 0.1, 0.4}};"//OutputForm];
	Q = {{0.1, 0.5, 0.4},{0.9, 0.1, 0},{0.3, 0.1, 0.4}};
	Print[">>> flag = CheckProbMatrix[Q];"//OutputForm];
	flag = CheckProbMatrix[Q];
	Print[">>> Print[flag];"//OutputForm];
	Print[flag];
	Print[">>> Q = {{0.1, 0.5, 0.4},{0.9, 0.1, 0},{0.3, 0.3, 0.4}};"//OutputForm];
	Q = {{0.1, 0.5, 0.4},{0.9, 0.1, 0},{0.3, 0.3, 0.4}};
	Print[">>> flag = CheckProbMatrix[Q];"//OutputForm];
	flag = CheckProbMatrix[Q];
	Print[">>> Print[flag];"//OutputForm];
	Print[flag];
	Print[">>> Q = {{0.1, 0.5, 0.4},{0.9, 0.1, 0},{0.3, 0.3, 0.4}};"//OutputForm];
	Q = {{0.1, 0.5, 0.4},{0.9, 0.1, 0},{0.3, 0.3, 0.4}};
	Print[">>> flag = CheckProbMatrix[Q,True];"//OutputForm];
	flag = CheckProbMatrix[Q,True];
	Print[">>> Print[flag];"//OutputForm];
	Print[flag];
	Print[">>> Q = {{0.1, 0.5, 0.4},{0.9, 0.1, 0},{0.3, 0.1, 0.4}};"//OutputForm];
	Q = {{0.1, 0.5, 0.4},{0.9, 0.1, 0},{0.3, 0.1, 0.4}};
	Print[">>> flag = CheckProbMatrix[Q,True];"//OutputForm];
	flag = CheckProbMatrix[Q,True];
	Print[">>> Print[flag];"//OutputForm];
	Print[flag];
	Print["=== CheckProbVector ==="//OutputForm];
	Print[">>> Q = {1.1, -0.1};"//OutputForm];
	Q = {1.1, -0.1};
	Print[">>> flag = CheckProbVector[Q];"//OutputForm];
	flag = CheckProbVector[Q];
	Print[">>> Print[flag];"//OutputForm];
	Print[flag];
	Print[">>> Q = {1.1, 0.1};"//OutputForm];
	Q = {1.1, 0.1};
	Print[">>> flag = CheckProbVector[Q];"//OutputForm];
	flag = CheckProbVector[Q];
	Print[">>> Print[flag];"//OutputForm];
	Print[flag];
	Print[">>> Q = {1, 0};"//OutputForm];
	Q = {1, 0};
	Print[">>> flag = CheckProbVector[Q];"//OutputForm];
	flag = CheckProbVector[Q];
	Print[">>> Print[flag];"//OutputForm];
	Print[flag];
	Print[">>> Q = {0.9, -0.1};"//OutputForm];
	Q = {0.9, -0.1};
	Print[">>> flag = CheckProbVector[Q,True];"//OutputForm];
	flag = CheckProbVector[Q,True];
	Print[">>> Print[flag];"//OutputForm];
	Print[flag];
	Print[">>> Q = {0.9, 0.1};"//OutputForm];
	Q = {0.9, 0.1};
	Print[">>> flag = CheckProbVector[Q,True];"//OutputForm];
	flag = CheckProbVector[Q,True];
	Print[">>> Print[flag];"//OutputForm];
	Print[flag];
	Print[">>> Q = {0.8, 0.1};"//OutputForm];
	Q = {0.8, 0.1};
	Print[">>> flag = CheckProbVector[Q,True];"//OutputForm];
	flag = CheckProbVector[Q,True];
	Print[">>> Print[flag];"//OutputForm];
	Print[flag];
	
	$Output = tmpOut;
	Close[stream];

];
