import numpy as np
import numpy.matlib as ml
import matplotlib.pyplot as plt
import butools
from butools.utils import *
from butools.ph import *
from butools.dph import *
from butools.map import *
from butools.moments import *
from butools.reptrans import*
from butools.mc import *
from contextlib import redirect_stdout

def MomentsPythonGendocex():
	print('---BuTools: Moments package test file---')
	print('Enable the verbose messages with the BuToolsVerbose flag')
	butools.verbose = True
	print('Enable input parameter checking with the BuToolsCheckInput flag')
	butools.checkInput = True
	np.set_printoptions(precision=5,linewidth=1024)
	outFile = open('Moments_python.docex','w')
	with redirect_stdout(outFile):
		print('=== NormMomsFromMoms ===')
		print('>>> M = [1.2, 5, 38, 495, 9215]')
		M = [1.2, 5, 38, 495, 9215]
		print('>>> nmoms = NormMomsFromMoms(M)')
		nmoms = NormMomsFromMoms(M)
		print('>>> print(nmoms)')
		print(nmoms)
		print('>>> moms = MomsFromNormMoms(nmoms)')
		moms = MomsFromNormMoms(nmoms)
		print('>>> print(moms)')
		print(moms)
		print('>>> err = la.norm(np.array(moms)-np.array(M))')
		err = la.norm(np.array(moms)-np.array(M))
		print('>>> print(err)')
		print(err)
		print('=== MomsFromNormMoms ===')
		print('>>> M = [1.2, 5, 38, 495, 9215]')
		M = [1.2, 5, 38, 495, 9215]
		print('>>> nmoms = NormMomsFromMoms(M)')
		nmoms = NormMomsFromMoms(M)
		print('>>> print(nmoms)')
		print(nmoms)
		print('>>> moms = MomsFromNormMoms(nmoms)')
		moms = MomsFromNormMoms(nmoms)
		print('>>> print(moms)')
		print(moms)
		print('>>> err = la.norm(np.array(moms)-np.array(M))')
		err = la.norm(np.array(moms)-np.array(M))
		print('>>> print(err)')
		print(err)
		print('=== ReducedMomsFromMoms ===')
		print('>>> M = [1.2, 5, 38, 495, 9215]')
		M = [1.2, 5, 38, 495, 9215]
		print('>>> rmoms = ReducedMomsFromMoms(M)')
		rmoms = ReducedMomsFromMoms(M)
		print('>>> print(rmoms)')
		print(rmoms)
		print('>>> moms = MomsFromReducedMoms(rmoms)')
		moms = MomsFromReducedMoms(rmoms)
		print('>>> print(moms)')
		print(moms)
		print('>>> err = la.norm(np.array(moms)-np.array(M))')
		err = la.norm(np.array(moms)-np.array(M))
		print('>>> print(err)')
		print(err)
		print('=== MomsFromReducedMoms ===')
		print('>>> M = [1.2, 5, 38, 495, 9215]')
		M = [1.2, 5, 38, 495, 9215]
		print('>>> rmoms = ReducedMomsFromMoms(M)')
		rmoms = ReducedMomsFromMoms(M)
		print('>>> print(rmoms)')
		print(rmoms)
		print('>>> moms = MomsFromReducedMoms(rmoms)')
		moms = MomsFromReducedMoms(rmoms)
		print('>>> print(moms)')
		print(moms)
		print('>>> err = la.norm(np.array(moms)-np.array(M))')
		err = la.norm(np.array(moms)-np.array(M))
		print('>>> print(err)')
		print(err)
		print('=== FactorialMomsFromMoms ===')
		print('>>> M = [1.3, 2.4, 6.03, 20.5, 89.5, 474.9]')
		M = [1.3, 2.4, 6.03, 20.5, 89.5, 474.9]
		print('>>> fmoms = FactorialMomsFromMoms(M)')
		fmoms = FactorialMomsFromMoms(M)
		print('>>> print(fmoms)')
		print(fmoms)
		print('>>> moms = MomsFromFactorialMoms(fmoms)')
		moms = MomsFromFactorialMoms(fmoms)
		print('>>> print(moms)')
		print(moms)
		print('>>> err = la.norm(np.array(moms)-np.array(M))')
		err = la.norm(np.array(moms)-np.array(M))
		print('>>> print(err)')
		print(err)
		print('=== MomsFromFactorialMoms ===')
		print('>>> M = [1.3, 2.4, 6.03, 20.5, 89.5, 474.9]')
		M = [1.3, 2.4, 6.03, 20.5, 89.5, 474.9]
		print('>>> fmoms = FactorialMomsFromMoms(M)')
		fmoms = FactorialMomsFromMoms(M)
		print('>>> print(fmoms)')
		print(fmoms)
		print('>>> moms = MomsFromFactorialMoms(fmoms)')
		moms = MomsFromFactorialMoms(fmoms)
		print('>>> print(moms)')
		print(moms)
		print('>>> err = la.norm(np.array(moms)-np.array(M))')
		err = la.norm(np.array(moms)-np.array(M))
		print('>>> print(err)')
		print(err)
		print('=== JFactorialMomsFromJMoms ===')
		print('>>> MM = ml.matrix([[0.7, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])')
		MM = ml.matrix([[0.7, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
		print('>>> JFmoms = JFactorialMomsFromJMoms(MM)')
		JFmoms = JFactorialMomsFromJMoms(MM)
		print('>>> print(JFmoms)')
		print(JFmoms)
		print('>>> Jmoms = JMomsFromJFactorialMoms(JFmoms)')
		Jmoms = JMomsFromJFactorialMoms(JFmoms)
		print('>>> print(Jmoms)')
		print(Jmoms)
		print('>>> err = la.norm(np.array(Jmoms)-MM)')
		err = la.norm(np.array(Jmoms)-MM)
		print('>>> print(err)')
		print(err)
		print('=== JMomsFromJFactorialMoms ===')
		print('>>> MM = ml.matrix([[0.7, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])')
		MM = ml.matrix([[0.7, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
		print('>>> JFmoms = JFactorialMomsFromJMoms(MM)')
		JFmoms = JFactorialMomsFromJMoms(MM)
		print('>>> print(JFmoms)')
		print(JFmoms)
		print('>>> Jmoms = JMomsFromJFactorialMoms(JFmoms)')
		Jmoms = JMomsFromJFactorialMoms(JFmoms)
		print('>>> print(Jmoms)')
		print(Jmoms)
		print('>>> err = la.norm(np.array(Jmoms)-MM)')
		err = la.norm(np.array(Jmoms)-MM)
		print('>>> print(err)')
		print(err)
		print('=== HankelMomsFromMoms ===')
		print('>>> M = [1.3, 2.4, 6.03, 20.5, 89.5, 474.9]')
		M = [1.3, 2.4, 6.03, 20.5, 89.5, 474.9]
		print('>>> hmoms = HankelMomsFromMoms(M)')
		hmoms = HankelMomsFromMoms(M)
		print('>>> print(hmoms)')
		print(hmoms)
		print('>>> moms = MomsFromHankelMoms(hmoms)')
		moms = MomsFromHankelMoms(hmoms)
		print('>>> print(moms)')
		print(moms)
		print('>>> err = la.norm(np.array(moms)-np.array(M))')
		err = la.norm(np.array(moms)-np.array(M))
		print('>>> print(err)')
		print(err)
		print('=== MomsFromHankelMoms ===')
		print('>>> M = [1.3, 2.4, 6.03, 20.5, 89.5, 474.9]')
		M = [1.3, 2.4, 6.03, 20.5, 89.5, 474.9]
		print('>>> hmoms = HankelMomsFromMoms(M)')
		hmoms = HankelMomsFromMoms(M)
		print('>>> print(hmoms)')
		print(hmoms)
		print('>>> moms = MomsFromHankelMoms(hmoms)')
		moms = MomsFromHankelMoms(hmoms)
		print('>>> print(moms)')
		print(moms)
		print('>>> err = la.norm(np.array(moms)-np.array(M))')
		err = la.norm(np.array(moms)-np.array(M))
		print('>>> print(err)')
		print(err)
		print('=== CheckMoments ===')
		print('>>> M = [1.2, 5, 8, 29, 3412]')
		M = [1.2, 5, 8, 29, 3412]
		print('>>> flag = CheckMoments(M)')
		flag = CheckMoments(M)
		print('>>> print(flag)')
		print(flag)
		print('>>> M = [1.3, 2.4, 6.03, 20.5, 89.5]')
		M = [1.3, 2.4, 6.03, 20.5, 89.5]
		print('>>> flag = CheckMoments(M)')
		flag = CheckMoments(M)
		print('>>> print(flag)')
		print(flag)
	outFile.close()

if __name__ == "__main__":
	MomentsPythonGendocex()
