PHMathematicaGendocex[]:=
Module[{phmoms, mp, cdf, mean, mom3upper, a, b, memoms, flag, oo, err1, moms, co, B, x, mom3lower, tmpOut, ma, coo, mo, mb, pdf, A, y, n, cv2, stream, Cm, mom2, err2},
	Unprotect[Print];
	Print[args___] := Block[{$inMsg = True, result, str},
	   If[MatrixQ[args],
	    str = "{";
	    Do[str = StringJoin[str, ToString[args[[r]], FormatType -> InputForm]]; 
	     If[r < Length[args], str = StringJoin[str, ",\n "]], {r, Length[args]}];
	    str = StringJoin[str, "}"]; Print[str//OutputForm],
	    result = Print[args],
	    result = Print[args]
	    ]] /; ! TrueQ[$inMsg];
	Print["---BuTools: PH package test file---"//OutputForm];
	Print["Enable the verbose messages with the BuToolsVerbose flag"//OutputForm];
	BuTools`Verbose = True;
	Print["Enable input parameter checking with the BuToolsCheckInput flag"//OutputForm];
	BuTools`CheckInput = True;
	On[Assert];
	tmpOut = $Output;
	stream = OpenWrite["PH_mathematica.docex", FormatType -> InputForm, PageWidth -> Infinity];
	$Output = {stream};
	Print["=== MomentsFromME ==="//OutputForm];
	Print[">>> a = {0.2, 0.3, 0.5};"//OutputForm];
	a = {0.2, 0.3, 0.5};
	Print[">>> A = {{-1, 0, 0},{0, -3, 2},{0, -2, -3}};"//OutputForm];
	A = {{-1, 0, 0},{0, -3, 2},{0, -2, -3}};
	Print[">>> moms = MomentsFromME[a,A];"//OutputForm];
	moms = MomentsFromME[a,A];
	Print[">>> Print[moms];"//OutputForm];
	Print[moms];
	Print[">>> moms = MomentsFromME[a,A,9];"//OutputForm];
	moms = MomentsFromME[a,A,9];
	Print[">>> Print[moms];"//OutputForm];
	Print[moms];
	Print["=== MomentsFromPH ==="//OutputForm];
	Print[">>> a = {0.1, 0.9, 0};"//OutputForm];
	a = {0.1, 0.9, 0};
	Print[">>> A = {{-6.2, 2, 0},{2, -9, 1},{1, 0, -3}};"//OutputForm];
	A = {{-6.2, 2, 0},{2, -9, 1},{1, 0, -3}};
	Print[">>> moms = MomentsFromPH[a,A,5];"//OutputForm];
	moms = MomentsFromPH[a,A,5];
	Print[">>> Print[moms];"//OutputForm];
	Print[moms];
	Print["=== CdfFromME ==="//OutputForm];
	Print[">>> a = {0.2, 0.3, 0.5};"//OutputForm];
	a = {0.2, 0.3, 0.5};
	Print[">>> A = {{-1, 0, 0},{0, -3, 2},{0, -2, -3}};"//OutputForm];
	A = {{-1, 0, 0},{0, -3, 2},{0, -2, -3}};
	Print[">>> x = Range[0,5,0.01];"//OutputForm];
	x = Range[0,5,0.01];
	Print[">>> cdf = CdfFromME[a,A,x];"//OutputForm];
	cdf = CdfFromME[a,A,x];
	Print[">>> ListLinePlot[Transpose[{x, cdf}]]"//OutputForm];
	Print["=== CdfFromPH ==="//OutputForm];
	Print[">>> a = {0.1, 0.9, 0};"//OutputForm];
	a = {0.1, 0.9, 0};
	Print[">>> A = {{-6.2, 2, 0},{2, -9, 1},{1, 0, -3}};"//OutputForm];
	A = {{-6.2, 2, 0},{2, -9, 1},{1, 0, -3}};
	Print[">>> x = Range[0,3,0.002];"//OutputForm];
	x = Range[0,3,0.002];
	Print[">>> cdf = CdfFromPH[a,A,x];"//OutputForm];
	cdf = CdfFromPH[a,A,x];
	Print[">>> ListLinePlot[Transpose[{x, cdf}]]"//OutputForm];
	Print["=== PdfFromME ==="//OutputForm];
	Print[">>> a = {0.2, 0.3, 0.5};"//OutputForm];
	a = {0.2, 0.3, 0.5};
	Print[">>> A = {{-1, 0, 0},{0, -3, 2},{0, -2, -3}};"//OutputForm];
	A = {{-1, 0, 0},{0, -3, 2},{0, -2, -3}};
	Print[">>> x = Range[0,5,0.01];"//OutputForm];
	x = Range[0,5,0.01];
	Print[">>> pdf = PdfFromME[a,A,x];"//OutputForm];
	pdf = PdfFromME[a,A,x];
	Print[">>> ListLinePlot[Transpose[{x, pdf}]]"//OutputForm];
	Print["=== PdfFromPH ==="//OutputForm];
	Print[">>> a = {0.1, 0.9, 0};"//OutputForm];
	a = {0.1, 0.9, 0};
	Print[">>> A = {{-6.2, 2, 0},{2, -9, 1},{1, 0, -3}};"//OutputForm];
	A = {{-6.2, 2, 0},{2, -9, 1},{1, 0, -3}};
	Print[">>> x = Range[0,3,0.002];"//OutputForm];
	x = Range[0,3,0.002];
	Print[">>> pdf = PdfFromPH[a,A,x];"//OutputForm];
	pdf = PdfFromPH[a,A,x];
	Print[">>> ListLinePlot[Transpose[{x, pdf}]]"//OutputForm];
	Print["=== IntervalPdfFromPH ==="//OutputForm];
	Print[">>> a = {0.1, 0.9, 0};"//OutputForm];
	a = {0.1, 0.9, 0};
	Print[">>> A = {{-6.2, 2, 0},{2, -9, 1},{1, 0, -3}};"//OutputForm];
	A = {{-6.2, 2, 0},{2, -9, 1},{1, 0, -3}};
	Print[">>> x = Range[0,3,0.002];"//OutputForm];
	x = Range[0,3,0.002];
	Print[">>> {x,y} = IntervalPdfFromPH[a,A,x];"//OutputForm];
	{x,y} = IntervalPdfFromPH[a,A,x];
	Print[">>> ListLinePlot[Transpose[{x, y}]]"//OutputForm];
	Print["=== RandomPH ==="//OutputForm];
	Print[">>> {a,A} = RandomPH[3,8,4];"//OutputForm];
	{a,A} = RandomPH[3,8,4];
	Print[">>> Print[a];"//OutputForm];
	Print[a];
	Print[">>> Print[A];"//OutputForm];
	Print[A];
	Print["=== CheckMERepresentation ==="//OutputForm];
	Print[">>> a = {-0.2, 0.2};"//OutputForm];
	a = {-0.2, 0.2};
	Print[">>> A = {{1, -1},{1, -2}};"//OutputForm];
	A = {{1, -1},{1, -2}};
	Print[">>> flag = CheckMERepresentation[a,A];"//OutputForm];
	flag = CheckMERepresentation[a,A];
	Print[">>> Print[flag];"//OutputForm];
	Print[flag];
	Print[">>> a = {-0.2, 0.4, 0.8};"//OutputForm];
	a = {-0.2, 0.4, 0.8};
	Print[">>> A = {{-2, 0, 3},{0, -1, 1},{0, -1, -1}};"//OutputForm];
	A = {{-2, 0, 3},{0, -1, 1},{0, -1, -1}};
	Print[">>> flag = CheckMERepresentation[a,A];"//OutputForm];
	flag = CheckMERepresentation[a,A];
	Print[">>> Print[flag];"//OutputForm];
	Print[flag];
	Print[">>> a = {0.2, 0.3, 0.5};"//OutputForm];
	a = {0.2, 0.3, 0.5};
	Print[">>> A = {{-1, 0, 0},{0, -3, 2},{0, -2, -3}};"//OutputForm];
	A = {{-1, 0, 0},{0, -3, 2},{0, -2, -3}};
	Print[">>> flag = CheckMERepresentation[a,A];"//OutputForm];
	flag = CheckMERepresentation[a,A];
	Print[">>> Print[flag];"//OutputForm];
	Print[flag];
	Print["=== CheckPHRepresentation ==="//OutputForm];
	Print[">>> a = {0.2};"//OutputForm];
	a = {0.2};
	Print[">>> A = {{-1, 1},{1, -2}};"//OutputForm];
	A = {{-1, 1},{1, -2}};
	Print[">>> flag = CheckPHRepresentation[a,A];"//OutputForm];
	flag = CheckPHRepresentation[a,A];
	Print[">>> Print[flag];"//OutputForm];
	Print[flag];
	Print[">>> a = {0.2, 0.7};"//OutputForm];
	a = {0.2, 0.7};
	Print[">>> A = {{-1, 1},{1, -2}};"//OutputForm];
	A = {{-1, 1},{1, -2}};
	Print[">>> flag = CheckPHRepresentation[a,A];"//OutputForm];
	flag = CheckPHRepresentation[a,A];
	Print[">>> Print[flag];"//OutputForm];
	Print[flag];
	Print["=== CheckMEPositiveDensity ==="//OutputForm];
	Print[">>> a = {0.2, 0.3, 0.5};"//OutputForm];
	a = {0.2, 0.3, 0.5};
	Print[">>> A = {{-1, 0, 0},{0, -3, 2},{0, -2, -3}};"//OutputForm];
	A = {{-1, 0, 0},{0, -3, 2},{0, -2, -3}};
	Print[">>> flag = CheckMEPositiveDensity[a,A];"//OutputForm];
	flag = CheckMEPositiveDensity[a,A];
	Print[">>> Print[flag];"//OutputForm];
	Print[flag];
	Print[">>> a = {0.2, 0.3, 0.5};"//OutputForm];
	a = {0.2, 0.3, 0.5};
	Print[">>> A = {{-1, 0, 0},{0, -3, 2.9},{0, -2.9, -3}};"//OutputForm];
	A = {{-1, 0, 0},{0, -3, 2.9},{0, -2.9, -3}};
	Print[">>> flag = CheckMEPositiveDensity[a,A];"//OutputForm];
	flag = CheckMEPositiveDensity[a,A];
	Print[">>> Print[flag];"//OutputForm];
	Print[flag];
	Print["=== APHFrom3Moments ==="//OutputForm];
	Print[">>> moms = {10.0, 125.0, 8400.0};"//OutputForm];
	moms = {10.0, 125.0, 8400.0};
	Print[">>> {a,A} = APHFrom3Moments[moms];"//OutputForm];
	{a,A} = APHFrom3Moments[moms];
	Print[">>> Print[a];"//OutputForm];
	Print[a];
	Print[">>> Print[A];"//OutputForm];
	Print[A];
	Print[">>> phmoms = MomentsFromPH[a,A,3];"//OutputForm];
	phmoms = MomentsFromPH[a,A,3];
	Print[">>> Print[phmoms];"//OutputForm];
	Print[phmoms];
	Print[">>> moms = {10.0, 525.0, 31400.0};"//OutputForm];
	moms = {10.0, 525.0, 31400.0};
	Print[">>> {a,A} = APHFrom3Moments[moms];"//OutputForm];
	{a,A} = APHFrom3Moments[moms];
	Print[">>> Print[a];"//OutputForm];
	Print[a];
	Print[">>> Print[A];"//OutputForm];
	Print[A];
	Print[">>> phmoms = MomentsFromPH[a,A,3];"//OutputForm];
	phmoms = MomentsFromPH[a,A,3];
	Print[">>> Print[phmoms];"//OutputForm];
	Print[phmoms];
	Print["=== PH2From3Moments ==="//OutputForm];
	Print[">>> moms = {10.0, 160.0, 3500.0};"//OutputForm];
	moms = {10.0, 160.0, 3500.0};
	Print[">>> {a,A} = PH2From3Moments[moms];"//OutputForm];
	{a,A} = PH2From3Moments[moms];
	Print[">>> Print[a];"//OutputForm];
	Print[a];
	Print[">>> Print[A];"//OutputForm];
	Print[A];
	Print[">>> phmoms = MomentsFromPH[a,A,3];"//OutputForm];
	phmoms = MomentsFromPH[a,A,3];
	Print[">>> Print[phmoms];"//OutputForm];
	Print[phmoms];
	Print[">>> moms = {10.0, 260.0, 13500.0};"//OutputForm];
	moms = {10.0, 260.0, 13500.0};
	Print[">>> {a,A} = PH2From3Moments[moms];"//OutputForm];
	{a,A} = PH2From3Moments[moms];
	Print[">>> Print[a];"//OutputForm];
	Print[a];
	Print[">>> Print[A];"//OutputForm];
	Print[A];
	Print[">>> phmoms = MomentsFromPH[a,A,3];"//OutputForm];
	phmoms = MomentsFromPH[a,A,3];
	Print[">>> Print[phmoms];"//OutputForm];
	Print[phmoms];
	Print["=== PH3From5Moments ==="//OutputForm];
	Print[">>> a = {0.1, 0.9, 0};"//OutputForm];
	a = {0.1, 0.9, 0};
	Print[">>> A = {{-6.2, 2, 0},{2, -9, 1},{1, 0, -3}};"//OutputForm];
	A = {{-6.2, 2, 0},{2, -9, 1},{1, 0, -3}};
	Print[">>> moms = MomentsFromPH[a,A];"//OutputForm];
	moms = MomentsFromPH[a,A];
	Print[">>> Print[moms];"//OutputForm];
	Print[moms];
	Print[">>> {a,A} = PH3From5Moments[moms];"//OutputForm];
	{a,A} = PH3From5Moments[moms];
	Print[">>> Print[a];"//OutputForm];
	Print[a];
	Print[">>> Print[A];"//OutputForm];
	Print[A];
	Print[">>> phmoms = MomentsFromME[a,A,5];"//OutputForm];
	phmoms = MomentsFromME[a,A,5];
	Print[">>> Print[phmoms];"//OutputForm];
	Print[phmoms];
	Print[">>> a = {0.2, 0.3, 0.5};"//OutputForm];
	a = {0.2, 0.3, 0.5};
	Print[">>> A = {{-1, 0, 0},{0, -3, 0.5},{0, -0.5, -3}};"//OutputForm];
	A = {{-1, 0, 0},{0, -3, 0.5},{0, -0.5, -3}};
	Print[">>> moms = MomentsFromME[a,A];"//OutputForm];
	moms = MomentsFromME[a,A];
	Print[">>> Print[moms];"//OutputForm];
	Print[moms];
	Print[">>> {a,A} = PH3From5Moments[moms];"//OutputForm];
	{a,A} = PH3From5Moments[moms];
	Print[">>> Print[a];"//OutputForm];
	Print[a];
	Print[">>> Print[A];"//OutputForm];
	Print[A];
	Print[">>> phmoms = MomentsFromME[a,A,5];"//OutputForm];
	phmoms = MomentsFromME[a,A,5];
	Print[">>> Print[phmoms];"//OutputForm];
	Print[phmoms];
	Print["=== MEFromMoments ==="//OutputForm];
	Print[">>> a = {0.1, 0.9, 0};"//OutputForm];
	a = {0.1, 0.9, 0};
	Print[">>> A = {{-6.2, 2, 0},{2, -9, 1},{1, 0, -3}};"//OutputForm];
	A = {{-6.2, 2, 0},{2, -9, 1},{1, 0, -3}};
	Print[">>> moms = MomentsFromPH[a,A,5];"//OutputForm];
	moms = MomentsFromPH[a,A,5];
	Print[">>> Print[moms];"//OutputForm];
	Print[moms];
	Print[">>> {a,A} = MEFromMoments[moms];"//OutputForm];
	{a,A} = MEFromMoments[moms];
	Print[">>> Print[a];"//OutputForm];
	Print[a];
	Print[">>> Print[A];"//OutputForm];
	Print[A];
	Print[">>> memoms = MomentsFromME[a,A,5];"//OutputForm];
	memoms = MomentsFromME[a,A,5];
	Print[">>> Print[memoms];"//OutputForm];
	Print[memoms];
	Print["=== APH2ndMomentLowerBound ==="//OutputForm];
	Print[">>> mean = 1.9;"//OutputForm];
	mean = 1.9;
	Print[">>> n = 4;"//OutputForm];
	n = 4;
	Print[">>> mom2 = APH2ndMomentLowerBound[mean,n];"//OutputForm];
	mom2 = APH2ndMomentLowerBound[mean,n];
	Print[">>> Print[mom2];"//OutputForm];
	Print[mom2];
	Print[">>> cv2 = mom2/mean^2-1;"//OutputForm];
	cv2 = mom2/mean^2-1;
	Print[">>> Print[1/cv2];"//OutputForm];
	Print[1/cv2];
	Print["=== APH3rdMomentLowerBound ==="//OutputForm];
	Print[">>> mean = 1.9;"//OutputForm];
	mean = 1.9;
	Print[">>> mom2 = 5;"//OutputForm];
	mom2 = 5;
	Print[">>> n = 3;"//OutputForm];
	n = 3;
	Print[">>> mom3lower = APH3rdMomentLowerBound[mean,mom2,n];"//OutputForm];
	mom3lower = APH3rdMomentLowerBound[mean,mom2,n];
	Print[">>> Print[mom3lower];"//OutputForm];
	Print[mom3lower];
	Print[">>> mom3upper = APH3rdMomentUpperBound[mean,mom2,n];"//OutputForm];
	mom3upper = APH3rdMomentUpperBound[mean,mom2,n];
	Print[">>> Print[mom3upper];"//OutputForm];
	Print[mom3upper];
	Print[">>> mean = 1.9;"//OutputForm];
	mean = 1.9;
	Print[">>> mom2 = 5;"//OutputForm];
	mom2 = 5;
	Print[">>> n = 4;"//OutputForm];
	n = 4;
	Print[">>> mom3lower = APH3rdMomentLowerBound[mean,mom2,n];"//OutputForm];
	mom3lower = APH3rdMomentLowerBound[mean,mom2,n];
	Print[">>> Print[mom3lower];"//OutputForm];
	Print[mom3lower];
	Print[">>> mom3upper = APH3rdMomentUpperBound[mean,mom2,n];"//OutputForm];
	mom3upper = APH3rdMomentUpperBound[mean,mom2,n];
	Print[">>> Print[mom3upper];"//OutputForm];
	Print[mom3upper];
	Print["=== APH3rdMomentUpperBound ==="//OutputForm];
	Print[">>> mean = 1.9;"//OutputForm];
	mean = 1.9;
	Print[">>> mom2 = 5;"//OutputForm];
	mom2 = 5;
	Print[">>> n = 3;"//OutputForm];
	n = 3;
	Print[">>> mom3lower = APH3rdMomentLowerBound[mean,mom2,n];"//OutputForm];
	mom3lower = APH3rdMomentLowerBound[mean,mom2,n];
	Print[">>> Print[mom3lower];"//OutputForm];
	Print[mom3lower];
	Print[">>> mom3upper = APH3rdMomentUpperBound[mean,mom2,n];"//OutputForm];
	mom3upper = APH3rdMomentUpperBound[mean,mom2,n];
	Print[">>> Print[mom3upper];"//OutputForm];
	Print[mom3upper];
	Print[">>> mean = 1.9;"//OutputForm];
	mean = 1.9;
	Print[">>> mom2 = 5;"//OutputForm];
	mom2 = 5;
	Print[">>> n = 4;"//OutputForm];
	n = 4;
	Print[">>> mom3lower = APH3rdMomentLowerBound[mean,mom2,n];"//OutputForm];
	mom3lower = APH3rdMomentLowerBound[mean,mom2,n];
	Print[">>> Print[mom3lower];"//OutputForm];
	Print[mom3lower];
	Print[">>> mom3upper = APH3rdMomentUpperBound[mean,mom2,n];"//OutputForm];
	mom3upper = APH3rdMomentUpperBound[mean,mom2,n];
	Print[">>> Print[mom3upper];"//OutputForm];
	Print[mom3upper];
	Print["=== CanonicalFromPH2 ==="//OutputForm];
	Print[">>> a = {0.12, 0.88};"//OutputForm];
	a = {0.12, 0.88};
	Print[">>> A = {{-1.28, 0},{3.94, -3.94}};"//OutputForm];
	A = {{-1.28, 0},{3.94, -3.94}};
	Print[">>> {b,B} = CanonicalFromPH2[a,A];"//OutputForm];
	{b,B} = CanonicalFromPH2[a,A];
	Print[">>> Print[b];"//OutputForm];
	Print[b];
	Print[">>> Print[B];"//OutputForm];
	Print[B];
	Print[">>> Cm = SimilarityMatrix[A,B];"//OutputForm];
	Cm = SimilarityMatrix[A,B];
	Print[">>> err1 = Norm[A.Cm-Cm.B];"//OutputForm];
	err1 = Norm[A.Cm-Cm.B];
	Print[">>> err2 = Norm[a.Cm-b];"//OutputForm];
	err2 = Norm[a.Cm-b];
	Print[">>> Print[Max[err1,err2]];"//OutputForm];
	Print[Max[err1,err2]];
	Print["=== CanonicalFromPH3 ==="//OutputForm];
	Print[">>> a = {0.1, 0.9, 0};"//OutputForm];
	a = {0.1, 0.9, 0};
	Print[">>> A = {{-6.2, 2, 0},{2, -9, 1},{1, 0, -3}};"//OutputForm];
	A = {{-6.2, 2, 0},{2, -9, 1},{1, 0, -3}};
	Print[">>> {b,B} = CanonicalFromPH3[a,A];"//OutputForm];
	{b,B} = CanonicalFromPH3[a,A];
	Print[">>> Print[b];"//OutputForm];
	Print[b];
	Print[">>> Print[B];"//OutputForm];
	Print[B];
	Print[">>> Cm = SimilarityMatrix[A,B];"//OutputForm];
	Cm = SimilarityMatrix[A,B];
	Print[">>> err1 = Norm[A.Cm-Cm.B];"//OutputForm];
	err1 = Norm[A.Cm-Cm.B];
	Print[">>> err2 = Norm[a.Cm-b];"//OutputForm];
	err2 = Norm[a.Cm-b];
	Print[">>> Print[Max[err1,err2]];"//OutputForm];
	Print[Max[err1,err2]];
	Print["=== AcyclicPHFromME ==="//OutputForm];
	Print[">>> a = {-0.4, 1.4, 0.};"//OutputForm];
	a = {-0.4, 1.4, 0.};
	Print[">>> A = {{-4., 1., 1.},{0., -2., 1.},{1., 0., -8.}};"//OutputForm];
	A = {{-4., 1., 1.},{0., -2., 1.},{1., 0., -8.}};
	Print[">>> {b,B} = AcyclicPHFromME[a,A];"//OutputForm];
	{b,B} = AcyclicPHFromME[a,A];
	Print[">>> Print[b];"//OutputForm];
	Print[b];
	Print[">>> Print[B];"//OutputForm];
	Print[B];
	Print[">>> ma = MomentsFromME[a,A,5];"//OutputForm];
	ma = MomentsFromME[a,A,5];
	Print[">>> Print[ma];"//OutputForm];
	Print[ma];
	Print[">>> mb = MomentsFromME[b,B,5];"//OutputForm];
	mb = MomentsFromME[b,B,5];
	Print[">>> Print[mb];"//OutputForm];
	Print[mb];
	Print["=== MonocyclicPHFromME ==="//OutputForm];
	Print[">>> a = {0.2, 0.3, 0.5};"//OutputForm];
	a = {0.2, 0.3, 0.5};
	Print[">>> A = {{-1., 0., 0.},{0., -3., 2.},{0., -2., -3.}};"//OutputForm];
	A = {{-1., 0., 0.},{0., -3., 2.},{0., -2., -3.}};
	Print[">>> {b,B} = MonocyclicPHFromME[a,A];"//OutputForm];
	{b,B} = MonocyclicPHFromME[a,A];
	Print[">>> Print[b];"//OutputForm];
	Print[b];
	Print[">>> Print[B];"//OutputForm];
	Print[B];
	Print[">>> ma = MomentsFromME[a,A,5];"//OutputForm];
	ma = MomentsFromME[a,A,5];
	Print[">>> Print[ma];"//OutputForm];
	Print[ma];
	Print[">>> mb = MomentsFromME[b,B,5];"//OutputForm];
	mb = MomentsFromME[b,B,5];
	Print[">>> Print[mb];"//OutputForm];
	Print[mb];
	Print["=== PHFromME ==="//OutputForm];
	Print[">>> a = {-0.4, 1.4};"//OutputForm];
	a = {-0.4, 1.4};
	Print[">>> A = {{-3.8, 2},{2, -9}};"//OutputForm];
	A = {{-3.8, 2},{2, -9}};
	Print[">>> flag = CheckMERepresentation[a,A];"//OutputForm];
	flag = CheckMERepresentation[a,A];
	Print[">>> Print[flag];"//OutputForm];
	Print[flag];
	Print[">>> flag = CheckPHRepresentation[a,A];"//OutputForm];
	flag = CheckPHRepresentation[a,A];
	Print[">>> Print[flag];"//OutputForm];
	Print[flag];
	Print[">>> {b,B} = PHFromME[a,A];"//OutputForm];
	{b,B} = PHFromME[a,A];
	Print[">>> Print[b];"//OutputForm];
	Print[b];
	Print[">>> Print[B];"//OutputForm];
	Print[B];
	Print[">>> flag = CheckPHRepresentation[b,B];"//OutputForm];
	flag = CheckPHRepresentation[b,B];
	Print[">>> Print[flag];"//OutputForm];
	Print[flag];
	Print[">>> Cm = SimilarityMatrix[A,B];"//OutputForm];
	Cm = SimilarityMatrix[A,B];
	Print[">>> err1 = Norm[A.Cm-Cm.B];"//OutputForm];
	err1 = Norm[A.Cm-Cm.B];
	Print[">>> err2 = Norm[a.Cm-b];"//OutputForm];
	err2 = Norm[a.Cm-b];
	Print[">>> Print[Max[err1,err2]];"//OutputForm];
	Print[Max[err1,err2]];
	Print[">>> a = {-0.5, 1.5};"//OutputForm];
	a = {-0.5, 1.5};
	Print[">>> A = {{-3.8, 2},{2, -9}};"//OutputForm];
	A = {{-3.8, 2},{2, -9}};
	Print[">>> flag = CheckMERepresentation[a,A];"//OutputForm];
	flag = CheckMERepresentation[a,A];
	Print[">>> Print[flag];"//OutputForm];
	Print[flag];
	Print[">>> flag = CheckPHRepresentation[a,A];"//OutputForm];
	flag = CheckPHRepresentation[a,A];
	Print[">>> Print[flag];"//OutputForm];
	Print[flag];
	Print[">>> {b,B} = PHFromME[a,A];"//OutputForm];
	{b,B} = PHFromME[a,A];
	Print[">>> Print[b];"//OutputForm];
	Print[b];
	Print[">>> Print[B];"//OutputForm];
	Print[B];
	Print[">>> flag = CheckPHRepresentation[b,B];"//OutputForm];
	flag = CheckPHRepresentation[b,B];
	Print[">>> Print[flag];"//OutputForm];
	Print[flag];
	Print[">>> Cm = SimilarityMatrix[A,B];"//OutputForm];
	Cm = SimilarityMatrix[A,B];
	Print[">>> err1 = Norm[A.Cm-Cm.B];"//OutputForm];
	err1 = Norm[A.Cm-Cm.B];
	Print[">>> err2 = Norm[a.Cm-b];"//OutputForm];
	err2 = Norm[a.Cm-b];
	Print[">>> Print[Max[err1,err2]];"//OutputForm];
	Print[Max[err1,err2]];
	Print["=== MEOrder ==="//OutputForm];
	Print[">>> a = {1./6, 1./6, 1./6, 1./6, 1./6, 1./6};"//OutputForm];
	a = {1./6, 1./6, 1./6, 1./6, 1./6, 1./6};
	Print[">>> A = {{-1., 0., 0., 0., 0., 0.},{0.5, -2., 1., 0., 0., 0.},{1., 0., -3., 1., 0., 0.},{1., 0., 1., -4., 1., 0.},{4., 0., 0., 0., -5., 0.},{5., 0., 0., 0., 0., -6.}};"//OutputForm];
	A = {{-1., 0., 0., 0., 0., 0.},{0.5, -2., 1., 0., 0., 0.},{1., 0., -3., 1., 0., 0.},{1., 0., 1., -4., 1., 0.},{4., 0., 0., 0., -5., 0.},{5., 0., 0., 0., 0., -6.}};
	Print[">>> co = MEOrder[a,A,\"cont\"];"//OutputForm];
	co = MEOrder[a,A,"cont"];
	Print[">>> Print[co];"//OutputForm];
	Print[co];
	Print[">>> oo = MEOrder[a,A,\"obs\"];"//OutputForm];
	oo = MEOrder[a,A,"obs"];
	Print[">>> Print[oo];"//OutputForm];
	Print[oo];
	Print[">>> coo = MEOrder[a,A,\"obscont\"];"//OutputForm];
	coo = MEOrder[a,A,"obscont"];
	Print[">>> Print[coo];"//OutputForm];
	Print[coo];
	Print[">>> mo = MEOrder[a,A,\"moment\"];"//OutputForm];
	mo = MEOrder[a,A,"moment"];
	Print[">>> Print[mo];"//OutputForm];
	Print[mo];
	Print[">>> a = {2./3, 1./3};"//OutputForm];
	a = {2./3, 1./3};
	Print[">>> A = {{-1., 1.},{0., -3.}};"//OutputForm];
	A = {{-1., 1.},{0., -3.}};
	Print[">>> co = MEOrder[a,A,\"cont\"];"//OutputForm];
	co = MEOrder[a,A,"cont"];
	Print[">>> Print[co];"//OutputForm];
	Print[co];
	Print[">>> oo = MEOrder[a,A,\"obs\"];"//OutputForm];
	oo = MEOrder[a,A,"obs"];
	Print[">>> Print[oo];"//OutputForm];
	Print[oo];
	Print[">>> coo = MEOrder[a,A,\"obscont\"];"//OutputForm];
	coo = MEOrder[a,A,"obscont"];
	Print[">>> Print[coo];"//OutputForm];
	Print[coo];
	Print[">>> mo = MEOrder[a,A,\"moment\"];"//OutputForm];
	mo = MEOrder[a,A,"moment"];
	Print[">>> Print[mo];"//OutputForm];
	Print[mo];
	Print[">>> b = {0.2, 0.3, 0.5};"//OutputForm];
	b = {0.2, 0.3, 0.5};
	Print[">>> B = {{-1., 0., 0.},{0., -3., 1.},{0., -1., -3.}};"//OutputForm];
	B = {{-1., 0., 0.},{0., -3., 1.},{0., -1., -3.}};
	Print[">>> {a,A} = MonocyclicPHFromME[b,B];"//OutputForm];
	{a,A} = MonocyclicPHFromME[b,B];
	Print[">>> Print[a];"//OutputForm];
	Print[a];
	Print[">>> Print[A];"//OutputForm];
	Print[A];
	Print[">>> co = MEOrder[a,A,\"cont\"];"//OutputForm];
	co = MEOrder[a,A,"cont"];
	Print[">>> Print[co];"//OutputForm];
	Print[co];
	Print[">>> oo = MEOrder[a,A,\"obs\"];"//OutputForm];
	oo = MEOrder[a,A,"obs"];
	Print[">>> Print[oo];"//OutputForm];
	Print[oo];
	Print[">>> coo = MEOrder[a,A,\"obscont\"];"//OutputForm];
	coo = MEOrder[a,A,"obscont"];
	Print[">>> Print[coo];"//OutputForm];
	Print[coo];
	Print[">>> mo = MEOrder[a,A,\"moment\"];"//OutputForm];
	mo = MEOrder[a,A,"moment"];
	Print[">>> Print[mo];"//OutputForm];
	Print[mo];
	Print["=== MEOrderFromMoments ==="//OutputForm];
	Print[">>> a = {0.1, 0.9, 0};"//OutputForm];
	a = {0.1, 0.9, 0};
	Print[">>> A = {{-6.2, 2., 0.},{2., -9., 1.},{1., 0., -3.}};"//OutputForm];
	A = {{-6.2, 2., 0.},{2., -9., 1.},{1., 0., -3.}};
	Print[">>> moms = MomentsFromME[a,A];"//OutputForm];
	moms = MomentsFromME[a,A];
	Print[">>> Print[moms];"//OutputForm];
	Print[moms];
	Print[">>> mo = MEOrderFromMoments[moms];"//OutputForm];
	mo = MEOrderFromMoments[moms];
	Print[">>> Print[mo];"//OutputForm];
	Print[mo];
	Print[">>> b = {0.2, 0.3, 0.5};"//OutputForm];
	b = {0.2, 0.3, 0.5};
	Print[">>> B = {{-1., 0., 0.},{0., -3., 2.},{0., -2., -3.}};"//OutputForm];
	B = {{-1., 0., 0.},{0., -3., 2.},{0., -2., -3.}};
	Print[">>> {a,A} = MonocyclicPHFromME[b,B];"//OutputForm];
	{a,A} = MonocyclicPHFromME[b,B];
	Print[">>> moms = MomentsFromME[a,A];"//OutputForm];
	moms = MomentsFromME[a,A];
	Print[">>> Print[moms];"//OutputForm];
	Print[moms];
	Print[">>> mo = MEOrderFromMoments[moms];"//OutputForm];
	mo = MEOrderFromMoments[moms];
	Print[">>> Print[mo];"//OutputForm];
	Print[mo];
	Print["=== MinimalRepFromME ==="//OutputForm];
	Print[">>> a = {1./6, 1./6, 1./6, 1./6, 1./6, 1./6};"//OutputForm];
	a = {1./6, 1./6, 1./6, 1./6, 1./6, 1./6};
	Print[">>> A = {{-1., 0., 0., 0., 0., 0.},{0.5, -2., 1., 0., 0., 0.},{1., 0., -3., 1., 0., 0.},{1., 0., 1., -4., 1., 0.},{4., 0., 0., 0., -5., 0.},{5., 0., 0., 0., 0., -6.}};"//OutputForm];
	A = {{-1., 0., 0., 0., 0., 0.},{0.5, -2., 1., 0., 0., 0.},{1., 0., -3., 1., 0., 0.},{1., 0., 1., -4., 1., 0.},{4., 0., 0., 0., -5., 0.},{5., 0., 0., 0., 0., -6.}};
	Print[">>> {b,B} = MinimalRepFromME[a,A,\"cont\"];"//OutputForm];
	{b,B} = MinimalRepFromME[a,A,"cont"];
	Print[">>> Print[b];"//OutputForm];
	Print[b];
	Print[">>> Print[B];"//OutputForm];
	Print[B];
	Print[">>> {b,B} = MinimalRepFromME[a,A,\"obs\"];"//OutputForm];
	{b,B} = MinimalRepFromME[a,A,"obs"];
	Print[">>> Print[b];"//OutputForm];
	Print[b];
	Print[">>> Print[B];"//OutputForm];
	Print[B];
	Print[">>> {b,B} = MinimalRepFromME[a,A,\"obscont\"];"//OutputForm];
	{b,B} = MinimalRepFromME[a,A,"obscont"];
	Print[">>> Print[b];"//OutputForm];
	Print[b];
	Print[">>> Print[B];"//OutputForm];
	Print[B];
	Print[">>> {b,B} = MinimalRepFromME[a,A,\"moment\"];"//OutputForm];
	{b,B} = MinimalRepFromME[a,A,"moment"];
	Print[">>> Print[b];"//OutputForm];
	Print[b];
	Print[">>> Print[B];"//OutputForm];
	Print[B];
	Print[">>> a = {2./3, 1./3};"//OutputForm];
	a = {2./3, 1./3};
	Print[">>> A = {{-1., 1.},{0., -3.}};"//OutputForm];
	A = {{-1., 1.},{0., -3.}};
	Print[">>> {b,B} = MinimalRepFromME[a,A,\"cont\"];"//OutputForm];
	{b,B} = MinimalRepFromME[a,A,"cont"];
	Print[">>> Print[b];"//OutputForm];
	Print[b];
	Print[">>> Print[B];"//OutputForm];
	Print[B];
	Print[">>> {b,B} = MinimalRepFromME[a,A,\"obs\"];"//OutputForm];
	{b,B} = MinimalRepFromME[a,A,"obs"];
	Print[">>> Print[b];"//OutputForm];
	Print[b];
	Print[">>> Print[B];"//OutputForm];
	Print[B];
	Print[">>> {b,B} = MinimalRepFromME[a,A,\"obscont\"];"//OutputForm];
	{b,B} = MinimalRepFromME[a,A,"obscont"];
	Print[">>> Print[b];"//OutputForm];
	Print[b];
	Print[">>> Print[B];"//OutputForm];
	Print[B];
	Print[">>> {b,B} = MinimalRepFromME[a,A,\"moment\"];"//OutputForm];
	{b,B} = MinimalRepFromME[a,A,"moment"];
	Print[">>> Print[b];"//OutputForm];
	Print[b];
	Print[">>> Print[B];"//OutputForm];
	Print[B];
	Print[">>> b = {0.2, 0.3, 0.5};"//OutputForm];
	b = {0.2, 0.3, 0.5};
	Print[">>> B = {{-1., 0., 0.},{0., -3., 1.},{0., -1., -3.}};"//OutputForm];
	B = {{-1., 0., 0.},{0., -3., 1.},{0., -1., -3.}};
	Print[">>> {a,A} = MonocyclicPHFromME[b,B];"//OutputForm];
	{a,A} = MonocyclicPHFromME[b,B];
	Print[">>> Print[a];"//OutputForm];
	Print[a];
	Print[">>> Print[A];"//OutputForm];
	Print[A];
	Print[">>> {b,B} = MinimalRepFromME[a,A,\"cont\"];"//OutputForm];
	{b,B} = MinimalRepFromME[a,A,"cont"];
	Print[">>> Print[b];"//OutputForm];
	Print[b];
	Print[">>> Print[B];"//OutputForm];
	Print[B];
	Print[">>> {b,B} = MinimalRepFromME[a,A,\"obs\"];"//OutputForm];
	{b,B} = MinimalRepFromME[a,A,"obs"];
	Print[">>> Print[b];"//OutputForm];
	Print[b];
	Print[">>> Print[B];"//OutputForm];
	Print[B];
	Print[">>> Cm = SimilarityMatrix[B,A];"//OutputForm];
	Cm = SimilarityMatrix[B,A];
	Print[">>> err1 = Norm[B.Cm-Cm.A];"//OutputForm];
	err1 = Norm[B.Cm-Cm.A];
	Print[">>> err2 = Norm[b.Cm-a];"//OutputForm];
	err2 = Norm[b.Cm-a];
	Print[">>> Print[Max[err1,err2]];"//OutputForm];
	Print[Max[err1,err2]];
	Print[">>> {b,B} = MinimalRepFromME[a,A,\"obscont\"];"//OutputForm];
	{b,B} = MinimalRepFromME[a,A,"obscont"];
	Print[">>> Print[b];"//OutputForm];
	Print[b];
	Print[">>> Print[B];"//OutputForm];
	Print[B];
	Print[">>> Cm = SimilarityMatrix[B,A];"//OutputForm];
	Cm = SimilarityMatrix[B,A];
	Print[">>> err1 = Norm[B.Cm-Cm.A];"//OutputForm];
	err1 = Norm[B.Cm-Cm.A];
	Print[">>> err2 = Norm[b.Cm-a];"//OutputForm];
	err2 = Norm[b.Cm-a];
	Print[">>> Print[Max[err1,err2]];"//OutputForm];
	Print[Max[err1,err2]];
	Print[">>> {b,B} = MinimalRepFromME[a,A,\"moment\"];"//OutputForm];
	{b,B} = MinimalRepFromME[a,A,"moment"];
	Print[">>> Print[b];"//OutputForm];
	Print[b];
	Print[">>> Print[B];"//OutputForm];
	Print[B];
	Print[">>> Cm = SimilarityMatrix[B,A];"//OutputForm];
	Cm = SimilarityMatrix[B,A];
	Print[">>> err1 = Norm[B.Cm-Cm.A];"//OutputForm];
	err1 = Norm[B.Cm-Cm.A];
	Print[">>> err2 = Norm[b.Cm-a];"//OutputForm];
	err2 = Norm[b.Cm-a];
	Print[">>> Print[Max[err1,err2]];"//OutputForm];
	Print[Max[err1,err2]];
	Print["=== SamplesFromPH ==="//OutputForm];
	Print[">>> a = {0.1, 0.9, 0};"//OutputForm];
	a = {0.1, 0.9, 0};
	Print[">>> A = {{-6.2, 2, 0},{2, -9, 1},{1, 0, -3}};"//OutputForm];
	A = {{-6.2, 2, 0},{2, -9, 1},{1, 0, -3}};
	Print[">>> x = SamplesFromPH[a,A,1000];"//OutputForm];
	x = SamplesFromPH[a,A,1000];
	Print[">>> mp = MomentsFromPH[a,A,3];"//OutputForm];
	mp = MomentsFromPH[a,A,3];
	Print[">>> Print[mp];"//OutputForm];
	Print[mp];
	
	$Output = tmpOut;
	Close[stream];

];
