function RepTransMatlabGendocex ()
	disp('---BuTools: RepTrans package test file---');
	disp('Enable the verbose messages with the BuToolsVerbose flag');
	global BuToolsVerbose;
	BuToolsVerbose = true;
	disp('Enable input parameter checking with the BuToolsCheckInput flag');
	global BuToolsCheckInput;
	BuToolsCheckInput = true;
	global BuToolsCheckPrecision;
	format compact
	diary('RepTrans_matlab.docex');
	disp('=== SimilarityMatrix ===');
	disp('>>> A1m = [0.2, 0.8, 0; 1.2, -0.4, 0.1; -0.2, 0.7, 0.5];');
	A1m = [0.2, 0.8, 0; 1.2, -0.4, 0.1; -0.2, 0.7, 0.5];
	disp('>>> T = [1, 2, -4, 6; 0, 8, -9, 7; -3, 7, 8, -2];');
	T = [1, 2, -4, 6; 0, 8, -9, 7; -3, 7, 8, -2];
	disp('>>> A2m = pinv(T)*A1m*T;');
	A2m = pinv(T)*A1m*T;
	disp('>>> B = SimilarityMatrix(A1m,A2m);');
	B = SimilarityMatrix(A1m,A2m);
	disp('>>> err = norm(A1m*B-B*A2m);');
	err = norm(A1m*B-B*A2m);
	disp('>>> disp(err);');
	disp(err);
	disp('=== TransformToAcyclic ===');
	disp('>>> A = [-0.8, 0.8, 0; 0.1, -0.3, 0.1; 0.2, 0, -0.5];');
	A = [-0.8, 0.8, 0; 0.1, -0.3, 0.1; 0.2, 0, -0.5];
	disp('>>> B = TransformToAcyclic(A);');
	B = TransformToAcyclic(A);
	disp('>>> disp(B);');
	disp(B);
	disp('>>> Cm = SimilarityMatrix(A,B);');
	Cm = SimilarityMatrix(A,B);
	disp('>>> err = norm(A*Cm-Cm*B);');
	err = norm(A*Cm-Cm*B);
	disp('>>> disp(err);');
	disp(err);
	disp('=== TransformToMonocyclic ===');
	disp('>>> A = [-1, 0, 0; 0, -3, 2; 0, -2, -3];');
	A = [-1, 0, 0; 0, -3, 2; 0, -2, -3];
	disp('>>> B = TransformToMonocyclic(A);');
	B = TransformToMonocyclic(A);
	disp('>>> disp(B);');
	disp(B);
	disp('>>> Cm = SimilarityMatrix(A,B);');
	Cm = SimilarityMatrix(A,B);
	disp('>>> err = norm(A*Cm-Cm*B);');
	err = norm(A*Cm-Cm*B);
	disp('>>> disp(err);');
	disp(err);
	disp('=== ExtendToMarkovian ===');
	disp('>>> alpha = [0.2, 0.3, 0.5];');
	alpha = [0.2, 0.3, 0.5];
	disp('>>> A = [-1, 0, 0; 0, -3, 0.6; 0, -0.6, -3];');
	A = [-1, 0, 0; 0, -3, 0.6; 0, -0.6, -3];
	disp('>>> B = TransformToMonocyclic(A);');
	B = TransformToMonocyclic(A);
	disp('>>> disp(B);');
	disp(B);
	disp('>>> Cm = SimilarityMatrix(A,B);');
	Cm = SimilarityMatrix(A,B);
	disp('>>> beta = alpha*Cm;');
	beta = alpha*Cm;
	disp('>>> disp(beta);');
	disp(beta);
	disp('>>> [m,M] = ExtendToMarkovian(beta,B);');
	[m,M] = ExtendToMarkovian(beta,B);
	disp('>>> disp(m);');
	disp(m);
	disp('>>> disp(M);');
	disp(M);
	disp('>>> Cm = SimilarityMatrix(B,M);');
	Cm = SimilarityMatrix(B,M);
	disp('>>> err = norm(B*Cm-Cm*M);');
	err = norm(B*Cm-Cm*M);
	disp('>>> disp(err);');
	disp(err);
	disp('=== SimilarityMatrixForVectors ===');
	disp('>>> vecA = [0.0, 0.3, -1.5, 0.0];');
	vecA = [0.0, 0.3, -1.5, 0.0];
	disp('>>> vecB = [1.0, 0.2, 0.0, 1.0];');
	vecB = [1.0, 0.2, 0.0, 1.0];
	disp('>>> vecA = vecA'';');
	vecA = vecA';
	disp('>>> vecB = vecB'';');
	vecB = vecB';
	disp('>>> B = SimilarityMatrixForVectors (vecA, vecB);');
	B = SimilarityMatrixForVectors (vecA, vecB);
	disp('>>> disp(B);');
	disp(B);
	disp('>>> err = norm(B*vecA-vecB);');
	err = norm(B*vecA-vecB);
	disp('>>> disp(err);');
	disp(err);
	diary off;
end
