function TestDPHPackage ()
	disp('---BuTools: DPH package test file---');
	disp('Enable the verbose messages with the BuToolsVerbose flag');
	global BuToolsVerbose;
	BuToolsVerbose = true;
	disp('Enable input parameter checking with the BuToolsCheckInput flag');
	global BuToolsCheckInput;
	BuToolsCheckInput = true;
	disp('========================================')
	help MomentsFromMG
	disp('Input:');
	disp('------');
	a = [-0.6, 0.3, 1.3];
	disp('a = ');
	disp(a);
	A = [0.25, 0.2, -0.15; 0.3, 0.1, 0.25; 0, 0.2, 0.47];
	disp('A = ');
	disp(A);
	disp('Test:');
	disp('-----');
	disp('moms = MomentsFromMG(a,A):');
	moms = MomentsFromMG(a,A);
	disp('moms = ');
	disp(moms);
	assert(CheckMoments(moms)==true , 'The function returned invalid moments!');
	disp('Test:');
	disp('-----');
	disp('moms = MomentsFromMG(a,A,3):');
	moms = MomentsFromMG(a,A,3);
	disp('moms = ');
	disp(moms);
	assert(CheckMoments(moms)==true , 'The function returned invalid moments!');
	disp('========================================')
	help MomentsFromDPH
	disp('Input:');
	disp('------');
	A = [0.76, 0, 0.24];
	disp('A = ');
	disp(A);
	A = [0.34, 0.66, 0; 0.79, 0.05, 0.07; 0.26, 0.73, 0.01];
	disp('A = ');
	disp(A);
	disp('Test:');
	disp('-----');
	disp('moms = MomentsFromDPH(a,A,5):');
	moms = MomentsFromDPH(a,A,5);
	disp('moms = ');
	disp(moms);
	assert(CheckMoments(moms)==true , 'The function returned invalid moments!');
	disp('========================================')
	help PmfFromMG
	disp('Input:');
	disp('------');
	a = [-0.6, 0.3, 1.3];
	disp('a = ');
	disp(a);
	A = [0.25, 0.2, -0.15; 0.3, 0.1, 0.25; 0, 0.2, 0.47];
	disp('A = ');
	disp(A);
	x = (0:1:100);
	disp('Test:');
	disp('-----');
	disp('pmf = PmfFromMG(a,A,x):');
	pmf = PmfFromMG(a,A,x);
	disp('pmf = ');
	disp(pmf);
	assert(all(pmf>=0) , 'PmfFromMG returned negative pmf!');
	assert(abs(x*pmf - MomentsFromMG(a,A,1))<10^-10 , 'The mean computed from the pmf does not match the theoretical result!');
	disp('========================================')
	help PmfFromDPH
	disp('Input:');
	disp('------');
	A = [0.76, 0, 0.24];
	disp('A = ');
	disp(A);
	A = [0.34, 0.66, 0; 0.79, 0.05, 0.07; 0.26, 0.73, 0.01];
	disp('A = ');
	disp(A);
	x = (0:1:1000);
	disp('Test:');
	disp('-----');
	disp('pmf = PmfFromDPH(a,A,x):');
	pmf = PmfFromDPH(a,A,x);
	disp('pmf = ');
	disp(pmf);
	assert(all(pmf>=0) , 'PmfFromDPH returned negative pmf!');
	assert(abs(x*pmf - MomentsFromDPH(a,A,1))<10^-10 , 'The mean computed from the pmf does not match the theoretical result!');
	disp('========================================')
	help CdfFromMG
	disp('Input:');
	disp('------');
	a = [-0.6, 0.3, 1.3];
	disp('a = ');
	disp(a);
	A = [0.25, 0.2, -0.15; 0.3, 0.1, 0.25; 0, 0.2, 0.47];
	disp('A = ');
	disp(A);
	x = (0:1:100);
	disp('Test:');
	disp('-----');
	disp('cdf = CdfFromMG(a,A,x):');
	cdf = CdfFromMG(a,A,x);
	disp('cdf = ');
	disp(cdf);
	assert(all(diff(cdf)>0) , 'The cdf is not increasing monotonously!');
	assert(abs(sum(1-cdf) - MomentsFromMG(a,A,1))<10^-10 , 'The mean computed from the cdf does not match the theoretical result!');
	disp('========================================')
	help CdfFromDPH
	disp('Input:');
	disp('------');
	a = [0.76, 0, 0.24];
	disp('a = ');
	disp(a);
	A = [0.34, 0.66, 0; 0.79, 0.05, 0.07; 0.26, 0.73, 0.01];
	disp('A = ');
	disp(A);
	x = (0:1:1000);
	disp('Test:');
	disp('-----');
	disp('cdf = CdfFromDPH(a,A,x):');
	cdf = CdfFromDPH(a,A,x);
	disp('cdf = ');
	disp(cdf);
	assert(all(diff(cdf)>0) , 'The cdf is not increasing monotonously!');
	assert(abs(sum(1-cdf) - MomentsFromDPH(a,A,1))<10^-10 , 'The mean computed from the cdf does not match the theoretical result!');
	disp('========================================')
	help RandomDPH
	disp('Test:');
	disp('-----');
	disp('[a,A] = RandomDPH(3,10,5):');
	[a,A] = RandomDPH(3,10,5);
	disp('a = ');
	disp(a);
	disp('A = ');
	disp(A);
	assert(CheckDPHRepresentation(a,A) , 'RandomDPH failed to return a valid DPH representation!');
	assert(max(abs(MomentsFromDPH(a,A,1)-10))<10^-14 , 'RandomDPH failed to match the given mean value!');
	disp('========================================')
	help CheckMGRepresentation
	disp('Input:');
	disp('------');
	a = [-0.6, 0.3, 1.3];
	disp('a = ');
	disp(a);
	A = [0.25, 0.2, -0.15; 0.3, 0.1, 0.25; 0, 0.2, 0.47];
	disp('A = ');
	disp(A);
	disp('Test:');
	disp('-----');
	disp('flag = CheckMGRepresentation(a,A):');
	flag = CheckMGRepresentation(a,A);
	disp('flag = ');
	disp(flag);
	assert(flag==true , 'CheckMGRepresentation failed to recognize a valid MG distribution!');
	disp('Input:');
	disp('------');
	a = [-0.6, 0.3, 1.3];
	disp('a = ');
	disp(a);
	A = [0.35, 0.2, -0.25; 0.3, 0.1, 0.25; 0, 0.2, 0.47];
	disp('A = ');
	disp(A);
	disp('Test:');
	disp('-----');
	disp('flag = CheckMGRepresentation(a,A):');
	flag = CheckMGRepresentation(a,A);
	disp('flag = ');
	disp(flag);
	assert(flag==false , 'CheckMGRepresentation failed to recognize wrong eigenvalues!');
	disp('========================================')
	help CheckDPHRepresentation
	disp('Input:');
	disp('------');
	a = [0.48, 0.08, 0.26, 0.18];
	disp('a = ');
	disp(a);
	A = [0, 0.08, 0.08, 0.8; 0.55, 0, 0.24, 0.19; 0.06, 0.03, 0, 0.001; 0.23, 0.005, 0.2, 0.53];
	disp('A = ');
	disp(A);
	disp('Test:');
	disp('-----');
	disp('flag = CheckDPHRepresentation(a,A):');
	flag = CheckDPHRepresentation(a,A);
	disp('flag = ');
	disp(flag);
	assert(flag==true , 'CheckDPHRepresentation failed to recognize a valid DPH distribution!');
	disp('Input:');
	disp('------');
	a = [0.48, 0.08];
	disp('a = ');
	disp(a);
	A = [0, 0.08; 0.55, 0.5];
	disp('A = ');
	disp(A);
	disp('Test:');
	disp('-----');
	disp('flag = CheckDPHRepresentation(a,A):');
	flag = CheckDPHRepresentation(a,A);
	disp('flag = ');
	disp(flag);
	assert(flag==false , 'CheckDPHRepresentation failed to recognize wrong row sums!');
	disp('========================================')
	help MGFromMoments
	disp('Input:');
	disp('------');
	moms = [4.08, 20.41, 130.45, 1054.41, 10463.73];
	disp('moms = ');
	disp(moms);
	disp('Test:');
	disp('-----');
	disp('[a,A] = MGFromMoments(moms):');
	[a,A] = MGFromMoments(moms);
	disp('a = ');
	disp(a);
	disp('A = ');
	disp(A);
	disp('memoms = MomentsFromMG(a,A,5):');
	memoms = MomentsFromMG(a,A,5);
	disp('memoms = ');
	disp(memoms);
	assert(norm(moms-memoms)<10^-9 , 'The moments of the result of MGFromMoments do not match the input!');
	disp('========================================')
	help DPHFromMG
	disp('Input:');
	disp('------');
	a = [-0.6, 0.3, 1.3];
	disp('a = ');
	disp(a);
	A = [0.1, 0.2, 0; 0.3, 0.1, 0.25; -0.3, 0.2, 0.77];
	disp('A = ');
	disp(A);
	disp('Test:');
	disp('-----');
	disp('flag = CheckMGRepresentation(a,A):');
	flag = CheckMGRepresentation(a,A);
	disp('flag = ');
	disp(flag);
	disp('flag = CheckDPHRepresentation(a,A):');
	flag = CheckDPHRepresentation(a,A);
	disp('flag = ');
	disp(flag);
	disp('[b,B] = DPHFromMG(a,A):');
	[b,B] = DPHFromMG(a,A);
	disp('b = ');
	disp(b);
	disp('B = ');
	disp(B);
	disp('flag = CheckDPHRepresentation(b,B):');
	flag = CheckDPHRepresentation(b,B);
	disp('flag = ');
	disp(flag);
	Cm = SimilarityMatrix(A,B);
	err1 = norm(A*Cm-Cm*B);
	err2 = norm(a*Cm-b);
	disp('Transformation errors:');
	disp(max(err1,err2));
	assert(flag && err1<10^-12 && err2<10^-12 , 'Transformation to DPH failed!');
	disp('========================================')
	help CanonicalFromDPH2
	disp('Input:');
	disp('------');
	a = [0, 1.0];
	disp('a = ');
	disp(a);
	A = [0.23, 0.22; 0.41, 0.48];
	disp('A = ');
	disp(A);
	disp('Test:');
	disp('-----');
	disp('[b,B] = CanonicalFromDPH2(a,A):');
	[b,B] = CanonicalFromDPH2(a,A);
	disp('b = ');
	disp(b);
	disp('B = ');
	disp(B);
	disp('ev = Eigenvalues(A):');
	ev = Eigenvalues(A);
	disp('ev = ');
	disp(ev);
	disp('flag = CheckDPHRepresentation(b,B):');
	flag = CheckDPHRepresentation(b,B);
	disp('flag = ');
	disp(flag);
	Cm = SimilarityMatrix(A,B);
	err1 = norm(A*Cm-Cm*B);
	err2 = norm(a*Cm-b);
	assert(err1<10^-12 && err2<10^-12 , 'Transformation to canonical DPH(2) failed!');
	disp('Input:');
	disp('------');
	a = [1.0, 0];
	disp('a = ');
	disp(a);
	A = [0, 0.61; 0.56, 0.44];
	disp('A = ');
	disp(A);
	disp('Test:');
	disp('-----');
	disp('[b,B] = CanonicalFromDPH2(a,A):');
	[b,B] = CanonicalFromDPH2(a,A);
	disp('b = ');
	disp(b);
	disp('B = ');
	disp(B);
	disp('ev = Eigenvalues(A):');
	ev = Eigenvalues(A);
	disp('ev = ');
	disp(ev);
	disp('flag = CheckDPHRepresentation(b,B):');
	flag = CheckDPHRepresentation(b,B);
	disp('flag = ');
	disp(flag);
	Cm = SimilarityMatrix(A,B);
	err1 = norm(A*Cm-Cm*B);
	err2 = norm(a*Cm-b);
	disp('Transformation errors:');
	disp(max(err1,err2));
	assert(err1<10^-12 && err2<10^-12 , 'Transformation to canonical DPH(2) failed!');
	disp('========================================')
	help CanonicalFromDPH3
	disp('Input:');
	disp('------');
	a = [0.46, 0.22, 0.32];
	disp('a = ');
	disp(a);
	A = [0.67, 0.01, 0.12; 0.06, 0.45, 0.15; 0.18, 0.43, 0.32];
	disp('A = ');
	disp(A);
	disp('Test:');
	disp('-----');
	disp('[b,B] = CanonicalFromDPH3(a,A):');
	[b,B] = CanonicalFromDPH3(a,A);
	disp('b = ');
	disp(b);
	disp('B = ');
	disp(B);
	disp('ev = Eigenvalues(A):');
	ev = Eigenvalues(A);
	disp('ev = ');
	disp(ev);
	disp('flag = CheckDPHRepresentation(b,B):');
	flag = CheckDPHRepresentation(b,B);
	disp('flag = ');
	disp(flag);
	Cm = SimilarityMatrix(A,B);
	err1 = norm(A*Cm-Cm*B);
	err2 = norm(a*Cm-b);
	disp('Transformation errors:');
	disp(max(err1,err2));
	assert(flag && err1<10^-12 && err2<10^-12 , 'Transformation to canonical DPH(3) failed!');
	disp('Input:');
	disp('------');
	a = [0.76, 0.12, 0.12];
	disp('a = ');
	disp(a);
	A = [0.31, 0., 0.; 0.98, 0., 0.02; 0.88, 0.04, 0.08];
	disp('A = ');
	disp(A);
	disp('Test:');
	disp('-----');
	disp('[b,B] = CanonicalFromDPH3(a,A):');
	[b,B] = CanonicalFromDPH3(a,A);
	disp('b = ');
	disp(b);
	disp('B = ');
	disp(B);
	disp('ev = Eigenvalues(A):');
	ev = Eigenvalues(A);
	disp('ev = ');
	disp(ev);
	disp('flag = CheckDPHRepresentation(b,B):');
	flag = CheckDPHRepresentation(b,B);
	disp('flag = ');
	disp(flag);
	Cm = SimilarityMatrix(A,B);
	err1 = norm(A*Cm-Cm*B);
	err2 = norm(a*Cm-b);
	disp('Transformation errors:');
	disp(max(err1,err2));
	assert(flag && err1<10^-12 && err2<10^-12 , 'Transformation to canonical DPH(3) failed!');
	disp('Input:');
	disp('------');
	a = [0.67, 0.07, 0.26];
	disp('a = ');
	disp(a);
	A = [0.31, 0., 0.; 0.98, 0., 0.02; 0.88, 0.04, 0.08];
	disp('A = ');
	disp(A);
	disp('Test:');
	disp('-----');
	disp('[b,B] = CanonicalFromDPH3(a,A):');
	[b,B] = CanonicalFromDPH3(a,A);
	disp('b = ');
	disp(b);
	disp('B = ');
	disp(B);
	disp('ev = Eigenvalues(A):');
	ev = Eigenvalues(A);
	disp('ev = ');
	disp(ev);
	disp('flag = CheckDPHRepresentation(b,B):');
	flag = CheckDPHRepresentation(b,B);
	disp('flag = ');
	disp(flag);
	Cm = SimilarityMatrix(A,B);
	err1 = norm(A*Cm-Cm*B);
	err2 = norm(a*Cm-b);
	disp('Transformation errors:');
	disp(max(err1,err2));
	assert(flag && err1<10^-12 && err2<10^-12 , 'Transformation to canonical DPH(3) failed!');
	disp('Input:');
	disp('------');
	a = [0.78, 0.04, 0.18];
	disp('a = ');
	disp(a);
	A = [0.06, 0.25, 0.31; 0.45, 0.18, 0.33; 0.98, 0, 0.01];
	disp('A = ');
	disp(A);
	disp('Test:');
	disp('-----');
	disp('[b,B] = CanonicalFromDPH3(a,A):');
	[b,B] = CanonicalFromDPH3(a,A);
	disp('b = ');
	disp(b);
	disp('B = ');
	disp(B);
	disp('ev = Eigenvalues(A):');
	ev = Eigenvalues(A);
	disp('ev = ');
	disp(ev);
	disp('flag = CheckDPHRepresentation(b,B):');
	flag = CheckDPHRepresentation(b,B);
	disp('flag = ');
	disp(flag);
	Cm = SimilarityMatrix(A,B);
	err1 = norm(A*Cm-Cm*B);
	err2 = norm(a*Cm-b);
	disp('Transformation errors:');
	disp(max(err1,err2));
	assert(flag && err1<10^-12 && err2<10^-12 , 'Transformation to canonical DPH(3) failed!');
	disp('========================================')
	help AcyclicDPHFromMG
	disp('Input:');
	disp('------');
	a = [0, 0, 1.0];
	disp('a = ');
	disp(a);
	A = [0.22, 0, 0; 0.3, 0.1, 0.55; 0.26, 0, 0.73];
	disp('A = ');
	disp(A);
	disp('Test:');
	disp('-----');
	disp('[b,B] = AcyclicDPHFromMG(a,A):');
	[b,B] = AcyclicDPHFromMG(a,A);
	disp('b = ');
	disp(b);
	disp('B = ');
	disp(B);
	disp('ma = MomentsFromMG(a,A,5):');
	ma = MomentsFromMG(a,A,5);
	disp('ma = ');
	disp(ma);
	disp('mb = MomentsFromMG(b,B,5):');
	mb = MomentsFromMG(b,B,5);
	disp('mb = ');
	disp(mb);
	disp('flag = CheckDPHRepresentation(b,B):');
	flag = CheckDPHRepresentation(b,B);
	disp('flag = ');
	disp(flag);
	Cm = SimilarityMatrix(A,B);
	err1 = norm(A*Cm-Cm*B);
	err2 = norm(a*Cm-b);
	disp('Transformation errors:');
	disp(max(err1,err2));
	assert(err1<10^-12 && err2<10^-12 , 'Transformation to canonical PH(3) failed!');
	disp('========================================')
	help DPH2From3Moments
	disp('Input:');
	disp('------');
	a = [0.9, 0.1];
	disp('a = ');
	disp(a);
	A = [0.2, 0.61; 0.58, 0.41];
	disp('A = ');
	disp(A);
	disp('Test:');
	disp('-----');
	disp('moms = MomentsFromDPH(a,A):');
	moms = MomentsFromDPH(a,A);
	disp('moms = ');
	disp(moms);
	disp('[b,B] = DPH2From3Moments(moms):');
	[b,B] = DPH2From3Moments(moms);
	disp('b = ');
	disp(b);
	disp('B = ');
	disp(B);
	disp('phmoms = MomentsFromDPH(b,B,3):');
	phmoms = MomentsFromDPH(b,B,3);
	disp('phmoms = ');
	disp(phmoms);
	assert(norm((phmoms-moms)/moms)<10^-12 , 'The moments of the result of DPH2From3Moments do not match the input!');
	disp('========================================')
	help DPH3From5Moments
	disp('Input:');
	disp('------');
	a = [0.7, 0.1, 0.2];
	disp('a = ');
	disp(a);
	A = [0.2, 0.51, 0.1; 0.58, 0.41, 0; 0.1, 0.4, 0.3];
	disp('A = ');
	disp(A);
	disp('Test:');
	disp('-----');
	disp('moms = MomentsFromDPH(a,A):');
	moms = MomentsFromDPH(a,A);
	disp('moms = ');
	disp(moms);
	disp('[b,B] = DPH3From5Moments(moms):');
	[b,B] = DPH3From5Moments(moms);
	disp('b = ');
	disp(b);
	disp('B = ');
	disp(B);
	disp('phmoms = MomentsFromMG(b,B,5):');
	phmoms = MomentsFromMG(b,B,5);
	disp('phmoms = ');
	disp(phmoms);
	assert(norm((phmoms-moms)/moms)<10^-12 , 'The moments of the result of DPH3From5Moments do not match the input!');
	disp('========================================')
	help SamplesFromDPH
	disp('Input:');
	disp('------');
	a = [0.76, 0, 0.24];
	disp('a = ');
	disp(a);
	A = [0.34, 0.66, 0; 0.79, 0.05, 0.07; 0.26, 0.73, 0.01];
	disp('A = ');
	disp(A);
	disp('x = SamplesFromDPH(a,A,1000):');
	x = SamplesFromDPH(a,A,1000);
	disp('mp = MomentsFromDPH(a,A,3):');
	mp = MomentsFromDPH(a,A,3);
	disp('mp = ');
	disp(mp);
end
