ClearAll["Global`*"]
AppendTo[$Path,"/home/gabor/github/butools/Mathematica"];
<<BuTools`
Print["---BuTools: DMAP package test file---"//OutputForm];
Print["Enable the verbose messages with the BuToolsVerbose flag"//OutputForm];
BuTools`Verbose = True;
Print["Enable input parameter checking with the BuToolsCheckInput flag"//OutputForm];
BuTools`CheckInput = true;
On[Assert];
Print["========================================"]
Print["Testing BuTools function MarginalDistributionFromDMAP"]
Print["Input:"//OutputForm];
Print["------"//OutputForm];
D0 = {{0, 0.02, 0, 0},{0, 0.17, 0.2, 0.14},{0.16, 0.17, 0.02, 0.18},{0, 0, 0, 0.12}};
Print["D0 = "//OutputForm];
Print[D0];
D1 = {{0, 0.88, 0.1, 0},{0.18, 0.07, 0.14, 0.1},{0.13, 0.15, 0.15, 0.04},{0.31, 0.18, 0.12, 0.27}};
Print["D1 = "//OutputForm];
Print[D1];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["{a, A} = MarginalDistributionFromDMAP[D0, D1];:"//OutputForm];
{a, A} = MarginalDistributionFromDMAP[D0, D1];
Print["a = "//OutputForm];
Print[a];
Print["A = "//OutputForm];
Print[A];
Assert[Length[a]==Dimensions[D0][[1]]&&CheckDPHRepresentation[a, A], "MarginalDistributionFromDMAP returned a wrong DPH representation!"];
Print["========================================"]
Print["Testing BuTools function MarginalMomentsFromDMAP"]
Print["Input:"//OutputForm];
Print["------"//OutputForm];
D0 = {{0, 0.02, 0, 0},{0, 0.17, 0.2, 0.14},{0.16, 0.17, 0.02, 0.18},{0, 0, 0, 0.12}};
Print["D0 = "//OutputForm];
Print[D0];
D1 = {{0, 0.88, 0.1, 0},{0.18, 0.07, 0.14, 0.1},{0.13, 0.15, 0.15, 0.04},{0.31, 0.18, 0.12, 0.27}};
Print["D1 = "//OutputForm];
Print[D1];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["moms = MarginalMomentsFromDMAP[D0, D1];:"//OutputForm];
moms = MarginalMomentsFromDMAP[D0, D1];
Print["moms = "//OutputForm];
Print[moms];
Assert[Length[moms]==2*Dimensions[D0][[1]]-1&&CheckMoments[moms], "MarginalMomentsFromDMAP returned wrong moments!"];
Print["========================================"]
Print["Testing BuTools function MarginalDistributionFromDRAP"]
Print["Input:"//OutputForm];
Print["------"//OutputForm];
H0 = {{0, 0, 0.13},{0, 0.6, 0.18},{0.31, 0.26, 0.02}};
Print["H0 = "//OutputForm];
Print[H0];
H1 = {{0, 1, -0.13},{0, 0.18, 0.04},{0.03, 0.09, 0.29}};
Print["H1 = "//OutputForm];
Print[H1];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["{a, A} = MarginalDistributionFromDRAP[H0, H1];:"//OutputForm];
{a, A} = MarginalDistributionFromDRAP[H0, H1];
Print["a = "//OutputForm];
Print[a];
Print["A = "//OutputForm];
Print[A];
Assert[Length[a]==Dimensions[H0][[1]]&&CheckMGRepresentation[a, A], "MarginalDistributionFromDRAP returned a wrong MG representation!"];
Print["========================================"]
Print["Testing BuTools function MarginalMomentsFromDRAP"]
Print["Input:"//OutputForm];
Print["------"//OutputForm];
H0 = {{0, 0, 0.13},{0, 0.6, 0.18},{0.31, 0.26, 0.02}};
Print["H0 = "//OutputForm];
Print[H0];
H1 = {{0, 1, -0.13},{0, 0.18, 0.04},{0.03, 0.09, 0.29}};
Print["H1 = "//OutputForm];
Print[H1];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["moms = MarginalMomentsFromDRAP[H0, H1];:"//OutputForm];
moms = MarginalMomentsFromDRAP[H0, H1];
Print["moms = "//OutputForm];
Print[moms];
Assert[Length[moms]==2*Dimensions[H0][[1]]-1&&CheckMoments[moms], "MarginalMomentsFromDRAP returned wrong moments!"];
Print["========================================"]
Print["Testing BuTools function MarginalDistributionFromDMMAP"]
D0 = {{0.34, 0, 0},{0.06, 0.05, 0.03},{0.11, 0.13, 0}};
Print["D0 = "//OutputForm];
Print[D0];
D1 = {{0.3, 0, 0},{0.16, 0.18, 0.05},{0.15, 0.04, 0.09}};
Print["D1 = "//OutputForm];
Print[D1];
D2 = {{0, 0.01, 0},{0.1, 0.07, 0.08},{0.13, 0.12, 0.13}};
Print["D2 = "//OutputForm];
Print[D2];
D3 = {{0.35, 0, 0},{0, 0.18, 0.04},{0.06, 0.03, 0.01}};
Print["D3 = "//OutputForm];
Print[D3];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["{a, A} = MarginalDistributionFromDMMAP[{D0, D1, D2, D3}];:"//OutputForm];
{a, A} = MarginalDistributionFromDMMAP[{D0, D1, D2, D3}];
Print["a = "//OutputForm];
Print[a];
Print["A = "//OutputForm];
Print[A];
Assert[Length[a]==Dimensions[D0][[1]]&&CheckDPHRepresentation[a, A], "MarginalDistributionFromDMMAP returned a wrong DPH representation!"];
Print["========================================"]
Print["Testing BuTools function MarginalMomentsFromDMMAP"]
Print["Input:"//OutputForm];
Print["------"//OutputForm];
D0 = {{0.34, 0, 0},{0.06, 0.05, 0.03},{0.11, 0.13, 0}};
Print["D0 = "//OutputForm];
Print[D0];
D1 = {{0.3, 0, 0},{0.16, 0.18, 0.05},{0.15, 0.04, 0.09}};
Print["D1 = "//OutputForm];
Print[D1];
D2 = {{0, 0.01, 0},{0.1, 0.07, 0.08},{0.13, 0.12, 0.13}};
Print["D2 = "//OutputForm];
Print[D2];
D3 = {{0.35, 0, 0},{0, 0.18, 0.04},{0.06, 0.03, 0.01}};
Print["D3 = "//OutputForm];
Print[D3];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["moms = MarginalMomentsFromDMMAP[{D0, D1, D2, D3}];:"//OutputForm];
moms = MarginalMomentsFromDMMAP[{D0, D1, D2, D3}];
Print["moms = "//OutputForm];
Print[moms];
Assert[Length[moms]==2*Dimensions[D0][[1]]-1&&CheckMoments[moms], "MarginalMomentsFromDMMAP returned wrong moments!"];
Print["========================================"]
Print["Testing BuTools function MarginalDistributionFromDMRAP"]
Print["Input:"//OutputForm];
Print["------"//OutputForm];
H0 = {{0.15, 0.2, 0.18},{-0.23, 0.17, 0.22},{0.19, 0.15, 0.16}};
Print["H0 = "//OutputForm];
Print[H0];
H1 = {{0.01, 0.08, 0.16},{0.02, 0.2, 0.07},{0.02, 0.15, 0.17}};
Print["H1 = "//OutputForm];
Print[H1];
H2 = {{0.14, 0.07, 0.01},{0.19, 0.02, 0.34},{0.06, 0.1, 0}};
Print["H2 = "//OutputForm];
Print[H2];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["{a, A} = MarginalDistributionFromDMRAP[{H0, H1, H2}];:"//OutputForm];
{a, A} = MarginalDistributionFromDMRAP[{H0, H1, H2}];
Print["a = "//OutputForm];
Print[a];
Print["A = "//OutputForm];
Print[A];
Assert[Length[a]==Dimensions[H0][[1]]&&CheckMGRepresentation[a, A], "MarginalDistributionFromDMRAP returned a wrong MG representation!"];
Print["========================================"]
Print["Testing BuTools function MarginalMomentsFromDMRAP"]
Print["Input:"//OutputForm];
Print["------"//OutputForm];
H0 = {{0.15, 0.2, 0.18},{-0.23, 0.17, 0.22},{0.19, 0.15, 0.16}};
Print["H0 = "//OutputForm];
Print[H0];
H1 = {{0.01, 0.08, 0.16},{0.02, 0.2, 0.07},{0.02, 0.15, 0.17}};
Print["H1 = "//OutputForm];
Print[H1];
H2 = {{0.14, 0.07, 0.01},{0.19, 0.02, 0.34},{0.06, 0.1, 0}};
Print["H2 = "//OutputForm];
Print[H2];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["moms = MarginalMomentsFromDMRAP[{H0, H1, H2}];:"//OutputForm];
moms = MarginalMomentsFromDMRAP[{H0, H1, H2}];
Print["moms = "//OutputForm];
Print[moms];
Assert[Length[moms]==2*Dimensions[H0][[1]]-1&&CheckMoments[moms], "MarginalMomentsFromDMRAP returned wrong moments!"];
Print["========================================"]
Print["Testing BuTools function LagCorrelationsFromDMAP"]
Print["Input:"//OutputForm];
Print["------"//OutputForm];
D0 = {{0, 0.02, 0, 0},{0, 0.17, 0.2, 0.14},{0.16, 0.17, 0.02, 0.18},{0, 0, 0, 0.12}};
Print["D0 = "//OutputForm];
Print[D0];
D1 = {{0, 0.88, 0.1, 0},{0.18, 0.07, 0.14, 0.1},{0.13, 0.15, 0.15, 0.04},{0.31, 0.18, 0.12, 0.27}};
Print["D1 = "//OutputForm];
Print[D1];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["corr = LagCorrelationsFromDMAP[D0, D1, 3];:"//OutputForm];
corr = LagCorrelationsFromDMAP[D0, D1, 3];
Print["corr = "//OutputForm];
Print[corr];
Assert[Length[corr]==3&&AllTrue[corr,#<=1 &]&&AllTrue[corr,#>=-1 &], "LagCorrelationsFromDMAP returned wrong autocorrelation coefficients!"];
Print["========================================"]
Print["Testing BuTools function LagCorrelationsFromDRAP"]
Print["Input:"//OutputForm];
Print["------"//OutputForm];
H0 = {{0, 0, 0.13},{0, 0.6, 0.18},{0.31, 0.26, 0.02}};
Print["H0 = "//OutputForm];
Print[H0];
H1 = {{0, 1, -0.13},{0, 0.18, 0.04},{0.03, 0.09, 0.29}};
Print["H1 = "//OutputForm];
Print[H1];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["corr = LagCorrelationsFromDRAP[H0, H1, 3];:"//OutputForm];
corr = LagCorrelationsFromDRAP[H0, H1, 3];
Print["corr = "//OutputForm];
Print[corr];
Assert[Length[corr]==3&&AllTrue[corr,#<=1 &]&&AllTrue[corr,#>=-1 &], "LagCorrelationsFromDRAP returned wrong autocorrelation coefficients!"];
Print["========================================"]
Print["Testing BuTools function LagkJointMomentsFromDMAP"]
Print["Input:"//OutputForm];
Print["------"//OutputForm];
D0 = {{0, 0.02, 0, 0},{0, 0.17, 0.2, 0.14},{0.16, 0.17, 0.02, 0.18},{0, 0, 0, 0.12}};
Print["D0 = "//OutputForm];
Print[D0];
D1 = {{0, 0.88, 0.1, 0},{0.18, 0.07, 0.14, 0.1},{0.13, 0.15, 0.15, 0.04},{0.31, 0.18, 0.12, 0.27}};
Print["D1 = "//OutputForm];
Print[D1];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["Nm = LagkJointMomentsFromDMAP[D0, D1, 4, 1];:"//OutputForm];
Nm = LagkJointMomentsFromDMAP[D0, D1, 4, 1];
Print["Nm = "//OutputForm];
Print[Nm];
Print["moms = MarginalMomentsFromDMAP[D0, D1, 4];:"//OutputForm];
moms = MarginalMomentsFromDMAP[D0, D1, 4];
Print["moms = "//OutputForm];
Print[moms];
cjm = Table[0,{3}];
Do[
    Nx = LagkJointMomentsFromDMAP[D0, D1, 1, i];
    cjm[[i]] = (Nx[[2, 2]]-moms[[1]]^2)/(moms[[2]]-moms[[1]]^2);
, {i,1,3,1}];
Print["Correlation from joint moments:"];
Print[cjm];
Print["corr = LagCorrelationsFromDMAP[D0, D1, 3];:"//OutputForm];
corr = LagCorrelationsFromDMAP[D0, D1, 3];
Print["corr = "//OutputForm];
Print[corr];
mNm1 = Flatten[Nm[[1, 2;;-1]]];
mNm2 = Flatten[Nm[[2;;-1, 1]]];
Assert[AllTrue[Flatten[Nm],#>0 &]&&Norm[moms-mNm1]<10^-12&&Norm[moms-mNm2]<10^-12&&Norm[corr-cjm]<10^-12, "Joint moment matrix is invalid!"];
Print["========================================"]
Print["Testing BuTools function LagkJointMomentsFromDRAP"]
Print["Input:"//OutputForm];
Print["------"//OutputForm];
H0 = {{0, 0, 0.13},{0, 0.6, 0.18},{0.31, 0.26, 0.02}};
Print["H0 = "//OutputForm];
Print[H0];
H1 = {{0, 1, -0.13},{0, 0.18, 0.04},{0.03, 0.09, 0.29}};
Print["H1 = "//OutputForm];
Print[H1];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["Nm = LagkJointMomentsFromDRAP[H0, H1, 4, 1];:"//OutputForm];
Nm = LagkJointMomentsFromDRAP[H0, H1, 4, 1];
Print[Length[Nm]];
Print["moms = MarginalMomentsFromDRAP[H0, H1, 4];:"//OutputForm];
moms = MarginalMomentsFromDRAP[H0, H1, 4];
Print["moms = "//OutputForm];
Print[moms];
cjm = Table[0,{3}];
Do[
    Nx = LagkJointMomentsFromDRAP[H0, H1, 1, i];
    cjm[[i]] = (Nx[[2, 2]]-moms[[1]]^2)/(moms[[2]]-moms[[1]]^2);
, {i,1,3,1}];
Print["Correlation from joint moments:"];
Print[cjm];
Print["corr = LagCorrelationsFromDRAP[H0, H1, 3];:"//OutputForm];
corr = LagCorrelationsFromDRAP[H0, H1, 3];
Print["corr = "//OutputForm];
Print[corr];
mNm1 = Flatten[Nm[[1, 2;;-1]]];
mNm2 = Flatten[Nm[[2;;-1, 1]]];
Assert[AllTrue[Flatten[Nm],#>0 &]&&Norm[moms-mNm1]<10^-12&&Norm[moms-mNm2]<10^-12&&Norm[corr-cjm]<10^-12, "Joint moment matrix is invalid!"];
Print["========================================"]
Print["Testing BuTools function LagkJointMomentsFromDMMAP"]
Print["Input:"//OutputForm];
Print["------"//OutputForm];
D0 = {{0.34, 0, 0},{0.06, 0.05, 0.03},{0.11, 0.13, 0}};
Print["D0 = "//OutputForm];
Print[D0];
D1 = {{0.3, 0, 0},{0.16, 0.18, 0.05},{0.15, 0.04, 0.09}};
Print["D1 = "//OutputForm];
Print[D1];
D2 = {{0, 0.01, 0},{0.1, 0.07, 0.08},{0.13, 0.12, 0.13}};
Print["D2 = "//OutputForm];
Print[D2];
D3 = {{0.35, 0, 0},{0, 0.18, 0.04},{0.06, 0.03, 0.01}};
Print["D3 = "//OutputForm];
Print[D3];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["Nm = LagkJointMomentsFromDMMAP[{D0, D1, D2, D3}, 3, 1];:"//OutputForm];
Nm = LagkJointMomentsFromDMMAP[{D0, D1, D2, D3}, 3, 1];
Print[Nm[[1]]];
Print[Nm[[2]]];
Print[Nm[[3]]];
Assert[Length[Nm]==3&&Norm[Nm[[1]]+Nm[[2]]+Nm[[3]]-LagkJointMomentsFromDMAP[D0, D1+D2+D3, 3, 1]]<10^-12, "Joint moment matrix is invalid!"];
Print["========================================"]
Print["Testing BuTools function LagkJointMomentsFromDMRAP"]
Print["Input:"//OutputForm];
Print["------"//OutputForm];
H0 = {{0.15, 0.2, 0.18},{-0.23, 0.17, 0.22},{0.19, 0.15, 0.16}};
Print["H0 = "//OutputForm];
Print[H0];
H1 = {{0.01, 0.08, 0.16},{0.02, 0.2, 0.07},{0.02, 0.15, 0.17}};
Print["H1 = "//OutputForm];
Print[H1];
H2 = {{0.14, 0.07, 0.01},{0.19, 0.02, 0.34},{0.06, 0.1, 0}};
Print["H2 = "//OutputForm];
Print[H2];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["Nm = LagkJointMomentsFromDMRAP[{H0, H1, H2}, 3, 2];:"//OutputForm];
Nm = LagkJointMomentsFromDMRAP[{H0, H1, H2}, 3, 2];
Print[Nm[[1]]];
Print[Nm[[2]]];
Assert[Length[Nm]==2&&Norm[Nm[[1]]+Nm[[2]]-LagkJointMomentsFromDRAP[H0, H1+H2, 3, 2]]<10^-12, "Joint moment matrix is invalid!"];
Print["========================================"]
Print["Testing BuTools function RandomDMAP"]
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["{D0, D1} = RandomDMAP[4, 5.62, 10];:"//OutputForm];
{D0, D1} = RandomDMAP[4, 5.62, 10];
Print["D0 = "//OutputForm];
Print[D0];
Print["D1 = "//OutputForm];
Print[D1];
Print["m = MarginalMomentsFromDMAP[D0, D1, 1][[1]];:"//OutputForm];
m = MarginalMomentsFromDMAP[D0, D1, 1][[1]];
Print["m = "//OutputForm];
Print[m];
Assert[CheckDMAPRepresentation[D0, D1], "RandomDMAP failed to return a valid DMAP representation!"];
Assert[Abs[m-5.62]<10^-14, "RandomDMAP failed to match the given mean value!"];
Print["========================================"]
Print["Testing BuTools function RandomDMMAP"]
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["Dm = RandomDMMAP[4, 3, 5.62, 10];:"//OutputForm];
Dm = RandomDMMAP[4, 3, 5.62, 10];
Print[Dm[[1]]];
Print[Dm[[2]]];
Print[Dm[[3]]];
Print[Dm[[4]]];
Print["m = MarginalMomentsFromDMMAP[Dm, 1][[1]];:"//OutputForm];
m = MarginalMomentsFromDMMAP[Dm, 1][[1]];
Print["m = "//OutputForm];
Print[m];
Assert[CheckDMMAPRepresentation[Dm], "RandomDMMAP failed to return a valid MMAP representation!"];
Assert[Abs[m-5.62]<10^-14, "RandomDMMAP failed to match the given mean value!"];
Print["========================================"]
Print["Testing BuTools function CheckDMAPRepresentation"]
Print["Input:"//OutputForm];
Print["------"//OutputForm];
D0 = {{0, 0.02, 0},{0, 0.17, 0.2},{0.16, 0.17, 0.02}};
Print["D0 = "//OutputForm];
Print[D0];
D1 = {{0, 0.88, 0.1, 0},{0.18, 0.07, 0.14, 0.1},{0.13, 0.15, 0.15, 0.04},{0.31, 0.18, 0.12, 0.27}};
Print["D1 = "//OutputForm];
Print[D1];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["flag = CheckDMAPRepresentation[D0, D1];:"//OutputForm];
flag = CheckDMAPRepresentation[D0, D1];
Print["flag = "//OutputForm];
Print[flag];
Assert[flag==False, "CheckDMAPRepresentation failed to detect the incompatible shapes of D0 and D1!"];
Print["Input:"//OutputForm];
Print["------"//OutputForm];
D0 = {{0, 0.02, 0},{0, 0.17, 0.2},{0.16, 0.17, 0.02}};
Print["D0 = "//OutputForm];
Print[D0];
D1 = {{0, 0.88, 0.1},{0.18, 0.07, 0.14},{0.13, 0.15, 0.15}};
Print["D1 = "//OutputForm];
Print[D1];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["flag = CheckDMAPRepresentation[D0, D1];:"//OutputForm];
flag = CheckDMAPRepresentation[D0, D1];
Print["flag = "//OutputForm];
Print[flag];
Assert[flag==False, "CheckDMAPRepresentation failed to detect invalid rowsums!"];
Print["Input:"//OutputForm];
Print["------"//OutputForm];
D0 = {{0, 0.02, 0, 0},{0, 0.17, 0.2, 0.14},{0.16, 0.17, 0.02, 0.18},{0, 0, 0, 0.12}};
Print["D0 = "//OutputForm];
Print[D0];
D1 = {{0, 0.88, 0.1, 0},{0.18, 0.07, 0.14, 0.1},{0.13, 0.15, 0.15, 0.04},{0.31, 0.18, 0.12, 0.27}};
Print["D1 = "//OutputForm];
Print[D1];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["flag = CheckDMAPRepresentation[D0, D1];:"//OutputForm];
flag = CheckDMAPRepresentation[D0, D1];
Print["flag = "//OutputForm];
Print[flag];
Assert[flag==True, "CheckDMAPRepresentation failed to recognize a valid DMAP representation!"];
Print["========================================"]
Print["Testing BuTools function CheckDRAPRepresentation"]
Print["Input:"//OutputForm];
Print["------"//OutputForm];
H0 = {{0, 0, 0.13},{0, 0.6, 0.18},{0.31, 0.26, 0.02},{0.2, 0, 0}};
Print["H0 = "//OutputForm];
Print[H0];
H1 = {{0, 1., -0.13},{0, 0.18, 0.04},{0.03, 0.09, 0.29},{0, 0.8, 0}};
Print["H1 = "//OutputForm];
Print[H1];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["flag = CheckDRAPRepresentation[H0, H1];:"//OutputForm];
flag = CheckDRAPRepresentation[H0, H1];
Print["flag = "//OutputForm];
Print[flag];
Assert[flag==False, "CheckDRAPRepresentation failed to detect the incompatible shapes of D0 and D1!"];
Print["Input:"//OutputForm];
Print["------"//OutputForm];
H0 = {{0.2, 0, 0.13},{0, 0.6, 0.18},{0.31, 0.26, 0.02}};
Print["H0 = "//OutputForm];
Print[H0];
H1 = {{0, 1., -0.13},{0, 0.18, 0.04},{0.03, 0.09, 0.29}};
Print["H1 = "//OutputForm];
Print[H1];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["flag = CheckDRAPRepresentation[H0, H1];:"//OutputForm];
flag = CheckDRAPRepresentation[H0, H1];
Print["flag = "//OutputForm];
Print[flag];
Assert[flag==False, "CheckDRAPRepresentation failed to detect invalid rowsums!"];
Print["Input:"//OutputForm];
Print["------"//OutputForm];
H0 = {{-1., 0, 0},{0, -2., 2.},{0, 3., -3.}};
Print["H0 = "//OutputForm];
Print[H0];
H1 = {{0, 0, 1.},{0, -1., 1.},{1., 0, -1.}};
Print["H1 = "//OutputForm];
Print[H1];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["flag = CheckDRAPRepresentation[H0, H1];:"//OutputForm];
flag = CheckDRAPRepresentation[H0, H1];
Print["flag = "//OutputForm];
Print[flag];
Assert[flag==False, "CheckDRAPRepresentation failed to detect invalid eigenvalues!"];
Print["Input:"//OutputForm];
Print["------"//OutputForm];
H0 = {{0, 0, 15.},{0, 0.6, 0.18},{0.31, 0.26, 0.02}};
Print["H0 = "//OutputForm];
Print[H0];
H1 = {{0, 1., -15.},{0, 0.18, 0.04},{0.03, 0.09, 0.29}};
Print["H1 = "//OutputForm];
Print[H1];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["flag = CheckDRAPRepresentation[H0, H1];:"//OutputForm];
flag = CheckDRAPRepresentation[H0, H1];
Print["flag = "//OutputForm];
Print[flag];
Assert[flag==False, "CheckDRAPRepresentation failed to detect invalid eigenvalues!"];
Print["Input:"//OutputForm];
Print["------"//OutputForm];
H0 = {{0, 0.5, 0.1},{0, -1.4, 3.1},{0.67, 0, 0.4}};
Print["H0 = "//OutputForm];
Print[H0];
H1 = {{0, 0.4, 0},{0, -0.2, -0.5},{0.3, -0.7, 0.33}};
Print["H1 = "//OutputForm];
Print[H1];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["flag = CheckDRAPRepresentation[H0, H1];:"//OutputForm];
flag = CheckDRAPRepresentation[H0, H1];
Print["flag = "//OutputForm];
Print[flag];
Assert[flag==False, "CheckDRAPRepresentation failed to detect invalid eigenvalues!"];
Print["Input:"//OutputForm];
Print["------"//OutputForm];
H0 = {{0, 0, 0.13},{0, 0.6, 0.18},{0.31, 0.26, 0.02}};
Print["H0 = "//OutputForm];
Print[H0];
H1 = {{0, 1., -0.13},{0, 0.18, 0.04},{0.03, 0.09, 0.29}};
Print["H1 = "//OutputForm];
Print[H1];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["flag = CheckDRAPRepresentation[H0, H1];:"//OutputForm];
flag = CheckDRAPRepresentation[H0, H1];
Print["flag = "//OutputForm];
Print[flag];
Assert[flag==True, "CheckDRAPRepresentation failed to recognize a valid RAP representation!"];
Print["========================================"]
Print["Testing BuTools function CheckDMMAPRepresentation"]
Print["Input:"//OutputForm];
Print["------"//OutputForm];
D0 = {{0.34, 0, 0},{0.06, 0.05, 0.03},{0.11, 0.13, 0}};
Print["D0 = "//OutputForm];
Print[D0];
D1 = {{0.3, 0, 0},{0.16, 0.18, 0.05},{0.15, 0.04, 0.09}};
Print["D1 = "//OutputForm];
Print[D1];
D2 = {{0, 0.01, 0},{0.1, 0.07, 0.08},{0.13, 0.12, 0.13}};
Print["D2 = "//OutputForm];
Print[D2];
D3 = {{0.35, 0, 0},{0, 0.18, 0.04},{0.06, 0.03, 0.01}};
Print["D3 = "//OutputForm];
Print[D3];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["flag = CheckDMMAPRepresentation[{D0, D1, D2, D3}];:"//OutputForm];
flag = CheckDMMAPRepresentation[{D0, D1, D2, D3}];
Print["flag = "//OutputForm];
Print[flag];
Assert[flag==True, "CheckDMMAPRepresentation failed to recognize a valid DMMAP representation!"];
Print["========================================"]
Print["Testing BuTools function CheckDMRAPRepresentation"]
Print["Input:"//OutputForm];
Print["------"//OutputForm];
H0 = {{0.15, 0.2, 0.18},{-0.23, 0.17, 0.22},{0.19, 0.15, 0.16}};
Print["H0 = "//OutputForm];
Print[H0];
H1 = {{0.01, 0.08, 0.16},{0.02, 0.2, 0.07},{0.02, 0.15, 0.17}};
Print["H1 = "//OutputForm];
Print[H1];
H2 = {{0.14, 0.07, 0.01},{0.19, 0.02, 0.34},{0.06, 0.1, 0}};
Print["H2 = "//OutputForm];
Print[H2];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["flag = CheckDMRAPRepresentation[{H0, H1, H2}];:"//OutputForm];
flag = CheckDMRAPRepresentation[{H0, H1, H2}];
Print["flag = "//OutputForm];
Print[flag];
Assert[flag==True, "CheckDMRAPRepresentation failed to recognize a valid DMRAP representation!"];
Print["========================================"]
Print["Testing BuTools function DRAPFromMoments"]
Print["Input:"//OutputForm];
Print["------"//OutputForm];
G0 = {{0, 0.02, 0, 0},{0, 0.17, 0.2, 0.14},{0.16, 0.17, 0.02, 0.18},{0, 0, 0, 0.12}};
Print["G0 = "//OutputForm];
Print[G0];
G1 = {{0, 0.88, 0.1, 0},{0.18, 0.07, 0.14, 0.1},{0.13, 0.15, 0.15, 0.04},{0.31, 0.18, 0.12, 0.27}};
Print["G1 = "//OutputForm];
Print[G1];
Print["moms = MarginalMomentsFromDRAP[G0, G1, 5];:"//OutputForm];
moms = MarginalMomentsFromDRAP[G0, G1, 5];
Print["moms = "//OutputForm];
Print[moms];
Print["Nm = LagkJointMomentsFromDRAP[G0, G1, 2, 1];:"//OutputForm];
Nm = LagkJointMomentsFromDRAP[G0, G1, 2, 1];
Print["Nm = "//OutputForm];
Print[Nm];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["{H0, H1} = DRAPFromMoments[moms, Nm];:"//OutputForm];
{H0, H1} = DRAPFromMoments[moms, Nm];
Print["H0 = "//OutputForm];
Print[H0];
Print["H1 = "//OutputForm];
Print[H1];
Print["rmoms = MarginalMomentsFromDRAP[H0, H1, 5];:"//OutputForm];
rmoms = MarginalMomentsFromDRAP[H0, H1, 5];
Print["rmoms = "//OutputForm];
Print[rmoms];
Print["rNm = LagkJointMomentsFromDRAP[H0, H1, 2, 1];:"//OutputForm];
rNm = LagkJointMomentsFromDRAP[H0, H1, 2, 1];
Print["rNm = "//OutputForm];
Print[rNm];
Assert[Norm[moms-rmoms]<10^-11&&Norm[Nm-rNm]<10^-12, "The moments and joint moments returned by RAPFromMoments are not the same as given!"];
Print["========================================"]
Print["Testing BuTools function DMRAPFromMoments"]
Print["Input:"//OutputForm];
Print["------"//OutputForm];
G0 = {{0.34, 0, 0},{0.06, 0.05, 0.03},{0.11, 0.13, 0}};
Print["G0 = "//OutputForm];
Print[G0];
G1 = {{0.3, 0, 0},{0.16, 0.18, 0.05},{0.15, 0.04, 0.09}};
Print["G1 = "//OutputForm];
Print[G1];
G2 = {{0, 0.01, 0},{0.1, 0.07, 0.08},{0.13, 0.12, 0.13}};
Print["G2 = "//OutputForm];
Print[G2];
G3 = {{0.35, 0, 0},{0, 0.18, 0.04},{0.06, 0.03, 0.01}};
Print["G3 = "//OutputForm];
Print[G3];
Print["G = {G0, G1, G2, G3};:"//OutputForm];
G = {G0, G1, G2, G3};
Print["moms = MarginalMomentsFromDMRAP[G, 5];:"//OutputForm];
moms = MarginalMomentsFromDMRAP[G, 5];
Print["moms = "//OutputForm];
Print[moms];
Print["Nm = LagkJointMomentsFromDMRAP[G, 2, 1];:"//OutputForm];
Nm = LagkJointMomentsFromDMRAP[G, 2, 1];
Print["{Nm1, Nm2, Nm3} = Nm;:"//OutputForm];
{Nm1, Nm2, Nm3} = Nm;
Print["Nm1 = "//OutputForm];
Print[Nm1];
Print["Nm2 = "//OutputForm];
Print[Nm2];
Print["Nm3 = "//OutputForm];
Print[Nm3];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["H = DMRAPFromMoments[moms, Nm];:"//OutputForm];
H = DMRAPFromMoments[moms, Nm];
Print["H[[1]]:"//OutputForm];
Print[H[[1]]];
Print["H[[2]]:"//OutputForm];
Print[H[[2]]];
Print["H[[3]]:"//OutputForm];
Print[H[[3]]];
Print["H[[4]]:"//OutputForm];
Print[H[[4]]];
BuTools`CheckPrecision = 10.^-10;
Print["rmoms = MarginalMomentsFromDMRAP[H, 5];:"//OutputForm];
rmoms = MarginalMomentsFromDMRAP[H, 5];
Print["rmoms = "//OutputForm];
Print[rmoms];
Print["rNm = LagkJointMomentsFromDMRAP[H, 2, 1];:"//OutputForm];
rNm = LagkJointMomentsFromDMRAP[H, 2, 1];
Print["{rNm1, rNm2, rNm3} = rNm;:"//OutputForm];
{rNm1, rNm2, rNm3} = rNm;
Print["rNm1 = "//OutputForm];
Print[rNm1];
Print["rNm2 = "//OutputForm];
Print[rNm2];
Print["rNm3 = "//OutputForm];
Print[rNm3];
Print["Norm[moms-rmoms]:"//OutputForm];
Print[Norm[moms-rmoms]];
Assert[Norm[moms-rmoms]<10^-9&&Norm[Nm1-rNm1]<10^-9&&Norm[Nm2-rNm2]<10^-9&&Norm[Nm3-rNm3]<10^-9, "The moments and joint moments returned by DMRAPFromMoments are not the same as given!"];
Print["========================================"]
Print["Testing BuTools function DMAPFromDRAP"]
Print["Input:"//OutputForm];
Print["------"//OutputForm];
H0 = {{0, 0, 0.13},{0, 0.6, 0.18},{0.31, 0.26, 0.02}};
Print["H0 = "//OutputForm];
Print[H0];
H1 = {{0, 1, -0.13},{0, 0.18, 0.04},{0.03, 0.09, 0.29}};
Print["H1 = "//OutputForm];
Print[H1];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["{D0, D1} = DMAPFromDRAP[H0, H1];:"//OutputForm];
{D0, D1} = DMAPFromDRAP[H0, H1];
Print["D0 = "//OutputForm];
Print[D0];
Print["D1 = "//OutputForm];
Print[D1];
Print["err = Norm[LagkJointMomentsFromDRAP[D0, D1, 3, 1]-LagkJointMomentsFromDRAP[H0, H1, 3, 1]];:"//OutputForm];
err = Norm[LagkJointMomentsFromDRAP[D0, D1, 3, 1]-LagkJointMomentsFromDRAP[H0, H1, 3, 1]];
Print["err = "//OutputForm];
Print[err];
Assert[err<10^-10, "The DMAP returned by DMAPFromDRAP is not similar to the input!"];
Assert[CheckDMAPRepresentation[D0, D1], "The result of DMAPFromDRAP is not a DMAP, as it should be!"];
Print["========================================"]
Print["Testing BuTools function DMMAPFromDMRAP"]
Print["Input:"//OutputForm];
Print["------"//OutputForm];
H0 = {{0.15, 0.2, 0.18},{-0.20, 0.17, 0.22},{0.19, 0.15, 0.16}};
Print["H0 = "//OutputForm];
Print[H0];
H1 = {{0.01, 0.08, 0.16},{0.02, 0.2, 0.07},{0.02, 0.15, 0.17}};
Print["H1 = "//OutputForm];
Print[H1];
H2 = {{0.14, 0.07, 0.01},{0.19, 0.02, 0.31},{0.06, 0.1, 0.}};
Print["H2 = "//OutputForm];
Print[H2];
H = {H0, H1, H2};
Print["moms = MarginalMomentsFromDMRAP[H];:"//OutputForm];
moms = MarginalMomentsFromDMRAP[H];
Print["moms = "//OutputForm];
Print[moms];
Print["jmom = LagkJointMomentsFromDMRAP[H, 3, 1];:"//OutputForm];
jmom = LagkJointMomentsFromDMRAP[H, 3, 1];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["G = DMMAPFromDMRAP[H];:"//OutputForm];
G = DMMAPFromDMRAP[H];
Print[G[[1]]];
Print[G[[2]]];
Print[G[[3]]];
Print["rmoms = MarginalMomentsFromDMMAP[G];:"//OutputForm];
rmoms = MarginalMomentsFromDMMAP[G];
Print["rmoms = "//OutputForm];
Print[rmoms];
Print["rjmom = LagkJointMomentsFromDMMAP[G, 3, 1];:"//OutputForm];
rjmom = LagkJointMomentsFromDMMAP[G, 3, 1];
Print["err = Norm[rjmom[[1]]-jmom[[1]]]+Norm[rjmom[[2]]-jmom[[2]]];:"//OutputForm];
err = Norm[rjmom[[1]]-jmom[[1]]]+Norm[rjmom[[2]]-jmom[[2]]];
Print["err = "//OutputForm];
Print[err];
Assert[err<10^-12, "The DMMAP returned by DMMAPFromDMRAP is not similar to the input!"];
Assert[CheckDMMAPRepresentation[G], "The result of DMMAPFromDMRAP is not a DMMAP, as it should be!"];
Print["========================================"]
Print["Testing BuTools function CanonicalFromDMAP2"]
Print["Input:"//OutputForm];
Print["------"//OutputForm];
D0 = {{0.46, 0.28},{0.35, 0.23}};
Print["D0 = "//OutputForm];
Print[D0];
D1 = {{0.08, 0.18},{0.14, 0.28}};
Print["D1 = "//OutputForm];
Print[D1];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["{H0, H1} = CanonicalFromDMAP2[D0, D1];:"//OutputForm];
{H0, H1} = CanonicalFromDMAP2[D0, D1];
Print["H0 = "//OutputForm];
Print[H0];
Print["H1 = "//OutputForm];
Print[H1];
Cm = SimilarityMatrix[H0, D0];
err1 = Norm[H0.Cm-Cm.D0];
err2 = Norm[H1.Cm-Cm.D1];
Print["Transformation errors:"];
Print[Max[err1, err2]];
Assert[CheckDMAPRepresentation[H0, H1], "The result of CanonicalFromDMAP2 is not a valid DMAP representation!"];
Assert[Max[err1, err2]<10^-12, "The DMAP returned by CanonicalFromDMAP2 is not similar to the input!"];
Print["Input:"//OutputForm];
Print["------"//OutputForm];
D0 = {{0.26, 0.28},{0.35, 0.23}};
Print["D0 = "//OutputForm];
Print[D0];
D1 = {{0.28, 0.18},{0.14, 0.28}};
Print["D1 = "//OutputForm];
Print[D1];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["{H0, H1} = CanonicalFromDMAP2[D0, D1];:"//OutputForm];
{H0, H1} = CanonicalFromDMAP2[D0, D1];
Print["H0 = "//OutputForm];
Print[H0];
Print["H1 = "//OutputForm];
Print[H1];
Cm = SimilarityMatrix[H0, D0];
err1 = Norm[H0.Cm-Cm.D0];
err2 = Norm[H1.Cm-Cm.D1];
Print["Transformation errors:"];
Print[Max[err1, err2]];
Assert[CheckDMAPRepresentation[H0, H1], "The result of CanonicalFromDMAP2 is not a valid DMAP representation!"];
Assert[Max[err1, err2]<10^-12, "The DMAP returned by CanonicalFromDMAP2 is not similar to the input!"];
Print["Input:"//OutputForm];
Print["------"//OutputForm];
D0 = {{0.14, 0.34},{0.35, 0.23}};
Print["D0 = "//OutputForm];
Print[D0];
D1 = {{0.22, 0.3},{0.28, 0.14}};
Print["D1 = "//OutputForm];
Print[D1];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["{H0, H1} = CanonicalFromDMAP2[D0, D1];:"//OutputForm];
{H0, H1} = CanonicalFromDMAP2[D0, D1];
Print["H0 = "//OutputForm];
Print[H0];
Print["H1 = "//OutputForm];
Print[H1];
Cm = SimilarityMatrix[H0, D0];
err1 = Norm[H0.Cm-Cm.D0];
err2 = Norm[H1.Cm-Cm.D1];
Print["Transformation errors:"];
Print[Max[err1, err2]];
Assert[CheckDMAPRepresentation[H0, H1], "The result of CanonicalFromDMAP2 is not a valid DMAP representation!"];
Assert[Max[err1, err2]<10^-12, "The DMAP returned by CanonicalFromDMAP2 is not similar to the input!"];
Print["========================================"]
Print["Testing BuTools function DMAP2FromMoments"]
Print["Input:"//OutputForm];
Print["------"//OutputForm];
D0 = {{0.2, 0.7},{0.6, 0.1}};
Print["D0 = "//OutputForm];
Print[D0];
D1 = {{0.09, 0.01},{0.2, 0.1}};
Print["D1 = "//OutputForm];
Print[D1];
Print["moms = MarginalMomentsFromDMAP[D0, D1, 3];:"//OutputForm];
moms = MarginalMomentsFromDMAP[D0, D1, 3];
Print["moms = "//OutputForm];
Print[moms];
Print["corr = LagCorrelationsFromDMAP[D0, D1, 1][[1]];:"//OutputForm];
corr = LagCorrelationsFromDMAP[D0, D1, 1][[1]];
Print["corr = "//OutputForm];
Print[corr];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["{D0, D1} = DMAP2FromMoments[moms, corr];:"//OutputForm];
{D0, D1} = DMAP2FromMoments[moms, corr];
Print["D0 = "//OutputForm];
Print[D0];
Print["D1 = "//OutputForm];
Print[D1];
Print["rmoms = MarginalMomentsFromDMAP[D0, D1, 3];:"//OutputForm];
rmoms = MarginalMomentsFromDMAP[D0, D1, 3];
Print["rmoms = "//OutputForm];
Print[rmoms];
Print["rcorr = LagCorrelationsFromDMAP[D0, D1, 1][[1]];:"//OutputForm];
rcorr = LagCorrelationsFromDMAP[D0, D1, 1][[1]];
Print["rcorr = "//OutputForm];
Print[rcorr];
Assert[CheckDMAPRepresentation[D0, D1], "DMAP2FromMoments returned an invalid DMAP representation!"];
Assert[Norm[moms-rmoms]<10^-11&&Abs[corr-rcorr]<10^-11, "The moments and the correlation returned by DMAP2FromMoments are not the same as given!"];
Print["========================================"]
Print["Testing BuTools function SamplesFromDMAP"]
Print["Input:"//OutputForm];
Print["------"//OutputForm];
D0 = {{0, 0.02, 0, 0},{0, 0.17, 0.2, 0.14},{0.16, 0.17, 0.02, 0.18},{0, 0, 0, 0.12}};
Print["D0 = "//OutputForm];
Print[D0];
D1 = {{0, 0.88, 0.1, 0},{0.18, 0.07, 0.14, 0.1},{0.13, 0.15, 0.15, 0.04},{0.31, 0.18, 0.12, 0.27}};
Print["D1 = "//OutputForm];
Print[D1];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["x = SamplesFromDMAP[D0, D1, 10000];:"//OutputForm];
x = SamplesFromDMAP[D0, D1, 10000];
Print["mt = MarginalMomentsFromTrace[x, 3];:"//OutputForm];
mt = MarginalMomentsFromTrace[x, 3];
Print["mt = "//OutputForm];
Print[mt];
Print["mm = MarginalMomentsFromDMAP[D0, D1, 3];:"//OutputForm];
mm = MarginalMomentsFromDMAP[D0, D1, 3];
Print["mm = "//OutputForm];
Print[mm];
Print["========================================"]
Print["Testing BuTools function SamplesFromDMMAP"]
Print["Input:"//OutputForm];
Print["------"//OutputForm];
D0 = {{0.34, 0, 0},{0.06, 0.05, 0.03},{0.11, 0.13, 0}};
Print["D0 = "//OutputForm];
Print[D0];
D1 = {{0.3, 0, 0},{0.16, 0.18, 0.05},{0.15, 0.04, 0.09}};
Print["D1 = "//OutputForm];
Print[D1];
D2 = {{0, 0.01, 0},{0.1, 0.07, 0.08},{0.13, 0.12, 0.13}};
Print["D2 = "//OutputForm];
Print[D2];
D3 = {{0.35, 0, 0},{0, 0.18, 0.04},{0.06, 0.03, 0.01}};
Print["D3 = "//OutputForm];
Print[D3];
Dm = {D0, D1, D2, D3};
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["x = SamplesFromDMMAP[Dm, 10000];:"//OutputForm];
x = SamplesFromDMMAP[Dm, 10000];
Print["mt = MarginalMomentsFromTrace[x[[1;;-1, 1]], 3];:"//OutputForm];
mt = MarginalMomentsFromTrace[x[[1;;-1, 1]], 3];
Print["mt = "//OutputForm];
Print[mt];
Print["mm = MarginalMomentsFromDMMAP[Dm, 3];:"//OutputForm];
mm = MarginalMomentsFromDMMAP[Dm, 3];
Print["mm = "//OutputForm];
Print[mm];
