ClearAll["Global`*"]
AppendTo[$Path,"/home/gabor/project/butools/Mathematica"];
<<BuTools`
Print["---BuTools: Queues package test file---"//OutputForm];
Print["Enable the verbose messages with the BuToolsVerbose flag"//OutputForm];
BuTools`Verbose = True;
Print["Enable input parameter checking with the BuToolsCheckInput flag"//OutputForm];
BuTools`CheckInput = true;
On[Assert];
Print["========================================"]
Print["Testing BuTools function QBDQueue"]
Print["Input:"//OutputForm];
Print["------"//OutputForm];
B = {{6., 1., 0.},{0., 4., 1.},{2., 0., 0.}};
Print["B = "//OutputForm];
Print[B];
F = {{0., 1., 1.},{5., 0., 0.},{1., 3., 0.}};
Print["F = "//OutputForm];
Print[F];
L = {{-14., 3., 2.},{0., -14., 4.},{3., 1., -10.}};
Print["L = "//OutputForm];
Print[L];
L0 = L+B;
Print["L0 = "//OutputForm];
Print[L0];
BuTools`Verbose = False;
{pi0, R} = QBDSolve[B, L, F, L0];
lambd = Total[pi0.Inverse[IdentityMatrix[Dimensions[R][[1]]]-R].F];
BuTools`Verbose = True;
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["{ncd, ncm} = QBDQueue[B, L, F, L0, \"ncDistr\", 11, \"ncMoms\", 5];:"//OutputForm];
{ncd, ncm} = QBDQueue[B, L, F, L0, "ncDistr", 11, "ncMoms", 5];
Print["ncd = "//OutputForm];
Print[ncd];
Print["ncm = "//OutputForm];
Print[ncm];
Print["{alphap, Ap} = QBDQueue[B, L, F, L0, \"ncDistrDPH\"];:"//OutputForm];
{alphap, Ap} = QBDQueue[B, L, F, L0, "ncDistrDPH"];
Print["alphap = "//OutputForm];
Print[alphap];
Print["Ap = "//OutputForm];
Print[Ap];
Print["{alpha, A} = QBDQueue[B, L, F, L0, \"ncDistrMG\"];:"//OutputForm];
{alpha, A} = QBDQueue[B, L, F, L0, "ncDistrMG"];
Print["alpha = "//OutputForm];
Print[alpha];
Print["A = "//OutputForm];
Print[A];
Print["ncdFromDPH = PmfFromDPH[alphap, Ap, Range[0,10,1]];:"//OutputForm];
ncdFromDPH = PmfFromDPH[alphap, Ap, Range[0,10,1]];
Print["ncdFromDPH = "//OutputForm];
Print[ncdFromDPH];
Print["ncmFromMG = MomentsFromMG[alpha, A, 5];:"//OutputForm];
ncmFromMG = MomentsFromMG[alpha, A, 5];
Print["ncmFromMG = "//OutputForm];
Print[ncmFromMG];
Print["{std, stm} = QBDQueue[B, L, F, L0, \"stDistr\", Range[0.,1.,0.1], \"stMoms\", 5];:"//OutputForm];
{std, stm} = QBDQueue[B, L, F, L0, "stDistr", Range[0.,1.,0.1], "stMoms", 5];
Print["std = "//OutputForm];
Print[std];
Print["stm = "//OutputForm];
Print[stm];
Print["{betap, Bp} = QBDQueue[B, L, F, L0, \"stDistrPH\"];:"//OutputForm];
{betap, Bp} = QBDQueue[B, L, F, L0, "stDistrPH"];
Print["betap = "//OutputForm];
Print[betap];
Print["Bp = "//OutputForm];
Print[Bp];
Print["{beta, B} = QBDQueue[B, L, F, L0, \"stDistrME\"];:"//OutputForm];
{beta, B} = QBDQueue[B, L, F, L0, "stDistrME"];
Print["beta = "//OutputForm];
Print[beta];
Print["B = "//OutputForm];
Print[B];
Print["stdFromPH = CdfFromPH[betap, Bp, Range[0.,1.,0.1]];:"//OutputForm];
stdFromPH = CdfFromPH[betap, Bp, Range[0.,1.,0.1]];
Print["stdFromPH = "//OutputForm];
Print[stdFromPH];
Print["stmFromME = MomentsFromME[beta, B, 5];:"//OutputForm];
stmFromME = MomentsFromME[beta, B, 5];
Print["stmFromME = "//OutputForm];
Print[stmFromME];
Assert[CheckMGRepresentation[alpha, A], "QBDQueue: invalid MG representation of the queue length!"];
Assert[CheckMERepresentation[beta, B], "QBDQueue: invalid ME representation of the sojourn time!"];
Assert[CheckDPHRepresentation[alphap, Ap], "QBDQueue: invalid DPH representation of the queue length!"];
Assert[CheckPHRepresentation[betap, Bp], "QBDQueue: invalid PH representation of the sojourn time!"];
Assert[Abs[ncm[[1]]-stm[[1]]*lambd]<10^-12, "QBDQueue: Little formula does not hold!"];
Assert[Norm[(MomentsFromDPH[alphap, Ap, 5]-ncmFromMG)/ncmFromMG]<10^-12, "QBDQueue: the MG and DPH representations are not equal!"];
Assert[Norm[(MomentsFromPH[betap, Bp, 5]-stmFromME)/stmFromME]<10^-12, "QBDQueue: the ME and PH representations are not equal!"];
Assert[Norm[ncd-PmfFromMG[alpha, A, Range[0,10,1]]]<10^-12, "QBDQueue: ncdistr returns wrong queue length distribution!"];
Assert[Norm[std-CdfFromME[beta, B, Range[0.,1.,0.1]]]<10^-12, "QBDQueue: stDistr returns wrong sojourn time distribution!"];
Assert[Norm[(ncm-ncmFromMG)/ncm]<10^-12, "QBDQueue: ncmoms returns wrong queue length moments!"];
Assert[Norm[(stm-stmFromME)/stm]<10^-12, "QBDQueue: stMoms returns wrong sojourn time moments!"];
Print["Input:"//OutputForm];
Print["------"//OutputForm];
B = {{6., 1., 0.},{0., 4., 1.},{2., 0., 0.}};
Print["B = "//OutputForm];
Print[B];
F = {{0., 0., 0.},{5., 0., 0.},{1., 3., 0.}};
Print["F = "//OutputForm];
Print[F];
L = {{-12., 3., 2.},{0., -14., 4.},{3., 1., -10.}};
Print["L = "//OutputForm];
Print[L];
L0 = L+B;
Print["L0 = "//OutputForm];
Print[L0];
BuTools`Verbose = False;
{pi0, R} = QBDSolve[B, L, F, L0];
lambd = Total[pi0.Inverse[IdentityMatrix[Dimensions[R][[1]]]-R].F];
BuTools`Verbose = True;
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["{ncd, ncm} = QBDQueue[B, L, F, L0, \"ncDistr\", 11, \"ncMoms\", 5];:"//OutputForm];
{ncd, ncm} = QBDQueue[B, L, F, L0, "ncDistr", 11, "ncMoms", 5];
Print["ncd = "//OutputForm];
Print[ncd];
Print["ncm = "//OutputForm];
Print[ncm];
Print["{alphap, Ap} = QBDQueue[B, L, F, L0, \"ncDistrDPH\"];:"//OutputForm];
{alphap, Ap} = QBDQueue[B, L, F, L0, "ncDistrDPH"];
Print["alphap = "//OutputForm];
Print[alphap];
Print["Ap = "//OutputForm];
Print[Ap];
Print["{alpha, A} = QBDQueue[B, L, F, L0, \"ncDistrMG\"];:"//OutputForm];
{alpha, A} = QBDQueue[B, L, F, L0, "ncDistrMG"];
Print["alpha = "//OutputForm];
Print[alpha];
Print["A = "//OutputForm];
Print[A];
Print["ncdFromDPH = PmfFromDPH[alphap, Ap, Range[0,10,1]];:"//OutputForm];
ncdFromDPH = PmfFromDPH[alphap, Ap, Range[0,10,1]];
Print["ncdFromDPH = "//OutputForm];
Print[ncdFromDPH];
Print["ncmFromMG = MomentsFromMG[alpha, A, 5];:"//OutputForm];
ncmFromMG = MomentsFromMG[alpha, A, 5];
Print["ncmFromMG = "//OutputForm];
Print[ncmFromMG];
Print["{std, stm} = QBDQueue[B, L, F, L0, \"stDistr\", Range[0.,1.,0.1], \"stMoms\", 5];:"//OutputForm];
{std, stm} = QBDQueue[B, L, F, L0, "stDistr", Range[0.,1.,0.1], "stMoms", 5];
Print["std = "//OutputForm];
Print[std];
Print["stm = "//OutputForm];
Print[stm];
Print["{betap, Bp} = QBDQueue[B, L, F, L0, \"stDistrPH\"];:"//OutputForm];
{betap, Bp} = QBDQueue[B, L, F, L0, "stDistrPH"];
Print["betap = "//OutputForm];
Print[betap];
Print["Bp = "//OutputForm];
Print[Bp];
Print["{beta, B} = QBDQueue[B, L, F, L0, \"stDistrME\"];:"//OutputForm];
{beta, B} = QBDQueue[B, L, F, L0, "stDistrME"];
Print["beta = "//OutputForm];
Print[beta];
Print["B = "//OutputForm];
Print[B];
Print["stdFromPH = CdfFromPH[betap, Bp, Range[0.,1.,0.1]];:"//OutputForm];
stdFromPH = CdfFromPH[betap, Bp, Range[0.,1.,0.1]];
Print["stdFromPH = "//OutputForm];
Print[stdFromPH];
Print["stmFromME = MomentsFromME[beta, B, 5];:"//OutputForm];
stmFromME = MomentsFromME[beta, B, 5];
Print["stmFromME = "//OutputForm];
Print[stmFromME];
Assert[CheckMGRepresentation[alpha, A], "QBDQueue: invalid MG representation of the queue length!"];
Assert[CheckMERepresentation[beta, B], "QBDQueue: invalid ME representation of the sojourn time!"];
Assert[CheckDPHRepresentation[alphap, Ap], "QBDQueue: invalid DPH representation of the queue length!"];
Assert[CheckPHRepresentation[betap, Bp], "QBDQueue: invalid PH representation of the sojourn time!"];
Assert[Abs[ncm[[1]]-stm[[1]]*lambd]<10^-12, "QBDQueue: Little formula does not hold!"];
Assert[Norm[(MomentsFromDPH[alphap, Ap, 5]-ncmFromMG)/ncmFromMG]<10^-12, "QBDQueue: the MG and DPH representations are not equal!"];
Assert[Norm[(MomentsFromPH[betap, Bp, 5]-stmFromME)/stmFromME]<10^-12, "QBDQueue: the ME and PH representations are not equal!"];
Assert[Norm[ncd-PmfFromMG[alpha, A, Range[0,10,1]]]<10^-12, "QBDQueue: ncdistr returns wrong queue length distribution!"];
Assert[Norm[std-CdfFromME[beta, B, Range[0.,1.,0.1]]]<10^-12, "QBDQueue: stDistr returns wrong sojourn time distribution!"];
Assert[Norm[(ncm-ncmFromMG)/ncm]<10^-12, "QBDQueue: ncmoms returns wrong queue length moments!"];
Assert[Norm[(stm-stmFromME)/stm]<10^-12, "QBDQueue: stMoms returns wrong sojourn time moments!"];
Print["Input:"//OutputForm];
Print["------"//OutputForm];
B = {{6., 1., 0.},{0., 5., 0.},{0., 0., 0.}};
Print["B = "//OutputForm];
Print[B];
F = {{0., 3., 1.},{0., 5., 0.},{0., 0., 0.}};
Print["F = "//OutputForm];
Print[F];
L = {{-16., 3., 2.},{0., -14., 4.},{3., 1., -4.}};
Print["L = "//OutputForm];
Print[L];
L0 = {{-14., 10., 0.},{5., -10., 0.},{3., 1., -4.}};
Print["L0 = "//OutputForm];
Print[L0];
BuTools`Verbose = False;
{pi0, R} = QBDSolve[B, L, F, L0];
lambd = Total[pi0.Inverse[IdentityMatrix[Dimensions[R][[1]]]-R].F];
BuTools`Verbose = True;
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["{ncd, ncm} = QBDQueue[B, L, F, L0, \"ncDistr\", 11, \"ncMoms\", 5];:"//OutputForm];
{ncd, ncm} = QBDQueue[B, L, F, L0, "ncDistr", 11, "ncMoms", 5];
Print["ncd = "//OutputForm];
Print[ncd];
Print["ncm = "//OutputForm];
Print[ncm];
Print["{alphap, Ap} = QBDQueue[B, L, F, L0, \"ncDistrDPH\"];:"//OutputForm];
{alphap, Ap} = QBDQueue[B, L, F, L0, "ncDistrDPH"];
Print["alphap = "//OutputForm];
Print[alphap];
Print["Ap = "//OutputForm];
Print[Ap];
Print["{alpha, A} = QBDQueue[B, L, F, L0, \"ncDistrMG\"];:"//OutputForm];
{alpha, A} = QBDQueue[B, L, F, L0, "ncDistrMG"];
Print["alpha = "//OutputForm];
Print[alpha];
Print["A = "//OutputForm];
Print[A];
Print["ncdFromDPH = PmfFromDPH[alphap, Ap, Range[0,10,1]];:"//OutputForm];
ncdFromDPH = PmfFromDPH[alphap, Ap, Range[0,10,1]];
Print["ncdFromDPH = "//OutputForm];
Print[ncdFromDPH];
Print["ncmFromMG = MomentsFromMG[alpha, A, 5];:"//OutputForm];
ncmFromMG = MomentsFromMG[alpha, A, 5];
Print["ncmFromMG = "//OutputForm];
Print[ncmFromMG];
Print["{std, stm} = QBDQueue[B, L, F, L0, \"stDistr\", Range[0.,1.,0.1], \"stMoms\", 5];:"//OutputForm];
{std, stm} = QBDQueue[B, L, F, L0, "stDistr", Range[0.,1.,0.1], "stMoms", 5];
Print["std = "//OutputForm];
Print[std];
Print["stm = "//OutputForm];
Print[stm];
Print["{betap, Bp} = QBDQueue[B, L, F, L0, \"stDistrPH\"];:"//OutputForm];
{betap, Bp} = QBDQueue[B, L, F, L0, "stDistrPH"];
Print["betap = "//OutputForm];
Print[betap];
Print["Bp = "//OutputForm];
Print[Bp];
Print["{beta, B} = QBDQueue[B, L, F, L0, \"stDistrME\"];:"//OutputForm];
{beta, B} = QBDQueue[B, L, F, L0, "stDistrME"];
Print["beta = "//OutputForm];
Print[beta];
Print["B = "//OutputForm];
Print[B];
Print["stdFromPH = CdfFromPH[betap, Bp, Range[0.,1.,0.1]];:"//OutputForm];
stdFromPH = CdfFromPH[betap, Bp, Range[0.,1.,0.1]];
Print["stdFromPH = "//OutputForm];
Print[stdFromPH];
Print["stmFromME = MomentsFromME[beta, B, 5];:"//OutputForm];
stmFromME = MomentsFromME[beta, B, 5];
Print["stmFromME = "//OutputForm];
Print[stmFromME];
Assert[CheckMGRepresentation[alpha, A], "QBDQueue: invalid MG representation of the queue length!"];
Assert[CheckMERepresentation[beta, B], "QBDQueue: invalid ME representation of the sojourn time!"];
Assert[CheckDPHRepresentation[alphap, Ap], "QBDQueue: invalid DPH representation of the queue length!"];
Assert[CheckPHRepresentation[betap, Bp], "QBDQueue: invalid PH representation of the sojourn time!"];
Assert[Abs[ncm[[1]]-stm[[1]]*lambd]<10^-12, "QBDQueue: Little formula does not hold!"];
Assert[Norm[(MomentsFromDPH[alphap, Ap, 5]-ncmFromMG)/ncmFromMG]<10^-12, "QBDQueue: the MG and DPH representations are not equal!"];
Assert[Norm[(MomentsFromPH[betap, Bp, 5]-stmFromME)/stmFromME]<10^-12, "QBDQueue: the ME and PH representations are not equal!"];
Assert[Norm[ncd-PmfFromMG[alpha, A, Range[0,10,1]]]<10^-12, "QBDQueue: ncdistr returns wrong queue length distribution!"];
Assert[Norm[std-CdfFromME[beta, B, Range[0.,1.,0.1]]]<10^-12, "QBDQueue: stDistr returns wrong sojourn time distribution!"];
Assert[Norm[(ncm-ncmFromMG)/ncm]<10^-12, "QBDQueue: ncmoms returns wrong queue length moments!"];
Assert[Norm[(stm-stmFromME)/stm]<10^-12, "QBDQueue: stMoms returns wrong sojourn time moments!"];
Print["Input:"//OutputForm];
Print["------"//OutputForm];
B = {{0., 0.},{3., 4.}};
Print["B = "//OutputForm];
Print[B];
F = {{1., 0.},{2., 0.}};
Print["F = "//OutputForm];
Print[F];
L = {{-6., 5.},{3., -12.}};
Print["L = "//OutputForm];
Print[L];
L0 = {{-6., 5.},{6., -8.}};
Print["L0 = "//OutputForm];
Print[L0];
BuTools`Verbose = False;
{pi0, R} = QBDSolve[B, L, F, L0];
lambd = Total[pi0.Inverse[IdentityMatrix[Dimensions[R][[1]]]-R].F];
BuTools`Verbose = True;
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["{ncd, ncm} = QBDQueue[B, L, F, L0, \"ncDistr\", 11, \"ncMoms\", 5];:"//OutputForm];
{ncd, ncm} = QBDQueue[B, L, F, L0, "ncDistr", 11, "ncMoms", 5];
Print["ncd = "//OutputForm];
Print[ncd];
Print["ncm = "//OutputForm];
Print[ncm];
Print["{alphap, Ap} = QBDQueue[B, L, F, L0, \"ncDistrDPH\"];:"//OutputForm];
{alphap, Ap} = QBDQueue[B, L, F, L0, "ncDistrDPH"];
Print["alphap = "//OutputForm];
Print[alphap];
Print["Ap = "//OutputForm];
Print[Ap];
Print["{alpha, A} = QBDQueue[B, L, F, L0, \"ncDistrMG\"];:"//OutputForm];
{alpha, A} = QBDQueue[B, L, F, L0, "ncDistrMG"];
Print["alpha = "//OutputForm];
Print[alpha];
Print["A = "//OutputForm];
Print[A];
Print["ncdFromDPH = PmfFromDPH[alphap, Ap, Range[0,10,1]];:"//OutputForm];
ncdFromDPH = PmfFromDPH[alphap, Ap, Range[0,10,1]];
Print["ncdFromDPH = "//OutputForm];
Print[ncdFromDPH];
Print["ncmFromMG = MomentsFromMG[alpha, A, 5];:"//OutputForm];
ncmFromMG = MomentsFromMG[alpha, A, 5];
Print["ncmFromMG = "//OutputForm];
Print[ncmFromMG];
Print["{std, stm} = QBDQueue[B, L, F, L0, \"stDistr\", Range[0.,1.,0.1], \"stMoms\", 5];:"//OutputForm];
{std, stm} = QBDQueue[B, L, F, L0, "stDistr", Range[0.,1.,0.1], "stMoms", 5];
Print["std = "//OutputForm];
Print[std];
Print["stm = "//OutputForm];
Print[stm];
Print["{betap, Bp} = QBDQueue[B, L, F, L0, \"stDistrPH\"];:"//OutputForm];
{betap, Bp} = QBDQueue[B, L, F, L0, "stDistrPH"];
Print["betap = "//OutputForm];
Print[betap];
Print["Bp = "//OutputForm];
Print[Bp];
Print["{beta, B} = QBDQueue[B, L, F, L0, \"stDistrME\"];:"//OutputForm];
{beta, B} = QBDQueue[B, L, F, L0, "stDistrME"];
Print["beta = "//OutputForm];
Print[beta];
Print["B = "//OutputForm];
Print[B];
Print["stdFromPH = CdfFromPH[betap, Bp, Range[0.,1.,0.1]];:"//OutputForm];
stdFromPH = CdfFromPH[betap, Bp, Range[0.,1.,0.1]];
Print["stdFromPH = "//OutputForm];
Print[stdFromPH];
Print["stmFromME = MomentsFromME[beta, B, 5];:"//OutputForm];
stmFromME = MomentsFromME[beta, B, 5];
Print["stmFromME = "//OutputForm];
Print[stmFromME];
Assert[CheckMGRepresentation[alpha, A], "QBDQueue: invalid MG representation of the queue length!"];
Assert[CheckMERepresentation[beta, B], "QBDQueue: invalid ME representation of the sojourn time!"];
Assert[CheckDPHRepresentation[alphap, Ap], "QBDQueue: invalid DPH representation of the queue length!"];
Assert[CheckPHRepresentation[betap, Bp], "QBDQueue: invalid PH representation of the sojourn time!"];
Assert[Abs[ncm[[1]]-stm[[1]]*lambd]<10^-12, "QBDQueue: Little formula does not hold!"];
Assert[Norm[(MomentsFromDPH[alphap, Ap, 5]-ncmFromMG)/ncmFromMG]<10^-12, "QBDQueue: the MG and DPH representations are not equal!"];
Assert[Norm[(MomentsFromPH[betap, Bp, 5]-stmFromME)/stmFromME]<10^-12, "QBDQueue: the ME and PH representations are not equal!"];
Assert[Norm[ncd-PmfFromMG[alpha, A, Range[0,10,1]]]<10^-12, "QBDQueue: ncdistr returns wrong queue length distribution!"];
Assert[Norm[std-CdfFromME[beta, B, Range[0.,1.,0.1]]]<10^-12, "QBDQueue: stDistr returns wrong sojourn time distribution!"];
Assert[Norm[(ncm-ncmFromMG)/ncm]<10^-12, "QBDQueue: ncmoms returns wrong queue length moments!"];
Assert[Norm[(stm-stmFromME)/stm]<10^-12, "QBDQueue: stMoms returns wrong sojourn time moments!"];
Print["========================================"]
Print["Testing BuTools function MAPMAP1"]
Print["Input:"//OutputForm];
Print["------"//OutputForm];
D0 = {{-8., 1., 2.},{0., -6., 4.},{3., 0., -3.}};
Print["D0 = "//OutputForm];
Print[D0];
D1 = {{4., 1., 0.},{0., 2., 0.},{0., 0., 0.}};
Print["D1 = "//OutputForm];
Print[D1];
S0 = {{-10., 4.},{0., -7.}};
Print["S0 = "//OutputForm];
Print[S0];
S1 = {{5., 1.},{4., 3.}};
Print["S1 = "//OutputForm];
Print[S1];
lambd = 1./MarginalMomentsFromMAP[D0, D1, 1][[1]];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["{ncd, ncm} = MAPMAP1[D0, D1, S0, S1, \"ncDistr\", 11, \"ncMoms\", 5];:"//OutputForm];
{ncd, ncm} = MAPMAP1[D0, D1, S0, S1, "ncDistr", 11, "ncMoms", 5];
Print["ncd = "//OutputForm];
Print[ncd];
Print["ncm = "//OutputForm];
Print[ncm];
Print["{alphap, Ap} = MAPMAP1[D0, D1, S0, S1, \"ncDistrDPH\"];:"//OutputForm];
{alphap, Ap} = MAPMAP1[D0, D1, S0, S1, "ncDistrDPH"];
Print["alphap = "//OutputForm];
Print[alphap];
Print["Ap = "//OutputForm];
Print[Ap];
Print["{alpha, A} = MAPMAP1[D0, D1, S0, S1, \"ncDistrMG\"];:"//OutputForm];
{alpha, A} = MAPMAP1[D0, D1, S0, S1, "ncDistrMG"];
Print["alpha = "//OutputForm];
Print[alpha];
Print["A = "//OutputForm];
Print[A];
Print["ncdFromDPH = PmfFromDPH[alphap, Ap, Range[0,10,1]];:"//OutputForm];
ncdFromDPH = PmfFromDPH[alphap, Ap, Range[0,10,1]];
Print["ncdFromDPH = "//OutputForm];
Print[ncdFromDPH];
Print["ncmFromMG = MomentsFromMG[alpha, A, 5];:"//OutputForm];
ncmFromMG = MomentsFromMG[alpha, A, 5];
Print["ncmFromMG = "//OutputForm];
Print[ncmFromMG];
Print["{std, stm} = MAPMAP1[D0, D1, S0, S1, \"stDistr\", Range[0.,1.,0.1], \"stMoms\", 5];:"//OutputForm];
{std, stm} = MAPMAP1[D0, D1, S0, S1, "stDistr", Range[0.,1.,0.1], "stMoms", 5];
Print["std = "//OutputForm];
Print[std];
Print["stm = "//OutputForm];
Print[stm];
Print["{betap, Bp} = MAPMAP1[D0, D1, S0, S1, \"stDistrPH\"];:"//OutputForm];
{betap, Bp} = MAPMAP1[D0, D1, S0, S1, "stDistrPH"];
Print["betap = "//OutputForm];
Print[betap];
Print["Bp = "//OutputForm];
Print[Bp];
Print["{beta, B} = MAPMAP1[D0, D1, S0, S1, \"stDistrME\"];:"//OutputForm];
{beta, B} = MAPMAP1[D0, D1, S0, S1, "stDistrME"];
Print["beta = "//OutputForm];
Print[beta];
Print["B = "//OutputForm];
Print[B];
Print["stdFromPH = CdfFromPH[betap, Bp, Range[0.,1.,0.1]];:"//OutputForm];
stdFromPH = CdfFromPH[betap, Bp, Range[0.,1.,0.1]];
Print["stdFromPH = "//OutputForm];
Print[stdFromPH];
Print["stmFromME = MomentsFromME[beta, B, 5];:"//OutputForm];
stmFromME = MomentsFromME[beta, B, 5];
Print["stmFromME = "//OutputForm];
Print[stmFromME];
Assert[CheckMGRepresentation[alpha, A], "MAPMAP1: invalid MG representation of the queue length!"];
Assert[CheckMERepresentation[beta, B], "MAPMAP1: invalid ME representation of the sojourn time!"];
Assert[CheckDPHRepresentation[alphap, Ap], "MAPMAP1: invalid DPH representation of the queue length!"];
Assert[CheckPHRepresentation[betap, Bp], "MAPMAP1: invalid PH representation of the sojourn time!"];
Assert[Abs[ncm[[1]]-stm[[1]]*lambd]<10^-12, "MAPMAP1: Little formula does not hold!"];
Assert[Norm[(MomentsFromDPH[alphap, Ap, 5]-ncmFromMG)/ncmFromMG]<10^-12, "MAPMAP1: the MG and DPH representations are not equal!"];
Assert[Norm[(MomentsFromPH[betap, Bp, 5]-stmFromME)/stmFromME]<10^-12, "MAPMAP1: the ME and PH representations are not equal!"];
Assert[Norm[ncd-PmfFromMG[alpha, A, Range[0,10,1]]]<10^-12, "MAPMAP1: ncdistr returns wrong queue length distribution!"];
Assert[Norm[std-CdfFromME[beta, B, Range[0.,1.,0.1]]]<10^-12, "MAPMAP1: stDistr returns wrong sojourn time distribution!"];
Assert[Norm[(ncm-ncmFromMG)/ncm]<10^-12, "MAPMAP1: ncmoms returns wrong queue length moments!"];
Assert[Norm[(stm-stmFromME)/stm]<10^-12, "MAPMAP1: stMoms returns wrong sojourn time moments!"];
IA = IdentityMatrix[Dimensions[D0][[1]]];
IS = IdentityMatrix[Dimensions[S0][[1]]];
BuTools`Verbose = False;
{gamma, G} = QBDQueue[KroneckerProduct[IA, S1], KroneckerProduct[D0, IS]+KroneckerProduct[IA, S0], KroneckerProduct[D1, IS], KroneckerProduct[D0, IS], "stDistrME"];
BuTools`Verbose = True;
msmall = MomentsFromME[beta, B, 5];
mlarge = MomentsFromME[gamma, G, 5];
Assert[Norm[(msmall-mlarge)/msmall]<10^-12, "MAPMAP1: Large and small model does not give the same results!"];
Print["Input:"//OutputForm];
Print["------"//OutputForm];
delta = {0.5,0.1,0.4};
Print["delta = "//OutputForm];
Print[delta];
Dm = {{-8., 1., 2.},{0., -6., 4.},{3., 0., -3.}};
Print["Dm = "//OutputForm];
Print[Dm];
sigma = {0.2,0.7,0.1};
Print["sigma = "//OutputForm];
Print[sigma];
S = {{-10., 4., 0.},{5., -7., 2.},{1., 2., -8.}};
Print["S = "//OutputForm];
Print[S];
Print["D0 = Dm;:"//OutputForm];
D0 = Dm;
Print["D1 = Transpose[{Total[-Dm,{2}]}].{delta};:"//OutputForm];
D1 = Transpose[{Total[-Dm,{2}]}].{delta};
Print["S0 = S;:"//OutputForm];
S0 = S;
Print["S1 = Transpose[{Total[-S,{2}]}].{sigma};:"//OutputForm];
S1 = Transpose[{Total[-S,{2}]}].{sigma};
lambd = 1./MarginalMomentsFromMAP[D0, D1, 1][[1]];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["{ncd, ncm} = MAPMAP1[D0, D1, S0, S1, \"ncDistr\", 11, \"ncMoms\", 5];:"//OutputForm];
{ncd, ncm} = MAPMAP1[D0, D1, S0, S1, "ncDistr", 11, "ncMoms", 5];
Print["ncd = "//OutputForm];
Print[ncd];
Print["ncm = "//OutputForm];
Print[ncm];
Print["{alphap, Ap} = MAPMAP1[D0, D1, S0, S1, \"ncDistrDPH\"];:"//OutputForm];
{alphap, Ap} = MAPMAP1[D0, D1, S0, S1, "ncDistrDPH"];
Print["alphap = "//OutputForm];
Print[alphap];
Print["Ap = "//OutputForm];
Print[Ap];
Print["{alpha, A} = MAPMAP1[D0, D1, S0, S1, \"ncDistrMG\"];:"//OutputForm];
{alpha, A} = MAPMAP1[D0, D1, S0, S1, "ncDistrMG"];
Print["alpha = "//OutputForm];
Print[alpha];
Print["A = "//OutputForm];
Print[A];
Print["ncdFromDPH = PmfFromDPH[alphap, Ap, Range[0,10,1]];:"//OutputForm];
ncdFromDPH = PmfFromDPH[alphap, Ap, Range[0,10,1]];
Print["ncdFromDPH = "//OutputForm];
Print[ncdFromDPH];
Print["ncmFromMG = MomentsFromMG[alpha, A, 5];:"//OutputForm];
ncmFromMG = MomentsFromMG[alpha, A, 5];
Print["ncmFromMG = "//OutputForm];
Print[ncmFromMG];
Print["{std, stm} = MAPMAP1[D0, D1, S0, S1, \"stDistr\", Range[0.,1.,0.1], \"stMoms\", 5];:"//OutputForm];
{std, stm} = MAPMAP1[D0, D1, S0, S1, "stDistr", Range[0.,1.,0.1], "stMoms", 5];
Print["std = "//OutputForm];
Print[std];
Print["stm = "//OutputForm];
Print[stm];
Print["{betap, Bp} = MAPMAP1[D0, D1, S0, S1, \"stDistrPH\"];:"//OutputForm];
{betap, Bp} = MAPMAP1[D0, D1, S0, S1, "stDistrPH"];
Print["betap = "//OutputForm];
Print[betap];
Print["Bp = "//OutputForm];
Print[Bp];
Print["{beta, B} = MAPMAP1[D0, D1, S0, S1, \"stDistrME\"];:"//OutputForm];
{beta, B} = MAPMAP1[D0, D1, S0, S1, "stDistrME"];
Print["beta = "//OutputForm];
Print[beta];
Print["B = "//OutputForm];
Print[B];
Print["stdFromPH = CdfFromPH[betap, Bp, Range[0.,1.,0.1]];:"//OutputForm];
stdFromPH = CdfFromPH[betap, Bp, Range[0.,1.,0.1]];
Print["stdFromPH = "//OutputForm];
Print[stdFromPH];
Print["stmFromME = MomentsFromME[beta, B, 5];:"//OutputForm];
stmFromME = MomentsFromME[beta, B, 5];
Print["stmFromME = "//OutputForm];
Print[stmFromME];
Assert[CheckMGRepresentation[alpha, A], "MAPMAP1: invalid MG representation of the queue length!"];
Assert[CheckMERepresentation[beta, B], "MAPMAP1: invalid ME representation of the sojourn time!"];
Assert[CheckDPHRepresentation[alphap, Ap], "MAPMAP1: invalid DPH representation of the queue length!"];
Assert[CheckPHRepresentation[betap, Bp], "MAPMAP1: invalid PH representation of the sojourn time!"];
Assert[Abs[ncm[[1]]-stm[[1]]*lambd]<10^-12, "MAPMAP1: Little formula does not hold!"];
Assert[Norm[(MomentsFromDPH[alphap, Ap, 5]-ncmFromMG)/ncmFromMG]<10^-12, "MAPMAP1: the MG and DPH representations are not equal!"];
Assert[Norm[(MomentsFromPH[betap, Bp, 5]-stmFromME)/stmFromME]<10^-12, "MAPMAP1: the ME and PH representations are not equal!"];
Assert[Norm[ncd-PmfFromMG[alpha, A, Range[0,10,1]]]<10^-12, "MAPMAP1: ncdistr returns wrong queue length distribution!"];
Assert[Norm[std-CdfFromME[beta, B, Range[0.,1.,0.1]]]<10^-12, "MAPMAP1: stDistr returns wrong sojourn time distribution!"];
Assert[Norm[(ncm-ncmFromMG)/ncm]<10^-12, "MAPMAP1: ncmoms returns wrong queue length moments!"];
Assert[Norm[(stm-stmFromME)/stm]<10^-12, "MAPMAP1: stMoms returns wrong sojourn time moments!"];
IA = IdentityMatrix[Dimensions[D0][[1]]];
IS = IdentityMatrix[Dimensions[S0][[1]]];
BuTools`Verbose = False;
{gamma, G} = QBDQueue[KroneckerProduct[IA, S1], KroneckerProduct[D0, IS]+KroneckerProduct[IA, S0], KroneckerProduct[D1, IS], KroneckerProduct[D0, IS], "stDistrME"];
BuTools`Verbose = True;
msmall = MomentsFromME[beta, B, 5];
mlarge = MomentsFromME[gamma, G, 5];
Assert[Norm[(msmall-mlarge)/msmall]<10^-12, "MAPMAP1: Large and small model does not give the same results!"];
Print["Input:"//OutputForm];
Print["------"//OutputForm];
D0 = {{-8., 2.},{1., -3.}};
Print["D0 = "//OutputForm];
Print[D0];
D1 = {{1., 5.},{0., 2.}};
Print["D1 = "//OutputForm];
Print[D1];
S0 = {{-10., 4.},{0., -7.}};
Print["S0 = "//OutputForm];
Print[S0];
S1 = {{5., 1.},{4., 3.}};
Print["S1 = "//OutputForm];
Print[S1];
lambd = 1./MarginalMomentsFromMAP[D0, D1, 1][[1]];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["{ncd, ncm} = MAPMAP1[D0, D1, S0, S1, \"ncDistr\", 11, \"ncMoms\", 5];:"//OutputForm];
{ncd, ncm} = MAPMAP1[D0, D1, S0, S1, "ncDistr", 11, "ncMoms", 5];
Print["ncd = "//OutputForm];
Print[ncd];
Print["ncm = "//OutputForm];
Print[ncm];
Print["{alphap, Ap} = MAPMAP1[D0, D1, S0, S1, \"ncDistrDPH\"];:"//OutputForm];
{alphap, Ap} = MAPMAP1[D0, D1, S0, S1, "ncDistrDPH"];
Print["alphap = "//OutputForm];
Print[alphap];
Print["Ap = "//OutputForm];
Print[Ap];
Print["{alpha, A} = MAPMAP1[D0, D1, S0, S1, \"ncDistrMG\"];:"//OutputForm];
{alpha, A} = MAPMAP1[D0, D1, S0, S1, "ncDistrMG"];
Print["alpha = "//OutputForm];
Print[alpha];
Print["A = "//OutputForm];
Print[A];
Print["ncdFromDPH = PmfFromDPH[alphap, Ap, Range[0,10,1]];:"//OutputForm];
ncdFromDPH = PmfFromDPH[alphap, Ap, Range[0,10,1]];
Print["ncdFromDPH = "//OutputForm];
Print[ncdFromDPH];
Print["ncmFromMG = MomentsFromMG[alpha, A, 5];:"//OutputForm];
ncmFromMG = MomentsFromMG[alpha, A, 5];
Print["ncmFromMG = "//OutputForm];
Print[ncmFromMG];
Print["{std, stm} = MAPMAP1[D0, D1, S0, S1, \"stDistr\", Range[0.,1.,0.1], \"stMoms\", 5];:"//OutputForm];
{std, stm} = MAPMAP1[D0, D1, S0, S1, "stDistr", Range[0.,1.,0.1], "stMoms", 5];
Print["std = "//OutputForm];
Print[std];
Print["stm = "//OutputForm];
Print[stm];
Print["{betap, Bp} = MAPMAP1[D0, D1, S0, S1, \"stDistrPH\"];:"//OutputForm];
{betap, Bp} = MAPMAP1[D0, D1, S0, S1, "stDistrPH"];
Print["betap = "//OutputForm];
Print[betap];
Print["Bp = "//OutputForm];
Print[Bp];
Print["{beta, B} = MAPMAP1[D0, D1, S0, S1, \"stDistrME\"];:"//OutputForm];
{beta, B} = MAPMAP1[D0, D1, S0, S1, "stDistrME"];
Print["beta = "//OutputForm];
Print[beta];
Print["B = "//OutputForm];
Print[B];
Print["stdFromPH = CdfFromPH[betap, Bp, Range[0.,1.,0.1]];:"//OutputForm];
stdFromPH = CdfFromPH[betap, Bp, Range[0.,1.,0.1]];
Print["stdFromPH = "//OutputForm];
Print[stdFromPH];
Print["stmFromME = MomentsFromME[beta, B, 5];:"//OutputForm];
stmFromME = MomentsFromME[beta, B, 5];
Print["stmFromME = "//OutputForm];
Print[stmFromME];
Assert[CheckMGRepresentation[alpha, A], "MAPMAP1: invalid MG representation of the queue length!"];
Assert[CheckMERepresentation[beta, B], "MAPMAP1: invalid ME representation of the sojourn time!"];
Assert[CheckDPHRepresentation[alphap, Ap], "MAPMAP1: invalid DPH representation of the queue length!"];
Assert[CheckPHRepresentation[betap, Bp], "MAPMAP1: invalid PH representation of the sojourn time!"];
Assert[Abs[ncm[[1]]-stm[[1]]*lambd]<10^-12, "MAPMAP1: Little formula does not hold!"];
Assert[Norm[(MomentsFromDPH[alphap, Ap, 5]-ncmFromMG)/ncmFromMG]<10^-12, "MAPMAP1: the MG and DPH representations are not equal!"];
Assert[Norm[(MomentsFromPH[betap, Bp, 5]-stmFromME)/stmFromME]<10^-12, "MAPMAP1: the ME and PH representations are not equal!"];
Assert[Norm[ncd-PmfFromMG[alpha, A, Range[0,10,1]]]<10^-12, "MAPMAP1: ncdistr returns wrong queue length distribution!"];
Assert[Norm[std-CdfFromME[beta, B, Range[0.,1.,0.1]]]<10^-12, "MAPMAP1: stDistr returns wrong sojourn time distribution!"];
Assert[Norm[(ncm-ncmFromMG)/ncm]<10^-12, "MAPMAP1: ncmoms returns wrong queue length moments!"];
Assert[Norm[(stm-stmFromME)/stm]<10^-12, "MAPMAP1: stMoms returns wrong sojourn time moments!"];
IA = IdentityMatrix[Dimensions[D0][[1]]];
IS = IdentityMatrix[Dimensions[S0][[1]]];
BuTools`Verbose = False;
{gamma, G} = QBDQueue[KroneckerProduct[IA, S1], KroneckerProduct[D0, IS]+KroneckerProduct[IA, S0], KroneckerProduct[D1, IS], KroneckerProduct[D0, IS], "stDistrME"];
BuTools`Verbose = True;
msmall = MomentsFromME[beta, B, 5];
mlarge = MomentsFromME[gamma, G, 5];
Assert[Norm[(msmall-mlarge)/msmall]<10^-12, "MAPMAP1: Large and small model does not give the same results!"];
Print["Input:"//OutputForm];
Print["------"//OutputForm];
S0 = {{-10., 4., 0.},{5., -7., 2.},{1., 2., -8.}};
Print["S0 = "//OutputForm];
Print[S0];
S1 = {{0., 0., 6.},{0., 0., 0.},{0., 3., 2.}};
Print["S1 = "//OutputForm];
Print[S1];
D0 = {{-8., 1., 2.},{0., -6., 4.},{3., 0., -3.}};
Print["D0 = "//OutputForm];
Print[D0];
D1 = {{4., 1., 0.},{0., 0., 2.},{0., 0., 0.}};
Print["D1 = "//OutputForm];
Print[D1];
lambd = 1./MarginalMomentsFromMAP[D0, D1, 1][[1]];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["{ncd, ncm} = MAPMAP1[D0, D1, S0, S1, \"ncDistr\", 11, \"ncMoms\", 5];:"//OutputForm];
{ncd, ncm} = MAPMAP1[D0, D1, S0, S1, "ncDistr", 11, "ncMoms", 5];
Print["ncd = "//OutputForm];
Print[ncd];
Print["ncm = "//OutputForm];
Print[ncm];
Print["{alphap, Ap} = MAPMAP1[D0, D1, S0, S1, \"ncDistrDPH\"];:"//OutputForm];
{alphap, Ap} = MAPMAP1[D0, D1, S0, S1, "ncDistrDPH"];
Print["alphap = "//OutputForm];
Print[alphap];
Print["Ap = "//OutputForm];
Print[Ap];
Print["{alpha, A} = MAPMAP1[D0, D1, S0, S1, \"ncDistrMG\"];:"//OutputForm];
{alpha, A} = MAPMAP1[D0, D1, S0, S1, "ncDistrMG"];
Print["alpha = "//OutputForm];
Print[alpha];
Print["A = "//OutputForm];
Print[A];
Print["ncdFromDPH = PmfFromDPH[alphap, Ap, Range[0,10,1]];:"//OutputForm];
ncdFromDPH = PmfFromDPH[alphap, Ap, Range[0,10,1]];
Print["ncdFromDPH = "//OutputForm];
Print[ncdFromDPH];
Print["ncmFromMG = MomentsFromMG[alpha, A, 5];:"//OutputForm];
ncmFromMG = MomentsFromMG[alpha, A, 5];
Print["ncmFromMG = "//OutputForm];
Print[ncmFromMG];
Print["{std, stm} = MAPMAP1[D0, D1, S0, S1, \"stDistr\", Range[0.,1.,0.1], \"stMoms\", 5];:"//OutputForm];
{std, stm} = MAPMAP1[D0, D1, S0, S1, "stDistr", Range[0.,1.,0.1], "stMoms", 5];
Print["std = "//OutputForm];
Print[std];
Print["stm = "//OutputForm];
Print[stm];
Print["{betap, Bp} = MAPMAP1[D0, D1, S0, S1, \"stDistrPH\"];:"//OutputForm];
{betap, Bp} = MAPMAP1[D0, D1, S0, S1, "stDistrPH"];
Print["betap = "//OutputForm];
Print[betap];
Print["Bp = "//OutputForm];
Print[Bp];
Print["{beta, B} = MAPMAP1[D0, D1, S0, S1, \"stDistrME\"];:"//OutputForm];
{beta, B} = MAPMAP1[D0, D1, S0, S1, "stDistrME"];
Print["beta = "//OutputForm];
Print[beta];
Print["B = "//OutputForm];
Print[B];
Print["stdFromPH = CdfFromPH[betap, Bp, Range[0.,1.,0.1]];:"//OutputForm];
stdFromPH = CdfFromPH[betap, Bp, Range[0.,1.,0.1]];
Print["stdFromPH = "//OutputForm];
Print[stdFromPH];
Print["stmFromME = MomentsFromME[beta, B, 5];:"//OutputForm];
stmFromME = MomentsFromME[beta, B, 5];
Print["stmFromME = "//OutputForm];
Print[stmFromME];
Assert[CheckMGRepresentation[alpha, A], "MAPMAP1: invalid MG representation of the queue length!"];
Assert[CheckMERepresentation[beta, B], "MAPMAP1: invalid ME representation of the sojourn time!"];
Assert[CheckDPHRepresentation[alphap, Ap], "MAPMAP1: invalid DPH representation of the queue length!"];
Assert[CheckPHRepresentation[betap, Bp], "MAPMAP1: invalid PH representation of the sojourn time!"];
Assert[Abs[ncm[[1]]-stm[[1]]*lambd]<10^-12, "MAPMAP1: Little formula does not hold!"];
Assert[Norm[(MomentsFromDPH[alphap, Ap, 5]-ncmFromMG)/ncmFromMG]<10^-12, "MAPMAP1: the MG and DPH representations are not equal!"];
Assert[Norm[(MomentsFromPH[betap, Bp, 5]-stmFromME)/stmFromME]<10^-12, "MAPMAP1: the ME and PH representations are not equal!"];
Assert[Norm[ncd-PmfFromMG[alpha, A, Range[0,10,1]]]<10^-12, "MAPMAP1: ncdistr returns wrong queue length distribution!"];
Assert[Norm[std-CdfFromME[beta, B, Range[0.,1.,0.1]]]<10^-12, "MAPMAP1: stDistr returns wrong sojourn time distribution!"];
Assert[Norm[(ncm-ncmFromMG)/ncm]<10^-12, "MAPMAP1: ncmoms returns wrong queue length moments!"];
Assert[Norm[(stm-stmFromME)/stm]<10^-12, "MAPMAP1: stMoms returns wrong sojourn time moments!"];
IA = IdentityMatrix[Dimensions[D0][[1]]];
IS = IdentityMatrix[Dimensions[S0][[1]]];
BuTools`Verbose = False;
{gamma, G} = QBDQueue[KroneckerProduct[IA, S1], KroneckerProduct[D0, IS]+KroneckerProduct[IA, S0], KroneckerProduct[D1, IS], KroneckerProduct[D0, IS], "stDistrME"];
BuTools`Verbose = True;
msmall = MomentsFromME[beta, B, 5];
mlarge = MomentsFromME[gamma, G, 5];
Assert[Norm[(msmall-mlarge)/msmall]<10^-12, "MAPMAP1: Large and small model does not give the same results!"];
Print["Input:"//OutputForm];
Print["------"//OutputForm];
D0 = {{-8., 1., 2.},{0., -6., 4.},{3., 0., -3.}};
Print["D0 = "//OutputForm];
Print[D0];
D1 = {{4., 1., 0.},{0., 0., 2.},{0., 0., 0.}};
Print["D1 = "//OutputForm];
Print[D1];
sigma = {0.2,0.7,0.1};
Print["sigma = "//OutputForm];
Print[sigma];
S = {{-10., 4., 0.},{5., -7., 2.},{1., 2., -8.}};
Print["S = "//OutputForm];
Print[S];
Print["S0 = S;:"//OutputForm];
S0 = S;
Print["S1 = Transpose[{Total[-S,{2}]}].{sigma};:"//OutputForm];
S1 = Transpose[{Total[-S,{2}]}].{sigma};
lambd = 1./MarginalMomentsFromMAP[D0, D1, 1][[1]];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["{ncd, ncm} = MAPMAP1[D0, D1, S0, S1, \"ncDistr\", 11, \"ncMoms\", 5];:"//OutputForm];
{ncd, ncm} = MAPMAP1[D0, D1, S0, S1, "ncDistr", 11, "ncMoms", 5];
Print["ncd = "//OutputForm];
Print[ncd];
Print["ncm = "//OutputForm];
Print[ncm];
Print["{alphap, Ap} = MAPMAP1[D0, D1, S0, S1, \"ncDistrDPH\"];:"//OutputForm];
{alphap, Ap} = MAPMAP1[D0, D1, S0, S1, "ncDistrDPH"];
Print["alphap = "//OutputForm];
Print[alphap];
Print["Ap = "//OutputForm];
Print[Ap];
Print["{alpha, A} = MAPMAP1[D0, D1, S0, S1, \"ncDistrMG\"];:"//OutputForm];
{alpha, A} = MAPMAP1[D0, D1, S0, S1, "ncDistrMG"];
Print["alpha = "//OutputForm];
Print[alpha];
Print["A = "//OutputForm];
Print[A];
Print["ncdFromDPH = PmfFromDPH[alphap, Ap, Range[0,10,1]];:"//OutputForm];
ncdFromDPH = PmfFromDPH[alphap, Ap, Range[0,10,1]];
Print["ncdFromDPH = "//OutputForm];
Print[ncdFromDPH];
Print["ncmFromMG = MomentsFromMG[alpha, A, 5];:"//OutputForm];
ncmFromMG = MomentsFromMG[alpha, A, 5];
Print["ncmFromMG = "//OutputForm];
Print[ncmFromMG];
Print["{std, stm} = MAPMAP1[D0, D1, S0, S1, \"stDistr\", Range[0.,1.,0.1], \"stMoms\", 5];:"//OutputForm];
{std, stm} = MAPMAP1[D0, D1, S0, S1, "stDistr", Range[0.,1.,0.1], "stMoms", 5];
Print["std = "//OutputForm];
Print[std];
Print["stm = "//OutputForm];
Print[stm];
Print["{betap, Bp} = MAPMAP1[D0, D1, S0, S1, \"stDistrPH\"];:"//OutputForm];
{betap, Bp} = MAPMAP1[D0, D1, S0, S1, "stDistrPH"];
Print["betap = "//OutputForm];
Print[betap];
Print["Bp = "//OutputForm];
Print[Bp];
Print["{beta, B} = MAPMAP1[D0, D1, S0, S1, \"stDistrME\"];:"//OutputForm];
{beta, B} = MAPMAP1[D0, D1, S0, S1, "stDistrME"];
Print["beta = "//OutputForm];
Print[beta];
Print["B = "//OutputForm];
Print[B];
Print["stdFromPH = CdfFromPH[betap, Bp, Range[0.,1.,0.1]];:"//OutputForm];
stdFromPH = CdfFromPH[betap, Bp, Range[0.,1.,0.1]];
Print["stdFromPH = "//OutputForm];
Print[stdFromPH];
Print["stmFromME = MomentsFromME[beta, B, 5];:"//OutputForm];
stmFromME = MomentsFromME[beta, B, 5];
Print["stmFromME = "//OutputForm];
Print[stmFromME];
Assert[CheckMGRepresentation[alpha, A], "MAPMAP1: invalid MG representation of the queue length!"];
Assert[CheckMERepresentation[beta, B], "MAPMAP1: invalid ME representation of the sojourn time!"];
Assert[CheckDPHRepresentation[alphap, Ap], "MAPMAP1: invalid DPH representation of the queue length!"];
Assert[CheckPHRepresentation[betap, Bp], "MAPMAP1: invalid PH representation of the sojourn time!"];
Assert[Abs[ncm[[1]]-stm[[1]]*lambd]<10^-12, "MAPMAP1: Little formula does not hold!"];
Assert[Norm[(MomentsFromDPH[alphap, Ap, 5]-ncmFromMG)/ncmFromMG]<10^-12, "MAPMAP1: the MG and DPH representations are not equal!"];
Assert[Norm[(MomentsFromPH[betap, Bp, 5]-stmFromME)/stmFromME]<10^-12, "MAPMAP1: the ME and PH representations are not equal!"];
Assert[Norm[ncd-PmfFromMG[alpha, A, Range[0,10,1]]]<10^-12, "MAPMAP1: ncdistr returns wrong queue length distribution!"];
Assert[Norm[std-CdfFromME[beta, B, Range[0.,1.,0.1]]]<10^-12, "MAPMAP1: stDistr returns wrong sojourn time distribution!"];
Assert[Norm[(ncm-ncmFromMG)/ncm]<10^-12, "MAPMAP1: ncmoms returns wrong queue length moments!"];
Assert[Norm[(stm-stmFromME)/stm]<10^-12, "MAPMAP1: stMoms returns wrong sojourn time moments!"];
IA = IdentityMatrix[Dimensions[D0][[1]]];
IS = IdentityMatrix[Dimensions[S0][[1]]];
BuTools`Verbose = False;
{gamma, G} = QBDQueue[KroneckerProduct[IA, S1], KroneckerProduct[D0, IS]+KroneckerProduct[IA, S0], KroneckerProduct[D1, IS], KroneckerProduct[D0, IS], "stDistrME"];
BuTools`Verbose = True;
msmall = MomentsFromME[beta, B, 5];
mlarge = MomentsFromME[gamma, G, 5];
Assert[Norm[(msmall-mlarge)/msmall]<10^-12, "MAPMAP1: Large and small model do not give the same results!"];
Print["========================================"]
Print["Testing BuTools function MMAPPH1PRPR"]
Print["Input:"//OutputForm];
Print["------"//OutputForm];
D0 = {{-5.49, 0., 1.15, 0.},{0., -2.29, 0., 0.},{0., 0.08, -1.32, 0.},{0.72, 1.17, 0.7, -7.07}};
Print["D0 = "//OutputForm];
Print[D0];
D1 = {{0.25, 0.38, 0.64, 0.},{0., 0., 0., 1.09},{0., 1.24, 0., 0.},{0.37, 0., 0., 0.}};
Print["D1 = "//OutputForm];
Print[D1];
D2 = {{0.3, 1.0, 0., 0.48},{0., 0.2, 0., 0.},{0., 0., 0., 0.},{0.61, 0., 0., 0.2}};
Print["D2 = "//OutputForm];
Print[D2];
D3 = {{0., 0.98, 0., 0.31},{0., 0., 1.0, 0.},{0., 0., 0., 0.},{1.1, 0.84, 0.33, 1.03}};
Print["D3 = "//OutputForm];
Print[D3];
sigma3 = {0.83333,0.11404,0.05263};
Print["sigma3 = "//OutputForm];
Print[sigma3];
S3 = {{-3., 0., 0.},{0.73077, -0.73077, 0.},{0., 0.5, -0.5}};
Print["S3 = "//OutputForm];
Print[S3];
sigma2 = {1.};
Print["sigma2 = "//OutputForm];
Print[sigma2];
S2 = {{-2.}};
Print["S2 = "//OutputForm];
Print[S2];
sigma1 = {0.25,0.75};
Print["sigma1 = "//OutputForm];
Print[sigma1];
S1 = {{-2.5, 2.5},{0., -10.}};
Print["S1 = "//OutputForm];
Print[S1];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["{ncm1, ncd1, ncm2, ncd2, ncm3, ncd3} = MMAPPH1PRPR[{D0, D1, D2, D3}, {sigma1, sigma2, sigma3}, {S1, S2, S3}, \"ncMoms\", 3, \"ncDistr\", 500];:"//OutputForm];
{ncm1, ncd1, ncm2, ncd2, ncm3, ncd3} = MMAPPH1PRPR[{D0, D1, D2, D3}, {sigma1, sigma2, sigma3}, {S1, S2, S3}, "ncMoms", 3, "ncDistr", 500];
momFromDistr1 = ncd1.Transpose[Join[{Range[0,499,1]},{Range[0,499,1]^2},{Range[0,499,1]^3}]];
momFromDistr2 = ncd2.Transpose[Join[{Range[0,499,1]},{Range[0,499,1]^2},{Range[0,499,1]^3}]];
momFromDistr3 = ncd3.Transpose[Join[{Range[0,499,1]},{Range[0,499,1]^2},{Range[0,499,1]^3}]];
Assert[Norm[(momFromDistr1-ncm1)/ncm1]<0.001&&Norm[(momFromDistr2-ncm2)/ncm2]<0.001&&Norm[(momFromDistr3-ncm3)/ncm3]<0.001, "MMAPPH1PRPR: queue length moments and queue length distribution are not consistent!"];
distrPoints = {1., 5., 10.};
Print["{stm1, std1, stm2, std2, stm3, std3} = MMAPPH1PRPR[{D0, D1, D2, D3}, {sigma1, sigma2, sigma3}, {S1, S2, S3}, \"stMoms\", 3, \"stDistr\", distrPoints];:"//OutputForm];
{stm1, std1, stm2, std2, stm3, std3} = MMAPPH1PRPR[{D0, D1, D2, D3}, {sigma1, sigma2, sigma3}, {S1, S2, S3}, "stMoms", 3, "stDistr", distrPoints];
Print["stm1 = "//OutputForm];
Print[stm1];
Print["std1 = "//OutputForm];
Print[std1];
Print["stm2 = "//OutputForm];
Print[stm2];
Print["std2 = "//OutputForm];
Print[std2];
Print["stm3 = "//OutputForm];
Print[stm3];
Print["std3 = "//OutputForm];
Print[std3];
Assert[Min[std1]>=0&&Max[std1]<=1&&AllTrue[Differences[std1],#>=-10^-14 &]&&Min[std2]>=0&&Max[std2]<=1&&AllTrue[Differences[std2],#>=-10^-14 &]&&Min[std3]>=0&&Max[std3]<=1&&AllTrue[Differences[std3],#>=-10^-14 &], "MMAPPH1PRPR: invalid sojourn time distribution!"];
lambda1 = 1./MarginalMomentsFromMAP[D0+D2+D3, D1, 1][[1]];
lambda2 = 1./MarginalMomentsFromMAP[D0+D1+D3, D2, 1][[1]];
lambda3 = 1./MarginalMomentsFromMAP[D0+D1+D2, D3, 1][[1]];
Assert[Abs[ncm1[[1]]-stm1[[1]]*lambda1]<10^-12, "MMAPPH1PRPR: Little formula does not hold for class 1!"];
Assert[Abs[ncm2[[1]]-stm2[[1]]*lambda2]<10^-12, "MMAPPH1PRPR: Little formula does not hold for class 2!"];
Assert[Abs[ncm3[[1]]-stm3[[1]]*lambda3]<10^-12, "MMAPPH1PRPR: Little formula does not hold for class 3!"];
Print["Input:"//OutputForm];
Print["------"//OutputForm];
D0 = {{-5.49, 0., 1.15, 0.},{0., -2.29, 0., 0.},{0., 0.08, -1.32, 0.},{0.72, 1.17, 0.7, -7.07}};
Print["D0 = "//OutputForm];
Print[D0];
D1 = {{0.25, 0.38, 0.64, 0.},{0., 0., 0., 1.09},{0., 1.24, 0., 0.},{0.37, 0., 0., 0.}};
Print["D1 = "//OutputForm];
Print[D1];
D2 = {{0.3, 1.0, 0., 0.48},{0., 0.2, 0., 0.},{0., 0., 0., 0.},{0.61, 0., 0., 0.2}};
Print["D2 = "//OutputForm];
Print[D2];
D3 = {{0., 0.98, 0., 0.31},{0., 0., 1.0, 0.},{0., 0., 0., 0.},{1.1, 0.84, 0.33, 1.03}};
Print["D3 = "//OutputForm];
Print[D3];
sigma3 = {0.16667,0.83333};
Print["sigma3 = "//OutputForm];
Print[sigma3];
S3 = {{-0.5, 0.5},{0., -3.}};
Print["S3 = "//OutputForm];
Print[S3];
sigma2 = {0.58824,0.41176};
Print["sigma2 = "//OutputForm];
Print[sigma2];
S2 = {{-2.3529, 2.3529},{0., -4.}};
Print["S2 = "//OutputForm];
Print[S2];
sigma1 = {0.25,0.75};
Print["sigma1 = "//OutputForm];
Print[sigma1];
S1 = {{-2.5, 2.5},{0., -10.}};
Print["S1 = "//OutputForm];
Print[S1];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["{ncm1, ncd1, ncm2, ncd2, ncm3, ncd3} = MMAPPH1PRPR[{D0, D1, D2, D3}, {sigma1, sigma2, sigma3}, {S1, S2, S3}, \"ncMoms\", 3, \"ncDistr\", 500];:"//OutputForm];
{ncm1, ncd1, ncm2, ncd2, ncm3, ncd3} = MMAPPH1PRPR[{D0, D1, D2, D3}, {sigma1, sigma2, sigma3}, {S1, S2, S3}, "ncMoms", 3, "ncDistr", 500];
momFromDistr1 = ncd1.Transpose[Join[{Range[0,499,1]},{Range[0,499,1]^2},{Range[0,499,1]^3}]];
momFromDistr2 = ncd2.Transpose[Join[{Range[0,499,1]},{Range[0,499,1]^2},{Range[0,499,1]^3}]];
momFromDistr3 = ncd3.Transpose[Join[{Range[0,499,1]},{Range[0,499,1]^2},{Range[0,499,1]^3}]];
Assert[Norm[(momFromDistr1-ncm1)/ncm1]<0.001&&Norm[(momFromDistr2-ncm2)/ncm2]<0.001&&Norm[(momFromDistr3-ncm3)/ncm3]<0.001, "MMAPPH1PRPR: queue length moments and queue length distribution are not consistent!"];
distrPoints = {1., 5., 10.};
Print["{stm1, std1, stm2, std2, stm3, std3} = MMAPPH1PRPR[{D0, D1, D2, D3}, {sigma1, sigma2, sigma3}, {S1, S2, S3}, \"stMoms\", 3, \"stDistr\", distrPoints];:"//OutputForm];
{stm1, std1, stm2, std2, stm3, std3} = MMAPPH1PRPR[{D0, D1, D2, D3}, {sigma1, sigma2, sigma3}, {S1, S2, S3}, "stMoms", 3, "stDistr", distrPoints];
Print["stm1 = "//OutputForm];
Print[stm1];
Print["std1 = "//OutputForm];
Print[std1];
Print["stm2 = "//OutputForm];
Print[stm2];
Print["std2 = "//OutputForm];
Print[std2];
Print["stm3 = "//OutputForm];
Print[stm3];
Print["std3 = "//OutputForm];
Print[std3];
Assert[Min[std1]>=0&&Max[std1]<=1&&AllTrue[Differences[std1],#>=-10^-14 &]&&Min[std2]>=0&&Max[std2]<=1&&AllTrue[Differences[std2],#>=-10^-14 &]&&Min[std3]>=0&&Max[std3]<=1&&AllTrue[Differences[std3],#>=-10^-14 &], "MMAPPH1PRPR: invalid sojourn time distribution!"];
lambda1 = 1./MarginalMomentsFromMAP[D0+D2+D3, D1, 1][[1]];
lambda2 = 1./MarginalMomentsFromMAP[D0+D1+D3, D2, 1][[1]];
lambda3 = 1./MarginalMomentsFromMAP[D0+D1+D2, D3, 1][[1]];
Assert[Abs[ncm1[[1]]-stm1[[1]]*lambda1]<10^-12, "MMAPPH1PRPR: Little formula does not hold for class 1!"];
Assert[Abs[ncm2[[1]]-stm2[[1]]*lambda2]<10^-12, "MMAPPH1PRPR: Little formula does not hold for class 2!"];
Assert[Abs[ncm3[[1]]-stm3[[1]]*lambda3]<10^-12, "MMAPPH1PRPR: Little formula does not hold for class 3!"];
Print["========================================"]
Print["Testing BuTools function MMAPPH1NPPR"]
Print["Input:"//OutputForm];
Print["------"//OutputForm];
D0 = {{-5.49, 0., 1.15, 0.},{0., -2.29, 0., 0.},{0., 0.08, -1.32, 0.},{0.72, 1.17, 0.7, -7.07}};
Print["D0 = "//OutputForm];
Print[D0];
D1 = {{0.25, 0.38, 0.64, 0.},{0., 0., 0., 1.09},{0., 1.24, 0., 0.},{0.37, 0., 0., 0.}};
Print["D1 = "//OutputForm];
Print[D1];
D2 = {{0.3, 1.0, 0., 0.48},{0., 0.2, 0., 0.},{0., 0., 0., 0.},{0.61, 0., 0., 0.2}};
Print["D2 = "//OutputForm];
Print[D2];
D3 = {{0., 0.98, 0., 0.31},{0., 0., 1.0, 0.},{0., 0., 0., 0.},{1.1, 0.84, 0.33, 1.03}};
Print["D3 = "//OutputForm];
Print[D3];
sigma3 = {0.83333,0.11404,0.05263};
Print["sigma3 = "//OutputForm];
Print[sigma3];
S3 = {{-3., 0., 0.},{0.73077, -0.73077, 0.},{0., 0.5, -0.5}};
Print["S3 = "//OutputForm];
Print[S3];
sigma2 = {1.};
Print["sigma2 = "//OutputForm];
Print[sigma2];
S2 = {{-2.}};
Print["S2 = "//OutputForm];
Print[S2];
sigma1 = {0.25,0.75};
Print["sigma1 = "//OutputForm];
Print[sigma1];
S1 = {{-2.5, 2.5},{0., -10.}};
Print["S1 = "//OutputForm];
Print[S1];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["{ncm1, ncd1, ncm2, ncd2, ncm3, ncd3} = MMAPPH1NPPR[{D0, D1, D2, D3}, {sigma1, sigma2, sigma3}, {S1, S2, S3}, \"ncMoms\", 3, \"ncDistr\", 500];:"//OutputForm];
{ncm1, ncd1, ncm2, ncd2, ncm3, ncd3} = MMAPPH1NPPR[{D0, D1, D2, D3}, {sigma1, sigma2, sigma3}, {S1, S2, S3}, "ncMoms", 3, "ncDistr", 500];
momFromDistr1 = ncd1.Transpose[Join[{Range[0,499,1]},{Range[0,499,1]^2},{Range[0,499,1]^3}]];
momFromDistr2 = ncd2.Transpose[Join[{Range[0,499,1]},{Range[0,499,1]^2},{Range[0,499,1]^3}]];
momFromDistr3 = ncd3.Transpose[Join[{Range[0,499,1]},{Range[0,499,1]^2},{Range[0,499,1]^3}]];
Assert[Norm[(momFromDistr1-ncm1)/ncm1]<0.001&&Norm[(momFromDistr2-ncm2)/ncm2]<0.001&&Norm[(momFromDistr3-ncm3)/ncm3]<0.001, "MMAPPH1NPPR: queue length moments and queue length distribution are not consistent!"];
distrPoints = {1., 5., 10.};
Print["{stm1, std1, stm2, std2, stm3, std3} = MMAPPH1NPPR[{D0, D1, D2, D3}, {sigma1, sigma2, sigma3}, {S1, S2, S3}, \"stMoms\", 3, \"stDistr\", distrPoints];:"//OutputForm];
{stm1, std1, stm2, std2, stm3, std3} = MMAPPH1NPPR[{D0, D1, D2, D3}, {sigma1, sigma2, sigma3}, {S1, S2, S3}, "stMoms", 3, "stDistr", distrPoints];
Print["stm1 = "//OutputForm];
Print[stm1];
Print["std1 = "//OutputForm];
Print[std1];
Print["stm2 = "//OutputForm];
Print[stm2];
Print["std2 = "//OutputForm];
Print[std2];
Print["stm3 = "//OutputForm];
Print[stm3];
Print["std3 = "//OutputForm];
Print[std3];
Assert[Min[std1]>=0&&Max[std1]<=1&&AllTrue[Differences[std1],#>=-10^-14 &]&&Min[std2]>=0&&Max[std2]<=1&&AllTrue[Differences[std2],#>=-10^-14 &]&&Min[std3]>=0&&Max[std3]<=1&&AllTrue[Differences[std3],#>=-10^-14 &], "MMAPPH1NPPR: invalid sojourn time distribution!"];
lambda1 = 1./MarginalMomentsFromMAP[D0+D2+D3, D1, 1][[1]];
lambda2 = 1./MarginalMomentsFromMAP[D0+D1+D3, D2, 1][[1]];
lambda3 = 1./MarginalMomentsFromMAP[D0+D1+D2, D3, 1][[1]];
Assert[Abs[ncm1[[1]]-stm1[[1]]*lambda1]<10^-12, "MMAPPH1NPPR: Little formula does not hold for class 1!"];
Assert[Abs[ncm2[[1]]-stm2[[1]]*lambda2]<10^-12, "MMAPPH1NPPR: Little formula does not hold for class 2!"];
Assert[Abs[ncm3[[1]]-stm3[[1]]*lambda3]<10^-12, "MMAPPH1NPPR: Little formula does not hold for class 3!"];
Print["Input:"//OutputForm];
Print["------"//OutputForm];
D0 = {{-5.49, 0., 1.15, 0.},{0., -2.29, 0., 0.},{0., 0.08, -1.32, 0.},{0.72, 1.17, 0.7, -7.07}};
Print["D0 = "//OutputForm];
Print[D0];
D1 = {{0.25, 0.38, 0.64, 0.},{0., 0., 0., 1.09},{0., 1.24, 0., 0.},{0.37, 0., 0., 0.}};
Print["D1 = "//OutputForm];
Print[D1];
D2 = {{0.3, 1.0, 0., 0.48},{0., 0.2, 0., 0.},{0., 0., 0., 0.},{0.61, 0., 0., 0.2}};
Print["D2 = "//OutputForm];
Print[D2];
D3 = {{0., 0.98, 0., 0.31},{0., 0., 1.0, 0.},{0., 0., 0., 0.},{1.1, 0.84, 0.33, 1.03}};
Print["D3 = "//OutputForm];
Print[D3];
sigma3 = {0.16667,0.83333};
Print["sigma3 = "//OutputForm];
Print[sigma3];
S3 = {{-0.5, 0.5},{0., -3.}};
Print["S3 = "//OutputForm];
Print[S3];
sigma2 = {0.58824,0.41176};
Print["sigma2 = "//OutputForm];
Print[sigma2];
S2 = {{-2.3529, 2.3529},{0., -4.}};
Print["S2 = "//OutputForm];
Print[S2];
sigma1 = {0.25,0.75};
Print["sigma1 = "//OutputForm];
Print[sigma1];
S1 = {{-2.5, 2.5},{0., -10.}};
Print["S1 = "//OutputForm];
Print[S1];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["{ncm1, ncd1, ncm2, ncd2, ncm3, ncd3} = MMAPPH1NPPR[{D0, D1, D2, D3}, {sigma1, sigma2, sigma3}, {S1, S2, S3}, \"ncMoms\", 3, \"ncDistr\", 500];:"//OutputForm];
{ncm1, ncd1, ncm2, ncd2, ncm3, ncd3} = MMAPPH1NPPR[{D0, D1, D2, D3}, {sigma1, sigma2, sigma3}, {S1, S2, S3}, "ncMoms", 3, "ncDistr", 500];
momFromDistr1 = ncd1.Transpose[Join[{Range[0,499,1]},{Range[0,499,1]^2},{Range[0,499,1]^3}]];
momFromDistr2 = ncd2.Transpose[Join[{Range[0,499,1]},{Range[0,499,1]^2},{Range[0,499,1]^3}]];
momFromDistr3 = ncd3.Transpose[Join[{Range[0,499,1]},{Range[0,499,1]^2},{Range[0,499,1]^3}]];
Assert[Norm[(momFromDistr1-ncm1)/ncm1]<0.001&&Norm[(momFromDistr2-ncm2)/ncm2]<0.001&&Norm[(momFromDistr3-ncm3)/ncm3]<0.001, "MMAPPH1NPPR: queue length moments and queue length distribution are not consistent!"];
distrPoints = {1., 5., 10.};
Print["{stm1, std1, stm2, std2, stm3, std3} = MMAPPH1NPPR[{D0, D1, D2, D3}, {sigma1, sigma2, sigma3}, {S1, S2, S3}, \"stMoms\", 3, \"stDistr\", distrPoints];:"//OutputForm];
{stm1, std1, stm2, std2, stm3, std3} = MMAPPH1NPPR[{D0, D1, D2, D3}, {sigma1, sigma2, sigma3}, {S1, S2, S3}, "stMoms", 3, "stDistr", distrPoints];
Print["stm1 = "//OutputForm];
Print[stm1];
Print["std1 = "//OutputForm];
Print[std1];
Print["stm2 = "//OutputForm];
Print[stm2];
Print["std2 = "//OutputForm];
Print[std2];
Print["stm3 = "//OutputForm];
Print[stm3];
Print["std3 = "//OutputForm];
Print[std3];
Assert[Min[std1]>=0&&Max[std1]<=1&&AllTrue[Differences[std1],#>=-10^-14 &]&&Min[std2]>=0&&Max[std2]<=1&&AllTrue[Differences[std2],#>=-10^-14 &]&&Min[std3]>=0&&Max[std3]<=1&&AllTrue[Differences[std3],#>=-10^-14 &], "MMAPPH1NPPR: invalid sojourn time distribution!"];
lambda1 = 1./MarginalMomentsFromMAP[D0+D2+D3, D1, 1][[1]];
lambda2 = 1./MarginalMomentsFromMAP[D0+D1+D3, D2, 1][[1]];
lambda3 = 1./MarginalMomentsFromMAP[D0+D1+D2, D3, 1][[1]];
Assert[Abs[ncm1[[1]]-stm1[[1]]*lambda1]<10^-12, "MMAPPH1NPPR: Little formula does not hold for class 1!"];
Assert[Abs[ncm2[[1]]-stm2[[1]]*lambda2]<10^-12, "MMAPPH1NPPR: Little formula does not hold for class 2!"];
Assert[Abs[ncm3[[1]]-stm3[[1]]*lambda3]<10^-12, "MMAPPH1NPPR: Little formula does not hold for class 3!"];
Print["========================================"]
Print["Testing BuTools function MMAPPH1FCFS"]
Print["Input:"//OutputForm];
Print["------"//OutputForm];
D0 = {{-5.49, 0., 1.15, 0.},{0., -2.29, 0., 0.},{0., 0.08, -1.32, 0.},{0.72, 1.17, 0.7, -7.07}};
Print["D0 = "//OutputForm];
Print[D0];
D1 = {{0.25, 0.38, 0.64, 0.},{0., 0., 0., 1.09},{0., 1.24, 0., 0.},{0.37, 0., 0., 0.}};
Print["D1 = "//OutputForm];
Print[D1];
D2 = {{0.3, 1.0, 0., 0.48},{0., 0.2, 0., 0.},{0., 0., 0., 0.},{0.61, 0., 0., 0.2}};
Print["D2 = "//OutputForm];
Print[D2];
D3 = {{0., 0.98, 0., 0.31},{0., 0., 1.0, 0.},{0., 0., 0., 0.},{1.1, 0.84, 0.33, 1.03}};
Print["D3 = "//OutputForm];
Print[D3];
sigma3 = {0.83333,0.11404,0.05263};
Print["sigma3 = "//OutputForm];
Print[sigma3];
S3 = {{-3., 0., 0.},{0.73077, -0.73077, 0.},{0., 0.5, -0.5}};
Print["S3 = "//OutputForm];
Print[S3];
sigma2 = {1.};
Print["sigma2 = "//OutputForm];
Print[sigma2];
S2 = {{-2.}};
Print["S2 = "//OutputForm];
Print[S2];
sigma1 = {0.25,0.75};
Print["sigma1 = "//OutputForm];
Print[sigma1];
S1 = {{-2.5, 2.5},{0., -10.}};
Print["S1 = "//OutputForm];
Print[S1];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["{ncm1, ncd1, ncm2, ncd2, ncm3, ncd3} = MMAPPH1FCFS[{D0, D1, D2, D3}, {sigma1, sigma2, sigma3}, {S1, S2, S3}, \"ncMoms\", 3, \"ncDistr\", 500];:"//OutputForm];
{ncm1, ncd1, ncm2, ncd2, ncm3, ncd3} = MMAPPH1FCFS[{D0, D1, D2, D3}, {sigma1, sigma2, sigma3}, {S1, S2, S3}, "ncMoms", 3, "ncDistr", 500];
momFromDistr1 = ncd1.Transpose[Join[{Range[0,499,1]},{Range[0,499,1]^2},{Range[0,499,1]^3}]];
momFromDistr2 = ncd2.Transpose[Join[{Range[0,499,1]},{Range[0,499,1]^2},{Range[0,499,1]^3}]];
momFromDistr3 = ncd3.Transpose[Join[{Range[0,499,1]},{Range[0,499,1]^2},{Range[0,499,1]^3}]];
Assert[Norm[(momFromDistr1-ncm1)/ncm1]<0.001&&Norm[(momFromDistr2-ncm2)/ncm2]<0.001&&Norm[(momFromDistr3-ncm3)/ncm3]<0.001, "MMAPPH1FCFS: queue length moments and queue length distribution are not consistent!"];
distrPoints = {1., 5., 10.};
Print["{stm1, std1, stm2, std2, stm3, std3} = MMAPPH1FCFS[{D0, D1, D2, D3}, {sigma1, sigma2, sigma3}, {S1, S2, S3}, \"stMoms\", 3, \"stDistr\", distrPoints];:"//OutputForm];
{stm1, std1, stm2, std2, stm3, std3} = MMAPPH1FCFS[{D0, D1, D2, D3}, {sigma1, sigma2, sigma3}, {S1, S2, S3}, "stMoms", 3, "stDistr", distrPoints];
Print["stm1 = "//OutputForm];
Print[stm1];
Print["std1 = "//OutputForm];
Print[std1];
Print["stm2 = "//OutputForm];
Print[stm2];
Print["std2 = "//OutputForm];
Print[std2];
Print["stm3 = "//OutputForm];
Print[stm3];
Print["std3 = "//OutputForm];
Print[std3];
Print["{betap1, Bp1, betap2, Bp2, betap3, Bp3} = MMAPPH1FCFS[{D0, D1, D2, D3}, {sigma1, sigma2, sigma3}, {S1, S2, S3}, \"stDistrPH\"];:"//OutputForm];
{betap1, Bp1, betap2, Bp2, betap3, Bp3} = MMAPPH1FCFS[{D0, D1, D2, D3}, {sigma1, sigma2, sigma3}, {S1, S2, S3}, "stDistrPH"];
Print["{beta1, B1, beta2, B2, beta3, B3} = MMAPPH1FCFS[{D0, D1, D2, D3}, {sigma1, sigma2, sigma3}, {S1, S2, S3}, \"stDistrME\"];:"//OutputForm];
{beta1, B1, beta2, B2, beta3, B3} = MMAPPH1FCFS[{D0, D1, D2, D3}, {sigma1, sigma2, sigma3}, {S1, S2, S3}, "stDistrME"];
Print["stdFromPH1 = CdfFromPH[betap1, Bp1, distrPoints];:"//OutputForm];
stdFromPH1 = CdfFromPH[betap1, Bp1, distrPoints];
Print["stdFromPH1 = "//OutputForm];
Print[stdFromPH1];
Print["stmFromME1 = MomentsFromME[beta1, B1, 3];:"//OutputForm];
stmFromME1 = MomentsFromME[beta1, B1, 3];
Print["stmFromME1 = "//OutputForm];
Print[stmFromME1];
Print["stdFromPH2 = CdfFromPH[betap2, Bp2, distrPoints];:"//OutputForm];
stdFromPH2 = CdfFromPH[betap2, Bp2, distrPoints];
Print["stdFromPH2 = "//OutputForm];
Print[stdFromPH2];
Print["stmFromME2 = MomentsFromME[beta2, B2, 3];:"//OutputForm];
stmFromME2 = MomentsFromME[beta2, B2, 3];
Print["stmFromME2 = "//OutputForm];
Print[stmFromME2];
Print["stdFromPH3 = CdfFromPH[betap3, Bp3, distrPoints];:"//OutputForm];
stdFromPH3 = CdfFromPH[betap3, Bp3, distrPoints];
Print["stdFromPH3 = "//OutputForm];
Print[stdFromPH3];
Print["stmFromME3 = MomentsFromME[beta3, B3, 3];:"//OutputForm];
stmFromME3 = MomentsFromME[beta3, B3, 3];
Print["stmFromME3 = "//OutputForm];
Print[stmFromME3];
Assert[Min[std1]>=0&&Max[std1]<=1&&AllTrue[Differences[std1],#>=-10^-14 &]&&Min[std2]>=0&&Max[std2]<=1&&AllTrue[Differences[std2],#>=-10^-14 &]&&Min[std3]>=0&&Max[std3]<=1&&AllTrue[Differences[std3],#>=-10^-14 &], "MMAPPH1FCFS: invalid sojourn time distribution!"];
Assert[Norm[(MomentsFromPH[betap1, Bp1, 3]-stmFromME1)/stmFromME1]<10^-12, "MMAPPH1FCFS: the ME and PH representations for class 1 are not equal!"];
Assert[Norm[(MomentsFromPH[betap2, Bp2, 3]-stmFromME2)/stmFromME2]<10^-12, "MMAPPH1FCFS: the ME and PH representations for class 2 are not equal!"];
Assert[Norm[(MomentsFromPH[betap3, Bp3, 3]-stmFromME3)/stmFromME3]<10^-12, "MMAPPH1FCFS: the ME and PH representations for class 3 are not equal!"];
Assert[Norm[std1-CdfFromME[beta1, B1, distrPoints]]<10^-12, "MMAPPH1FCFS: stDistr returns wrong sojourn time distribution for class 1!"];
Assert[Norm[std2-CdfFromME[beta2, B2, distrPoints]]<10^-12, "MMAPPH1FCFS: stDistr returns wrong sojourn time distribution for class 2!"];
Assert[Norm[std3-CdfFromME[beta3, B3, distrPoints]]<10^-12, "MMAPPH1FCFS: stDistr returns wrong sojourn time distribution for class 3!"];
Assert[Norm[(stm1-stmFromME1)/stm1]<10^-12, "MMAPPH1FCFS: stMoms returns wrong sojourn time moments for class 1!"];
Assert[Norm[(stm2-stmFromME2)/stm2]<10^-12, "MMAPPH1FCFS: stMoms returns wrong sojourn time moments for class 2!"];
Assert[Norm[(stm3-stmFromME3)/stm3]<10^-12, "MMAPPH1FCFS: stMoms returns wrong sojourn time moments for class 3!"];
lambda1 = 1./MarginalMomentsFromMAP[D0+D2+D3, D1, 1][[1]];
lambda2 = 1./MarginalMomentsFromMAP[D0+D1+D3, D2, 1][[1]];
lambda3 = 1./MarginalMomentsFromMAP[D0+D1+D2, D3, 1][[1]];
Assert[Abs[ncm1[[1]]-stm1[[1]]*lambda1]<10^-12, "MMAPPH1FCFS: Little formula does not hold for class 1!"];
Assert[Abs[ncm2[[1]]-stm2[[1]]*lambda2]<10^-12, "MMAPPH1FCFS: Little formula does not hold for class 2!"];
Assert[Abs[ncm3[[1]]-stm3[[1]]*lambda3]<10^-12, "MMAPPH1FCFS: Little formula does not hold for class 3!"];
Print["Input:"//OutputForm];
Print["------"//OutputForm];
D0 = {{-5.49, 0., 1.15, 0.},{0., -2.29, 0., 0.},{0., 0.08, -1.32, 0.},{0.72, 1.17, 0.7, -7.07}};
Print["D0 = "//OutputForm];
Print[D0];
D1 = {{0.25, 0.38, 0.64, 0.},{0., 0., 0., 1.09},{0., 1.24, 0., 0.},{0.37, 0., 0., 0.}};
Print["D1 = "//OutputForm];
Print[D1];
D2 = {{0.3, 1.0, 0., 0.48},{0., 0.2, 0., 0.},{0., 0., 0., 0.},{0.61, 0., 0., 0.2}};
Print["D2 = "//OutputForm];
Print[D2];
D3 = {{0., 0.98, 0., 0.31},{0., 0., 1.0, 0.},{0., 0., 0., 0.},{1.1, 0.84, 0.33, 1.03}};
Print["D3 = "//OutputForm];
Print[D3];
sigma3 = {0.16667,0.83333};
Print["sigma3 = "//OutputForm];
Print[sigma3];
S3 = {{-0.5, 0.5},{0., -3.}};
Print["S3 = "//OutputForm];
Print[S3];
sigma2 = {0.58824,0.41176};
Print["sigma2 = "//OutputForm];
Print[sigma2];
S2 = {{-2.3529, 2.3529},{0., -4.}};
Print["S2 = "//OutputForm];
Print[S2];
sigma1 = {0.25,0.75};
Print["sigma1 = "//OutputForm];
Print[sigma1];
S1 = {{-2.5, 2.5},{0., -10.}};
Print["S1 = "//OutputForm];
Print[S1];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["{ncm1, ncd1, ncm2, ncd2, ncm3, ncd3} = MMAPPH1FCFS[{D0, D1, D2, D3}, {sigma1, sigma2, sigma3}, {S1, S2, S3}, \"ncMoms\", 3, \"ncDistr\", 500];:"//OutputForm];
{ncm1, ncd1, ncm2, ncd2, ncm3, ncd3} = MMAPPH1FCFS[{D0, D1, D2, D3}, {sigma1, sigma2, sigma3}, {S1, S2, S3}, "ncMoms", 3, "ncDistr", 500];
momFromDistr1 = ncd1.Transpose[Join[{Range[0,499,1]},{Range[0,499,1]^2},{Range[0,499,1]^3}]];
momFromDistr2 = ncd2.Transpose[Join[{Range[0,499,1]},{Range[0,499,1]^2},{Range[0,499,1]^3}]];
momFromDistr3 = ncd3.Transpose[Join[{Range[0,499,1]},{Range[0,499,1]^2},{Range[0,499,1]^3}]];
Assert[Norm[(momFromDistr1-ncm1)/ncm1]<0.001&&Norm[(momFromDistr2-ncm2)/ncm2]<0.001&&Norm[(momFromDistr3-ncm3)/ncm3]<0.001, "MMAPPH1FCFS: queue length moments and queue length distribution are not consistent!"];
distrPoints = {1., 5., 10.};
Print["{stm1, std1, stm2, std2, stm3, std3} = MMAPPH1FCFS[{D0, D1, D2, D3}, {sigma1, sigma2, sigma3}, {S1, S2, S3}, \"stMoms\", 3, \"stDistr\", distrPoints];:"//OutputForm];
{stm1, std1, stm2, std2, stm3, std3} = MMAPPH1FCFS[{D0, D1, D2, D3}, {sigma1, sigma2, sigma3}, {S1, S2, S3}, "stMoms", 3, "stDistr", distrPoints];
Print["stm1 = "//OutputForm];
Print[stm1];
Print["std1 = "//OutputForm];
Print[std1];
Print["stm2 = "//OutputForm];
Print[stm2];
Print["std2 = "//OutputForm];
Print[std2];
Print["stm3 = "//OutputForm];
Print[stm3];
Print["std3 = "//OutputForm];
Print[std3];
Print["{betap1, Bp1, betap2, Bp2, betap3, Bp3} = MMAPPH1FCFS[{D0, D1, D2, D3}, {sigma1, sigma2, sigma3}, {S1, S2, S3}, \"stDistrPH\"];:"//OutputForm];
{betap1, Bp1, betap2, Bp2, betap3, Bp3} = MMAPPH1FCFS[{D0, D1, D2, D3}, {sigma1, sigma2, sigma3}, {S1, S2, S3}, "stDistrPH"];
Print["{beta1, B1, beta2, B2, beta3, B3} = MMAPPH1FCFS[{D0, D1, D2, D3}, {sigma1, sigma2, sigma3}, {S1, S2, S3}, \"stDistrME\"];:"//OutputForm];
{beta1, B1, beta2, B2, beta3, B3} = MMAPPH1FCFS[{D0, D1, D2, D3}, {sigma1, sigma2, sigma3}, {S1, S2, S3}, "stDistrME"];
Print["stdFromPH1 = CdfFromPH[betap1, Bp1, distrPoints];:"//OutputForm];
stdFromPH1 = CdfFromPH[betap1, Bp1, distrPoints];
Print["stdFromPH1 = "//OutputForm];
Print[stdFromPH1];
Print["stmFromME1 = MomentsFromME[beta1, B1, 3];:"//OutputForm];
stmFromME1 = MomentsFromME[beta1, B1, 3];
Print["stmFromME1 = "//OutputForm];
Print[stmFromME1];
Print["stdFromPH2 = CdfFromPH[betap2, Bp2, distrPoints];:"//OutputForm];
stdFromPH2 = CdfFromPH[betap2, Bp2, distrPoints];
Print["stdFromPH2 = "//OutputForm];
Print[stdFromPH2];
Print["stmFromME2 = MomentsFromME[beta2, B2, 3];:"//OutputForm];
stmFromME2 = MomentsFromME[beta2, B2, 3];
Print["stmFromME2 = "//OutputForm];
Print[stmFromME2];
Print["stdFromPH3 = CdfFromPH[betap3, Bp3, distrPoints];:"//OutputForm];
stdFromPH3 = CdfFromPH[betap3, Bp3, distrPoints];
Print["stdFromPH3 = "//OutputForm];
Print[stdFromPH3];
Print["stmFromME3 = MomentsFromME[beta3, B3, 3];:"//OutputForm];
stmFromME3 = MomentsFromME[beta3, B3, 3];
Print["stmFromME3 = "//OutputForm];
Print[stmFromME3];
Assert[Min[std1]>=0&&Max[std1]<=1&&AllTrue[Differences[std1],#>=-10^-14 &]&&Min[std2]>=0&&Max[std2]<=1&&AllTrue[Differences[std2],#>=-10^-14 &]&&Min[std3]>=0&&Max[std3]<=1&&AllTrue[Differences[std3],#>=-10^-14 &], "MMAPPH1FCFS: invalid sojourn time distribution!"];
Assert[Norm[(MomentsFromPH[betap1, Bp1, 3]-stmFromME1)/stmFromME1]<10^-12, "MMAPPH1FCFS: the ME and PH representations for class 1 are not equal!"];
Assert[Norm[(MomentsFromPH[betap2, Bp2, 3]-stmFromME2)/stmFromME2]<10^-12, "MMAPPH1FCFS: the ME and PH representations for class 2 are not equal!"];
Assert[Norm[(MomentsFromPH[betap3, Bp3, 3]-stmFromME3)/stmFromME3]<10^-12, "MMAPPH1FCFS: the ME and PH representations for class 3 are not equal!"];
Assert[Norm[std1-CdfFromME[beta1, B1, distrPoints]]<10^-12, "MMAPPH1FCFS: stDistr returns wrong sojourn time distribution for class 1!"];
Assert[Norm[std2-CdfFromME[beta2, B2, distrPoints]]<10^-12, "MMAPPH1FCFS: stDistr returns wrong sojourn time distribution for class 2!"];
Assert[Norm[std3-CdfFromME[beta3, B3, distrPoints]]<10^-12, "MMAPPH1FCFS: stDistr returns wrong sojourn time distribution for class 3!"];
Assert[Norm[(stm1-stmFromME1)/stm1]<10^-12, "MMAPPH1FCFS: stMoms returns wrong sojourn time moments for class 1!"];
Assert[Norm[(stm2-stmFromME2)/stm2]<10^-12, "MMAPPH1FCFS: stMoms returns wrong sojourn time moments for class 2!"];
Assert[Norm[(stm3-stmFromME3)/stm3]<10^-12, "MMAPPH1FCFS: stMoms returns wrong sojourn time moments for class 3!"];
lambda1 = 1./MarginalMomentsFromMAP[D0+D2+D3, D1, 1][[1]];
lambda2 = 1./MarginalMomentsFromMAP[D0+D1+D3, D2, 1][[1]];
lambda3 = 1./MarginalMomentsFromMAP[D0+D1+D2, D3, 1][[1]];
Assert[Abs[ncm1[[1]]-stm1[[1]]*lambda1]<10^-12, "MMAPPH1FCFS: Little formula does not hold for class 1!"];
Assert[Abs[ncm2[[1]]-stm2[[1]]*lambda2]<10^-12, "MMAPPH1FCFS: Little formula does not hold for class 2!"];
Assert[Abs[ncm3[[1]]-stm3[[1]]*lambda3]<10^-12, "MMAPPH1FCFS: Little formula does not hold for class 3!"];
Print["========================================"]
Print["Testing BuTools function FluidQueue"]
Print["Input:"//OutputForm];
Print["------"//OutputForm];
Q = {{-9., 2., 4., 0., 1., 2.},{6., -25., 5., 3., 7., 4.},{1., 3., -4., 0., 0., 0.},{0., 0., 0., -8., 3., 5.},{7., 3., 0., 2., -13., 1.},{7., 8., 0., 3., 8., -26.}};
Print["Q = "//OutputForm];
Print[Q];
vRin = {4.,2.,1.,0.,0.,3.};
Print["vRin = "//OutputForm];
Print[vRin];
vRout = {6.,2.,0.,0.,3.,2.};
Print["vRout = "//OutputForm];
Print[vRout];
Print["Rin = DiagonalMatrix[vRin];:"//OutputForm];
Rin = DiagonalMatrix[vRin];
Print["Rout = DiagonalMatrix[vRout];:"//OutputForm];
Rout = DiagonalMatrix[vRout];
lambd = Total[CTMCSolve[Q].Rin];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["{fld, flm} = FluidQueue[Q, Rin, Rout, \"flDistr\", Range[0.,1.,0.1], \"flMoms\", 5];:"//OutputForm];
{fld, flm} = FluidQueue[Q, Rin, Rout, "flDistr", Range[0.,1.,0.1], "flMoms", 5];
Print["fld = "//OutputForm];
Print[fld];
Print["flm = "//OutputForm];
Print[flm];
Print["{alphap, Ap} = FluidQueue[Q, Rin, Rout, \"flDistrPH\"];:"//OutputForm];
{alphap, Ap} = FluidQueue[Q, Rin, Rout, "flDistrPH"];
Print["alphap = "//OutputForm];
Print[alphap];
Print["Ap = "//OutputForm];
Print[Ap];
Print["{alpha, A} = FluidQueue[Q, Rin, Rout, \"flDistrME\"];:"//OutputForm];
{alpha, A} = FluidQueue[Q, Rin, Rout, "flDistrME"];
Print["alpha = "//OutputForm];
Print[alpha];
Print["A = "//OutputForm];
Print[A];
Print["fldFromPH = CdfFromPH[alphap, Ap, Range[0.,1.,0.1]];:"//OutputForm];
fldFromPH = CdfFromPH[alphap, Ap, Range[0.,1.,0.1]];
Print["fldFromPH = "//OutputForm];
Print[fldFromPH];
Print["flmFromME = MomentsFromME[alpha, A, 5];:"//OutputForm];
flmFromME = MomentsFromME[alpha, A, 5];
Print["flmFromME = "//OutputForm];
Print[flmFromME];
Print["{std, stm} = FluidQueue[Q, Rin, Rout, \"stDistr\", Range[0.,1.,0.1], \"stMoms\", 5];:"//OutputForm];
{std, stm} = FluidQueue[Q, Rin, Rout, "stDistr", Range[0.,1.,0.1], "stMoms", 5];
Print["std = "//OutputForm];
Print[std];
Print["stm = "//OutputForm];
Print[stm];
Print["{betap, Bp} = FluidQueue[Q, Rin, Rout, \"stDistrPH\"];:"//OutputForm];
{betap, Bp} = FluidQueue[Q, Rin, Rout, "stDistrPH"];
Print["betap = "//OutputForm];
Print[betap];
Print["Bp = "//OutputForm];
Print[Bp];
Print["{beta, B} = FluidQueue[Q, Rin, Rout, \"stDistrME\"];:"//OutputForm];
{beta, B} = FluidQueue[Q, Rin, Rout, "stDistrME"];
Print["beta = "//OutputForm];
Print[beta];
Print["B = "//OutputForm];
Print[B];
Print["stdFromPH = CdfFromPH[betap, Bp, Range[0.,1.,0.1]];:"//OutputForm];
stdFromPH = CdfFromPH[betap, Bp, Range[0.,1.,0.1]];
Print["stdFromPH = "//OutputForm];
Print[stdFromPH];
Print["stmFromME = MomentsFromME[beta, B, 5];:"//OutputForm];
stmFromME = MomentsFromME[beta, B, 5];
Print["stmFromME = "//OutputForm];
Print[stmFromME];
Assert[CheckMERepresentation[alpha, A], "FluidQueue: invalid ME representation of the queue length!"];
Assert[CheckMERepresentation[beta, B], "FluidQueue: invalid ME representation of the sojourn time!"];
Assert[CheckPHRepresentation[alphap, Ap], "FluidQueue: invalid PH representation of the queue length!"];
Assert[CheckPHRepresentation[betap, Bp], "FluidQueue: invalid PH representation of the sojourn time!"];
Assert[Abs[flm[[1]]-stm[[1]]*lambd]<10^-12, "FluidQueue: Little formula does not hold!"];
Assert[Norm[(MomentsFromPH[alphap, Ap, 5]-flmFromME)/flmFromME]<10^-12, "FluidQueue: the ME and PH representations are not equal!"];
Assert[Norm[(MomentsFromPH[betap, Bp, 5]-stmFromME)/stmFromME]<10^-12, "FluidQueue: the ME and PH representations are not equal!"];
Assert[Norm[fld-CdfFromME[alpha, A, Range[0.,1.,0.1]]]<10^-12, "FluidQueue: flDistr returns wrong queue length distribution!"];
Assert[Norm[std-CdfFromME[beta, B, Range[0.,1.,0.1]]]<10^-12, "FluidQueue: stDistr returns wrong sojourn time distribution!"];
Assert[Norm[(flm-flmFromME)/flm]<10^-12, "FluidQueue: flmoms returns wrong queue length moments!"];
Assert[Norm[(stm-stmFromME)/stm]<10^-12, "FluidQueue: stMoms returns wrong sojourn time moments!"];
Print["========================================"]
Print["Testing BuTools function FluFluQueue"]
Print["Input:"//OutputForm];
Print["------"//OutputForm];
Qin = {{-2., 1., 1.},{2., -5., 3.},{4., 0., -4.}};
Print["Qin = "//OutputForm];
Print[Qin];
vRin = {3.,7.,0.};
Print["vRin = "//OutputForm];
Print[vRin];
Print["Rin = DiagonalMatrix[vRin];:"//OutputForm];
Rin = DiagonalMatrix[vRin];
Qout = {{-4., 1., 3.},{6., -8., 2.},{3., 7., -10.}};
Print["Qout = "//OutputForm];
Print[Qout];
vRout = {1.,7.,15.};
Print["vRout = "//OutputForm];
Print[vRout];
Print["Rout = DiagonalMatrix[vRout];:"//OutputForm];
Rout = DiagonalMatrix[vRout];
lambd = Total[CTMCSolve[Qin].Rin];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["{fld, flm} = FluFluQueue[Qin, Rin, Qout, Rout, False, \"flDistr\", Range[0.,1.,0.1], \"flMoms\", 5];:"//OutputForm];
{fld, flm} = FluFluQueue[Qin, Rin, Qout, Rout, False, "flDistr", Range[0.,1.,0.1], "flMoms", 5];
Print["fld = "//OutputForm];
Print[fld];
Print["flm = "//OutputForm];
Print[flm];
Print["{alphap, Ap} = FluFluQueue[Qin, Rin, Qout, Rout, False, \"flDistrPH\"];:"//OutputForm];
{alphap, Ap} = FluFluQueue[Qin, Rin, Qout, Rout, False, "flDistrPH"];
Print["alphap = "//OutputForm];
Print[alphap];
Print["Ap = "//OutputForm];
Print[Ap];
Print["{alpha, A} = FluFluQueue[Qin, Rin, Qout, Rout, False, \"flDistrME\"];:"//OutputForm];
{alpha, A} = FluFluQueue[Qin, Rin, Qout, Rout, False, "flDistrME"];
Print["alpha = "//OutputForm];
Print[alpha];
Print["A = "//OutputForm];
Print[A];
Print["fldFromPH = CdfFromPH[alphap, Ap, Range[0.,1.,0.1]];:"//OutputForm];
fldFromPH = CdfFromPH[alphap, Ap, Range[0.,1.,0.1]];
Print["fldFromPH = "//OutputForm];
Print[fldFromPH];
Print["flmFromME = MomentsFromME[alpha, A, 5];:"//OutputForm];
flmFromME = MomentsFromME[alpha, A, 5];
Print["flmFromME = "//OutputForm];
Print[flmFromME];
Print["{std, stm} = FluFluQueue[Qin, Rin, Qout, Rout, False, \"stDistr\", Range[0.,1.,0.1], \"stMoms\", 5];:"//OutputForm];
{std, stm} = FluFluQueue[Qin, Rin, Qout, Rout, False, "stDistr", Range[0.,1.,0.1], "stMoms", 5];
Print["std = "//OutputForm];
Print[std];
Print["stm = "//OutputForm];
Print[stm];
Print["{betap, Bp} = FluFluQueue[Qin, Rin, Qout, Rout, False, \"stDistrPH\"];:"//OutputForm];
{betap, Bp} = FluFluQueue[Qin, Rin, Qout, Rout, False, "stDistrPH"];
Print["betap = "//OutputForm];
Print[betap];
Print["Bp = "//OutputForm];
Print[Bp];
Print["{beta, B} = FluFluQueue[Qin, Rin, Qout, Rout, False, \"stDistrME\"];:"//OutputForm];
{beta, B} = FluFluQueue[Qin, Rin, Qout, Rout, False, "stDistrME"];
Print["beta = "//OutputForm];
Print[beta];
Print["B = "//OutputForm];
Print[B];
Print["stdFromPH = CdfFromPH[betap, Bp, Range[0.,1.,0.1]];:"//OutputForm];
stdFromPH = CdfFromPH[betap, Bp, Range[0.,1.,0.1]];
Print["stdFromPH = "//OutputForm];
Print[stdFromPH];
Print["stmFromME = MomentsFromME[beta, B, 5];:"//OutputForm];
stmFromME = MomentsFromME[beta, B, 5];
Print["stmFromME = "//OutputForm];
Print[stmFromME];
Assert[CheckMERepresentation[alpha, A], "FluFluQueue: invalid ME representation of the queue length!"];
Assert[CheckMERepresentation[beta, B], "FluFluQueue: invalid ME representation of the sojourn time!"];
Assert[CheckPHRepresentation[alphap, Ap], "FluFluQueue: invalid PH representation of the queue length!"];
Assert[CheckPHRepresentation[betap, Bp], "FluFluQueue: invalid PH representation of the sojourn time!"];
Assert[Abs[flm[[1]]-stm[[1]]*lambd]<10^-12, "FluFluQueue: Little formula does not hold!"];
Assert[Norm[(MomentsFromPH[alphap, Ap, 5]-flmFromME)/flmFromME]<10^-12, "FluFluQueue: the ME and PH representations are not equal!"];
Assert[Norm[(MomentsFromPH[betap, Bp, 5]-stmFromME)/stmFromME]<10^-12, "FluFluQueue: the ME and PH representations are not equal!"];
Assert[Norm[fld-CdfFromME[alpha, A, Range[0.,1.,0.1]]]<10^-12, "FluFluQueue: flDistr returns wrong queue length distribution!"];
Assert[Norm[std-CdfFromME[beta, B, Range[0.,1.,0.1]]]<10^-12, "FluFluQueue: stDistr returns wrong sojourn time distribution!"];
Assert[Norm[(flm-flmFromME)/flm]<10^-12, "FluFluQueue: flmoms returns wrong queue length moments!"];
Assert[Norm[(stm-stmFromME)/stm]<10^-12, "FluFluQueue: stMoms returns wrong sojourn time moments!"];
Iin = IdentityMatrix[Dimensions[Qin][[1]]];
Iout = IdentityMatrix[Dimensions[Qout][[1]]];
BuTools`Verbose = False;
{gamma, G} = FluidQueue[KroneckerProduct[Qin, Iout]+KroneckerProduct[Iin, Qout], KroneckerProduct[Rin, Iout], KroneckerProduct[Iin, Rout], "stDistrME"];
BuTools`Verbose = True;
msmall = MomentsFromME[beta, B, 5];
mlarge = MomentsFromME[gamma, G, 5];
Assert[Norm[(msmall-mlarge)/msmall]<10^-12, "FluFluQueue: Large and small model do not give the same results!"];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["{fld, flm} = FluFluQueue[Qin, Rin, Qout, Rout, True, \"flDistr\", Range[0.,1.,0.1], \"flMoms\", 5];:"//OutputForm];
{fld, flm} = FluFluQueue[Qin, Rin, Qout, Rout, True, "flDistr", Range[0.,1.,0.1], "flMoms", 5];
Print["fld = "//OutputForm];
Print[fld];
Print["flm = "//OutputForm];
Print[flm];
Print["{alphap, Ap} = FluFluQueue[Qin, Rin, Qout, Rout, True, \"flDistrPH\"];:"//OutputForm];
{alphap, Ap} = FluFluQueue[Qin, Rin, Qout, Rout, True, "flDistrPH"];
Print["alphap = "//OutputForm];
Print[alphap];
Print["Ap = "//OutputForm];
Print[Ap];
Print["{alpha, A} = FluFluQueue[Qin, Rin, Qout, Rout, True, \"flDistrME\"];:"//OutputForm];
{alpha, A} = FluFluQueue[Qin, Rin, Qout, Rout, True, "flDistrME"];
Print["alpha = "//OutputForm];
Print[alpha];
Print["A = "//OutputForm];
Print[A];
Print["fldFromPH = CdfFromPH[alphap, Ap, Range[0.,1.,0.1]];:"//OutputForm];
fldFromPH = CdfFromPH[alphap, Ap, Range[0.,1.,0.1]];
Print["fldFromPH = "//OutputForm];
Print[fldFromPH];
Print["flmFromME = MomentsFromME[alpha, A, 5];:"//OutputForm];
flmFromME = MomentsFromME[alpha, A, 5];
Print["flmFromME = "//OutputForm];
Print[flmFromME];
Print["{std, stm} = FluFluQueue[Qin, Rin, Qout, Rout, True, \"stDistr\", Range[0.,1.,0.1], \"stMoms\", 5];:"//OutputForm];
{std, stm} = FluFluQueue[Qin, Rin, Qout, Rout, True, "stDistr", Range[0.,1.,0.1], "stMoms", 5];
Print["std = "//OutputForm];
Print[std];
Print["stm = "//OutputForm];
Print[stm];
Print["{betap, Bp} = FluFluQueue[Qin, Rin, Qout, Rout, True, \"stDistrPH\"];:"//OutputForm];
{betap, Bp} = FluFluQueue[Qin, Rin, Qout, Rout, True, "stDistrPH"];
Print["betap = "//OutputForm];
Print[betap];
Print["Bp = "//OutputForm];
Print[Bp];
Print["{beta, B} = FluFluQueue[Qin, Rin, Qout, Rout, True, \"stDistrME\"];:"//OutputForm];
{beta, B} = FluFluQueue[Qin, Rin, Qout, Rout, True, "stDistrME"];
Print["beta = "//OutputForm];
Print[beta];
Print["B = "//OutputForm];
Print[B];
Print["stdFromPH = CdfFromPH[betap, Bp, Range[0.,1.,0.1]];:"//OutputForm];
stdFromPH = CdfFromPH[betap, Bp, Range[0.,1.,0.1]];
Print["stdFromPH = "//OutputForm];
Print[stdFromPH];
Print["stmFromME = MomentsFromME[beta, B, 5];:"//OutputForm];
stmFromME = MomentsFromME[beta, B, 5];
Print["stmFromME = "//OutputForm];
Print[stmFromME];
Assert[CheckMERepresentation[alpha, A], "FluFluQueue: invalid ME representation of the queue length!"];
Assert[CheckMERepresentation[beta, B], "FluFluQueue: invalid ME representation of the sojourn time!"];
Assert[CheckPHRepresentation[alphap, Ap], "FluFluQueue: invalid PH representation of the queue length!"];
Assert[CheckPHRepresentation[betap, Bp], "FluFluQueue: invalid PH representation of the sojourn time!"];
Assert[Abs[flm[[1]]-stm[[1]]*lambd]<10^-12, "FluFluQueue: Little formula does not hold!"];
Assert[Norm[(MomentsFromPH[alphap, Ap, 5]-flmFromME)/flmFromME]<10^-12, "FluFluQueue: the ME and PH representations are not equal!"];
Assert[Norm[(MomentsFromPH[betap, Bp, 5]-stmFromME)/stmFromME]<10^-12, "FluFluQueue: the ME and PH representations are not equal!"];
Assert[Norm[fld-CdfFromME[alpha, A, Range[0.,1.,0.1]]]<10^-12, "FluFluQueue: flDistr returns wrong queue length distribution!"];
Assert[Norm[std-CdfFromME[beta, B, Range[0.,1.,0.1]]]<10^-12, "FluFluQueue: stDistr returns wrong sojourn time distribution!"];
Assert[Norm[(flm-flmFromME)/flm]<10^-12, "FluFluQueue: flmoms returns wrong queue length moments!"];
Assert[Norm[(stm-stmFromME)/stm]<10^-12, "FluFluQueue: stMoms returns wrong sojourn time moments!"];
Iin = IdentityMatrix[Dimensions[Qin][[1]]];
Iout = IdentityMatrix[Dimensions[Qout][[1]]];
BuTools`Verbose = False;
{gamma, G} = FluidQueue[KroneckerProduct[Qin, Iout]+KroneckerProduct[Iin, Qout], KroneckerProduct[Rin, Iout], KroneckerProduct[Iin, Rout], "Q0", KroneckerProduct[Qin, Iout]+KroneckerProduct[Rin, PseudoInverse[Rout].Qout], "stDistrME"];
BuTools`Verbose = True;
msmall = MomentsFromME[beta, B, 5];
mlarge = MomentsFromME[gamma, G, 5];
Assert[Norm[(msmall-mlarge)/msmall]<10^-12, "FluFluQueue: Large and small model do not give the same results!"];
