clear all
run('/home/gabor/github/butools/Matlab/BuToolsInit.m')

disp('---BuTools: Queues package test file---');
disp('Enable the verbose messages with the BuToolsVerbose flag');
global BuToolsVerbose;
BuToolsVerbose = true;
disp('Enable input parameter checking with the BuToolsCheckInput flag');
global BuToolsCheckInput;
BuToolsCheckInput = true;
global BuToolsCheckPrecision;
format short g;
disp('========================================')
disp('Testing BuTools function QBDQueue')
disp('Input:');
disp('------');
B = [6., 1., 0.; 0., 4., 1.; 2., 0., 0.];
disp('B = ');
disp(B);
F = [0., 1., 1.; 5., 0., 0.; 1., 3., 0.];
disp('F = ');
disp(F);
L = [-14., 3., 2.; 0., -14., 4.; 3., 1., -10.];
disp('L = ');
disp(L);
L0 = L+B;
disp('L0 = ');
disp(L0);
BuToolsVerbose = false;
[pi0, R] = QBDSolve(B, L, F, L0);
lambd = sum(pi0*inv(eye(size(R,1))-R)*F);
BuToolsVerbose = true;
disp('Test:');
disp('-----');
disp('[qld, qlm] = QBDQueue(B, L, F, L0, ''qlDistr'', (0:1:10), ''qlMoms'', 5);:');
[qld, qlm] = QBDQueue(B, L, F, L0, 'qlDistr', (0:1:10), 'qlMoms', 5);
disp('qld = ');
disp(qld);
disp('qlm = ');
disp(qlm);
disp('[alphap, Ap] = QBDQueue(B, L, F, L0, ''qlDistrDPH'');:');
[alphap, Ap] = QBDQueue(B, L, F, L0, 'qlDistrDPH');
disp('alphap = ');
disp(alphap);
disp('Ap = ');
disp(Ap);
disp('[alpha, A] = QBDQueue(B, L, F, L0, ''qlDistrMG'');:');
[alpha, A] = QBDQueue(B, L, F, L0, 'qlDistrMG');
disp('alpha = ');
disp(alpha);
disp('A = ');
disp(A);
disp('qldFromDPH = PmfFromDPH(alphap, Ap, (0:1:10));:');
qldFromDPH = PmfFromDPH(alphap, Ap, (0:1:10));
disp('qldFromDPH = ');
disp(qldFromDPH);
disp('qlmFromMG = MomentsFromMG(alpha, A, 5);:');
qlmFromMG = MomentsFromMG(alpha, A, 5);
disp('qlmFromMG = ');
disp(qlmFromMG);
disp('[std, stm] = QBDQueue(B, L, F, L0, ''stDistr'', (0.:0.1:1.), ''stMoms'', 5);:');
[std, stm] = QBDQueue(B, L, F, L0, 'stDistr', (0.:0.1:1.), 'stMoms', 5);
disp('std = ');
disp(std);
disp('stm = ');
disp(stm);
disp('[betap, Bp] = QBDQueue(B, L, F, L0, ''stDistrPH'');:');
[betap, Bp] = QBDQueue(B, L, F, L0, 'stDistrPH');
disp('betap = ');
disp(betap);
disp('Bp = ');
disp(Bp);
disp('[beta, B] = QBDQueue(B, L, F, L0, ''stDistrME'');:');
[beta, B] = QBDQueue(B, L, F, L0, 'stDistrME');
disp('beta = ');
disp(beta);
disp('B = ');
disp(B);
disp('stdFromPH = CdfFromPH(betap, Bp, (0.:0.1:1.));:');
stdFromPH = CdfFromPH(betap, Bp, (0.:0.1:1.));
disp('stdFromPH = ');
disp(stdFromPH);
disp('stmFromME = MomentsFromME(beta, B, 5);:');
stmFromME = MomentsFromME(beta, B, 5);
disp('stmFromME = ');
disp(stmFromME);
assert(CheckMGRepresentation(alpha, A), 'QBDQueue: invalid MG representation of the queue length!');
assert(CheckMERepresentation(beta, B), 'QBDQueue: invalid ME representation of the sojourn time!');
assert(CheckDPHRepresentation(alphap, Ap), 'QBDQueue: invalid DPH representation of the queue length!');
assert(CheckPHRepresentation(betap, Bp), 'QBDQueue: invalid PH representation of the sojourn time!');
assert(abs(qlm(1)-stm(1)*lambd)<1e-12, 'QBDQueue: Little formula does not hold!');
assert(norm((MomentsFromDPH(alphap, Ap, 5)-qlmFromMG)./qlmFromMG)<1e-12, 'QBDQueue: the MG and DPH representations are not equal!');
assert(norm((MomentsFromPH(betap, Bp, 5)-stmFromME)./stmFromME)<1e-12, 'QBDQueue: the ME and PH representations are not equal!');
assert(norm(qld-PmfFromMG(alpha, A, (0:1:10)))<1e-12, 'QBDQueue: qlDistr returns wrong queue length distribution!');
assert(norm(std-CdfFromME(beta, B, (0.:0.1:1.)))<1e-12, 'QBDQueue: stDistr returns wrong sojourn time distribution!');
assert(norm((qlm-qlmFromMG)./qlm)<1e-12, 'QBDQueue: qlMoms returns wrong queue length moments!');
assert(norm((stm-stmFromME)./stm)<1e-12, 'QBDQueue: stMoms returns wrong sojourn time moments!');
disp('Input:');
disp('------');
B = [6., 1., 0.; 0., 4., 1.; 2., 0., 0.];
disp('B = ');
disp(B);
F = [0., 0., 0.; 5., 0., 0.; 1., 3., 0.];
disp('F = ');
disp(F);
L = [-12., 3., 2.; 0., -14., 4.; 3., 1., -10.];
disp('L = ');
disp(L);
L0 = L+B;
disp('L0 = ');
disp(L0);
BuToolsVerbose = false;
[pi0, R] = QBDSolve(B, L, F, L0);
lambd = sum(pi0*inv(eye(size(R,1))-R)*F);
BuToolsVerbose = true;
disp('Test:');
disp('-----');
disp('[qld, qlm] = QBDQueue(B, L, F, L0, ''qlDistr'', (0:1:10), ''qlMoms'', 5);:');
[qld, qlm] = QBDQueue(B, L, F, L0, 'qlDistr', (0:1:10), 'qlMoms', 5);
disp('qld = ');
disp(qld);
disp('qlm = ');
disp(qlm);
disp('[alphap, Ap] = QBDQueue(B, L, F, L0, ''qlDistrDPH'');:');
[alphap, Ap] = QBDQueue(B, L, F, L0, 'qlDistrDPH');
disp('alphap = ');
disp(alphap);
disp('Ap = ');
disp(Ap);
disp('[alpha, A] = QBDQueue(B, L, F, L0, ''qlDistrMG'');:');
[alpha, A] = QBDQueue(B, L, F, L0, 'qlDistrMG');
disp('alpha = ');
disp(alpha);
disp('A = ');
disp(A);
disp('qldFromDPH = PmfFromDPH(alphap, Ap, (0:1:10));:');
qldFromDPH = PmfFromDPH(alphap, Ap, (0:1:10));
disp('qldFromDPH = ');
disp(qldFromDPH);
disp('qlmFromMG = MomentsFromMG(alpha, A, 5);:');
qlmFromMG = MomentsFromMG(alpha, A, 5);
disp('qlmFromMG = ');
disp(qlmFromMG);
disp('[std, stm] = QBDQueue(B, L, F, L0, ''stDistr'', (0.:0.1:1.), ''stMoms'', 5);:');
[std, stm] = QBDQueue(B, L, F, L0, 'stDistr', (0.:0.1:1.), 'stMoms', 5);
disp('std = ');
disp(std);
disp('stm = ');
disp(stm);
disp('[betap, Bp] = QBDQueue(B, L, F, L0, ''stDistrPH'');:');
[betap, Bp] = QBDQueue(B, L, F, L0, 'stDistrPH');
disp('betap = ');
disp(betap);
disp('Bp = ');
disp(Bp);
disp('[beta, B] = QBDQueue(B, L, F, L0, ''stDistrME'');:');
[beta, B] = QBDQueue(B, L, F, L0, 'stDistrME');
disp('beta = ');
disp(beta);
disp('B = ');
disp(B);
disp('stdFromPH = CdfFromPH(betap, Bp, (0.:0.1:1.));:');
stdFromPH = CdfFromPH(betap, Bp, (0.:0.1:1.));
disp('stdFromPH = ');
disp(stdFromPH);
disp('stmFromME = MomentsFromME(beta, B, 5);:');
stmFromME = MomentsFromME(beta, B, 5);
disp('stmFromME = ');
disp(stmFromME);
assert(CheckMGRepresentation(alpha, A), 'QBDQueue: invalid MG representation of the queue length!');
assert(CheckMERepresentation(beta, B), 'QBDQueue: invalid ME representation of the sojourn time!');
assert(CheckDPHRepresentation(alphap, Ap), 'QBDQueue: invalid DPH representation of the queue length!');
assert(CheckPHRepresentation(betap, Bp), 'QBDQueue: invalid PH representation of the sojourn time!');
assert(abs(qlm(1)-stm(1)*lambd)<1e-12, 'QBDQueue: Little formula does not hold!');
assert(norm((MomentsFromDPH(alphap, Ap, 5)-qlmFromMG)./qlmFromMG)<1e-12, 'QBDQueue: the MG and DPH representations are not equal!');
assert(norm((MomentsFromPH(betap, Bp, 5)-stmFromME)./stmFromME)<1e-12, 'QBDQueue: the ME and PH representations are not equal!');
assert(norm(qld-PmfFromMG(alpha, A, (0:1:10)))<1e-12, 'QBDQueue: qlDistr returns wrong queue length distribution!');
assert(norm(std-CdfFromME(beta, B, (0.:0.1:1.)))<1e-12, 'QBDQueue: stDistr returns wrong sojourn time distribution!');
assert(norm((qlm-qlmFromMG)./qlm)<1e-12, 'QBDQueue: qlMoms returns wrong queue length moments!');
assert(norm((stm-stmFromME)./stm)<1e-12, 'QBDQueue: stMoms returns wrong sojourn time moments!');
disp('Input:');
disp('------');
B = [6., 1., 0.; 0., 5., 0.; 0., 0., 0.];
disp('B = ');
disp(B);
F = [0., 3., 1.; 0., 5., 0.; 0., 0., 0.];
disp('F = ');
disp(F);
L = [-16., 3., 2.; 0., -14., 4.; 3., 1., -4.];
disp('L = ');
disp(L);
L0 = [-14., 10., 0.; 5., -10., 0.; 3., 1., -4.];
disp('L0 = ');
disp(L0);
BuToolsVerbose = false;
[pi0, R] = QBDSolve(B, L, F, L0);
lambd = sum(pi0*inv(eye(size(R,1))-R)*F);
BuToolsVerbose = true;
disp('Test:');
disp('-----');
disp('[qld, qlm] = QBDQueue(B, L, F, L0, ''qlDistr'', (0:1:10), ''qlMoms'', 5);:');
[qld, qlm] = QBDQueue(B, L, F, L0, 'qlDistr', (0:1:10), 'qlMoms', 5);
disp('qld = ');
disp(qld);
disp('qlm = ');
disp(qlm);
disp('[alphap, Ap] = QBDQueue(B, L, F, L0, ''qlDistrDPH'');:');
[alphap, Ap] = QBDQueue(B, L, F, L0, 'qlDistrDPH');
disp('alphap = ');
disp(alphap);
disp('Ap = ');
disp(Ap);
disp('[alpha, A] = QBDQueue(B, L, F, L0, ''qlDistrMG'');:');
[alpha, A] = QBDQueue(B, L, F, L0, 'qlDistrMG');
disp('alpha = ');
disp(alpha);
disp('A = ');
disp(A);
disp('qldFromDPH = PmfFromDPH(alphap, Ap, (0:1:10));:');
qldFromDPH = PmfFromDPH(alphap, Ap, (0:1:10));
disp('qldFromDPH = ');
disp(qldFromDPH);
disp('qlmFromMG = MomentsFromMG(alpha, A, 5);:');
qlmFromMG = MomentsFromMG(alpha, A, 5);
disp('qlmFromMG = ');
disp(qlmFromMG);
disp('[std, stm] = QBDQueue(B, L, F, L0, ''stDistr'', (0.:0.1:1.), ''stMoms'', 5);:');
[std, stm] = QBDQueue(B, L, F, L0, 'stDistr', (0.:0.1:1.), 'stMoms', 5);
disp('std = ');
disp(std);
disp('stm = ');
disp(stm);
disp('[betap, Bp] = QBDQueue(B, L, F, L0, ''stDistrPH'');:');
[betap, Bp] = QBDQueue(B, L, F, L0, 'stDistrPH');
disp('betap = ');
disp(betap);
disp('Bp = ');
disp(Bp);
disp('[beta, B] = QBDQueue(B, L, F, L0, ''stDistrME'');:');
[beta, B] = QBDQueue(B, L, F, L0, 'stDistrME');
disp('beta = ');
disp(beta);
disp('B = ');
disp(B);
disp('stdFromPH = CdfFromPH(betap, Bp, (0.:0.1:1.));:');
stdFromPH = CdfFromPH(betap, Bp, (0.:0.1:1.));
disp('stdFromPH = ');
disp(stdFromPH);
disp('stmFromME = MomentsFromME(beta, B, 5);:');
stmFromME = MomentsFromME(beta, B, 5);
disp('stmFromME = ');
disp(stmFromME);
assert(CheckMGRepresentation(alpha, A), 'QBDQueue: invalid MG representation of the queue length!');
assert(CheckMERepresentation(beta, B), 'QBDQueue: invalid ME representation of the sojourn time!');
assert(CheckDPHRepresentation(alphap, Ap), 'QBDQueue: invalid DPH representation of the queue length!');
assert(CheckPHRepresentation(betap, Bp), 'QBDQueue: invalid PH representation of the sojourn time!');
assert(abs(qlm(1)-stm(1)*lambd)<1e-12, 'QBDQueue: Little formula does not hold!');
assert(norm((MomentsFromDPH(alphap, Ap, 5)-qlmFromMG)./qlmFromMG)<1e-12, 'QBDQueue: the MG and DPH representations are not equal!');
assert(norm((MomentsFromPH(betap, Bp, 5)-stmFromME)./stmFromME)<1e-12, 'QBDQueue: the ME and PH representations are not equal!');
assert(norm(qld-PmfFromMG(alpha, A, (0:1:10)))<1e-12, 'QBDQueue: qlDistr returns wrong queue length distribution!');
assert(norm(std-CdfFromME(beta, B, (0.:0.1:1.)))<1e-12, 'QBDQueue: stDistr returns wrong sojourn time distribution!');
assert(norm((qlm-qlmFromMG)./qlm)<1e-12, 'QBDQueue: qlMoms returns wrong queue length moments!');
assert(norm((stm-stmFromME)./stm)<1e-12, 'QBDQueue: stMoms returns wrong sojourn time moments!');
disp('Input:');
disp('------');
B = [0., 0.; 3., 4.];
disp('B = ');
disp(B);
F = [1., 0.; 2., 0.];
disp('F = ');
disp(F);
L = [-6., 5.; 3., -12.];
disp('L = ');
disp(L);
L0 = [-6., 5.; 6., -8.];
disp('L0 = ');
disp(L0);
BuToolsVerbose = false;
[pi0, R] = QBDSolve(B, L, F, L0);
lambd = sum(pi0*inv(eye(size(R,1))-R)*F);
BuToolsVerbose = true;
disp('Test:');
disp('-----');
disp('[qld, qlm] = QBDQueue(B, L, F, L0, ''qlDistr'', (0:1:10), ''qlMoms'', 5);:');
[qld, qlm] = QBDQueue(B, L, F, L0, 'qlDistr', (0:1:10), 'qlMoms', 5);
disp('qld = ');
disp(qld);
disp('qlm = ');
disp(qlm);
disp('[alphap, Ap] = QBDQueue(B, L, F, L0, ''qlDistrDPH'');:');
[alphap, Ap] = QBDQueue(B, L, F, L0, 'qlDistrDPH');
disp('alphap = ');
disp(alphap);
disp('Ap = ');
disp(Ap);
disp('[alpha, A] = QBDQueue(B, L, F, L0, ''qlDistrMG'');:');
[alpha, A] = QBDQueue(B, L, F, L0, 'qlDistrMG');
disp('alpha = ');
disp(alpha);
disp('A = ');
disp(A);
disp('qldFromDPH = PmfFromDPH(alphap, Ap, (0:1:10));:');
qldFromDPH = PmfFromDPH(alphap, Ap, (0:1:10));
disp('qldFromDPH = ');
disp(qldFromDPH);
disp('qlmFromMG = MomentsFromMG(alpha, A, 5);:');
qlmFromMG = MomentsFromMG(alpha, A, 5);
disp('qlmFromMG = ');
disp(qlmFromMG);
disp('[std, stm] = QBDQueue(B, L, F, L0, ''stDistr'', (0.:0.1:1.), ''stMoms'', 5);:');
[std, stm] = QBDQueue(B, L, F, L0, 'stDistr', (0.:0.1:1.), 'stMoms', 5);
disp('std = ');
disp(std);
disp('stm = ');
disp(stm);
disp('[betap, Bp] = QBDQueue(B, L, F, L0, ''stDistrPH'');:');
[betap, Bp] = QBDQueue(B, L, F, L0, 'stDistrPH');
disp('betap = ');
disp(betap);
disp('Bp = ');
disp(Bp);
disp('[beta, B] = QBDQueue(B, L, F, L0, ''stDistrME'');:');
[beta, B] = QBDQueue(B, L, F, L0, 'stDistrME');
disp('beta = ');
disp(beta);
disp('B = ');
disp(B);
disp('stdFromPH = CdfFromPH(betap, Bp, (0.:0.1:1.));:');
stdFromPH = CdfFromPH(betap, Bp, (0.:0.1:1.));
disp('stdFromPH = ');
disp(stdFromPH);
disp('stmFromME = MomentsFromME(beta, B, 5);:');
stmFromME = MomentsFromME(beta, B, 5);
disp('stmFromME = ');
disp(stmFromME);
assert(CheckMGRepresentation(alpha, A), 'QBDQueue: invalid MG representation of the queue length!');
assert(CheckMERepresentation(beta, B), 'QBDQueue: invalid ME representation of the sojourn time!');
assert(CheckDPHRepresentation(alphap, Ap), 'QBDQueue: invalid DPH representation of the queue length!');
assert(CheckPHRepresentation(betap, Bp), 'QBDQueue: invalid PH representation of the sojourn time!');
assert(abs(qlm(1)-stm(1)*lambd)<1e-12, 'QBDQueue: Little formula does not hold!');
assert(norm((MomentsFromDPH(alphap, Ap, 5)-qlmFromMG)./qlmFromMG)<1e-12, 'QBDQueue: the MG and DPH representations are not equal!');
assert(norm((MomentsFromPH(betap, Bp, 5)-stmFromME)./stmFromME)<1e-12, 'QBDQueue: the ME and PH representations are not equal!');
assert(norm(qld-PmfFromMG(alpha, A, (0:1:10)))<1e-12, 'QBDQueue: qlDistr returns wrong queue length distribution!');
assert(norm(std-CdfFromME(beta, B, (0.:0.1:1.)))<1e-12, 'QBDQueue: stDistr returns wrong sojourn time distribution!');
assert(norm((qlm-qlmFromMG)./qlm)<1e-12, 'QBDQueue: qlMoms returns wrong queue length moments!');
assert(norm((stm-stmFromME)./stm)<1e-12, 'QBDQueue: stMoms returns wrong sojourn time moments!');
disp('========================================')
disp('Testing BuTools function MAPMAP1')
disp('Input:');
disp('------');
D0 = [-8., 1., 2.; 0., -6., 4.; 3., 0., -3.];
disp('D0 = ');
disp(D0);
D1 = [4., 1., 0.; 0., 2., 0.; 0., 0., 0.];
disp('D1 = ');
disp(D1);
S0 = [-10., 4.; 0., -7.];
disp('S0 = ');
disp(S0);
S1 = [5., 1.; 4., 3.];
disp('S1 = ');
disp(S1);
lambd = 1./MarginalMomentsFromMAP(D0, D1, 1);
disp('Test:');
disp('-----');
disp('[qld, qlm] = MAPMAP1(D0, D1, S0, S1, ''qlDistr'', (0:1:10), ''qlMoms'', 5);:');
[qld, qlm] = MAPMAP1(D0, D1, S0, S1, 'qlDistr', (0:1:10), 'qlMoms', 5);
disp('qld = ');
disp(qld);
disp('qlm = ');
disp(qlm);
disp('[alphap, Ap] = MAPMAP1(D0, D1, S0, S1, ''qlDistrDPH'');:');
[alphap, Ap] = MAPMAP1(D0, D1, S0, S1, 'qlDistrDPH');
disp('alphap = ');
disp(alphap);
disp('Ap = ');
disp(Ap);
disp('[alpha, A] = MAPMAP1(D0, D1, S0, S1, ''qlDistrMG'');:');
[alpha, A] = MAPMAP1(D0, D1, S0, S1, 'qlDistrMG');
disp('alpha = ');
disp(alpha);
disp('A = ');
disp(A);
disp('qldFromDPH = PmfFromDPH(alphap, Ap, (0:1:10));:');
qldFromDPH = PmfFromDPH(alphap, Ap, (0:1:10));
disp('qldFromDPH = ');
disp(qldFromDPH);
disp('qlmFromMG = MomentsFromMG(alpha, A, 5);:');
qlmFromMG = MomentsFromMG(alpha, A, 5);
disp('qlmFromMG = ');
disp(qlmFromMG);
disp('[std, stm] = MAPMAP1(D0, D1, S0, S1, ''stDistr'', (0.:0.1:1.), ''stMoms'', 5);:');
[std, stm] = MAPMAP1(D0, D1, S0, S1, 'stDistr', (0.:0.1:1.), 'stMoms', 5);
disp('std = ');
disp(std);
disp('stm = ');
disp(stm);
disp('[betap, Bp] = MAPMAP1(D0, D1, S0, S1, ''stDistrPH'');:');
[betap, Bp] = MAPMAP1(D0, D1, S0, S1, 'stDistrPH');
disp('betap = ');
disp(betap);
disp('Bp = ');
disp(Bp);
disp('[beta, B] = MAPMAP1(D0, D1, S0, S1, ''stDistrME'');:');
[beta, B] = MAPMAP1(D0, D1, S0, S1, 'stDistrME');
disp('beta = ');
disp(beta);
disp('B = ');
disp(B);
disp('stdFromPH = CdfFromPH(betap, Bp, (0.:0.1:1.));:');
stdFromPH = CdfFromPH(betap, Bp, (0.:0.1:1.));
disp('stdFromPH = ');
disp(stdFromPH);
disp('stmFromME = MomentsFromME(beta, B, 5);:');
stmFromME = MomentsFromME(beta, B, 5);
disp('stmFromME = ');
disp(stmFromME);
assert(CheckMGRepresentation(alpha, A), 'MAPMAP1: invalid MG representation of the queue length!');
assert(CheckMERepresentation(beta, B), 'MAPMAP1: invalid ME representation of the sojourn time!');
assert(CheckDPHRepresentation(alphap, Ap), 'MAPMAP1: invalid DPH representation of the queue length!');
assert(CheckPHRepresentation(betap, Bp), 'MAPMAP1: invalid PH representation of the sojourn time!');
assert(abs(qlm(1)-stm(1)*lambd)<1e-12, 'MAPMAP1: Little formula does not hold!');
assert(norm((MomentsFromDPH(alphap, Ap, 5)-qlmFromMG)./qlmFromMG)<1e-12, 'MAPMAP1: the MG and DPH representations are not equal!');
assert(norm((MomentsFromPH(betap, Bp, 5)-stmFromME)./stmFromME)<1e-12, 'MAPMAP1: the ME and PH representations are not equal!');
assert(norm(qld-PmfFromMG(alpha, A, (0:1:10)))<1e-12, 'MAPMAP1: qlDistr returns wrong queue length distribution!');
assert(norm(std-CdfFromME(beta, B, (0.:0.1:1.)))<1e-12, 'MAPMAP1: stDistr returns wrong sojourn time distribution!');
assert(norm((qlm-qlmFromMG)./qlm)<1e-12, 'MAPMAP1: qlMoms returns wrong queue length moments!');
assert(norm((stm-stmFromME)./stm)<1e-12, 'MAPMAP1: stMoms returns wrong sojourn time moments!');
IA = eye(size(D0,1));
IS = eye(size(S0,1));
BuToolsVerbose = false;
[gamma, G] = QBDQueue(kron(IA, S1), kron(D0, IS)+kron(IA, S0), kron(D1, IS), kron(D0, IS), 'stDistrME');
BuToolsVerbose = true;
msmall = MomentsFromME(beta, B, 5);
mlarge = MomentsFromME(gamma, G, 5);
assert(norm((msmall-mlarge)./msmall)<1e-12, 'MAPMAP1: Large and small model does not give the same results!');
disp('Input:');
disp('------');
delta = [0.5,0.1,0.4];
disp('delta = ');
disp(delta);
D = [-8., 1., 2.; 0., -6., 4.; 3., 0., -3.];
disp('D = ');
disp(D);
sigma = [0.2,0.7,0.1];
disp('sigma = ');
disp(sigma);
S = [-10., 4., 0.; 5., -7., 2.; 1., 2., -8.];
disp('S = ');
disp(S);
disp('D0 = D;:');
D0 = D;
disp('D1 = sum(-D,2)*delta;:');
D1 = sum(-D,2)*delta;
disp('S0 = S;:');
S0 = S;
disp('S1 = sum(-S,2)*sigma;:');
S1 = sum(-S,2)*sigma;
lambd = 1./MarginalMomentsFromMAP(D0, D1, 1);
disp('Test:');
disp('-----');
disp('[qld, qlm] = MAPMAP1(D0, D1, S0, S1, ''qlDistr'', (0:1:10), ''qlMoms'', 5);:');
[qld, qlm] = MAPMAP1(D0, D1, S0, S1, 'qlDistr', (0:1:10), 'qlMoms', 5);
disp('qld = ');
disp(qld);
disp('qlm = ');
disp(qlm);
disp('[alphap, Ap] = MAPMAP1(D0, D1, S0, S1, ''qlDistrDPH'');:');
[alphap, Ap] = MAPMAP1(D0, D1, S0, S1, 'qlDistrDPH');
disp('alphap = ');
disp(alphap);
disp('Ap = ');
disp(Ap);
disp('[alpha, A] = MAPMAP1(D0, D1, S0, S1, ''qlDistrMG'');:');
[alpha, A] = MAPMAP1(D0, D1, S0, S1, 'qlDistrMG');
disp('alpha = ');
disp(alpha);
disp('A = ');
disp(A);
disp('qldFromDPH = PmfFromDPH(alphap, Ap, (0:1:10));:');
qldFromDPH = PmfFromDPH(alphap, Ap, (0:1:10));
disp('qldFromDPH = ');
disp(qldFromDPH);
disp('qlmFromMG = MomentsFromMG(alpha, A, 5);:');
qlmFromMG = MomentsFromMG(alpha, A, 5);
disp('qlmFromMG = ');
disp(qlmFromMG);
disp('[std, stm] = MAPMAP1(D0, D1, S0, S1, ''stDistr'', (0.:0.1:1.), ''stMoms'', 5);:');
[std, stm] = MAPMAP1(D0, D1, S0, S1, 'stDistr', (0.:0.1:1.), 'stMoms', 5);
disp('std = ');
disp(std);
disp('stm = ');
disp(stm);
disp('[betap, Bp] = MAPMAP1(D0, D1, S0, S1, ''stDistrPH'');:');
[betap, Bp] = MAPMAP1(D0, D1, S0, S1, 'stDistrPH');
disp('betap = ');
disp(betap);
disp('Bp = ');
disp(Bp);
disp('[beta, B] = MAPMAP1(D0, D1, S0, S1, ''stDistrME'');:');
[beta, B] = MAPMAP1(D0, D1, S0, S1, 'stDistrME');
disp('beta = ');
disp(beta);
disp('B = ');
disp(B);
disp('stdFromPH = CdfFromPH(betap, Bp, (0.:0.1:1.));:');
stdFromPH = CdfFromPH(betap, Bp, (0.:0.1:1.));
disp('stdFromPH = ');
disp(stdFromPH);
disp('stmFromME = MomentsFromME(beta, B, 5);:');
stmFromME = MomentsFromME(beta, B, 5);
disp('stmFromME = ');
disp(stmFromME);
assert(CheckMGRepresentation(alpha, A), 'MAPMAP1: invalid MG representation of the queue length!');
assert(CheckMERepresentation(beta, B), 'MAPMAP1: invalid ME representation of the sojourn time!');
assert(CheckDPHRepresentation(alphap, Ap), 'MAPMAP1: invalid DPH representation of the queue length!');
assert(CheckPHRepresentation(betap, Bp), 'MAPMAP1: invalid PH representation of the sojourn time!');
assert(abs(qlm(1)-stm(1)*lambd)<1e-12, 'MAPMAP1: Little formula does not hold!');
assert(norm((MomentsFromDPH(alphap, Ap, 5)-qlmFromMG)./qlmFromMG)<1e-12, 'MAPMAP1: the MG and DPH representations are not equal!');
assert(norm((MomentsFromPH(betap, Bp, 5)-stmFromME)./stmFromME)<1e-12, 'MAPMAP1: the ME and PH representations are not equal!');
assert(norm(qld-PmfFromMG(alpha, A, (0:1:10)))<1e-12, 'MAPMAP1: qlDistr returns wrong queue length distribution!');
assert(norm(std-CdfFromME(beta, B, (0.:0.1:1.)))<1e-12, 'MAPMAP1: stDistr returns wrong sojourn time distribution!');
assert(norm((qlm-qlmFromMG)./qlm)<1e-12, 'MAPMAP1: qlMoms returns wrong queue length moments!');
assert(norm((stm-stmFromME)./stm)<1e-12, 'MAPMAP1: stMoms returns wrong sojourn time moments!');
IA = eye(size(D0,1));
IS = eye(size(S0,1));
BuToolsVerbose = false;
[gamma, G] = QBDQueue(kron(IA, S1), kron(D0, IS)+kron(IA, S0), kron(D1, IS), kron(D0, IS), 'stDistrME');
BuToolsVerbose = true;
msmall = MomentsFromME(beta, B, 5);
mlarge = MomentsFromME(gamma, G, 5);
assert(norm((msmall-mlarge)./msmall)<1e-12, 'MAPMAP1: Large and small model does not give the same results!');
disp('Input:');
disp('------');
D0 = [-8., 2.; 1., -3.];
disp('D0 = ');
disp(D0);
D1 = [1., 5.; 0., 2.];
disp('D1 = ');
disp(D1);
S0 = [-10., 4.; 0., -7.];
disp('S0 = ');
disp(S0);
S1 = [5., 1.; 4., 3.];
disp('S1 = ');
disp(S1);
lambd = 1./MarginalMomentsFromMAP(D0, D1, 1);
disp('Test:');
disp('-----');
disp('[qld, qlm] = MAPMAP1(D0, D1, S0, S1, ''qlDistr'', (0:1:10), ''qlMoms'', 5);:');
[qld, qlm] = MAPMAP1(D0, D1, S0, S1, 'qlDistr', (0:1:10), 'qlMoms', 5);
disp('qld = ');
disp(qld);
disp('qlm = ');
disp(qlm);
disp('[alphap, Ap] = MAPMAP1(D0, D1, S0, S1, ''qlDistrDPH'');:');
[alphap, Ap] = MAPMAP1(D0, D1, S0, S1, 'qlDistrDPH');
disp('alphap = ');
disp(alphap);
disp('Ap = ');
disp(Ap);
disp('[alpha, A] = MAPMAP1(D0, D1, S0, S1, ''qlDistrMG'');:');
[alpha, A] = MAPMAP1(D0, D1, S0, S1, 'qlDistrMG');
disp('alpha = ');
disp(alpha);
disp('A = ');
disp(A);
disp('qldFromDPH = PmfFromDPH(alphap, Ap, (0:1:10));:');
qldFromDPH = PmfFromDPH(alphap, Ap, (0:1:10));
disp('qldFromDPH = ');
disp(qldFromDPH);
disp('qlmFromMG = MomentsFromMG(alpha, A, 5);:');
qlmFromMG = MomentsFromMG(alpha, A, 5);
disp('qlmFromMG = ');
disp(qlmFromMG);
disp('[std, stm] = MAPMAP1(D0, D1, S0, S1, ''stDistr'', (0.:0.1:1.), ''stMoms'', 5);:');
[std, stm] = MAPMAP1(D0, D1, S0, S1, 'stDistr', (0.:0.1:1.), 'stMoms', 5);
disp('std = ');
disp(std);
disp('stm = ');
disp(stm);
disp('[betap, Bp] = MAPMAP1(D0, D1, S0, S1, ''stDistrPH'');:');
[betap, Bp] = MAPMAP1(D0, D1, S0, S1, 'stDistrPH');
disp('betap = ');
disp(betap);
disp('Bp = ');
disp(Bp);
disp('[beta, B] = MAPMAP1(D0, D1, S0, S1, ''stDistrME'');:');
[beta, B] = MAPMAP1(D0, D1, S0, S1, 'stDistrME');
disp('beta = ');
disp(beta);
disp('B = ');
disp(B);
disp('stdFromPH = CdfFromPH(betap, Bp, (0.:0.1:1.));:');
stdFromPH = CdfFromPH(betap, Bp, (0.:0.1:1.));
disp('stdFromPH = ');
disp(stdFromPH);
disp('stmFromME = MomentsFromME(beta, B, 5);:');
stmFromME = MomentsFromME(beta, B, 5);
disp('stmFromME = ');
disp(stmFromME);
assert(CheckMGRepresentation(alpha, A), 'MAPMAP1: invalid MG representation of the queue length!');
assert(CheckMERepresentation(beta, B), 'MAPMAP1: invalid ME representation of the sojourn time!');
assert(CheckDPHRepresentation(alphap, Ap), 'MAPMAP1: invalid DPH representation of the queue length!');
assert(CheckPHRepresentation(betap, Bp), 'MAPMAP1: invalid PH representation of the sojourn time!');
assert(abs(qlm(1)-stm(1)*lambd)<1e-12, 'MAPMAP1: Little formula does not hold!');
assert(norm((MomentsFromDPH(alphap, Ap, 5)-qlmFromMG)./qlmFromMG)<1e-12, 'MAPMAP1: the MG and DPH representations are not equal!');
assert(norm((MomentsFromPH(betap, Bp, 5)-stmFromME)./stmFromME)<1e-12, 'MAPMAP1: the ME and PH representations are not equal!');
assert(norm(qld-PmfFromMG(alpha, A, (0:1:10)))<1e-12, 'MAPMAP1: qlDistr returns wrong queue length distribution!');
assert(norm(std-CdfFromME(beta, B, (0.:0.1:1.)))<1e-12, 'MAPMAP1: stDistr returns wrong sojourn time distribution!');
assert(norm((qlm-qlmFromMG)./qlm)<1e-12, 'MAPMAP1: qlMoms returns wrong queue length moments!');
assert(norm((stm-stmFromME)./stm)<1e-12, 'MAPMAP1: stMoms returns wrong sojourn time moments!');
IA = eye(size(D0,1));
IS = eye(size(S0,1));
BuToolsVerbose = false;
[gamma, G] = QBDQueue(kron(IA, S1), kron(D0, IS)+kron(IA, S0), kron(D1, IS), kron(D0, IS), 'stDistrME');
BuToolsVerbose = true;
msmall = MomentsFromME(beta, B, 5);
mlarge = MomentsFromME(gamma, G, 5);
assert(norm((msmall-mlarge)./msmall)<1e-12, 'MAPMAP1: Large and small model does not give the same results!');
disp('Input:');
disp('------');
S0 = [-10., 4., 0.; 5., -7., 2.; 1., 2., -8.];
disp('S0 = ');
disp(S0);
S1 = [0., 0., 6.; 0., 0., 0.; 0., 3., 2.];
disp('S1 = ');
disp(S1);
D0 = [-8., 1., 2.; 0., -6., 4.; 3., 0., -3.];
disp('D0 = ');
disp(D0);
D1 = [4., 1., 0.; 0., 0., 2.; 0., 0., 0.];
disp('D1 = ');
disp(D1);
lambd = 1./MarginalMomentsFromMAP(D0, D1, 1);
disp('Test:');
disp('-----');
disp('[qld, qlm] = MAPMAP1(D0, D1, S0, S1, ''qlDistr'', (0:1:10), ''qlMoms'', 5);:');
[qld, qlm] = MAPMAP1(D0, D1, S0, S1, 'qlDistr', (0:1:10), 'qlMoms', 5);
disp('qld = ');
disp(qld);
disp('qlm = ');
disp(qlm);
disp('[alphap, Ap] = MAPMAP1(D0, D1, S0, S1, ''qlDistrDPH'');:');
[alphap, Ap] = MAPMAP1(D0, D1, S0, S1, 'qlDistrDPH');
disp('alphap = ');
disp(alphap);
disp('Ap = ');
disp(Ap);
disp('[alpha, A] = MAPMAP1(D0, D1, S0, S1, ''qlDistrMG'');:');
[alpha, A] = MAPMAP1(D0, D1, S0, S1, 'qlDistrMG');
disp('alpha = ');
disp(alpha);
disp('A = ');
disp(A);
disp('qldFromDPH = PmfFromDPH(alphap, Ap, (0:1:10));:');
qldFromDPH = PmfFromDPH(alphap, Ap, (0:1:10));
disp('qldFromDPH = ');
disp(qldFromDPH);
disp('qlmFromMG = MomentsFromMG(alpha, A, 5);:');
qlmFromMG = MomentsFromMG(alpha, A, 5);
disp('qlmFromMG = ');
disp(qlmFromMG);
disp('[std, stm] = MAPMAP1(D0, D1, S0, S1, ''stDistr'', (0.:0.1:1.), ''stMoms'', 5);:');
[std, stm] = MAPMAP1(D0, D1, S0, S1, 'stDistr', (0.:0.1:1.), 'stMoms', 5);
disp('std = ');
disp(std);
disp('stm = ');
disp(stm);
disp('[betap, Bp] = MAPMAP1(D0, D1, S0, S1, ''stDistrPH'');:');
[betap, Bp] = MAPMAP1(D0, D1, S0, S1, 'stDistrPH');
disp('betap = ');
disp(betap);
disp('Bp = ');
disp(Bp);
disp('[beta, B] = MAPMAP1(D0, D1, S0, S1, ''stDistrME'');:');
[beta, B] = MAPMAP1(D0, D1, S0, S1, 'stDistrME');
disp('beta = ');
disp(beta);
disp('B = ');
disp(B);
disp('stdFromPH = CdfFromPH(betap, Bp, (0.:0.1:1.));:');
stdFromPH = CdfFromPH(betap, Bp, (0.:0.1:1.));
disp('stdFromPH = ');
disp(stdFromPH);
disp('stmFromME = MomentsFromME(beta, B, 5);:');
stmFromME = MomentsFromME(beta, B, 5);
disp('stmFromME = ');
disp(stmFromME);
assert(CheckMGRepresentation(alpha, A), 'MAPMAP1: invalid MG representation of the queue length!');
assert(CheckMERepresentation(beta, B), 'MAPMAP1: invalid ME representation of the sojourn time!');
assert(CheckDPHRepresentation(alphap, Ap), 'MAPMAP1: invalid DPH representation of the queue length!');
assert(CheckPHRepresentation(betap, Bp), 'MAPMAP1: invalid PH representation of the sojourn time!');
assert(abs(qlm(1)-stm(1)*lambd)<1e-12, 'MAPMAP1: Little formula does not hold!');
assert(norm((MomentsFromDPH(alphap, Ap, 5)-qlmFromMG)./qlmFromMG)<1e-12, 'MAPMAP1: the MG and DPH representations are not equal!');
assert(norm((MomentsFromPH(betap, Bp, 5)-stmFromME)./stmFromME)<1e-12, 'MAPMAP1: the ME and PH representations are not equal!');
assert(norm(qld-PmfFromMG(alpha, A, (0:1:10)))<1e-12, 'MAPMAP1: qlDistr returns wrong queue length distribution!');
assert(norm(std-CdfFromME(beta, B, (0.:0.1:1.)))<1e-12, 'MAPMAP1: stDistr returns wrong sojourn time distribution!');
assert(norm((qlm-qlmFromMG)./qlm)<1e-12, 'MAPMAP1: qlMoms returns wrong queue length moments!');
assert(norm((stm-stmFromME)./stm)<1e-12, 'MAPMAP1: stMoms returns wrong sojourn time moments!');
IA = eye(size(D0,1));
IS = eye(size(S0,1));
BuToolsVerbose = false;
[gamma, G] = QBDQueue(kron(IA, S1), kron(D0, IS)+kron(IA, S0), kron(D1, IS), kron(D0, IS), 'stDistrME');
BuToolsVerbose = true;
msmall = MomentsFromME(beta, B, 5);
mlarge = MomentsFromME(gamma, G, 5);
assert(norm((msmall-mlarge)./msmall)<1e-12, 'MAPMAP1: Large and small model does not give the same results!');
disp('Input:');
disp('------');
D0 = [-8., 1., 2.; 0., -6., 4.; 3., 0., -3.];
disp('D0 = ');
disp(D0);
D1 = [4., 1., 0.; 0., 0., 2.; 0., 0., 0.];
disp('D1 = ');
disp(D1);
sigma = [0.2,0.7,0.1];
disp('sigma = ');
disp(sigma);
S = [-10., 4., 0.; 5., -7., 2.; 1., 2., -8.];
disp('S = ');
disp(S);
disp('S0 = S;:');
S0 = S;
disp('S1 = sum(-S,2)*sigma;:');
S1 = sum(-S,2)*sigma;
lambd = 1./MarginalMomentsFromMAP(D0, D1, 1);
disp('Test:');
disp('-----');
disp('[qld, qlm] = MAPMAP1(D0, D1, S0, S1, ''qlDistr'', (0:1:10), ''qlMoms'', 5);:');
[qld, qlm] = MAPMAP1(D0, D1, S0, S1, 'qlDistr', (0:1:10), 'qlMoms', 5);
disp('qld = ');
disp(qld);
disp('qlm = ');
disp(qlm);
disp('[alphap, Ap] = MAPMAP1(D0, D1, S0, S1, ''qlDistrDPH'');:');
[alphap, Ap] = MAPMAP1(D0, D1, S0, S1, 'qlDistrDPH');
disp('alphap = ');
disp(alphap);
disp('Ap = ');
disp(Ap);
disp('[alpha, A] = MAPMAP1(D0, D1, S0, S1, ''qlDistrMG'');:');
[alpha, A] = MAPMAP1(D0, D1, S0, S1, 'qlDistrMG');
disp('alpha = ');
disp(alpha);
disp('A = ');
disp(A);
disp('qldFromDPH = PmfFromDPH(alphap, Ap, (0:1:10));:');
qldFromDPH = PmfFromDPH(alphap, Ap, (0:1:10));
disp('qldFromDPH = ');
disp(qldFromDPH);
disp('qlmFromMG = MomentsFromMG(alpha, A, 5);:');
qlmFromMG = MomentsFromMG(alpha, A, 5);
disp('qlmFromMG = ');
disp(qlmFromMG);
disp('[std, stm] = MAPMAP1(D0, D1, S0, S1, ''stDistr'', (0.:0.1:1.), ''stMoms'', 5);:');
[std, stm] = MAPMAP1(D0, D1, S0, S1, 'stDistr', (0.:0.1:1.), 'stMoms', 5);
disp('std = ');
disp(std);
disp('stm = ');
disp(stm);
disp('[betap, Bp] = MAPMAP1(D0, D1, S0, S1, ''stDistrPH'');:');
[betap, Bp] = MAPMAP1(D0, D1, S0, S1, 'stDistrPH');
disp('betap = ');
disp(betap);
disp('Bp = ');
disp(Bp);
disp('[beta, B] = MAPMAP1(D0, D1, S0, S1, ''stDistrME'');:');
[beta, B] = MAPMAP1(D0, D1, S0, S1, 'stDistrME');
disp('beta = ');
disp(beta);
disp('B = ');
disp(B);
disp('stdFromPH = CdfFromPH(betap, Bp, (0.:0.1:1.));:');
stdFromPH = CdfFromPH(betap, Bp, (0.:0.1:1.));
disp('stdFromPH = ');
disp(stdFromPH);
disp('stmFromME = MomentsFromME(beta, B, 5);:');
stmFromME = MomentsFromME(beta, B, 5);
disp('stmFromME = ');
disp(stmFromME);
assert(CheckMGRepresentation(alpha, A), 'MAPMAP1: invalid MG representation of the queue length!');
assert(CheckMERepresentation(beta, B), 'MAPMAP1: invalid ME representation of the sojourn time!');
assert(CheckDPHRepresentation(alphap, Ap), 'MAPMAP1: invalid DPH representation of the queue length!');
assert(CheckPHRepresentation(betap, Bp), 'MAPMAP1: invalid PH representation of the sojourn time!');
assert(abs(qlm(1)-stm(1)*lambd)<1e-12, 'MAPMAP1: Little formula does not hold!');
assert(norm((MomentsFromDPH(alphap, Ap, 5)-qlmFromMG)./qlmFromMG)<1e-12, 'MAPMAP1: the MG and DPH representations are not equal!');
assert(norm((MomentsFromPH(betap, Bp, 5)-stmFromME)./stmFromME)<1e-12, 'MAPMAP1: the ME and PH representations are not equal!');
assert(norm(qld-PmfFromMG(alpha, A, (0:1:10)))<1e-12, 'MAPMAP1: qlDistr returns wrong queue length distribution!');
assert(norm(std-CdfFromME(beta, B, (0.:0.1:1.)))<1e-12, 'MAPMAP1: stDistr returns wrong sojourn time distribution!');
assert(norm((qlm-qlmFromMG)./qlm)<1e-12, 'MAPMAP1: qlMoms returns wrong queue length moments!');
assert(norm((stm-stmFromME)./stm)<1e-12, 'MAPMAP1: stMoms returns wrong sojourn time moments!');
IA = eye(size(D0,1));
IS = eye(size(S0,1));
BuToolsVerbose = false;
[gamma, G] = QBDQueue(kron(IA, S1), kron(D0, IS)+kron(IA, S0), kron(D1, IS), kron(D0, IS), 'stDistrME');
BuToolsVerbose = true;
msmall = MomentsFromME(beta, B, 5);
mlarge = MomentsFromME(gamma, G, 5);
assert(norm((msmall-mlarge)./msmall)<1e-12, 'MAPMAP1: Large and small model do not give the same results!');
disp('========================================')
disp('Testing BuTools function MMAPPH1PRPR')
disp('Input:');
disp('------');
D0 = [-5.49, 0., 1.15, 0.; 0., -2.29, 0., 0.; 0., 0.08, -1.32, 0.; 0.72, 1.17, 0.7, -7.07];
disp('D0 = ');
disp(D0);
D1 = [0.25, 0.38, 0.64, 0.; 0., 0., 0., 1.09; 0., 1.24, 0., 0.; 0.37, 0., 0., 0.];
disp('D1 = ');
disp(D1);
D2 = [0.3, 1.0, 0., 0.48; 0., 0.2, 0., 0.; 0., 0., 0., 0.; 0.61, 0., 0., 0.2];
disp('D2 = ');
disp(D2);
D3 = [0., 0.98, 0., 0.31; 0., 0., 1.0, 0.; 0., 0., 0., 0.; 1.1, 0.84, 0.33, 1.03];
disp('D3 = ');
disp(D3);
sigma3 = [0.83333,0.11404,0.05263];
disp('sigma3 = ');
disp(sigma3);
S3 = [-3., 0., 0.; 0.73077, -0.73077, 0.; 0., 0.5, -0.5];
disp('S3 = ');
disp(S3);
sigma2 = [1.];
disp('sigma2 = ');
disp(sigma2);
S2 = [-2.];
disp('S2 = ');
disp(S2);
sigma1 = [0.25,0.75];
disp('sigma1 = ');
disp(sigma1);
S1 = [-2.5, 2.5; 0., -10.];
disp('S1 = ');
disp(S1);
disp('Test:');
disp('-----');
disp('[qlm, qld] = MMAPPH1PRPR({D0, D1, D2, D3}, {sigma1, sigma2, sigma3}, {S1, S2, S3}, ''qlMoms'', 3, ''qlDistr'', 500);:');
[qlm, qld] = MMAPPH1PRPR({D0, D1, D2, D3}, {sigma1, sigma2, sigma3}, {S1, S2, S3}, 'qlMoms', 3, 'qlDistr', 500);
momFromDistr = [(0:1:499);(0:1:499).^2;(0:1:499).^3]*qld;
assert(norm((momFromDistr-qlm)./qlm)<0.001, 'MMAPPH1PRPR: queue length moments and queue length distribution are not consistent!');
distrPoints = [1., 5., 10.];
disp('[stm, std] = MMAPPH1PRPR({D0, D1, D2, D3}, {sigma1, sigma2, sigma3}, {S1, S2, S3}, ''stMoms'', 3, ''stDistr'', distrPoints);:');
[stm, std] = MMAPPH1PRPR({D0, D1, D2, D3}, {sigma1, sigma2, sigma3}, {S1, S2, S3}, 'stMoms', 3, 'stDistr', distrPoints);
disp('stm = ');
disp(stm);
disp('std = ');
disp(std);
assert(min(min(std))>=0&&max(max(std))<=1&&all(all(diff(std)>=0)), 'MMAPPH1PRPR: invalid sojourn time distribution!');
lambda1 = 1./MarginalMomentsFromMAP(D0+D2+D3, D1, 1);
lambda2 = 1./MarginalMomentsFromMAP(D0+D1+D3, D2, 1);
lambda3 = 1./MarginalMomentsFromMAP(D0+D1+D2, D3, 1);
assert(abs(qlm(1, 1)-stm(1, 1)*lambda1)<1e-12, 'MMAPPH1PRPR: Little formula does not hold for class 1!');
assert(abs(qlm(1, 2)-stm(1, 2)*lambda2)<1e-12, 'MMAPPH1PRPR: Little formula does not hold for class 2!');
assert(abs(qlm(1, 3)-stm(1, 3)*lambda3)<1e-12, 'MMAPPH1PRPR: Little formula does not hold for class 3!');
disp('Input:');
disp('------');
D0 = [-5.49, 0., 1.15, 0.; 0., -2.29, 0., 0.; 0., 0.08, -1.32, 0.; 0.72, 1.17, 0.7, -7.07];
disp('D0 = ');
disp(D0);
D1 = [0.25, 0.38, 0.64, 0.; 0., 0., 0., 1.09; 0., 1.24, 0., 0.; 0.37, 0., 0., 0.];
disp('D1 = ');
disp(D1);
D2 = [0.3, 1.0, 0., 0.48; 0., 0.2, 0., 0.; 0., 0., 0., 0.; 0.61, 0., 0., 0.2];
disp('D2 = ');
disp(D2);
D3 = [0., 0.98, 0., 0.31; 0., 0., 1.0, 0.; 0., 0., 0., 0.; 1.1, 0.84, 0.33, 1.03];
disp('D3 = ');
disp(D3);
sigma3 = [0.16667,0.83333];
disp('sigma3 = ');
disp(sigma3);
S3 = [-0.5, 0.5; 0., -3.];
disp('S3 = ');
disp(S3);
sigma2 = [0.58824,0.41176];
disp('sigma2 = ');
disp(sigma2);
S2 = [-2.3529, 2.3529; 0., -4.];
disp('S2 = ');
disp(S2);
sigma1 = [0.25,0.75];
disp('sigma1 = ');
disp(sigma1);
S1 = [-2.5, 2.5; 0., -10.];
disp('S1 = ');
disp(S1);
disp('Test:');
disp('-----');
disp('[qlm, qld] = MMAPPH1PRPR({D0, D1, D2, D3}, {sigma1, sigma2, sigma3}, {S1, S2, S3}, ''qlMoms'', 3, ''qlDistr'', 500);:');
[qlm, qld] = MMAPPH1PRPR({D0, D1, D2, D3}, {sigma1, sigma2, sigma3}, {S1, S2, S3}, 'qlMoms', 3, 'qlDistr', 500);
momFromDistr = [(0:1:499);(0:1:499).^2;(0:1:499).^3]*qld;
assert(norm((momFromDistr-qlm)./qlm)<0.001, 'MMAPPH1PRPR: queue length moments and queue length distribution are not consistent!');
distrPoints = [1., 5., 10.];
disp('[stm, std] = MMAPPH1PRPR({D0, D1, D2, D3}, {sigma1, sigma2, sigma3}, {S1, S2, S3}, ''stMoms'', 3, ''stDistr'', distrPoints);:');
[stm, std] = MMAPPH1PRPR({D0, D1, D2, D3}, {sigma1, sigma2, sigma3}, {S1, S2, S3}, 'stMoms', 3, 'stDistr', distrPoints);
disp('stm = ');
disp(stm);
disp('std = ');
disp(std);
assert(min(min(std))>=0&&max(max(std))<=1&&all(all(diff(std)>=0)), 'MMAPPH1PRPR: invalid sojourn time distribution!');
lambda1 = 1./MarginalMomentsFromMAP(D0+D2+D3, D1, 1);
lambda2 = 1./MarginalMomentsFromMAP(D0+D1+D3, D2, 1);
lambda3 = 1./MarginalMomentsFromMAP(D0+D1+D2, D3, 1);
assert(abs(qlm(1, 1)-stm(1, 1)*lambda1)<1e-12, 'MMAPPH1PRPR: Little formula does not hold for class 1!');
assert(abs(qlm(1, 2)-stm(1, 2)*lambda2)<1e-12, 'MMAPPH1PRPR: Little formula does not hold for class 2!');
assert(abs(qlm(1, 3)-stm(1, 3)*lambda3)<1e-12, 'MMAPPH1PRPR: Little formula does not hold for class 3!');
disp('========================================')
disp('Testing BuTools function MMAPPH1NPPR')
disp('Input:');
disp('------');
D0 = [-5.49, 0., 1.15, 0.; 0., -2.29, 0., 0.; 0., 0.08, -1.32, 0.; 0.72, 1.17, 0.7, -7.07];
disp('D0 = ');
disp(D0);
D1 = [0.25, 0.38, 0.64, 0.; 0., 0., 0., 1.09; 0., 1.24, 0., 0.; 0.37, 0., 0., 0.];
disp('D1 = ');
disp(D1);
D2 = [0.3, 1.0, 0., 0.48; 0., 0.2, 0., 0.; 0., 0., 0., 0.; 0.61, 0., 0., 0.2];
disp('D2 = ');
disp(D2);
D3 = [0., 0.98, 0., 0.31; 0., 0., 1.0, 0.; 0., 0., 0., 0.; 1.1, 0.84, 0.33, 1.03];
disp('D3 = ');
disp(D3);
sigma3 = [0.83333,0.11404,0.05263];
disp('sigma3 = ');
disp(sigma3);
S3 = [-3., 0., 0.; 0.73077, -0.73077, 0.; 0., 0.5, -0.5];
disp('S3 = ');
disp(S3);
sigma2 = [1.];
disp('sigma2 = ');
disp(sigma2);
S2 = [-2.];
disp('S2 = ');
disp(S2);
sigma1 = [0.25,0.75];
disp('sigma1 = ');
disp(sigma1);
S1 = [-2.5, 2.5; 0., -10.];
disp('S1 = ');
disp(S1);
disp('Test:');
disp('-----');
disp('[qlm, qld] = MMAPPH1NPPR({D0, D1, D2, D3}, {sigma1, sigma2, sigma3}, {S1, S2, S3}, ''qlMoms'', 3, ''qlDistr'', 500);:');
[qlm, qld] = MMAPPH1NPPR({D0, D1, D2, D3}, {sigma1, sigma2, sigma3}, {S1, S2, S3}, 'qlMoms', 3, 'qlDistr', 500);
momFromDistr = [(0:1:499);(0:1:499).^2;(0:1:499).^3]*qld;
assert(norm((momFromDistr-qlm)./qlm)<0.001, 'MMAPPH1NPPR: queue length moments and queue length distribution are not consistent!');
distrPoints = [1., 5., 10.];
disp('[stm, std] = MMAPPH1NPPR({D0, D1, D2, D3}, {sigma1, sigma2, sigma3}, {S1, S2, S3}, ''stMoms'', 3, ''stDistr'', distrPoints);:');
[stm, std] = MMAPPH1NPPR({D0, D1, D2, D3}, {sigma1, sigma2, sigma3}, {S1, S2, S3}, 'stMoms', 3, 'stDistr', distrPoints);
disp('stm = ');
disp(stm);
disp('std = ');
disp(std);
assert(min(min(std))>=0&&max(max(std))<=1&&all(all(diff(std)>=0)), 'MMAPPH1NPPR: invalid sojourn time distribution!');
lambda1 = 1./MarginalMomentsFromMAP(D0+D2+D3, D1, 1);
lambda2 = 1./MarginalMomentsFromMAP(D0+D1+D3, D2, 1);
lambda3 = 1./MarginalMomentsFromMAP(D0+D1+D2, D3, 1);
assert(abs(qlm(1, 1)-stm(1, 1)*lambda1)<1e-12, 'MMAPPH1NPPR: Little formula does not hold for class 1!');
assert(abs(qlm(1, 2)-stm(1, 2)*lambda2)<1e-12, 'MMAPPH1NPPR: Little formula does not hold for class 2!');
assert(abs(qlm(1, 3)-stm(1, 3)*lambda3)<1e-12, 'MMAPPH1NPPR: Little formula does not hold for class 3!');
disp('Input:');
disp('------');
D0 = [-5.49, 0., 1.15, 0.; 0., -2.29, 0., 0.; 0., 0.08, -1.32, 0.; 0.72, 1.17, 0.7, -7.07];
disp('D0 = ');
disp(D0);
D1 = [0.25, 0.38, 0.64, 0.; 0., 0., 0., 1.09; 0., 1.24, 0., 0.; 0.37, 0., 0., 0.];
disp('D1 = ');
disp(D1);
D2 = [0.3, 1.0, 0., 0.48; 0., 0.2, 0., 0.; 0., 0., 0., 0.; 0.61, 0., 0., 0.2];
disp('D2 = ');
disp(D2);
D3 = [0., 0.98, 0., 0.31; 0., 0., 1.0, 0.; 0., 0., 0., 0.; 1.1, 0.84, 0.33, 1.03];
disp('D3 = ');
disp(D3);
sigma3 = [0.16667,0.83333];
disp('sigma3 = ');
disp(sigma3);
S3 = [-0.5, 0.5; 0., -3.];
disp('S3 = ');
disp(S3);
sigma2 = [0.58824,0.41176];
disp('sigma2 = ');
disp(sigma2);
S2 = [-2.3529, 2.3529; 0., -4.];
disp('S2 = ');
disp(S2);
sigma1 = [0.25,0.75];
disp('sigma1 = ');
disp(sigma1);
S1 = [-2.5, 2.5; 0., -10.];
disp('S1 = ');
disp(S1);
disp('Test:');
disp('-----');
disp('[qlm, qld] = MMAPPH1NPPR({D0, D1, D2, D3}, {sigma1, sigma2, sigma3}, {S1, S2, S3}, ''qlMoms'', 3, ''qlDistr'', 500);:');
[qlm, qld] = MMAPPH1NPPR({D0, D1, D2, D3}, {sigma1, sigma2, sigma3}, {S1, S2, S3}, 'qlMoms', 3, 'qlDistr', 500);
momFromDistr = [(0:1:499);(0:1:499).^2;(0:1:499).^3]*qld;
assert(norm((momFromDistr-qlm)./qlm)<0.001, 'MMAPPH1NPPR: queue length moments and queue length distribution are not consistent!');
distrPoints = [1., 5., 10.];
disp('[stm, std] = MMAPPH1NPPR({D0, D1, D2, D3}, {sigma1, sigma2, sigma3}, {S1, S2, S3}, ''stMoms'', 3, ''stDistr'', distrPoints);:');
[stm, std] = MMAPPH1NPPR({D0, D1, D2, D3}, {sigma1, sigma2, sigma3}, {S1, S2, S3}, 'stMoms', 3, 'stDistr', distrPoints);
disp('stm = ');
disp(stm);
disp('std = ');
disp(std);
assert(min(min(std))>=0&&max(max(std))<=1&&all(all(diff(std)>=0)), 'MMAPPH1NPPR: invalid sojourn time distribution!');
lambda1 = 1./MarginalMomentsFromMAP(D0+D2+D3, D1, 1);
lambda2 = 1./MarginalMomentsFromMAP(D0+D1+D3, D2, 1);
lambda3 = 1./MarginalMomentsFromMAP(D0+D1+D2, D3, 1);
assert(abs(qlm(1, 1)-stm(1, 1)*lambda1)<1e-12, 'MMAPPH1NPPR: Little formula does not hold for class 1!');
assert(abs(qlm(1, 2)-stm(1, 2)*lambda2)<1e-12, 'MMAPPH1NPPR: Little formula does not hold for class 2!');
assert(abs(qlm(1, 3)-stm(1, 3)*lambda3)<1e-12, 'MMAPPH1NPPR: Little formula does not hold for class 3!');
disp('========================================')
disp('Testing BuTools function FluidQueue')
disp('Input:');
disp('------');
Q = [-9., 2., 4., 0., 1., 2.; 6., -25., 5., 3., 7., 4.; 1., 3., -4., 0., 0., 0.; 0., 0., 0., -8., 3., 5.; 7., 3., 0., 2., -13., 1.; 7., 8., 0., 3., 8., -26.];
disp('Q = ');
disp(Q);
vRin = [4.,2.,1.,0.,0.,3.];
disp('vRin = ');
disp(vRin);
vRout = [6.,2.,0.,0.,3.,2.];
disp('vRout = ');
disp(vRout);
disp('Rin = diag(vRin);:');
Rin = diag(vRin);
disp('Rout = diag(vRout);:');
Rout = diag(vRout);
lambd = sum(CTMCSolve(Q)*Rin);
disp('Test:');
disp('-----');
disp('[qld, qlm] = FluidQueue(Q, Rin, Rout, ''qlDistr'', (0.:0.1:1.), ''qlMoms'', 5);:');
[qld, qlm] = FluidQueue(Q, Rin, Rout, 'qlDistr', (0.:0.1:1.), 'qlMoms', 5);
disp('qld = ');
disp(qld);
disp('qlm = ');
disp(qlm);
disp('[alphap, Ap] = FluidQueue(Q, Rin, Rout, ''qlDistrPH'');:');
[alphap, Ap] = FluidQueue(Q, Rin, Rout, 'qlDistrPH');
disp('alphap = ');
disp(alphap);
disp('Ap = ');
disp(Ap);
disp('[alpha, A] = FluidQueue(Q, Rin, Rout, ''qlDistrME'');:');
[alpha, A] = FluidQueue(Q, Rin, Rout, 'qlDistrME');
disp('alpha = ');
disp(alpha);
disp('A = ');
disp(A);
disp('qldFromPH = CdfFromPH(alphap, Ap, (0.:0.1:1.));:');
qldFromPH = CdfFromPH(alphap, Ap, (0.:0.1:1.));
disp('qldFromPH = ');
disp(qldFromPH);
disp('qlmFromME = MomentsFromME(alpha, A, 5);:');
qlmFromME = MomentsFromME(alpha, A, 5);
disp('qlmFromME = ');
disp(qlmFromME);
disp('[std, stm] = FluidQueue(Q, Rin, Rout, ''stDistr'', (0.:0.1:1.), ''stMoms'', 5);:');
[std, stm] = FluidQueue(Q, Rin, Rout, 'stDistr', (0.:0.1:1.), 'stMoms', 5);
disp('std = ');
disp(std);
disp('stm = ');
disp(stm);
disp('[betap, Bp] = FluidQueue(Q, Rin, Rout, ''stDistrPH'');:');
[betap, Bp] = FluidQueue(Q, Rin, Rout, 'stDistrPH');
disp('betap = ');
disp(betap);
disp('Bp = ');
disp(Bp);
disp('[beta, B] = FluidQueue(Q, Rin, Rout, ''stDistrME'');:');
[beta, B] = FluidQueue(Q, Rin, Rout, 'stDistrME');
disp('beta = ');
disp(beta);
disp('B = ');
disp(B);
disp('stdFromPH = CdfFromPH(betap, Bp, (0.:0.1:1.));:');
stdFromPH = CdfFromPH(betap, Bp, (0.:0.1:1.));
disp('stdFromPH = ');
disp(stdFromPH);
disp('stmFromME = MomentsFromME(beta, B, 5);:');
stmFromME = MomentsFromME(beta, B, 5);
disp('stmFromME = ');
disp(stmFromME);
assert(CheckMERepresentation(alpha, A), 'FluidQueue: invalid ME representation of the queue length!');
assert(CheckMERepresentation(beta, B), 'FluidQueue: invalid ME representation of the sojourn time!');
assert(CheckPHRepresentation(alphap, Ap), 'FluidQueue: invalid PH representation of the queue length!');
assert(CheckPHRepresentation(betap, Bp), 'FluidQueue: invalid PH representation of the sojourn time!');
assert(abs(qlm(1)-stm(1)*lambd)<1e-12, 'FluidQueue: Little formula does not hold!');
assert(norm((MomentsFromPH(alphap, Ap, 5)-qlmFromME)./qlmFromME)<1e-12, 'FluidQueue: the ME and PH representations are not equal!');
assert(norm((MomentsFromPH(betap, Bp, 5)-stmFromME)./stmFromME)<1e-12, 'FluidQueue: the ME and PH representations are not equal!');
assert(norm(qld-CdfFromME(alpha, A, (0.:0.1:1.)))<1e-12, 'FluidQueue: qlDistr returns wrong queue length distribution!');
assert(norm(std-CdfFromME(beta, B, (0.:0.1:1.)))<1e-12, 'FluidQueue: stDistr returns wrong sojourn time distribution!');
assert(norm((qlm-qlmFromME)./qlm)<1e-12, 'FluidQueue: qlMoms returns wrong queue length moments!');
assert(norm((stm-stmFromME)./stm)<1e-12, 'FluidQueue: stMoms returns wrong sojourn time moments!');
disp('========================================')
disp('Testing BuTools function FluFluQueue')
disp('Input:');
disp('------');
Qin = [-2., 1., 1.; 2., -5., 3.; 4., 0., -4.];
disp('Qin = ');
disp(Qin);
vRin = [3.,7.,0.];
disp('vRin = ');
disp(vRin);
disp('Rin = diag(vRin);:');
Rin = diag(vRin);
Qout = [-4., 1., 3.; 6., -8., 2.; 3., 7., -10.];
disp('Qout = ');
disp(Qout);
vRout = [1.,7.,15.];
disp('vRout = ');
disp(vRout);
disp('Rout = diag(vRout);:');
Rout = diag(vRout);
lambd = sum(CTMCSolve(Qin)*Rin);
disp('Test:');
disp('-----');
disp('[qld, qlm] = FluFluQueue(Qin, Rin, Qout, Rout, false, ''qlDistr'', (0.:0.1:1.), ''qlMoms'', 5);:');
[qld, qlm] = FluFluQueue(Qin, Rin, Qout, Rout, false, 'qlDistr', (0.:0.1:1.), 'qlMoms', 5);
disp('qld = ');
disp(qld);
disp('qlm = ');
disp(qlm);
disp('[alphap, Ap] = FluFluQueue(Qin, Rin, Qout, Rout, false, ''qlDistrPH'');:');
[alphap, Ap] = FluFluQueue(Qin, Rin, Qout, Rout, false, 'qlDistrPH');
disp('alphap = ');
disp(alphap);
disp('Ap = ');
disp(Ap);
disp('[alpha, A] = FluFluQueue(Qin, Rin, Qout, Rout, false, ''qlDistrME'');:');
[alpha, A] = FluFluQueue(Qin, Rin, Qout, Rout, false, 'qlDistrME');
disp('alpha = ');
disp(alpha);
disp('A = ');
disp(A);
disp('qldFromPH = CdfFromPH(alphap, Ap, (0.:0.1:1.));:');
qldFromPH = CdfFromPH(alphap, Ap, (0.:0.1:1.));
disp('qldFromPH = ');
disp(qldFromPH);
disp('qlmFromME = MomentsFromME(alpha, A, 5);:');
qlmFromME = MomentsFromME(alpha, A, 5);
disp('qlmFromME = ');
disp(qlmFromME);
disp('[std, stm] = FluFluQueue(Qin, Rin, Qout, Rout, false, ''stDistr'', (0.:0.1:1.), ''stMoms'', 5);:');
[std, stm] = FluFluQueue(Qin, Rin, Qout, Rout, false, 'stDistr', (0.:0.1:1.), 'stMoms', 5);
disp('std = ');
disp(std);
disp('stm = ');
disp(stm);
disp('[betap, Bp] = FluFluQueue(Qin, Rin, Qout, Rout, false, ''stDistrPH'');:');
[betap, Bp] = FluFluQueue(Qin, Rin, Qout, Rout, false, 'stDistrPH');
disp('betap = ');
disp(betap);
disp('Bp = ');
disp(Bp);
disp('[beta, B] = FluFluQueue(Qin, Rin, Qout, Rout, false, ''stDistrME'');:');
[beta, B] = FluFluQueue(Qin, Rin, Qout, Rout, false, 'stDistrME');
disp('beta = ');
disp(beta);
disp('B = ');
disp(B);
disp('stdFromPH = CdfFromPH(betap, Bp, (0.:0.1:1.));:');
stdFromPH = CdfFromPH(betap, Bp, (0.:0.1:1.));
disp('stdFromPH = ');
disp(stdFromPH);
disp('stmFromME = MomentsFromME(beta, B, 5);:');
stmFromME = MomentsFromME(beta, B, 5);
disp('stmFromME = ');
disp(stmFromME);
assert(CheckMERepresentation(alpha, A), 'FluFluQueue: invalid ME representation of the queue length!');
assert(CheckMERepresentation(beta, B), 'FluFluQueue: invalid ME representation of the sojourn time!');
assert(CheckPHRepresentation(alphap, Ap), 'FluFluQueue: invalid PH representation of the queue length!');
assert(CheckPHRepresentation(betap, Bp), 'FluFluQueue: invalid PH representation of the sojourn time!');
assert(abs(qlm(1)-stm(1)*lambd)<1e-12, 'FluFluQueue: Little formula does not hold!');
assert(norm((MomentsFromPH(alphap, Ap, 5)-qlmFromME)./qlmFromME)<1e-12, 'FluFluQueue: the ME and PH representations are not equal!');
assert(norm((MomentsFromPH(betap, Bp, 5)-stmFromME)./stmFromME)<1e-12, 'FluFluQueue: the ME and PH representations are not equal!');
assert(norm(qld-CdfFromME(alpha, A, (0.:0.1:1.)))<1e-12, 'FluFluQueue: qlDistr returns wrong queue length distribution!');
assert(norm(std-CdfFromME(beta, B, (0.:0.1:1.)))<1e-12, 'FluFluQueue: stDistr returns wrong sojourn time distribution!');
assert(norm((qlm-qlmFromME)./qlm)<1e-12, 'FluFluQueue: qlMoms returns wrong queue length moments!');
assert(norm((stm-stmFromME)./stm)<1e-12, 'FluFluQueue: stMoms returns wrong sojourn time moments!');
Iin = eye(size(Qin,1));
Iout = eye(size(Qout,1));
BuToolsVerbose = false;
[gamma, G] = FluidQueue(kron(Qin, Iout)+kron(Iin, Qout), kron(Rin, Iout), kron(Iin, Rout), 'stDistrME');
BuToolsVerbose = true;
msmall = MomentsFromME(beta, B, 5);
mlarge = MomentsFromME(gamma, G, 5);
assert(norm((msmall-mlarge)./msmall)<1e-12, 'FluFluQueue: Large and small model do not give the same results!');
disp('Test:');
disp('-----');
disp('[qld, qlm] = FluFluQueue(Qin, Rin, Qout, Rout, true, ''qlDistr'', (0.:0.1:1.), ''qlMoms'', 5);:');
[qld, qlm] = FluFluQueue(Qin, Rin, Qout, Rout, true, 'qlDistr', (0.:0.1:1.), 'qlMoms', 5);
disp('qld = ');
disp(qld);
disp('qlm = ');
disp(qlm);
disp('[alphap, Ap] = FluFluQueue(Qin, Rin, Qout, Rout, true, ''qlDistrPH'');:');
[alphap, Ap] = FluFluQueue(Qin, Rin, Qout, Rout, true, 'qlDistrPH');
disp('alphap = ');
disp(alphap);
disp('Ap = ');
disp(Ap);
disp('[alpha, A] = FluFluQueue(Qin, Rin, Qout, Rout, true, ''qlDistrME'');:');
[alpha, A] = FluFluQueue(Qin, Rin, Qout, Rout, true, 'qlDistrME');
disp('alpha = ');
disp(alpha);
disp('A = ');
disp(A);
disp('qldFromPH = CdfFromPH(alphap, Ap, (0.:0.1:1.));:');
qldFromPH = CdfFromPH(alphap, Ap, (0.:0.1:1.));
disp('qldFromPH = ');
disp(qldFromPH);
disp('qlmFromME = MomentsFromME(alpha, A, 5);:');
qlmFromME = MomentsFromME(alpha, A, 5);
disp('qlmFromME = ');
disp(qlmFromME);
disp('[std, stm] = FluFluQueue(Qin, Rin, Qout, Rout, true, ''stDistr'', (0.:0.1:1.), ''stMoms'', 5);:');
[std, stm] = FluFluQueue(Qin, Rin, Qout, Rout, true, 'stDistr', (0.:0.1:1.), 'stMoms', 5);
disp('std = ');
disp(std);
disp('stm = ');
disp(stm);
disp('[betap, Bp] = FluFluQueue(Qin, Rin, Qout, Rout, true, ''stDistrPH'');:');
[betap, Bp] = FluFluQueue(Qin, Rin, Qout, Rout, true, 'stDistrPH');
disp('betap = ');
disp(betap);
disp('Bp = ');
disp(Bp);
disp('[beta, B] = FluFluQueue(Qin, Rin, Qout, Rout, true, ''stDistrME'');:');
[beta, B] = FluFluQueue(Qin, Rin, Qout, Rout, true, 'stDistrME');
disp('beta = ');
disp(beta);
disp('B = ');
disp(B);
disp('stdFromPH = CdfFromPH(betap, Bp, (0.:0.1:1.));:');
stdFromPH = CdfFromPH(betap, Bp, (0.:0.1:1.));
disp('stdFromPH = ');
disp(stdFromPH);
disp('stmFromME = MomentsFromME(beta, B, 5);:');
stmFromME = MomentsFromME(beta, B, 5);
disp('stmFromME = ');
disp(stmFromME);
assert(CheckMERepresentation(alpha, A), 'FluFluQueue: invalid ME representation of the queue length!');
assert(CheckMERepresentation(beta, B), 'FluFluQueue: invalid ME representation of the sojourn time!');
assert(CheckPHRepresentation(alphap, Ap), 'FluFluQueue: invalid PH representation of the queue length!');
assert(CheckPHRepresentation(betap, Bp), 'FluFluQueue: invalid PH representation of the sojourn time!');
assert(abs(qlm(1)-stm(1)*lambd)<1e-12, 'FluFluQueue: Little formula does not hold!');
assert(norm((MomentsFromPH(alphap, Ap, 5)-qlmFromME)./qlmFromME)<1e-12, 'FluFluQueue: the ME and PH representations are not equal!');
assert(norm((MomentsFromPH(betap, Bp, 5)-stmFromME)./stmFromME)<1e-12, 'FluFluQueue: the ME and PH representations are not equal!');
assert(norm(qld-CdfFromME(alpha, A, (0.:0.1:1.)))<1e-12, 'FluFluQueue: qlDistr returns wrong queue length distribution!');
assert(norm(std-CdfFromME(beta, B, (0.:0.1:1.)))<1e-12, 'FluFluQueue: stDistr returns wrong sojourn time distribution!');
assert(norm((qlm-qlmFromME)./qlm)<1e-12, 'FluFluQueue: qlMoms returns wrong queue length moments!');
assert(norm((stm-stmFromME)./stm)<1e-12, 'FluFluQueue: stMoms returns wrong sojourn time moments!');
Iin = eye(size(Qin,1));
Iout = eye(size(Qout,1));
BuToolsVerbose = false;
[gamma, G] = FluidQueue(kron(Qin, Iout)+kron(Iin, Qout), kron(Rin, Iout), kron(Iin, Rout), 'Q0', kron(Qin, Iout)+kron(Rin, pinv(Rout)*Qout), 'stDistrME');
BuToolsVerbose = true;
msmall = MomentsFromME(beta, B, 5);
mlarge = MomentsFromME(gamma, G, 5);
assert(norm((msmall-mlarge)./msmall)<1e-12, 'FluFluQueue: Large and small model do not give the same results!');

