TestMAPPackage[]:=
Module[{A, rNm2, rcorr1, H1, jmom, a, rjmom, D, m, flag, Nm1, H, D2, Cm, rmoms, mom, Nm2, Nm3, H0, H2, rmom, D1, corr1, D0, rNm, G3, x, moms, err, ub, rNm3, rcorr, mm, rNm1, lb, Nm, err1, G2, corr, G, D3, err2, G1, G0},
	Print["---BuTools: MAP package test file---"//OutputForm];
	Print["Enable the verbose messages with the BuToolsVerbose flag"//OutputForm];
	BuTools`Verbose = True;
	Print["Enable input parameter checking with the BuToolsCheckInput flag"//OutputForm];
	BuTools`CheckInput = True;
	On[Assert];
	Print["========================================"];
	?"MarginalDistributionFromMAP";
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	D0 = {{-0.17, 0, 0, 0.07},{0.01, -0.78, 0.03, 0.08},{0.22, 0.17, -1.1, 0.02},{0.04, 0.12, 0, -0.42}};
	Print["D0 = "//OutputForm];
	Print[D0];
	D1 = {{0, 0.06, 0, 0.04},{0.04, 0.19, 0.21, 0.22},{0.22, 0.13, 0.15, 0.19},{0.05, 0, 0.17, 0.04}};
	Print["D1 = "//OutputForm];
	Print[D1];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["{a,A} = MarginalDistributionFromMAP[D0,D1]:"//OutputForm];
	{a,A} = MarginalDistributionFromMAP[D0,D1];
	Print["a = "//OutputForm];
	Print[a];
	Print["A = "//OutputForm];
	Print[A];
	Assert[Length[a]==Dimensions[D0][[1]] && CheckPHRepresentation[a,A] , "MarginalDistributionFromMAP returned a wrong PH representation!"];
	Print["========================================"];
	?"MarginalMomentsFromMAP";
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	D0 = {{-0.17, 0, 0, 0.07},{0.01, -0.78, 0.03, 0.08},{0.22, 0.17, -1.1, 0.02},{0.04, 0.12, 0, -0.42}};
	Print["D0 = "//OutputForm];
	Print[D0];
	D1 = {{0, 0.06, 0, 0.04},{0.04, 0.19, 0.21, 0.22},{0.22, 0.13, 0.15, 0.19},{0.05, 0, 0.17, 0.04}};
	Print["D1 = "//OutputForm];
	Print[D1];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["moms = MarginalMomentsFromMAP[D0,D1]:"//OutputForm];
	moms = MarginalMomentsFromMAP[D0,D1];
	Print["moms = "//OutputForm];
	Print[moms];
	Assert[Length[moms]==2*Dimensions[D0][[1]]-1 && CheckMoments[moms] , "MarginalMomentsFromMAP returned wrong moments!"];
	Print["========================================"];
	?"MarginalDistributionFromRAP";
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	H0 = {{-2, 0, 0},{0, -3, 1},{0, -1, -2}};
	Print["H0 = "//OutputForm];
	Print[H0];
	H1 = {{1.8, 0.2, 0},{0.2, 1.8, 0},{0.2, 1.8, 1}};
	Print["H1 = "//OutputForm];
	Print[H1];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["{a,A} = MarginalDistributionFromRAP[H0,H1]:"//OutputForm];
	{a,A} = MarginalDistributionFromRAP[H0,H1];
	Print["a = "//OutputForm];
	Print[a];
	Print["A = "//OutputForm];
	Print[A];
	Assert[Length[a]==Dimensions[H0][[1]] && CheckMERepresentation[a,A] , "MarginalDistributionFromRAP returned a wrong ME representation!"];
	Print["========================================"];
	?"MarginalMomentsFromRAP";
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	H0 = {{-2., 0, 0},{0, -3., 1.},{0, -1., -2.}};
	Print["H0 = "//OutputForm];
	Print[H0];
	H1 = {{1.8, 0.2, 0},{0.2, 1.8, 0},{0.2, 1.8, 1.}};
	Print["H1 = "//OutputForm];
	Print[H1];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["moms = MarginalMomentsFromRAP[H0,H1]:"//OutputForm];
	moms = MarginalMomentsFromRAP[H0,H1];
	Print["moms = "//OutputForm];
	Print[moms];
	Assert[Length[moms]==2*Dimensions[H0][[1]]-1 && CheckMoments[moms] , "MarginalMomentsFromRAP returned wrong moments!"];
	Print["========================================"];
	?"MarginalDistributionFromMMAP";
	D0 = {{-1.78, 0.29},{0.07, -0.92}};
	Print["D0 = "//OutputForm];
	Print[D0];
	D1 = {{0.15, 0.49},{0.23, 0.36}};
	Print["D1 = "//OutputForm];
	Print[D1];
	D2 = {{0.11, 0.2},{0.01, 0}};
	Print["D2 = "//OutputForm];
	Print[D2];
	D3 = {{0.14, 0.4},{0.11, 0.14}};
	Print["D3 = "//OutputForm];
	Print[D3];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["{a,A} = MarginalDistributionFromMMAP[{D0,D1,D2,D3}]:"//OutputForm];
	{a,A} = MarginalDistributionFromMMAP[{D0,D1,D2,D3}];
	Print["a = "//OutputForm];
	Print[a];
	Print["A = "//OutputForm];
	Print[A];
	Assert[Length[a]==Dimensions[D0][[1]] && CheckPHRepresentation[a,A] , "MarginalDistributionFromMMAP returned a wrong PH representation!"];
	Print["========================================"];
	?"MarginalMomentsFromMMAP";
	D0 = {{-1.78, 0.29},{0.07, -0.92}};
	Print["D0 = "//OutputForm];
	Print[D0];
	D1 = {{0.15, 0.49},{0.23, 0.36}};
	Print["D1 = "//OutputForm];
	Print[D1];
	D2 = {{0.11, 0.2},{0.01, 0}};
	Print["D2 = "//OutputForm];
	Print[D2];
	D3 = {{0.14, 0.4},{0.11, 0.14}};
	Print["D3 = "//OutputForm];
	Print[D3];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["moms = MarginalMomentsFromMMAP[{D0,D1,D2,D3}]:"//OutputForm];
	moms = MarginalMomentsFromMMAP[{D0,D1,D2,D3}];
	Print["moms = "//OutputForm];
	Print[moms];
	Assert[Length[moms]==2*Dimensions[D0][[1]]-1 && CheckMoments[moms] , "MarginalMomentsFromMMAP returned wrong moments!"];
	Print["========================================"];
	?"MarginalDistributionFromMRAP";
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	x = 0.18;
	H0 = {{-5., 0.1+x, 0.9, 1.},{1., -8., 0.9, 0.1},{0.9, 0.1, -4., 1.},{1., 2., 3., -9.}};
	Print["H0 = "//OutputForm];
	Print[H0];
	H1 = {{0.1-x, 0.7, 0.1, 0.1},{0.1, 1., 1.8, 0.1},{0.1, 0.1, 0.1, 0.7},{0.7, 0.1, 0.1, 0.1}};
	Print["H1 = "//OutputForm];
	Print[H1];
	H2 = {{0.1, 0.1, 0.1, 1.7},{1.8, 0.1, 1., 0.1},{0.1, 0.1, 0.7, 0.1},{0.1, 1., 0.1, 0.8}};
	Print["H2 = "//OutputForm];
	Print[H2];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["{a,A} = MarginalDistributionFromMRAP[{H0,H1,H2}]:"//OutputForm];
	{a,A} = MarginalDistributionFromMRAP[{H0,H1,H2}];
	Print["a = "//OutputForm];
	Print[a];
	Print["A = "//OutputForm];
	Print[A];
	Assert[Length[a]==Dimensions[H0][[1]] && CheckMERepresentation[a,A] , "MarginalDistributionFromMRAP returned a wrong ME representation!"];
	Print["========================================"];
	?"MarginalMomentsFromMRAP";
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	x = 0.18;
	H0 = {{-5., 0.1+x, 0.9, 1.},{1., -8., 0.9, 0.1},{0.9, 0.1, -4., 1.},{1., 2., 3., -9.}};
	Print["H0 = "//OutputForm];
	Print[H0];
	H1 = {{0.1-x, 0.7, 0.1, 0.1},{0.1, 1., 1.8, 0.1},{0.1, 0.1, 0.1, 0.7},{0.7, 0.1, 0.1, 0.1}};
	Print["H1 = "//OutputForm];
	Print[H1];
	H2 = {{0.1, 0.1, 0.1, 1.7},{1.8, 0.1, 1., 0.1},{0.1, 0.1, 0.7, 0.1},{0.1, 1., 0.1, 0.8}};
	Print["H2 = "//OutputForm];
	Print[H2];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["moms = MarginalMomentsFromMRAP[{H0,H1,H2}]:"//OutputForm];
	moms = MarginalMomentsFromMRAP[{H0,H1,H2}];
	Print["moms = "//OutputForm];
	Print[moms];
	Assert[Length[moms]==2*Dimensions[H0][[1]]-1 && CheckMoments[moms] , "MarginalMomentsFromMRAP returned wrong moments!"];
	Print["========================================"];
	?"LagCorrelationsFromMAP";
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	D0 = {{-5., 0, 1., 1.},{1., -8., 1., 0},{1., 0, -4., 1.},{1., 2., 3., -9.}};
	Print["D0 = "//OutputForm];
	Print[D0];
	D1 = {{0, 1., 0, 2.},{2., 1., 3., 0},{0, 0, 1., 1.},{1., 1., 0, 1.}};
	Print["D1 = "//OutputForm];
	Print[D1];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["corr = LagCorrelationsFromMAP[D0,D1,3]:"//OutputForm];
	corr = LagCorrelationsFromMAP[D0,D1,3];
	Print["corr = "//OutputForm];
	Print[corr];
	Assert[Length[corr]==3 && AllTrue[Flatten[corr],#<1 &] && AllTrue[Flatten[corr],#>-1 &] , "LagCorrelationsFromMAP returned wrong autocorrelation coefficients!"];
	Print["========================================"];
	?"LagCorrelationsFromRAP";
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	H0 = {{-2., 0, 0},{0, -3., 1.},{0, -1., -2.}};
	Print["H0 = "//OutputForm];
	Print[H0];
	H1 = {{1.8, 0.2, 0},{0.2, 1.8, 0},{0.2, 1.8, 1.}};
	Print["H1 = "//OutputForm];
	Print[H1];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["corr = LagCorrelationsFromRAP[H0,H1,3]:"//OutputForm];
	corr = LagCorrelationsFromRAP[H0,H1,3];
	Print["corr = "//OutputForm];
	Print[corr];
	Assert[Length[corr]==3 && AllTrue[Flatten[corr],#<1 &] && AllTrue[Flatten[corr],#>-1 &] , "LagCorrelationsFromRAP returned wrong autocorrelation coefficients!"];
	Print["========================================"];
	?"LagkJointMomentsFromMAP";
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	D0 = {{-5., 0, 1., 1.},{1., -8., 1., 0},{1., 0, -4., 1.},{1., 2., 3., -9.}};
	Print["D0 = "//OutputForm];
	Print[D0];
	D1 = {{0, 1., 0, 2.},{2., 1., 3., 0},{0, 0, 1., 1.},{1., 1., 0, 1.}};
	Print["D1 = "//OutputForm];
	Print[D1];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["Nm = LagkJointMomentsFromMAP[D0,D1,4,1]:"//OutputForm];
	Nm = LagkJointMomentsFromMAP[D0,D1,4,1];
	Print["Nm = "//OutputForm];
	Print[Nm];
	Print["moms = MarginalMomentsFromMAP[D0,D1,4]:"//OutputForm];
	moms = MarginalMomentsFromMAP[D0,D1,4];
	Print["moms = "//OutputForm];
	Print[moms];
	cjm=Table[(LagkJointMomentsFromMAP[D0,D1,1,i][[2,2]]-moms[[1]]^2) / (moms[[2]]-moms[[1]]^2),{i,1,3}];
	Print["Correlation from joint moments:"//OutputForm];
	Print[cjm];
	Print["corr = LagCorrelationsFromMAP[D0,D1,3]:"//OutputForm];
	corr = LagCorrelationsFromMAP[D0,D1,3];
	Print["corr = "//OutputForm];
	Print[corr];
	mNm1 = Nm[[1,2;;]]; mNm2 = Nm[[2;;,1]];
	Assert[AllTrue[Flatten[Nm],Positive] && Norm[moms-mNm1]<10^-14 && Norm[moms-mNm2]<10^-14 && Norm[corr-cjm]<10^-14 , "Joint moment matrix is invalid!"];
	Print["========================================"];
	?"LagkJointMomentsFromRAP";
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	H0 = {{-2., 0, 0},{0, -3., 1.},{0, -1., -2.}};
	Print["H0 = "//OutputForm];
	Print[H0];
	H1 = {{1.8, 0.2, 0},{0.2, 1.8, 0},{0.2, 1.8, 1.}};
	Print["H1 = "//OutputForm];
	Print[H1];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["Nm = LagkJointMomentsFromRAP[H0,H1,4,1]:"//OutputForm];
	Nm = LagkJointMomentsFromRAP[H0,H1,4,1];
	Print[Length[Nm]];
	Print["moms = MarginalMomentsFromRAP[H0,H1,4]:"//OutputForm];
	moms = MarginalMomentsFromRAP[H0,H1,4];
	Print["moms = "//OutputForm];
	Print[moms];
	cjm={};
	cjm=Table[(LagkJointMomentsFromRAP[H0,H1,1,i][[2,2]]-moms[[1]]^2) / (moms[[2]]-moms[[1]]^2),{i,1,3}];
	Print["Correlation from joint moments:"//OutputForm];
	Print[cjm];
	Print["corr = LagCorrelationsFromRAP[H0,H1,3]:"//OutputForm];
	corr = LagCorrelationsFromRAP[H0,H1,3];
	Print["corr = "//OutputForm];
	Print[corr];
	mNm1 = Nm[[1,2;;]]; mNm2 = Nm[[2;;,1]];
	Assert[AllTrue[Flatten[Nm],Positive] && Norm[moms-mNm1]<10^-14 && Norm[moms-mNm2]<10^-14 && Norm[corr-cjm]<10^-14 , "Joint moment matrix is invalid!"];
	Print["========================================"];
	?"LagkJointMomentsFromMMAP";
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	D0 = {{-1.78, 0.29},{0.07, -0.92}};
	Print["D0 = "//OutputForm];
	Print[D0];
	D1 = {{0.15, 0.49},{0.23, 0.36}};
	Print["D1 = "//OutputForm];
	Print[D1];
	D2 = {{0.11, 0.2},{0.01, 0}};
	Print["D2 = "//OutputForm];
	Print[D2];
	D3 = {{0.14, 0.4},{0.11, 0.14}};
	Print["D3 = "//OutputForm];
	Print[D3];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["Nm = LagkJointMomentsFromMMAP[{D0,D1,D2,D3},3,1]:"//OutputForm];
	Nm = LagkJointMomentsFromMMAP[{D0,D1,D2,D3},3,1];
	Print[Nm[[1]]];
	Print[Nm[[2]]];
	Print[Nm[[3]]];
	Assert[Length[Nm]==3 && Norm[Nm[[1]]+Nm[[2]]+Nm[[3]]-LagkJointMomentsFromMAP[D0,D1+D2+D3,3,1]]<10^-14 , "Joint moment matrix is invalid!"];
	Print["========================================"];
	?"LagkJointMomentsFromMRAP";
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	x = 0.18;
	H0 = {{-5., 0.1+x, 0.9, 1.},{1., -8., 0.9, 0.1},{0.9, 0.1, -4., 1.},{1., 2., 3., -9.}};
	Print["H0 = "//OutputForm];
	Print[H0];
	H1 = {{0.1-x, 0.7, 0.1, 0.1},{0.1, 1., 1.8, 0.1},{0.1, 0.1, 0.1, 0.7},{0.7, 0.1, 0.1, 0.1}};
	Print["H1 = "//OutputForm];
	Print[H1];
	H2 = {{0.1, 0.1, 0.1, 1.7},{1.8, 0.1, 1., 0.1},{0.1, 0.1, 0.7, 0.1},{0.1, 1., 0.1, 0.8}};
	Print["H2 = "//OutputForm];
	Print[H2];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["Nm = LagkJointMomentsFromMRAP[{H0,H1,H2},3,2]:"//OutputForm];
	Nm = LagkJointMomentsFromMRAP[{H0,H1,H2},3,2];
	Print[Nm[[1]]];
	Print[Nm[[2]]];
	Assert[Length[Nm]==2 && Norm[Nm[[1]]+Nm[[2]]-LagkJointMomentsFromRAP[H0,H1+H2,3,2]]<10^-14 , "Joint moment matrix is invalid!"];
	Print["========================================"];
	?"RandomMAP";
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["{D0,D1} = RandomMAP[4,1.62,10]:"//OutputForm];
	{D0,D1} = RandomMAP[4,1.62,10];
	Print["D0 = "//OutputForm];
	Print[D0];
	Print["D1 = "//OutputForm];
	Print[D1];
	Print["m = MarginalMomentsFromMAP[D0,D1,1][[1]]:"//OutputForm];
	m = MarginalMomentsFromMAP[D0,D1,1][[1]];
	Print["m = "//OutputForm];
	Print[m];
	Assert[CheckMAPRepresentation[D0,D1] , "RandomMAP failed to return a valid MAP representation!"];
	Assert[Abs[m-1.62]<10^-14 , "RandomMAP failed to match the given mean value!"];
	Print["========================================"];
	?"RandomMMAP";
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["D = RandomMMAP[4,3,1.62,10]:"//OutputForm];
	D = RandomMMAP[4,3,1.62,10];
	Print[D[[1]]];
	Print[D[[2]]];
	Print[D[[3]]];
	Print[D[[4]]];
	Print["m = MarginalMomentsFromMMAP[D,1][[1]]:"//OutputForm];
	m = MarginalMomentsFromMMAP[D,1][[1]];
	Print["m = "//OutputForm];
	Print[m];
	Assert[CheckMMAPRepresentation[D] , "RandomMMAP failed to return a valid MMAP representation!"];
	Assert[Abs[m-1.62]<10^-14 , "RandomMMAP failed to match the given mean value!"];
	Print["========================================"];
	?"CheckMAPRepresentation";
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	D0 = {{-1., 0, 1.},{0, -2., 0},{1., 0, -3.}};
	Print["D0 = "//OutputForm];
	Print[D0];
	D1 = {{-1., 0, 1., 0},{0, -2., 0, 1.},{1., 0, -3., 0},{1., 2., 2., 1.}};
	Print["D1 = "//OutputForm];
	Print[D1];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["flag = CheckMAPRepresentation[D0,D1]:"//OutputForm];
	flag = CheckMAPRepresentation[D0,D1];
	Print["flag = "//OutputForm];
	Print[flag];
	Assert[flag==False , "CheckMAPRepresentation failed to detect the incompatible shapes of D0 and D1!"];
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	D0 = {{-1., 0, 1.},{0, -2., 0},{1., 0, -3.}};
	Print["D0 = "//OutputForm];
	Print[D0];
	D1 = {{1., 0, 1.},{0, 2., 0},{1., 0, 3.}};
	Print["D1 = "//OutputForm];
	Print[D1];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["flag = CheckMAPRepresentation[D0,D1]:"//OutputForm];
	flag = CheckMAPRepresentation[D0,D1];
	Print["flag = "//OutputForm];
	Print[flag];
	Assert[flag==False , "CheckMAPRepresentation failed to detect invalid rowsums!"];
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	D0 = {{-3., 0, 1.},{0, -2., 0},{1., 0, -5.}};
	Print["D0 = "//OutputForm];
	Print[D0];
	D1 = {{1., 0, 1.},{0, 2., 0},{1., 0, 3.}};
	Print["D1 = "//OutputForm];
	Print[D1];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["flag = CheckMAPRepresentation[D0,D1]:"//OutputForm];
	flag = CheckMAPRepresentation[D0,D1];
	Print["flag = "//OutputForm];
	Print[flag];
	Assert[flag==True , "CheckMAPRepresentation failed to recognize a valid MAP representation!"];
	Print["========================================"];
	?"CheckRAPRepresentation";
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	H0 = {{-1., 0, 1.},{0, -2., 0},{1., 0, -3.},{1., 2., 2.}};
	Print["H0 = "//OutputForm];
	Print[H0];
	H1 = {{-1., 0, 1.},{0, -2., 0},{1., 0, -3.},{1., 2., 2.}};
	Print["H1 = "//OutputForm];
	Print[H1];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["flag = CheckRAPRepresentation[H0,H1]:"//OutputForm];
	flag = CheckRAPRepresentation[H0,H1];
	Print["flag = "//OutputForm];
	Print[flag];
	Assert[flag==False , "CheckRAPRepresentation failed to detect the incompatible shapes of D0 and D1!"];
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	H0 = {{-1., 0, 2.},{0, 2., 0},{1., 0, -3.}};
	Print["H0 = "//OutputForm];
	Print[H0];
	H1 = {{-1., 0, 1.},{0, -2., 0},{1., 0, -3.}};
	Print["H1 = "//OutputForm];
	Print[H1];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["flag = CheckRAPRepresentation[H0,H1]:"//OutputForm];
	flag = CheckRAPRepresentation[H0,H1];
	Print["flag = "//OutputForm];
	Print[flag];
	Assert[flag==False , "CheckRAPRepresentation failed to detect invalid rowsums!"];
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	H0 = {{-1., 0, 0},{0, -2., 2.},{0, 3., -3.}};
	Print["H0 = "//OutputForm];
	Print[H0];
	H1 = {{0, 0, 1.},{0, -1., 1.},{1., 0, -1.}};
	Print["H1 = "//OutputForm];
	Print[H1];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["flag = CheckRAPRepresentation[H0,H1]:"//OutputForm];
	flag = CheckRAPRepresentation[H0,H1];
	Print["flag = "//OutputForm];
	Print[flag];
	Assert[flag==False , "CheckRAPRepresentation failed to detect invalid eigenvalues!"];
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	H0 = {{-2., 0, 0},{0, -1., 1.},{0, -1., -1.}};
	Print["H0 = "//OutputForm];
	Print[H0];
	H1 = {{1., 0, 1.},{0, 1., -1.},{1., 0, 1.}};
	Print["H1 = "//OutputForm];
	Print[H1];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["flag = CheckRAPRepresentation[H0,H1]:"//OutputForm];
	flag = CheckRAPRepresentation[H0,H1];
	Print["flag = "//OutputForm];
	Print[flag];
	Assert[flag==False , "CheckRAPRepresentation failed to detect invalid eigenvalues!"];
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	H0 = {{-1., 0, 0},{0, -2., 1.},{0, -1., -2.}};
	Print["H0 = "//OutputForm];
	Print[H0];
	H1 = {{1., 0, 0},{0, 1., 0},{1., 1., 1.}};
	Print["H1 = "//OutputForm];
	Print[H1];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["flag = CheckRAPRepresentation[H0,H1]:"//OutputForm];
	flag = CheckRAPRepresentation[H0,H1];
	Print["flag = "//OutputForm];
	Print[flag];
	Assert[flag==True , "CheckRAPRepresentation failed to recognize a valid RAP representation!"];
	Print["========================================"];
	?"CheckMMAPRepresentation";
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	D0 = {{-1.05, 0.03, 0.07},{0.19, -1.63, 0.06},{0, 0.2, -1.03}};
	Print["D0 = "//OutputForm];
	Print[D0];
	D1 = {{0.16, 0.11, 0},{0.1, 0.16, 0},{0.27, 0, 0.19}};
	Print["D1 = "//OutputForm];
	Print[D1];
	D2 = {{0.01, 0.09, 0.13},{0.26, 0.21, 0.05},{0, 0.16, 0.07}};
	Print["D2 = "//OutputForm];
	Print[D2];
	D3 = {{0.19, 0.06, 0.2},{0.17, 0.16, 0.27},{0, 0, 0.14}};
	Print["D3 = "//OutputForm];
	Print[D3];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["flag = CheckMMAPRepresentation[{D0,D1,D2,D3}]:"//OutputForm];
	flag = CheckMMAPRepresentation[{D0,D1,D2,D3}];
	Print["flag = "//OutputForm];
	Print[flag];
	Assert[flag==True , "CheckMMAPRepresentation failed to recognize a valid MMAP representation!"];
	Print["========================================"];
	?"CheckMRAPRepresentation";
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	x = 0.18;
	H0 = {{-5., 0.1+x, 0.9, 1.},{1., -8., 0.9, 0.1},{0.9, 0.1, -4., 1.},{1., 2., 3., -9.}};
	Print["H0 = "//OutputForm];
	Print[H0];
	H1 = {{0.1-x, 0.7, 0.1, 0.1},{0.1, 1., 1.8, 0.1},{0.1, 0.1, 0.1, 0.7},{0.7, 0.1, 0.1, 0.1}};
	Print["H1 = "//OutputForm];
	Print[H1];
	H2 = {{0.1, 0.1, 0.1, 1.7},{1.8, 0.1, 1., 0.1},{0.1, 0.1, 0.7, 0.1},{0.1, 1., 0.1, 0.8}};
	Print["H2 = "//OutputForm];
	Print[H2];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["flag = CheckMRAPRepresentation[{H0,H1,H2}]:"//OutputForm];
	flag = CheckMRAPRepresentation[{H0,H1,H2}];
	Print["flag = "//OutputForm];
	Print[flag];
	Assert[flag==True , "CheckMRAPRepresentation failed to recognize a valid MRAP representation!"];
	Print["========================================"];
	?"RAPFromMoments";
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	G0 = {{-6.2, 2., 0.},{2., -9., 1.},{1., 0, -3.}};
	Print["G0 = "//OutputForm];
	Print[G0];
	G1 = {{2.2, -2., 4.},{2., 2., 2.},{1., 0, 1.}};
	Print["G1 = "//OutputForm];
	Print[G1];
	Print["moms = MarginalMomentsFromRAP[G0,G1,5]:"//OutputForm];
	moms = MarginalMomentsFromRAP[G0,G1,5];
	Print["moms = "//OutputForm];
	Print[moms];
	Print["Nm = LagkJointMomentsFromRAP[G0,G1,2,1]:"//OutputForm];
	Nm = LagkJointMomentsFromRAP[G0,G1,2,1];
	Print["Nm = "//OutputForm];
	Print[Nm];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["{H0,H1} = RAPFromMoments[moms,Nm]:"//OutputForm];
	{H0,H1} = RAPFromMoments[moms,Nm];
	Print["H0 = "//OutputForm];
	Print[H0];
	Print["H1 = "//OutputForm];
	Print[H1];
	Print["rmoms = MarginalMomentsFromRAP[H0,H1,5]:"//OutputForm];
	rmoms = MarginalMomentsFromRAP[H0,H1,5];
	Print["rmoms = "//OutputForm];
	Print[rmoms];
	Print["rNm = LagkJointMomentsFromRAP[H0,H1,2,1]:"//OutputForm];
	rNm = LagkJointMomentsFromRAP[H0,H1,2,1];
	Print["rNm = "//OutputForm];
	Print[rNm];
	Assert[Norm[moms-rmoms]<10^-12 && Norm[Nm-rNm]<10^-12 , "The moments and joint moments returned by RAPFromMoments are not the same as given!"];
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	G0 = {{-5., 0, 1., 1.},{1., -8., 1., 0},{1., 0, -4., 1.},{1., 2., 3., -9.}};
	Print["G0 = "//OutputForm];
	Print[G0];
	G1 = {{0, 1., 0, 2.},{2., 1., 3., 0},{0, 0, 1., 1.},{1., 1., 0, 1.}};
	Print["G1 = "//OutputForm];
	Print[G1];
	Print["moms = MarginalMomentsFromRAP[G0,G1,7]:"//OutputForm];
	moms = MarginalMomentsFromRAP[G0,G1,7];
	Print["moms = "//OutputForm];
	Print[moms];
	Print["Nm = LagkJointMomentsFromRAP[G0,G1,3,1]:"//OutputForm];
	Nm = LagkJointMomentsFromRAP[G0,G1,3,1];
	Print["Nm = "//OutputForm];
	Print[Nm];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["{H0,H1} = RAPFromMoments[moms,Nm]:"//OutputForm];
	{H0,H1} = RAPFromMoments[moms,Nm];
	Print["H0 = "//OutputForm];
	Print[H0];
	Print["H1 = "//OutputForm];
	Print[H1];
	BuTools`CheckPrecision = 10.^-8;
	Print["rmoms = MarginalMomentsFromRAP[H0,H1,7]:"//OutputForm];
	rmoms = MarginalMomentsFromRAP[H0,H1,7];
	Print["rmoms = "//OutputForm];
	Print[rmoms];
	Print["rNm = LagkJointMomentsFromRAP[H0,H1,3,1]:"//OutputForm];
	rNm = LagkJointMomentsFromRAP[H0,H1,3,1];
	Print["rNm = "//OutputForm];
	Print[rNm];
	Assert[CheckRAPRepresentation[H0,H1,10^-8] , "RAPFromMoments returned an invalid RAP representation!"];
	Assert[Norm[moms-rmoms]<10^-8 && Norm[Nm-rNm]<10^-8 , "The moments and joint moments returned by RAPFromMoments are not the same as given!"];
	Print["========================================"];
	?"MRAPFromMoments";
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	G0 = {{-1.05, 0.03, 0.07},{0.19, -1.63, 0.06},{0, 0.2, -1.03}};
	Print["G0 = "//OutputForm];
	Print[G0];
	G1 = {{0.16, 0.11, 0},{0.1, 0.16, 0},{0.27, 0, 0.19}};
	Print["G1 = "//OutputForm];
	Print[G1];
	G2 = {{0.01, 0.09, 0.13},{0.26, 0.21, 0.05},{0, 0.16, 0.07}};
	Print["G2 = "//OutputForm];
	Print[G2];
	G3 = {{0.19, 0.06, 0.2},{0.17, 0.16, 0.27},{0, 0, 0.14}};
	Print["G3 = "//OutputForm];
	Print[G3];
	Print["G = {G0,G1,G2,G3}:"//OutputForm];
	G = {G0,G1,G2,G3};
	Print["moms = MarginalMomentsFromMRAP[G,5]:"//OutputForm];
	moms = MarginalMomentsFromMRAP[G,5];
	Print["moms = "//OutputForm];
	Print[moms];
	Print["Nm = LagkJointMomentsFromMRAP[G,2,1]:"//OutputForm];
	Nm = LagkJointMomentsFromMRAP[G,2,1];
	Print["{Nm1, Nm2, Nm3} = Nm:"//OutputForm];
	{Nm1, Nm2, Nm3} = Nm;
	Print["Nm1 = "//OutputForm];
	Print[Nm1];
	Print["Nm2 = "//OutputForm];
	Print[Nm2];
	Print["Nm3 = "//OutputForm];
	Print[Nm3];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["H = MRAPFromMoments[moms,Nm]:"//OutputForm];
	H = MRAPFromMoments[moms,Nm];
	Print["H[[1]]:"//OutputForm];
	Print[H[[1]]];
	Print["H[[2]]:"//OutputForm];
	Print[H[[2]]];
	Print["H[[3]]:"//OutputForm];
	Print[H[[3]]];
	Print["H[[4]]:"//OutputForm];
	Print[H[[4]]];
	BuTools`CheckPrecision = 10.^-10;
	Print["rmoms = MarginalMomentsFromMRAP[H,5]:"//OutputForm];
	rmoms = MarginalMomentsFromMRAP[H,5];
	Print["rmoms = "//OutputForm];
	Print[rmoms];
	Print["rNm = LagkJointMomentsFromMRAP[H,2,1]:"//OutputForm];
	rNm = LagkJointMomentsFromMRAP[H,2,1];
	Print["{rNm1, rNm2, rNm3} = rNm:"//OutputForm];
	{rNm1, rNm2, rNm3} = rNm;
	Print["rNm1 = "//OutputForm];
	Print[rNm1];
	Print["rNm2 = "//OutputForm];
	Print[rNm2];
	Print["rNm3 = "//OutputForm];
	Print[rNm3];
	Assert[Norm[moms-rmoms]<10^-9 && Norm[Nm1-rNm1]<10^-10 && Norm[Nm2-rNm2]<10^-10 && Norm[Nm3-rNm3]<10^-10 , "The moments and joint moments returned by MRAPFromMoments are not the same as given!"];
	Print["========================================"];
	?"RAPFromMomentsAndCorrelations";
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	H0 = {{-6.2, 2., 0},{2., -9., 1.},{1., 0, -3.}};
	Print["H0 = "//OutputForm];
	Print[H0];
	H1 = {{2.2, 0, 2.},{0, 4., 2.},{0, 1., 1.}};
	Print["H1 = "//OutputForm];
	Print[H1];
	Print["mom = MarginalMomentsFromRAP[H0,H1]:"//OutputForm];
	mom = MarginalMomentsFromRAP[H0,H1];
	Print["mom = "//OutputForm];
	Print[mom];
	Print["corr = LagCorrelationsFromRAP[H0,H1,3]:"//OutputForm];
	corr = LagCorrelationsFromRAP[H0,H1,3];
	Print["corr = "//OutputForm];
	Print[corr];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["{G0,G1} = RAPFromMomentsAndCorrelations[mom,corr]:"//OutputForm];
	{G0,G1} = RAPFromMomentsAndCorrelations[mom,corr];
	Print["G0 = "//OutputForm];
	Print[G0];
	Print["G1 = "//OutputForm];
	Print[G1];
	Print["rmom = MarginalMomentsFromRAP[G0,G1]:"//OutputForm];
	rmom = MarginalMomentsFromRAP[G0,G1];
	Print["rmom = "//OutputForm];
	Print[rmom];
	Print["rcorr = LagCorrelationsFromRAP[G0,G1,3]:"//OutputForm];
	rcorr = LagCorrelationsFromRAP[G0,G1,3];
	Print["rcorr = "//OutputForm];
	Print[rcorr];
	Assert[CheckRAPRepresentation[G0,G1] , "RAPFromMomentsAndCorrelations returned an invalid RAP representation!"];
	Assert[Norm[rmom-mom]+Norm[rcorr-corr]<10^-12 , "The result of RAPFromMomentsAndCorrelations has different moments or correlations than given!"];
	Print["========================================"];
	?"MAP2FromMoments";
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	D0 = {{-14., 1.},{1, -25.}};
	Print["D0 = "//OutputForm];
	Print[D0];
	D1 = {{6., 7.},{3., 21.}};
	Print["D1 = "//OutputForm];
	Print[D1];
	Print["moms = MarginalMomentsFromMAP[D0, D1, 3]:"//OutputForm];
	moms = MarginalMomentsFromMAP[D0, D1, 3];
	Print["moms = "//OutputForm];
	Print[moms];
	Print["corr = LagCorrelationsFromMAP[D0, D1, 1][[1]]:"//OutputForm];
	corr = LagCorrelationsFromMAP[D0, D1, 1][[1]];
	Print["corr = "//OutputForm];
	Print[corr];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["{D0,D1} = MAP2FromMoments[moms,corr]:"//OutputForm];
	{D0,D1} = MAP2FromMoments[moms,corr];
	Print["D0 = "//OutputForm];
	Print[D0];
	Print["D1 = "//OutputForm];
	Print[D1];
	Print["rmoms = MarginalMomentsFromMAP[D0, D1, 3]:"//OutputForm];
	rmoms = MarginalMomentsFromMAP[D0, D1, 3];
	Print["rmoms = "//OutputForm];
	Print[rmoms];
	Print["rcorr = LagCorrelationsFromMAP[D0, D1, 1][[1]]:"//OutputForm];
	rcorr = LagCorrelationsFromMAP[D0, D1, 1][[1]];
	Print["rcorr = "//OutputForm];
	Print[rcorr];
	Assert[CheckMAPRepresentation[D0,D1] , "MAP2FromMoments returned an invalid MAP representation!"];
	Assert[Norm[moms-rmoms]<10^-12 && Abs[corr-rcorr]<10^-12 , "The moments and the correlation returned by MAP2FromMoments are not the same as given!"];
	Print["========================================"];
	?"MAP2CorrelationBounds";
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	D0 = {{-14., 1.},{1., -25.}};
	Print["D0 = "//OutputForm];
	Print[D0];
	D1 = {{6., 7.},{3., 21.}};
	Print["D1 = "//OutputForm];
	Print[D1];
	Print["moms = MarginalMomentsFromMAP[D0,D1,3]:"//OutputForm];
	moms = MarginalMomentsFromMAP[D0,D1,3];
	Print["moms = "//OutputForm];
	Print[moms];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["{lb,ub} = MAP2CorrelationBounds[moms]:"//OutputForm];
	{lb,ub} = MAP2CorrelationBounds[moms];
	Print["lb = "//OutputForm];
	Print[lb];
	Print["ub = "//OutputForm];
	Print[ub];
	Assert[lb<=0 && lb>=-1 && ub>=0 && ub<=1 , "Correlation bounds given by MAP2CorrelationBounds are not correct"];
	Print["========================================"];
	?"MAPFromFewMomentsAndCorrelations";
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	moms = {1.1, 6.05};
	Print["moms = "//OutputForm];
	Print[moms];
	corr1 = -0.17;
	Print["corr1 = "//OutputForm];
	Print[corr1];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["{D0,D1} = MAPFromFewMomentsAndCorrelations[moms, corr1]:"//OutputForm];
	{D0,D1} = MAPFromFewMomentsAndCorrelations[moms, corr1];
	Print["D0 = "//OutputForm];
	Print[D0];
	Print["D1 = "//OutputForm];
	Print[D1];
	Print["rmoms = MarginalMomentsFromMAP[D0,D1,2]:"//OutputForm];
	rmoms = MarginalMomentsFromMAP[D0,D1,2];
	Print["rmoms = "//OutputForm];
	Print[rmoms];
	Print["rcorr1 = LagCorrelationsFromMAP[D0,D1,1][[1]]:"//OutputForm];
	rcorr1 = LagCorrelationsFromMAP[D0,D1,1][[1]];
	Print["rcorr1 = "//OutputForm];
	Print[rcorr1];
	Assert[CheckMAPRepresentation[D0,D1] , "MAPFromFewMomentsAndCorrelations returned with a non-Markovian representation!"];
	Assert[Norm[rmoms-moms]<10^-12 && Abs[rcorr1-corr1]<10^-12 , "MAPFromFewMomentsAndCorrelations failed to match the marginal moments or the lag-1 autocorrelation!"];
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	moms = {1.2, 4.32, 20.};
	Print["moms = "//OutputForm];
	Print[moms];
	corr1 = -0.4;
	Print["corr1 = "//OutputForm];
	Print[corr1];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["{D0,D1} = MAPFromFewMomentsAndCorrelations[moms, corr1]:"//OutputForm];
	{D0,D1} = MAPFromFewMomentsAndCorrelations[moms, corr1];
	Print["D0 = "//OutputForm];
	Print[D0];
	Print["D1 = "//OutputForm];
	Print[D1];
	BuTools`CheckPrecision = 10.^-12;
	Print["rmoms = MarginalMomentsFromMAP[D0,D1,3]:"//OutputForm];
	rmoms = MarginalMomentsFromMAP[D0,D1,3];
	Print["rmoms = "//OutputForm];
	Print[rmoms];
	Print["rcorr1 = LagCorrelationsFromMAP[D0,D1,1][[1]]:"//OutputForm];
	rcorr1 = LagCorrelationsFromMAP[D0,D1,1][[1]];
	Print["rcorr1 = "//OutputForm];
	Print[rcorr1];
	Assert[CheckMAPRepresentation[D0,D1,10^-13] , "MAPFromFewMomentsAndCorrelations returned with a non-Markovian representation!"];
	Assert[Norm[rmoms-moms]<10^-12 && Abs[rcorr1-corr1]<10^-12 , "MAPFromFewMomentsAndCorrelations failed to match the marginal moments or the lag-1 autocorrelation!"];
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	moms = {1.2, 4.32, 20.};
	Print["moms = "//OutputForm];
	Print[moms];
	corr1 = 0.4;
	Print["corr1 = "//OutputForm];
	Print[corr1];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["{D0,D1} = MAPFromFewMomentsAndCorrelations[moms, corr1]:"//OutputForm];
	{D0,D1} = MAPFromFewMomentsAndCorrelations[moms, corr1];
	Print["D0 = "//OutputForm];
	Print[D0];
	Print["D1 = "//OutputForm];
	Print[D1];
	Print["rmoms = MarginalMomentsFromMAP[D0,D1,3]:"//OutputForm];
	rmoms = MarginalMomentsFromMAP[D0,D1,3];
	Print["rmoms = "//OutputForm];
	Print[rmoms];
	Print["rcorr1 = LagCorrelationsFromMAP[D0,D1,1][[1]]:"//OutputForm];
	rcorr1 = LagCorrelationsFromMAP[D0,D1,1][[1]];
	Print["rcorr1 = "//OutputForm];
	Print[rcorr1];
	Assert[CheckMAPRepresentation[D0,D1,10^-13] , "MAPFromFewMomentsAndCorrelations returned with a non-Markovian representation!"];
	Assert[Norm[rmoms-moms]<10^-12 && Abs[rcorr1-corr1]<10^-12 , "MAPFromFewMomentsAndCorrelations failed to match the marginal moments or the lag-1 autocorrelation!"];
	Print["========================================"];
	?"CanonicalFromMAP2";
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	D0 = {{-14., 1.},{1., -25.}};
	Print["D0 = "//OutputForm];
	Print[D0];
	D1 = {{6., 7.},{3., 21.}};
	Print["D1 = "//OutputForm];
	Print[D1];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["{H0,H1} = CanonicalFromMAP2[D0,D1]:"//OutputForm];
	{H0,H1} = CanonicalFromMAP2[D0,D1];
	Print["H0 = "//OutputForm];
	Print[H0];
	Print["H1 = "//OutputForm];
	Print[H1];
	Cm = SimilarityMatrix[H0,D0];
	err1 = Norm[H0.Cm-Cm.D0];
	err2 = Norm[H1.Cm-Cm.D1];
	Print["Transformation errors:"//OutputForm];
	Print[Max[err1,err2]];
	Assert[CheckMAPRepresentation[H0,H1] , "The result of CanonicalFromMAP2 is not a valid MAP representation!"];
	Assert[Max[err1,err2]<10^-12 , "The MAP returned by CanonicalFromMAP2 is not similar to the input!"];
	Print["========================================"];
	?"MAPFromRAP";
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	D0 = {{-2., 2.},{2., -9.}};
	Print["D0 = "//OutputForm];
	Print[D0];
	D1 = {{-2., 2.},{3., 4.}};
	Print["D1 = "//OutputForm];
	Print[D1];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["{H0,H1} = MAPFromRAP[D0,D1]:"//OutputForm];
	{H0,H1} = MAPFromRAP[D0,D1];
	Print["H0 = "//OutputForm];
	Print[H0];
	Print["H1 = "//OutputForm];
	Print[H1];
	Print["err = Norm[LagkJointMomentsFromRAP[D0,D1,3,1]-LagkJointMomentsFromRAP[H0,H1,3,1]]:"//OutputForm];
	err = Norm[LagkJointMomentsFromRAP[D0,D1,3,1]-LagkJointMomentsFromRAP[H0,H1,3,1]];
	Print["err = "//OutputForm];
	Print[err];
	Assert[err<10^-12 , "The RAP returned by MAPFromRAP is not similar to the input!"];
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	D0 = {{-2.4, 2.},{2., -9.}};
	Print["D0 = "//OutputForm];
	Print[D0];
	D1 = {{-1.6, 2.},{3., 4.}};
	Print["D1 = "//OutputForm];
	Print[D1];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["{H0,H1} = MAPFromRAP[D0,D1]:"//OutputForm];
	{H0,H1} = MAPFromRAP[D0,D1];
	Print["H0 = "//OutputForm];
	Print[H0];
	Print["H1 = "//OutputForm];
	Print[H1];
	Print["err = Norm[LagkJointMomentsFromRAP[D0,D1,3,1]-LagkJointMomentsFromRAP[H0,H1,3,1]]:"//OutputForm];
	err = Norm[LagkJointMomentsFromRAP[D0,D1,3,1]-LagkJointMomentsFromRAP[H0,H1,3,1]];
	Print["err = "//OutputForm];
	Print[err];
	Assert[err<10^-12 , "The MAP returned by MAPFromRAP is not similar to the input!"];
	Assert[CheckMAPRepresentation[H0,H1] , "The result of MAPFromRAP is not a MAP, as it should be!"];
	Print["========================================"];
	?"MMAPFromMRAP";
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	x = 0.18;
	H0 = {{-5., 0.1+x, 0.9, 1.},{1., -8., 0.9, 0.1},{0.9, 0.1, -4., 1.},{1., 2., 3., -9.}};
	Print["H0 = "//OutputForm];
	Print[H0];
	H1 = {{0.1-x, 0.7, 0.1, 0.1},{0.1, 1., 1.8, 0.1},{0.1, 0.1, 0.1, 0.7},{0.7, 0.1, 0.1, 0.1}};
	Print["H1 = "//OutputForm];
	Print[H1];
	H2 = {{0.1, 0.1, 0.1, 1.7},{1.8, 0.1, 1., 0.1},{0.1, 0.1, 0.7, 0.1},{0.1, 1., 0.1, 0.8}};
	Print["H2 = "//OutputForm];
	Print[H2];
	H = {H0,H1,H2};
	Print["moms = MarginalMomentsFromMRAP[H]:"//OutputForm];
	moms = MarginalMomentsFromMRAP[H];
	Print["moms = "//OutputForm];
	Print[moms];
	Print["jmom = LagkJointMomentsFromMRAP[H,3,1]:"//OutputForm];
	jmom = LagkJointMomentsFromMRAP[H,3,1];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["G = MMAPFromMRAP[H]:"//OutputForm];
	G = MMAPFromMRAP[H];
	Print[G[[1]]];
	Print[G[[2]]];
	Print[G[[3]]];
	Print["rmoms = MarginalMomentsFromMMAP[G]:"//OutputForm];
	rmoms = MarginalMomentsFromMMAP[G];
	Print["rmoms = "//OutputForm];
	Print[rmoms];
	Print["rjmom = LagkJointMomentsFromMMAP[G,3,1]:"//OutputForm];
	rjmom = LagkJointMomentsFromMMAP[G,3,1];
	Print["err = Norm[rjmom[[1]]-jmom[[1]]] + Norm[rjmom[[2]]-jmom[[2]]]:"//OutputForm];
	err = Norm[rjmom[[1]]-jmom[[1]]] + Norm[rjmom[[2]]-jmom[[2]]];
	Print["err = "//OutputForm];
	Print[err];
	Assert[err<10^-12 , "The MMAP returned by MMAPFromMRAP is not similar to the input!"];
	Assert[CheckMMAPRepresentation[G] , "The result of MMAPFromMRAP is not a MMAP, as it should be!"];
	Print["========================================"];
	?"MinimalRepFromRAP";
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	D0 = {{-5., 1., 0},{3., -3., 0},{1., 1., -5.}};
	Print["D0 = "//OutputForm];
	Print[D0];
	D1 = {{0, 0, 4.},{0, 0, 0},{1., 1., 1.}};
	Print["D1 = "//OutputForm];
	Print[D1];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["{H0,H1} = MinimalRepFromRAP[D0,D1,\"cont\"]:"//OutputForm];
	{H0,H1} = MinimalRepFromRAP[D0,D1,"cont"];
	Print["H0 = "//OutputForm];
	Print[H0];
	Print["H1 = "//OutputForm];
	Print[H1];
	Cm = SimilarityMatrix[H0,D0];
	err1 = Norm[H0.Cm-Cm.D0];
	err2 = Norm[H1.Cm-Cm.D1];
	Print["Transformation errors:"//OutputForm];
	Print[Max[err1,err2]];
	Assert[CheckRAPRepresentation[H0,H1] , "MinimalRepFromRAP did not return a valid RAP representation!"];
	Assert[Dimensions[H0][[1]]==3 && Max[err1,err2]<10^-12 , "MinimalRepFromRAP returned a RAP which is non-similar to the input or has an unexpected size!"];
	Print["{H0,H1} = MinimalRepFromRAP[D0,D1,\"obs\"]:"//OutputForm];
	{H0,H1} = MinimalRepFromRAP[D0,D1,"obs"];
	Print["H0 = "//OutputForm];
	Print[H0];
	Print["H1 = "//OutputForm];
	Print[H1];
	Cm = SimilarityMatrix[H0,D0];
	err1 = Norm[H0.Cm-Cm.D0];
	err2 = Norm[H1.Cm-Cm.D1];
	Print["Transformation errors:"//OutputForm];
	Print[Max[err1,err2]];
	Assert[CheckRAPRepresentation[H0,H1] , "MinimalRepFromRAP did not return a valid RAP representation!"];
	Assert[Dimensions[H0][[1]]==2 && Max[err1,err2]<10^-12 , "MinimalRepFromRAP returned a RAP which is non-similar to the input or has an unexpected size!"];
	Print["{H0,H1} = MinimalRepFromRAP[D0,D1,\"obscont\"]:"//OutputForm];
	{H0,H1} = MinimalRepFromRAP[D0,D1,"obscont"];
	Print["H0 = "//OutputForm];
	Print[H0];
	Print["H1 = "//OutputForm];
	Print[H1];
	Cm = SimilarityMatrix[H0,D0];
	err1 = Norm[H0.Cm-Cm.D0];
	err2 = Norm[H1.Cm-Cm.D1];
	Print["Transformation errors:"//OutputForm];
	Print[Max[err1,err2]];
	Assert[CheckRAPRepresentation[H0,H1] , "MinimalRepFromRAP did not return a valid RAP representation!"];
	Assert[Dimensions[H0][[1]]==2 && Max[err1,err2]<10^-12 , "MinimalRepFromRAP returned a RAP which is non-similar to the input or has an "];
	Print["========================================"];
	?"MinimalRepFromMRAP";
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	D0 = {{-5., 1., 0},{3., -3., 0},{1., 1., -5.}};
	Print["D0 = "//OutputForm];
	Print[D0];
	D1 = {{0, 0, 0.8},{0, 0, 0},{0.2, 0.2, 0.2}};
	Print["D1 = "//OutputForm];
	Print[D1];
	D2 = {{0, 0, 3.2},{0, 0, 0},{0.8, 0.8, 0.8}};
	Print["D2 = "//OutputForm];
	Print[D2];
	D = {D0,D1,D2};
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["H = MinimalRepFromMRAP[D,\"cont\"]:"//OutputForm];
	H = MinimalRepFromMRAP[D,"cont"];
	Print[H[[1]]];
	Print[H[[2]]];
	Print[H[[3]]];
	Cm = SimilarityMatrix[H[[1]],D[[1]]];
	err = Norm[H[[1]].Cm-Cm.D[[1]]] + Norm[H[[2]].Cm-Cm.D[[2]]] + Norm[H[[3]].Cm-Cm.D[[3]]];
	Print["Transformation errors:"//OutputForm];
	Print[err];
	Assert[CheckMRAPRepresentation[H] , "MinimalRepFromMRAP did not return a valid MRAP representation!"];
	Assert[Dimensions[H[[2]]][[1]]==3 && err<10^-12 , "MinimalRepFromMRAP returned a MRAP which is non-similar to the input or has an unexpected size!"];
	Print["H = MinimalRepFromMRAP[D,\"obs\"]:"//OutputForm];
	H = MinimalRepFromMRAP[D,"obs"];
	Print[H[[1]]];
	Print[H[[2]]];
	Print[H[[3]]];
	Cm = SimilarityMatrix[H[[1]],D[[1]]];
	err = Norm[H[[1]].Cm-Cm.D[[1]]] + Norm[H[[2]].Cm-Cm.D[[2]]] + Norm[H[[3]].Cm-Cm.D[[3]]];
	Print["Transformation errors:"//OutputForm];
	Print[err];
	Assert[CheckMRAPRepresentation[H] , "MinimalRepFromMRAP did not return a valid MRAP representation!"];
	Assert[Dimensions[H[[2]]][[1]]==2 && err<10^-12 , "MinimalRepFromMRAP returned a MRAP which is non-similar to the input or has an unexpected size!"];
	Print["H = MinimalRepFromMRAP[D,\"obscont\"]:"//OutputForm];
	H = MinimalRepFromMRAP[D,"obscont"];
	Print[H[[1]]];
	Print[H[[2]]];
	Print[H[[3]]];
	Cm = SimilarityMatrix[H[[1]],D[[1]]];
	err = Norm[H[[1]].Cm-Cm.D[[1]]] + Norm[H[[2]].Cm-Cm.D[[2]]] + Norm[H[[3]].Cm-Cm.D[[3]]];
	Print["Transformation errors:"//OutputForm];
	Print[err];
	Assert[CheckMRAPRepresentation[H] , "MinimalRepFromMRAP did not return a valid MRAP representation!"];
	Assert[Dimensions[H[[2]]][[1]]==2 && err<10^-12 , "MinimalRepFromMRAP returned a MRAP which is non-similar to the input or has an unexpected size!"];
	Print["========================================"];
	?"SamplesFromMAP";
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	D0 = {{-0.17, 0, 0, 0.07},{0.01, -0.78, 0.03, 0.08},{0.22, 0.17, -1.1, 0.02},{0.04, 0.12, 0, -0.42}};
	Print["D0 = "//OutputForm];
	Print[D0];
	D1 = {{0, 0.06, 0, 0.04},{0.04, 0.19, 0.21, 0.22},{0.22, 0.13, 0.15, 0.19},{0.05, 0, 0.17, 0.04}};
	Print["D1 = "//OutputForm];
	Print[D1];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["x = SamplesFromMAP[D0,D1,10000]:"//OutputForm];
	x = SamplesFromMAP[D0,D1,10000];
	Print["mm = MarginalMomentsFromMAP[D0,D1,3]:"//OutputForm];
	mm = MarginalMomentsFromMAP[D0,D1,3];
	Print["mm = "//OutputForm];
	Print[mm];
	Print["========================================"];
	?"SamplesFromMMAP";
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	D0 = {{-1.78, 0.29},{0.07, -0.92}};
	Print["D0 = "//OutputForm];
	Print[D0];
	D1 = {{0.15, 0.49},{0.23, 0.36}};
	Print["D1 = "//OutputForm];
	Print[D1];
	D2 = {{0.11, 0.2},{0.01, 0}};
	Print["D2 = "//OutputForm];
	Print[D2];
	D3 = {{0.14, 0.4},{0.11, 0.14}};
	Print["D3 = "//OutputForm];
	Print[D3];
	D = {D0,D1,D2,D3};
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["x = SamplesFromMMAP[D,10000]:"//OutputForm];
	x = SamplesFromMMAP[D,10000];
	Print["mm = MarginalMomentsFromMMAP[D,3]:"//OutputForm];
	mm = MarginalMomentsFromMMAP[D,3];
	Print["mm = "//OutputForm];
	Print[mm];

];
