TestDPHPackage[]:=
Module[{cdf, moms, A, pmf, err2, ev, ma, err1, a, mp, flag, phmoms, B, Cm, mb, x, memoms, b},
	Print["---BuTools: DPH package test file---"//OutputForm];
	Print["Enable the verbose messages with the BuToolsVerbose flag"//OutputForm];
	BuTools`Verbose = True;
	Print["Enable input parameter checking with the BuToolsCheckInput flag"//OutputForm];
	BuTools`CheckInput = True;
	On[Assert];
	Print["========================================"];
	?"MomentsFromMG";
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	a = {-0.6, 0.3, 1.3};
	Print["a = "//OutputForm];
	Print[a];
	A = {{0.25, 0.2, -0.15},{0.3, 0.1, 0.25},{0, 0.2, 0.47}};
	Print["A = "//OutputForm];
	Print[A];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["moms = MomentsFromMG[a,A]:"//OutputForm];
	moms = MomentsFromMG[a,A];
	Print["moms = "//OutputForm];
	Print[moms];
	Assert[CheckMoments[moms]==True , "The function returned invalid moments!"];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["moms = MomentsFromMG[a,A,3]:"//OutputForm];
	moms = MomentsFromMG[a,A,3];
	Print["moms = "//OutputForm];
	Print[moms];
	Assert[CheckMoments[moms]==True , "The function returned invalid moments!"];
	Print["========================================"];
	?"MomentsFromDPH";
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	a = {0.76, 0, 0.24};
	Print["a = "//OutputForm];
	Print[a];
	A = {{0.34, 0.66, 0},{0.79, 0.05, 0.07},{0.26, 0.73, 0.01}};
	Print["A = "//OutputForm];
	Print[A];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["moms = MomentsFromDPH[a,A,5]:"//OutputForm];
	moms = MomentsFromDPH[a,A,5];
	Print["moms = "//OutputForm];
	Print[moms];
	Assert[CheckMoments[moms]==True , "The function returned invalid moments!"];
	Print["========================================"];
	?"PmfFromMG";
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	a = {-0.6, 0.3, 1.3};
	Print["a = "//OutputForm];
	Print[a];
	A = {{0.25, 0.2, -0.15},{0.3, 0.1, 0.25},{0, 0.2, 0.47}};
	Print["A = "//OutputForm];
	Print[A];
	x = Range[0,100,1];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["pmf = PmfFromMG[a,A,x]:"//OutputForm];
	pmf = PmfFromMG[a,A,x];
	Assert[AllTrue[pmf,NonNegative] , "PmfFromMG returned negative pmf!"];
	Assert[Abs[pmf.x - MomentsFromMG[a,A,1][[1]]]<10^-10 , "The mean computed from the pmf does not match the theoretical result!"];
	Print["========================================"];
	?"PmfFromDPH";
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	a = {0.76, 0, 0.24};
	Print["a = "//OutputForm];
	Print[a];
	A = {{0.34, 0.66, 0},{0.79, 0.05, 0.07},{0.26, 0.73, 0.01}};
	Print["A = "//OutputForm];
	Print[A];
	x = Range[0,1000,1];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["pmf = PmfFromDPH[a,A,x]:"//OutputForm];
	pmf = PmfFromDPH[a,A,x];
	Assert[AllTrue[pmf,NonNegative] , "PmfFromMG returned negative pmf!"];
	Assert[Abs[pmf.x - MomentsFromDPH[a,A,1][[1]]]<10^-10 , "The mean computed from the pmf does not match the theoretical result!"];
	Print["========================================"];
	?"CdfFromMG";
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	a = {-0.6, 0.3, 1.3};
	Print["a = "//OutputForm];
	Print[a];
	A = {{0.25, 0.2, -0.15},{0.3, 0.1, 0.25},{0, 0.2, 0.47}};
	Print["A = "//OutputForm];
	Print[A];
	x = Range[0,100,1];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["cdf = CdfFromMG[a,A,x]:"//OutputForm];
	cdf = CdfFromMG[a,A,x];
	Assert[AllTrue[Differences[cdf],NonNegative] , "The cdf is not increasing monotonously!"];
	Assert[Abs[Total[1-cdf] - MomentsFromMG[a,A,1][[1]]]<10^-10 , "The mean computed from the cdf does not match the theoretical result!"];
	Print["========================================"];
	?"CdfFromDPH";
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	a = {0.76, 0, 0.24};
	Print["a = "//OutputForm];
	Print[a];
	A = {{0.34, 0.66, 0},{0.79, 0.05, 0.07},{0.26, 0.73, 0.01}};
	Print["A = "//OutputForm];
	Print[A];
	x = Range[0,1000,1];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["cdf = CdfFromDPH[a,A,x]:"//OutputForm];
	cdf = CdfFromDPH[a,A,x];
	Assert[AllTrue[Differences[cdf],NonNegative] , "The cdf is not increasing monotonously!"];
	Assert[Abs[Total[1-cdf] - MomentsFromDPH[a,A,1][[1]]]<10^-10 , "The mean computed from the cdf does not match the theoretical result!"];
	Print["========================================"];
	?"RandomDPH";
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["{a,A} = RandomDPH[3,10,5]:"//OutputForm];
	{a,A} = RandomDPH[3,10,5];
	Print["a = "//OutputForm];
	Print[a];
	Print["A = "//OutputForm];
	Print[A];
	Assert[CheckDPHRepresentation[a,A] , "RandomDPH failed to return a valid DPH representation!"];
	Assert[Max[Abs[MomentsFromDPH[a,A,1][[1]]-10]]<10^-14 , "RandomDPH failed to match the given mean value!"];
	Print["========================================"];
	?"CheckMGRepresentation";
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	a = {-0.6, 0.3, 1.3};
	Print["a = "//OutputForm];
	Print[a];
	A = {{0.25, 0.2, -0.15},{0.3, 0.1, 0.25},{0, 0.2, 0.47}};
	Print["A = "//OutputForm];
	Print[A];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["flag = CheckMGRepresentation[a,A]:"//OutputForm];
	flag = CheckMGRepresentation[a,A];
	Print["flag = "//OutputForm];
	Print[flag];
	Assert[flag==True , "CheckMGRepresentation failed to recognize a valid MG distribution!"];
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	a = {-0.6, 0.3, 1.3};
	Print["a = "//OutputForm];
	Print[a];
	A = {{0.35, 0.2, -0.25},{0.3, 0.1, 0.25},{0, 0.2, 0.47}};
	Print["A = "//OutputForm];
	Print[A];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["flag = CheckMGRepresentation[a,A]:"//OutputForm];
	flag = CheckMGRepresentation[a,A];
	Print["flag = "//OutputForm];
	Print[flag];
	Assert[flag==False , "CheckMGRepresentation failed to recognize wrong eigenvalues!"];
	Print["========================================"];
	?"CheckDPHRepresentation";
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	a = {0.48, 0.08, 0.26, 0.18};
	Print["a = "//OutputForm];
	Print[a];
	A = {{0, 0.08, 0.08, 0.8},{0.55, 0, 0.24, 0.19},{0.06, 0.03, 0, 0.001},{0.23, 0.005, 0.2, 0.53}};
	Print["A = "//OutputForm];
	Print[A];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["flag = CheckDPHRepresentation[a,A]:"//OutputForm];
	flag = CheckDPHRepresentation[a,A];
	Print["flag = "//OutputForm];
	Print[flag];
	Assert[flag==True , "CheckDPHRepresentation failed to recognize a valid DPH distribution!"];
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	a = {0.48, 0.08};
	Print["a = "//OutputForm];
	Print[a];
	A = {{0, 0.08},{0.55, 0.5}};
	Print["A = "//OutputForm];
	Print[A];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["flag = CheckDPHRepresentation[a,A]:"//OutputForm];
	flag = CheckDPHRepresentation[a,A];
	Print["flag = "//OutputForm];
	Print[flag];
	Assert[flag==False , "CheckDPHRepresentation failed to recognize wrong row sums!"];
	Print["========================================"];
	?"MGFromMoments";
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	moms = {4.08, 20.41, 130.45, 1054.41, 10463.73};
	Print["moms = "//OutputForm];
	Print[moms];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["{a,A} = MGFromMoments[moms]:"//OutputForm];
	{a,A} = MGFromMoments[moms];
	Print["a = "//OutputForm];
	Print[a];
	Print["A = "//OutputForm];
	Print[A];
	Print["memoms = MomentsFromMG[a,A,5]:"//OutputForm];
	memoms = MomentsFromMG[a,A,5];
	Print["memoms = "//OutputForm];
	Print[memoms];
	Assert[Norm[moms-memoms]<10^-9 , "The moments of the result of MGFromMoments do not match the input!"];
	Print["========================================"];
	?"DPHFromMG";
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	a = {-0.6, 0.3, 1.3};
	Print["a = "//OutputForm];
	Print[a];
	A = {{0.1, 0.2, 0},{0.3, 0.1, 0.25},{-0.3, 0.2, 0.77}};
	Print["A = "//OutputForm];
	Print[A];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["flag = CheckMGRepresentation[a,A]:"//OutputForm];
	flag = CheckMGRepresentation[a,A];
	Print["flag = "//OutputForm];
	Print[flag];
	Print["flag = CheckDPHRepresentation[a,A]:"//OutputForm];
	flag = CheckDPHRepresentation[a,A];
	Print["flag = "//OutputForm];
	Print[flag];
	Print["{b,B} = DPHFromMG[a,A]:"//OutputForm];
	{b,B} = DPHFromMG[a,A];
	Print["b = "//OutputForm];
	Print[b];
	Print["B = "//OutputForm];
	Print[B];
	Print["flag = CheckDPHRepresentation[b,B]:"//OutputForm];
	flag = CheckDPHRepresentation[b,B];
	Print["flag = "//OutputForm];
	Print[flag];
	Cm = SimilarityMatrix[A,B];
	err1 = Norm[A.Cm-Cm.B];
	err2 = Norm[a.Cm-b];
	Print["Transformation errors:"//OutputForm];
	Print[Max[err1,err2]];
	Assert[flag && err1<10^-12 && err2<10^-12 , "Transformation to DPH failed!"];
	Print["========================================"];
	?"CanonicalFromDPH2";
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	a = {0, 1.0};
	Print["a = "//OutputForm];
	Print[a];
	A = {{0.23, 0.22},{0.41, 0.48}};
	Print["A = "//OutputForm];
	Print[A];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["{b,B} = CanonicalFromDPH2[a,A]:"//OutputForm];
	{b,B} = CanonicalFromDPH2[a,A];
	Print["b = "//OutputForm];
	Print[b];
	Print["B = "//OutputForm];
	Print[B];
	Print["ev = Eigenvalues[A]:"//OutputForm];
	ev = Eigenvalues[A];
	Print["ev = "//OutputForm];
	Print[ev];
	Print["flag = CheckDPHRepresentation[b,B]:"//OutputForm];
	flag = CheckDPHRepresentation[b,B];
	Print["flag = "//OutputForm];
	Print[flag];
	Cm = SimilarityMatrix[A,B];
	err1 = Norm[A.Cm-Cm.B];
	err2 = Norm[a.Cm-b];
	Assert[err1<10^-12 && err2<10^-12 , "Transformation to canonical DPH(2) failed!"];
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	a = {1.0, 0};
	Print["a = "//OutputForm];
	Print[a];
	A = {{0, 0.61},{0.56, 0.44}};
	Print["A = "//OutputForm];
	Print[A];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["{b,B} = CanonicalFromDPH2[a,A]:"//OutputForm];
	{b,B} = CanonicalFromDPH2[a,A];
	Print["b = "//OutputForm];
	Print[b];
	Print["B = "//OutputForm];
	Print[B];
	Print["ev = Eigenvalues[A]:"//OutputForm];
	ev = Eigenvalues[A];
	Print["ev = "//OutputForm];
	Print[ev];
	Print["flag = CheckDPHRepresentation[b,B]:"//OutputForm];
	flag = CheckDPHRepresentation[b,B];
	Print["flag = "//OutputForm];
	Print[flag];
	Cm = SimilarityMatrix[A,B];
	err1 = Norm[A.Cm-Cm.B];
	err2 = Norm[a.Cm-b];
	Print["Transformation errors:"//OutputForm];
	Print[Max[err1,err2]];
	Assert[err1<10^-12 && err2<10^-12 , "Transformation to canonical DPH(2) failed!"];
	Print["========================================"];
	?"CanonicalFromDPH3";
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	a = {0.46, 0.22, 0.32};
	Print["a = "//OutputForm];
	Print[a];
	A = {{0.67, 0.01, 0.12},{0.06, 0.45, 0.15},{0.18, 0.43, 0.32}};
	Print["A = "//OutputForm];
	Print[A];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["{b,B} = CanonicalFromDPH3[a,A]:"//OutputForm];
	{b,B} = CanonicalFromDPH3[a,A];
	Print["b = "//OutputForm];
	Print[b];
	Print["B = "//OutputForm];
	Print[B];
	Print["ev = Eigenvalues[A]:"//OutputForm];
	ev = Eigenvalues[A];
	Print["ev = "//OutputForm];
	Print[ev];
	Print["flag = CheckDPHRepresentation[b,B]:"//OutputForm];
	flag = CheckDPHRepresentation[b,B];
	Print["flag = "//OutputForm];
	Print[flag];
	Cm = SimilarityMatrix[A,B];
	err1 = Norm[A.Cm-Cm.B];
	err2 = Norm[a.Cm-b];
	Print["Transformation errors:"//OutputForm];
	Print[Max[err1,err2]];
	Assert[flag && err1<10^-12 && err2<10^-12 , "Transformation to canonical DPH(3) failed!"];
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	a = {0.76, 0.12, 0.12};
	Print["a = "//OutputForm];
	Print[a];
	A = {{0.31, 0., 0.},{0.98, 0., 0.02},{0.88, 0.04, 0.08}};
	Print["A = "//OutputForm];
	Print[A];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["{b,B} = CanonicalFromDPH3[a,A]:"//OutputForm];
	{b,B} = CanonicalFromDPH3[a,A];
	Print["b = "//OutputForm];
	Print[b];
	Print["B = "//OutputForm];
	Print[B];
	Print["ev = Eigenvalues[A]:"//OutputForm];
	ev = Eigenvalues[A];
	Print["ev = "//OutputForm];
	Print[ev];
	Print["flag = CheckDPHRepresentation[b,B]:"//OutputForm];
	flag = CheckDPHRepresentation[b,B];
	Print["flag = "//OutputForm];
	Print[flag];
	Cm = SimilarityMatrix[A,B];
	err1 = Norm[A.Cm-Cm.B];
	err2 = Norm[a.Cm-b];
	Print["Transformation errors:"//OutputForm];
	Print[Max[err1,err2]];
	Assert[flag && err1<10^-12 && err2<10^-12 , "Transformation to canonical DPH(3) failed!"];
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	a = {0.67, 0.07, 0.26};
	Print["a = "//OutputForm];
	Print[a];
	A = {{0.31, 0., 0.},{0.98, 0., 0.02},{0.88, 0.04, 0.08}};
	Print["A = "//OutputForm];
	Print[A];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["{b,B} = CanonicalFromDPH3[a,A]:"//OutputForm];
	{b,B} = CanonicalFromDPH3[a,A];
	Print["b = "//OutputForm];
	Print[b];
	Print["B = "//OutputForm];
	Print[B];
	Print["ev = Eigenvalues[A]:"//OutputForm];
	ev = Eigenvalues[A];
	Print["ev = "//OutputForm];
	Print[ev];
	Print["flag = CheckDPHRepresentation[b,B]:"//OutputForm];
	flag = CheckDPHRepresentation[b,B];
	Print["flag = "//OutputForm];
	Print[flag];
	Cm = SimilarityMatrix[A,B];
	err1 = Norm[A.Cm-Cm.B];
	err2 = Norm[a.Cm-b];
	Print["Transformation errors:"//OutputForm];
	Print[Max[err1,err2]];
	Assert[flag && err1<10^-12 && err2<10^-12 , "Transformation to canonical DPH(3) failed!"];
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	a = {0.78, 0.04, 0.18};
	Print["a = "//OutputForm];
	Print[a];
	A = {{0.06, 0.25, 0.31},{0.45, 0.18, 0.33},{0.98, 0, 0.01}};
	Print["A = "//OutputForm];
	Print[A];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["{b,B} = CanonicalFromDPH3[a,A]:"//OutputForm];
	{b,B} = CanonicalFromDPH3[a,A];
	Print["b = "//OutputForm];
	Print[b];
	Print["B = "//OutputForm];
	Print[B];
	Print["ev = Eigenvalues[A]:"//OutputForm];
	ev = Eigenvalues[A];
	Print["ev = "//OutputForm];
	Print[ev];
	Print["flag = CheckDPHRepresentation[b,B]:"//OutputForm];
	flag = CheckDPHRepresentation[b,B];
	Print["flag = "//OutputForm];
	Print[flag];
	Cm = SimilarityMatrix[A,B];
	err1 = Norm[A.Cm-Cm.B];
	err2 = Norm[a.Cm-b];
	Print["Transformation errors:"//OutputForm];
	Print[Max[err1,err2]];
	Assert[flag && err1<10^-12 && err2<10^-12 , "Transformation to canonical DPH(3) failed!"];
	Print["========================================"];
	?"AcyclicDPHFromMG";
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	a = {0, 0, 1.0};
	Print["a = "//OutputForm];
	Print[a];
	A = {{0.22, 0, 0},{0.3, 0.1, 0.55},{0.26, 0, 0.73}};
	Print["A = "//OutputForm];
	Print[A];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["{b,B} = AcyclicDPHFromMG[a,A]:"//OutputForm];
	{b,B} = AcyclicDPHFromMG[a,A];
	Print["b = "//OutputForm];
	Print[b];
	Print["B = "//OutputForm];
	Print[B];
	Print["ma = MomentsFromMG[a,A,5]:"//OutputForm];
	ma = MomentsFromMG[a,A,5];
	Print["ma = "//OutputForm];
	Print[ma];
	Print["mb = MomentsFromMG[b,B,5]:"//OutputForm];
	mb = MomentsFromMG[b,B,5];
	Print["mb = "//OutputForm];
	Print[mb];
	Print["flag = CheckDPHRepresentation[b,B]:"//OutputForm];
	flag = CheckDPHRepresentation[b,B];
	Print["flag = "//OutputForm];
	Print[flag];
	Cm = SimilarityMatrix[A,B];
	err1 = Norm[A.Cm-Cm.B];
	err2 = Norm[a.Cm-b];
	Print["Transformation errors:"//OutputForm];
	Print[Max[err1,err2]];
	Assert[err1<10^-12 && err2<10^-12 , "Transformation to canonical PH(3) failed!"];
	Print["========================================"];
	?"DPH2From3Moments";
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	a = {0.9, 0.1};
	Print["a = "//OutputForm];
	Print[a];
	A = {{0.2, 0.61},{0.58, 0.41}};
	Print["A = "//OutputForm];
	Print[A];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["moms = MomentsFromDPH[a,A]:"//OutputForm];
	moms = MomentsFromDPH[a,A];
	Print["moms = "//OutputForm];
	Print[moms];
	Print["{b,B} = DPH2From3Moments[moms]:"//OutputForm];
	{b,B} = DPH2From3Moments[moms];
	Print["b = "//OutputForm];
	Print[b];
	Print["B = "//OutputForm];
	Print[B];
	Print["phmoms = MomentsFromDPH[b,B,3]:"//OutputForm];
	phmoms = MomentsFromDPH[b,B,3];
	Print["phmoms = "//OutputForm];
	Print[phmoms];
	Assert[Norm[(phmoms-moms)/moms]<10^-12 , "The moments of the result of DPH2From3Moments do not match the input!"];
	Print["========================================"];
	?"DPH3From5Moments";
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	a = {0.7, 0.1, 0.2};
	Print["a = "//OutputForm];
	Print[a];
	A = {{0.2, 0.51, 0.1},{0.58, 0.41, 0},{0.1, 0.4, 0.3}};
	Print["A = "//OutputForm];
	Print[A];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["moms = MomentsFromDPH[a,A]:"//OutputForm];
	moms = MomentsFromDPH[a,A];
	Print["moms = "//OutputForm];
	Print[moms];
	Print["{b,B} = DPH3From5Moments[moms]:"//OutputForm];
	{b,B} = DPH3From5Moments[moms];
	Print["b = "//OutputForm];
	Print[b];
	Print["B = "//OutputForm];
	Print[B];
	Print["phmoms = MomentsFromMG[b,B,5]:"//OutputForm];
	phmoms = MomentsFromMG[b,B,5];
	Print["phmoms = "//OutputForm];
	Print[phmoms];
	Assert[Norm[(phmoms-moms)/moms]<10^-12 , "The moments of the result of DPH3From5Moments do not match the input!"];
	Print["========================================"];
	?"SamplesFromDPH";
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	a = {0.76, 0, 0.24};
	Print["a = "//OutputForm];
	Print[a];
	A = {{0.34, 0.66, 0},{0.79, 0.05, 0.07},{0.26, 0.73, 0.01}};
	Print["A = "//OutputForm];
	Print[A];
	Print["x = SamplesFromDPH[a,A,1000]:"//OutputForm];
	x = SamplesFromDPH[a,A,1000];
	Print["mp = MomentsFromDPH[a,A,3]:"//OutputForm];
	mp = MomentsFromDPH[a,A,3];
	Print["mp = "//OutputForm];
	Print[mp];

];
