ClearAll["Global`*"]
AppendTo[$Path,"/home/gabor/github/butools/Mathematica"];
<<BuTools`
Print["---BuTools: MC package test file---"//OutputForm];
Print["Enable the verbose messages with the BuToolsVerbose flag"//OutputForm];
BuTools`Verbose = True;
Print["Enable input parameter checking with the BuToolsCheckInput flag"//OutputForm];
BuTools`CheckInput = true;
On[Assert];
Print["========================================"]
Print["Testing BuTools function CRPSolve"]
Print["Input:"//OutputForm];
Print["------"//OutputForm];
Q = {{-4.3, 3.5, 0.8},{-8.4, 6.5, 1.9},{17.3, -12.7, -4.6}};
Print["Q = "//OutputForm];
Print[Q];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["ret = CRPSolve[Q];:"//OutputForm];
ret = CRPSolve[Q];
Print["ret = "//OutputForm];
Print[ret];
Print["ret.Q:"//OutputForm];
Print[ret.Q];
Assert[Norm[ret.Q]<10^-12, "The solution does not satisfy ret*Q=0!"];
Print["========================================"]
Print["Testing BuTools function DRPSolve"]
Print["Input:"//OutputForm];
Print["------"//OutputForm];
Q = {{-0.9, 0.5, 1.4},{0.9, -0.9, 1},{0.3, 1.3, -0.6}};
Print["Q = "//OutputForm];
Print[Q];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["ret = DRPSolve[Q];:"//OutputForm];
ret = DRPSolve[Q];
Print["ret = "//OutputForm];
Print[ret];
Print["ret.Q-ret:"//OutputForm];
Print[ret.Q-ret];
Assert[Norm[ret.Q-ret]<10^-12, "The solution does not satisfy ret*Q=ret!"];
Print["========================================"]
Print["Testing BuTools function CTMCSolve"]
Print["Input:"//OutputForm];
Print["------"//OutputForm];
Q = {{-0.9, 0.5, 0.4},{0.9, -0.9, 0},{0.3, 0.3, -0.6}};
Print["Q = "//OutputForm];
Print[Q];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["ret = CTMCSolve[Q];:"//OutputForm];
ret = CTMCSolve[Q];
Print["ret = "//OutputForm];
Print[ret];
Print["ret.Q:"//OutputForm];
Print[ret.Q];
Assert[Norm[ret.Q]<10^-12, "The solution does not satisfy ret*Q=0!"];
Print["========================================"]
Print["Testing BuTools function DTMCSolve"]
Q = {{0.1, 0.5, 0.4},{0.9, 0.1, 0},{0.3, 0.3, 0.4}};
Print["Q = "//OutputForm];
Print[Q];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["ret = DTMCSolve[Q];:"//OutputForm];
ret = DTMCSolve[Q];
Print["ret = "//OutputForm];
Print[ret];
Print["ret.Q-ret:"//OutputForm];
Print[ret.Q-ret];
Assert[Norm[ret.Q-ret]<10^-12, "The solution does not satisfy ret*Q=ret!"];
Print["========================================"]
Print["Testing BuTools function CheckGenerator"]
Print["Input:"//OutputForm];
Print["------"//OutputForm];
Q = {{-0.9, 0.2, 0.4},{0, 0.9, 0.9},{0, 0.6, -0.6}};
Print["Q = "//OutputForm];
Print[Q];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["flag = CheckGenerator[Q, True];:"//OutputForm];
flag = CheckGenerator[Q, True];
Print["flag = "//OutputForm];
Print[flag];
Assert[flag==False, "CheckGenerator did not detect bad row sum!"];
Print["Input:"//OutputForm];
Print["------"//OutputForm];
Q = {{-0.9, 0.5, 0.4},{0.9, -0.9, 0},{0.3, 0.3, -0.6}};
Print["Q = "//OutputForm];
Print[Q];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["flag = CheckGenerator[Q, True];:"//OutputForm];
flag = CheckGenerator[Q, True];
Print["flag = "//OutputForm];
Print[flag];
Assert[flag==True, "CheckGenerator did not recognize a valid input!"];
Print["Input:"//OutputForm];
Print["------"//OutputForm];
Q = {{-0.9, 0.2, 0.4},{0.9, -0.9, 0},{0.3, 0.3, -0.6}};
Print["Q = "//OutputForm];
Print[Q];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["flag = CheckGenerator[Q, True];:"//OutputForm];
flag = CheckGenerator[Q, True];
Print["flag = "//OutputForm];
Print[flag];
Assert[flag==True, "CheckGenerator did not recognize a valid input!"];
Print["Input:"//OutputForm];
Print["------"//OutputForm];
Q = {{-0.9, 0.5, 0.4},{0.9, -1.1, 0},{0.3, 0.3, -0.6}};
Print["Q = "//OutputForm];
Print[Q];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["flag = CheckGenerator[Q];:"//OutputForm];
flag = CheckGenerator[Q];
Print["flag = "//OutputForm];
Print[flag];
Assert[flag==False, "CheckGenerator did not recognize the non-zero row sum!"];
Print["Input:"//OutputForm];
Print["------"//OutputForm];
Q = {{-0.9, 0.5, 0.4},{0.9, -0.9, 0},{0.3, 0.3, -0.6}};
Print["Q = "//OutputForm];
Print[Q];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["flag = CheckGenerator[Q];:"//OutputForm];
flag = CheckGenerator[Q];
Print["flag = "//OutputForm];
Print[flag];
Assert[flag==True, "CheckGenerator did not recognize a valid input!"];
Print["========================================"]
Print["Testing BuTools function CheckProbMatrix"]
Print["Input:"//OutputForm];
Print["------"//OutputForm];
Q = {{0.1, 0.5, 0.4},{0.9, 0.1, 0},{0.3, -0.1, 0.4}};
Print["Q = "//OutputForm];
Print[Q];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["flag = CheckProbMatrix[Q];:"//OutputForm];
flag = CheckProbMatrix[Q];
Print["flag = "//OutputForm];
Print[flag];
Assert[flag==False, "CheckProbMatrix did not recognize the negative entry!"];
Print["Input:"//OutputForm];
Print["------"//OutputForm];
Q = {{0.1, 0.5, 0.4},{0.9, 0.1, 0},{0.3, 0.1, 0.4}};
Print["Q = "//OutputForm];
Print[Q];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["flag = CheckProbMatrix[Q];:"//OutputForm];
flag = CheckProbMatrix[Q];
Print["flag = "//OutputForm];
Print[flag];
Assert[flag==False, "CheckProbMatrix did not recognize the invalid row sum!"];
Print["Input:"//OutputForm];
Print["------"//OutputForm];
Q = {{0.1, 0.5, 0.4},{0.9, 0.1, 0},{0.3, 0.3, 0.4}};
Print["Q = "//OutputForm];
Print[Q];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["flag = CheckProbMatrix[Q];:"//OutputForm];
flag = CheckProbMatrix[Q];
Print["flag = "//OutputForm];
Print[flag];
Assert[flag==True, "CheckProbMatrix did not recognize that the input is valid!"];
Print["Input:"//OutputForm];
Print["------"//OutputForm];
Q = {{0.1, 0.5, 0.4},{0.9, 0.1, 0},{0.3, 0.3, 0.4}};
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["flag = CheckProbMatrix[Q, True];:"//OutputForm];
flag = CheckProbMatrix[Q, True];
Print["flag = "//OutputForm];
Print[flag];
Assert[flag==False, "CheckProbMatrix did not recognize wrong transient matrix!"];
Print["Input:"//OutputForm];
Print["------"//OutputForm];
Q = {{0.1, 0.5, 0.4},{0.9, 0.1, 0},{0.3, 0.1, 0.4}};
Print["Q = "//OutputForm];
Print[Q];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["flag = CheckProbMatrix[Q, True];:"//OutputForm];
flag = CheckProbMatrix[Q, True];
Print["flag = "//OutputForm];
Print[flag];
Assert[flag==True, "CheckProbMatrix did not recognize that the input is valid!"];
Print["========================================"]
Print["Testing BuTools function CheckProbVector"]
Print["Input:"//OutputForm];
Print["------"//OutputForm];
Q = {1.1,-0.1};
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["flag = CheckProbVector[Q];:"//OutputForm];
flag = CheckProbVector[Q];
Print["flag = "//OutputForm];
Print[flag];
Assert[flag==False, "CheckProbVector did not recognize the negative entry!"];
Print["Input:"//OutputForm];
Print["------"//OutputForm];
Q = {1.1,0.1};
Print["Q = "//OutputForm];
Print[Q];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["flag = CheckProbVector[Q];:"//OutputForm];
flag = CheckProbVector[Q];
Print["flag = "//OutputForm];
Print[flag];
Assert[flag==False, "CheckProbVector did not recognize invalid sum!"];
Print["Input:"//OutputForm];
Print["------"//OutputForm];
Q = {1,0};
Print["Q = "//OutputForm];
Print[Q];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["flag = CheckProbVector[Q];:"//OutputForm];
flag = CheckProbVector[Q];
Print["flag = "//OutputForm];
Print[flag];
Assert[flag==True, "CheckProbVector did not recognize that the input is valid!"];
Print["Input:"//OutputForm];
Print["------"//OutputForm];
Q = {0.9,-0.1};
Print["Q = "//OutputForm];
Print[Q];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["flag = CheckProbVector[Q, True];:"//OutputForm];
flag = CheckProbVector[Q, True];
Print["flag = "//OutputForm];
Print[flag];
Assert[flag==False, "CheckProbVector did not recognize the negative entry!"];
Print["Input:"//OutputForm];
Print["------"//OutputForm];
Q = {0.9,0.1};
Print["Q = "//OutputForm];
Print[Q];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["flag = CheckProbVector[Q, True];:"//OutputForm];
flag = CheckProbVector[Q, True];
Print["flag = "//OutputForm];
Print[flag];
Assert[flag==True, "CheckProbVector did not recognize that the prob. vector is not transient!"];
Print["Input:"//OutputForm];
Print["------"//OutputForm];
Q = {0.8,0.1};
Print["Q = "//OutputForm];
Print[Q];
Print["Test:"//OutputForm];
Print["-----"//OutputForm];
Print["flag = CheckProbVector[Q, True];:"//OutputForm];
flag = CheckProbVector[Q, True];
Print["flag = "//OutputForm];
Print[flag];
Assert[flag==True, "CheckProbVector did not recognize that the input is valid!"];
