TestMomentsPackage[]:=
Module[{fmoms, MM, M, JFmoms, flag, rmoms, hmoms, Jmoms, nmoms, err, moms},
	Print["---BuTools: Moments package test file---"//OutputForm];
	Print["Enable the verbose messages with the BuToolsVerbose flag"//OutputForm];
	BuTools`Verbose = True;
	Print["Enable input parameter checking with the BuToolsCheckInput flag"//OutputForm];
	BuTools`CheckInput = True;
	On[Assert];
	Print["========================================"];
	?"NormMomsFromMoms";
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	M = {1.2, 5, 38, 495, 9215};
	Print["M = "//OutputForm];
	Print[M];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["nmoms = NormMomsFromMoms[M]:"//OutputForm];
	nmoms = NormMomsFromMoms[M];
	Print["nmoms = "//OutputForm];
	Print[nmoms];
	Print["moms = MomsFromNormMoms[nmoms]:"//OutputForm];
	moms = MomsFromNormMoms[nmoms];
	Print["moms = "//OutputForm];
	Print[moms];
	Print["err = Norm[moms-M]:"//OutputForm];
	err = Norm[moms-M];
	Print["err = "//OutputForm];
	Print[err];
	Assert[err<10^-10 , "Calling the moment conversion and its inverse did not give back the original moments!"];
	Print["========================================"];
	?"MomsFromNormMoms";
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	M = {1.2, 5, 38, 495, 9215};
	Print["M = "//OutputForm];
	Print[M];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["nmoms = NormMomsFromMoms[M]:"//OutputForm];
	nmoms = NormMomsFromMoms[M];
	Print["nmoms = "//OutputForm];
	Print[nmoms];
	Print["moms = MomsFromNormMoms[nmoms]:"//OutputForm];
	moms = MomsFromNormMoms[nmoms];
	Print["moms = "//OutputForm];
	Print[moms];
	Print["err = Norm[moms-M]:"//OutputForm];
	err = Norm[moms-M];
	Print["err = "//OutputForm];
	Print[err];
	Assert[err<10^-10 , "Calling the moment conversion and its inverse did not give back the original moments!"];
	Print["========================================"];
	?"ReducedMomsFromMoms";
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	M = {1.2, 5, 38, 495, 9215};
	Print["M = "//OutputForm];
	Print[M];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["rmoms = ReducedMomsFromMoms[M]:"//OutputForm];
	rmoms = ReducedMomsFromMoms[M];
	Print["rmoms = "//OutputForm];
	Print[rmoms];
	Print["moms = MomsFromReducedMoms[rmoms]:"//OutputForm];
	moms = MomsFromReducedMoms[rmoms];
	Print["moms = "//OutputForm];
	Print[moms];
	Print["err = Norm[moms-M]:"//OutputForm];
	err = Norm[moms-M];
	Print["err = "//OutputForm];
	Print[err];
	Assert[err<10^-10 , "Calling the moment conversion and its inverse did not give back the original moments!"];
	Print["========================================"];
	?"MomsFromReducedMoms";
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	M = {1.2, 5, 38, 495, 9215};
	Print["M = "//OutputForm];
	Print[M];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["rmoms = ReducedMomsFromMoms[M]:"//OutputForm];
	rmoms = ReducedMomsFromMoms[M];
	Print["rmoms = "//OutputForm];
	Print[rmoms];
	Print["moms = MomsFromReducedMoms[rmoms]:"//OutputForm];
	moms = MomsFromReducedMoms[rmoms];
	Print["moms = "//OutputForm];
	Print[moms];
	Print["err = Norm[moms-M]:"//OutputForm];
	err = Norm[moms-M];
	Print["err = "//OutputForm];
	Print[err];
	Assert[err<10^-10 , "Calling the moment conversion and its inverse did not give back the original moments!"];
	Print["========================================"];
	?"FactorialMomsFromMoms";
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	M = {1.3, 2.4, 6.03, 20.5, 89.5, 474.9};
	Print["M = "//OutputForm];
	Print[M];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["fmoms = FactorialMomsFromMoms[M]:"//OutputForm];
	fmoms = FactorialMomsFromMoms[M];
	Print["fmoms = "//OutputForm];
	Print[fmoms];
	Print["moms = MomsFromFactorialMoms[fmoms]:"//OutputForm];
	moms = MomsFromFactorialMoms[fmoms];
	Print["moms = "//OutputForm];
	Print[moms];
	Print["err = Norm[moms-M]:"//OutputForm];
	err = Norm[moms-M];
	Print["err = "//OutputForm];
	Print[err];
	Assert[err<10^-10 , "Calling the moment conversion and its inverse did not give back the original moments!"];
	Print["========================================"];
	?"MomsFromFactorialMoms";
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	M = {1.3, 2.4, 6.03, 20.5, 89.5, 474.9};
	Print["M = "//OutputForm];
	Print[M];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["fmoms = FactorialMomsFromMoms[M]:"//OutputForm];
	fmoms = FactorialMomsFromMoms[M];
	Print["fmoms = "//OutputForm];
	Print[fmoms];
	Print["moms = MomsFromFactorialMoms[fmoms]:"//OutputForm];
	moms = MomsFromFactorialMoms[fmoms];
	Print["moms = "//OutputForm];
	Print[moms];
	Print["err = Norm[moms-M]:"//OutputForm];
	err = Norm[moms-M];
	Print["err = "//OutputForm];
	Print[err];
	Assert[err<10^-10 , "Calling the moment conversion and its inverse did not give back the original moments!"];
	Print["========================================"];
	?"JFactorialMomsFromJMoms";
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	MM = {{0.7, 2, 3, 4},{5, 6, 7, 8},{9, 10, 11, 12}};
	Print["MM = "//OutputForm];
	Print[MM];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["JFmoms = JFactorialMomsFromJMoms[MM]:"//OutputForm];
	JFmoms = JFactorialMomsFromJMoms[MM];
	Print["JFmoms = "//OutputForm];
	Print[JFmoms];
	Print["Jmoms = JMomsFromJFactorialMoms[JFmoms]:"//OutputForm];
	Jmoms = JMomsFromJFactorialMoms[JFmoms];
	Print["Jmoms = "//OutputForm];
	Print[Jmoms];
	Print["err = Norm[Jmoms-MM]:"//OutputForm];
	err = Norm[Jmoms-MM];
	Print["err = "//OutputForm];
	Print[err];
	Assert[err<10^-10 , "Calling the moment conversion and its inverse did not give back the original moments!"];
	Print["========================================"];
	?"JMomsFromJFactorialMoms";
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	MM = {{0.7, 2, 3, 4},{5, 6, 7, 8},{9, 10, 11, 12}};
	Print["MM = "//OutputForm];
	Print[MM];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["JFmoms = JFactorialMomsFromJMoms[MM]:"//OutputForm];
	JFmoms = JFactorialMomsFromJMoms[MM];
	Print["JFmoms = "//OutputForm];
	Print[JFmoms];
	Print["Jmoms = JMomsFromJFactorialMoms[JFmoms]:"//OutputForm];
	Jmoms = JMomsFromJFactorialMoms[JFmoms];
	Print["Jmoms = "//OutputForm];
	Print[Jmoms];
	Print["err = Norm[Jmoms-MM]:"//OutputForm];
	err = Norm[Jmoms-MM];
	Print["err = "//OutputForm];
	Print[err];
	Assert[err<10^-10 , "Calling the moment conversion and its inverse did not give back the original moments!"];
	Print["========================================"];
	?"HankelMomsFromMoms";
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	M = {1.3, 2.4, 6.03, 20.5, 89.5, 474.9};
	Print["M = "//OutputForm];
	Print[M];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["hmoms = HankelMomsFromMoms[M]:"//OutputForm];
	hmoms = HankelMomsFromMoms[M];
	Print["hmoms = "//OutputForm];
	Print[hmoms];
	Print["moms = MomsFromHankelMoms[hmoms]:"//OutputForm];
	moms = MomsFromHankelMoms[hmoms];
	Print["moms = "//OutputForm];
	Print[moms];
	Print["err = Norm[moms-M]:"//OutputForm];
	err = Norm[moms-M];
	Print["err = "//OutputForm];
	Print[err];
	Assert[err<10^-10 , "Calling the moment conversion and its inverse did not give back the original moments!"];
	Print["========================================"];
	?"MomsFromHankelMoms";
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	M = {1.3, 2.4, 6.03, 20.5, 89.5, 474.9};
	Print["M = "//OutputForm];
	Print[M];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["hmoms = HankelMomsFromMoms[M]:"//OutputForm];
	hmoms = HankelMomsFromMoms[M];
	Print["hmoms = "//OutputForm];
	Print[hmoms];
	Print["moms = MomsFromHankelMoms[hmoms]:"//OutputForm];
	moms = MomsFromHankelMoms[hmoms];
	Print["moms = "//OutputForm];
	Print[moms];
	Print["err = Norm[moms-M]:"//OutputForm];
	err = Norm[moms-M];
	Print["err = "//OutputForm];
	Print[err];
	Assert[err<10^-10 , "Calling the moment conversion and its inverse did not give back the original moments!"];
	Print["========================================"];
	?"CheckMoments";
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	M = {1.2, 5, 8, 29, 3412};
	Print["M = "//OutputForm];
	Print[M];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["flag = CheckMoments[M]:"//OutputForm];
	flag = CheckMoments[M];
	Print["flag = "//OutputForm];
	Print[flag];
	Assert[flag==False , "CheckMoments did not recognize a valid moment sequence!"];
	Print["Input:"//OutputForm];
	Print["------"//OutputForm];
	M = {1.3, 2.4, 6.03, 20.5, 89.5};
	Print["M = "//OutputForm];
	Print[M];
	Print["Test:"//OutputForm];
	Print["-----"//OutputForm];
	Print["flag = CheckMoments[M]:"//OutputForm];
	flag = CheckMoments[M];
	Print["flag = "//OutputForm];
	Print[flag];
	Assert[flag==True , "CheckMoments did not recognize an invalid moment sequence!"];

];
